<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Part 7 Introduction to the Analysis of Complex Survey Data | Preparing and Analyzing Survey Data in R</title>
  <meta name="description" content="Provides guidance for preparing and analyzing survey data in R." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Part 7 Introduction to the Analysis of Complex Survey Data | Preparing and Analyzing Survey Data in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Provides guidance for preparing and analyzing survey data in R." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Part 7 Introduction to the Analysis of Complex Survey Data | Preparing and Analyzing Survey Data in R" />
  
  <meta name="twitter:description" content="Provides guidance for preparing and analyzing survey data in R." />
  

<meta name="author" content="George M. Harrison  University of Hawai‘i at Mānoa, College of Education" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="Reliability.html"/>
<link rel="next" href="references.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Preparing and Analyzing Survey Data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#prior-knowledge"><i class="fa fa-check"></i><b>1.1</b> Prior knowledge</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Prepping.html"><a href="Prepping.html"><i class="fa fa-check"></i><b>2</b> Preparing the Data</a><ul>
<li class="chapter" data-level="2.1" data-path="Prepping.html"><a href="Prepping.html#import-the-data-from-the-csv-file"><i class="fa fa-check"></i><b>2.1</b> Import the data from the CSV file</a><ul>
<li class="chapter" data-level="2.1.1" data-path="Prepping.html"><a href="Prepping.html#examining-the-imported-data-set"><i class="fa fa-check"></i><b>2.1.1</b> Examining the imported data set</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="Prepping.html"><a href="Prepping.html#managing-the-structure-of-the-data"><i class="fa fa-check"></i><b>2.2</b> Managing the structure of the data</a></li>
<li class="chapter" data-level="2.3" data-path="Prepping.html"><a href="Prepping.html#recoding-response-category-data"><i class="fa fa-check"></i><b>2.3</b> Recoding response-category data</a><ul>
<li class="chapter" data-level="2.3.1" data-path="Prepping.html"><a href="Prepping.html#reverse-coding-and-rescaling-data"><i class="fa fa-check"></i><b>2.3.1</b> Reverse-coding and rescaling data</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="Prepping.html"><a href="Prepping.html#creating-composite-scores-aka-indexes"><i class="fa fa-check"></i><b>2.4</b> Creating Composite Scores (AKA Indexes)</a></li>
<li class="chapter" data-level="2.5" data-path="Prepping.html"><a href="Prepping.html#a-general-formula-for-rescaling-data"><i class="fa fa-check"></i><b>2.5</b> A general formula for rescaling data</a></li>
<li class="chapter" data-level="2.6" data-path="Prepping.html"><a href="Prepping.html#create-and-use-a-custom-function"><i class="fa fa-check"></i><b>2.6</b> Create and use a custom function</a></li>
<li class="chapter" data-level="2.7" data-path="Prepping.html"><a href="Prepping.html#the-code-in-one-place-for-one-of-the-composite-scores"><i class="fa fa-check"></i><b>2.7</b> The code in one place for one of the composite scores</a></li>
<li class="chapter" data-level="2.8" data-path="Prepping.html"><a href="Prepping.html#a-shortcut-when-all-of-the-items-are-on-the-same-scale"><i class="fa fa-check"></i><b>2.8</b> A shortcut, when all of the items are on the same scale</a></li>
<li class="chapter" data-level="2.9" data-path="Prepping.html"><a href="Prepping.html#summary"><i class="fa fa-check"></i><b>2.9</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="Packages.html"><a href="Packages.html"><i class="fa fa-check"></i><b>3</b> Installing and Using Packages</a><ul>
<li class="chapter" data-level="3.1" data-path="Packages.html"><a href="Packages.html#seeing-if-we-need-to-install-a-package"><i class="fa fa-check"></i><b>3.1</b> Seeing if we need to install a package</a></li>
<li class="chapter" data-level="3.2" data-path="Packages.html"><a href="Packages.html#installing-a-package"><i class="fa fa-check"></i><b>3.2</b> Installing a package</a></li>
<li class="chapter" data-level="3.3" data-path="Packages.html"><a href="Packages.html#using-a-function-from-a-package"><i class="fa fa-check"></i><b>3.3</b> Using a function from a package</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="Descripts.html"><a href="Descripts.html"><i class="fa fa-check"></i><b>4</b> Estimating Descriptive Statistics</a><ul>
<li class="chapter" data-level="4.1" data-path="Descripts.html"><a href="Descripts.html#descriptive-statistics-of-categorical-data"><i class="fa fa-check"></i><b>4.1</b> Descriptive statistics of categorical data</a><ul>
<li class="chapter" data-level="4.1.1" data-path="Descripts.html"><a href="Descripts.html#creating-factors"><i class="fa fa-check"></i><b>4.1.1</b> Creating factors</a></li>
<li class="chapter" data-level="4.1.2" data-path="Descripts.html"><a href="Descripts.html#plotting-the-frequency-data"><i class="fa fa-check"></i><b>4.1.2</b> Plotting the frequency data</a></li>
<li class="chapter" data-level="4.1.3" data-path="Descripts.html"><a href="Descripts.html#cross-tabulations"><i class="fa fa-check"></i><b>4.1.3</b> Cross-tabulations</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="Descripts.html"><a href="Descripts.html#IntrvlDesc"><i class="fa fa-check"></i><b>4.2</b> Descriptive statistics of interval-level data</a><ul>
<li class="chapter" data-level="4.2.1" data-path="Descripts.html"><a href="Descripts.html#calculating-the-confidence-interval"><i class="fa fa-check"></i><b>4.2.1</b> Calculating the confidence interval</a></li>
<li class="chapter" data-level="4.2.2" data-path="Descripts.html"><a href="Descripts.html#generating-and-exporting-a-report"><i class="fa fa-check"></i><b>4.2.2</b> Generating and exporting a report</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="Descripts.html"><a href="Descripts.html#but-really-its-inferential"><i class="fa fa-check"></i><b>4.3</b> But really, it’s inferential</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ByDescripts.html"><a href="ByDescripts.html"><i class="fa fa-check"></i><b>5</b> Descriptive Statistics by Group</a><ul>
<li class="chapter" data-level="5.1" data-path="ByDescripts.html"><a href="ByDescripts.html#using-the-describeby-function"><i class="fa fa-check"></i><b>5.1</b> Using the <code>describeBy()</code> function</a></li>
<li class="chapter" data-level="5.2" data-path="ByDescripts.html"><a href="ByDescripts.html#confidence-intervals-for-each-groups-estimated-mean"><i class="fa fa-check"></i><b>5.2</b> Confidence intervals for each group’s estimated mean</a><ul>
<li class="chapter" data-level="5.2.1" data-path="ByDescripts.html"><a href="ByDescripts.html#separating-the-report-by-group"><i class="fa fa-check"></i><b>5.2.1</b> Separating the report by group</a></li>
<li class="chapter" data-level="5.2.2" data-path="ByDescripts.html"><a href="ByDescripts.html#calculating-the-confidence-interval-1"><i class="fa fa-check"></i><b>5.2.2</b> Calculating the confidence interval</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="ByDescripts.html"><a href="ByDescripts.html#plotting-the-by-group-means-and-confidence-intervals"><i class="fa fa-check"></i><b>5.3</b> Plotting the by-group means and confidence intervals</a><ul>
<li class="chapter" data-level="5.3.1" data-path="ByDescripts.html"><a href="ByDescripts.html#making-a-pretty-plot-maybe"><i class="fa fa-check"></i><b>5.3.1</b> Making a pretty plot, maybe</a></li>
<li class="chapter" data-level="5.3.2" data-path="ByDescripts.html"><a href="ByDescripts.html#saving-plots"><i class="fa fa-check"></i><b>5.3.2</b> Saving plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="Reliability.html"><a href="Reliability.html"><i class="fa fa-check"></i><b>6</b> Internal Consistency Reliability</a><ul>
<li class="chapter" data-level="6.1" data-path="Reliability.html"><a href="Reliability.html#doing-it-manually"><i class="fa fa-check"></i><b>6.1</b> Doing it manually</a></li>
<li class="chapter" data-level="6.2" data-path="Reliability.html"><a href="Reliability.html#doing-it-with-the-psych-package"><i class="fa fa-check"></i><b>6.2</b> Doing it with the psych package</a><ul>
<li class="chapter" data-level="6.2.1" data-path="Reliability.html"><a href="Reliability.html#omega-reliability-using-the-psych-package"><i class="fa fa-check"></i><b>6.2.1</b> Omega reliability using the psych package</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="Reliability.html"><a href="Reliability.html#summary-1"><i class="fa fa-check"></i><b>6.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="Complex.html"><a href="Complex.html"><i class="fa fa-check"></i><b>7</b> Introduction to the Analysis of Complex Survey Data</a><ul>
<li class="chapter" data-level="7.1" data-path="Complex.html"><a href="Complex.html#packages"><i class="fa fa-check"></i><b>7.1</b> Packages</a></li>
<li class="chapter" data-level="7.2" data-path="Complex.html"><a href="Complex.html#example-data"><i class="fa fa-check"></i><b>7.2</b> Example data</a></li>
<li class="chapter" data-level="7.3" data-path="Complex.html"><a href="Complex.html#the-three-hypothetical-complex-designs"><i class="fa fa-check"></i><b>7.3</b> The three hypothetical complex designs</a><ul>
<li class="chapter" data-level="7.3.1" data-path="Complex.html"><a href="Complex.html#pretending-we-have-a-cluster-sampled-design"><i class="fa fa-check"></i><b>7.3.1</b> Pretending we have a cluster-sampled design</a></li>
<li class="chapter" data-level="7.3.2" data-path="Complex.html"><a href="Complex.html#pretending-we-have-a-stratified-design"><i class="fa fa-check"></i><b>7.3.2</b> Pretending we have a stratified design</a></li>
<li class="chapter" data-level="7.3.3" data-path="Complex.html"><a href="Complex.html#pretending-we-have-a-stratified-cluster-sampled-design"><i class="fa fa-check"></i><b>7.3.3</b> Pretending we have a stratified cluster-sampled design</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="Complex.html"><a href="Complex.html#cluster-sampled-design"><i class="fa fa-check"></i><b>7.4</b> Cluster-sampled design</a><ul>
<li class="chapter" data-level="7.4.1" data-path="Complex.html"><a href="Complex.html#preparing-the-data"><i class="fa fa-check"></i><b>7.4.1</b> Preparing the data</a></li>
<li class="chapter" data-level="7.4.2" data-path="Complex.html"><a href="Complex.html#step-1-specifying-the-design"><i class="fa fa-check"></i><b>7.4.2</b> Step 1: Specifying the design</a></li>
<li class="chapter" data-level="7.4.3" data-path="Complex.html"><a href="Complex.html#step-2-calculating-the-estimates"><i class="fa fa-check"></i><b>7.4.3</b> Step 2: Calculating the estimates</a></li>
<li class="chapter" data-level="7.4.4" data-path="Complex.html"><a href="Complex.html#effective-sample-size"><i class="fa fa-check"></i><b>7.4.4</b> Effective sample size</a></li>
<li class="chapter" data-level="7.4.5" data-path="Complex.html"><a href="Complex.html#estimating-the-mean-per-cluster"><i class="fa fa-check"></i><b>7.4.5</b> Estimating the mean per cluster</a></li>
<li class="chapter" data-level="7.4.6" data-path="Complex.html"><a href="Complex.html#two-stage-cluster-sampled-design"><i class="fa fa-check"></i><b>7.4.6</b> Two-stage cluster-sampled design</a></li>
<li class="chapter" data-level="7.4.7" data-path="Complex.html"><a href="Complex.html#estimating-the-mean-per-cluster-1"><i class="fa fa-check"></i><b>7.4.7</b> Estimating the mean per cluster</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="Complex.html"><a href="Complex.html#stratified-design"><i class="fa fa-check"></i><b>7.5</b> Stratified design</a><ul>
<li class="chapter" data-level="7.5.1" data-path="Complex.html"><a href="Complex.html#preparing-our-data-set"><i class="fa fa-check"></i><b>7.5.1</b> Preparing our data set</a></li>
<li class="chapter" data-level="7.5.2" data-path="Complex.html"><a href="Complex.html#step-1-specifying-the-design-1"><i class="fa fa-check"></i><b>7.5.2</b> Step 1: Specifying the design</a></li>
<li class="chapter" data-level="7.5.3" data-path="Complex.html"><a href="Complex.html#step-2-calculating-the-estimates-1"><i class="fa fa-check"></i><b>7.5.3</b> Step 2: Calculating the estimates</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="Complex.html"><a href="Complex.html#stratified-cluster-sampled-design"><i class="fa fa-check"></i><b>7.6</b> Stratified cluster-sampled design</a><ul>
<li class="chapter" data-level="7.6.1" data-path="Complex.html"><a href="Complex.html#preparing-the-data-1"><i class="fa fa-check"></i><b>7.6.1</b> Preparing the data</a></li>
<li class="chapter" data-level="7.6.2" data-path="Complex.html"><a href="Complex.html#step-1-specifying-the-design-2"><i class="fa fa-check"></i><b>7.6.2</b> Step 1: Specifying the design</a></li>
<li class="chapter" data-level="7.6.3" data-path="Complex.html"><a href="Complex.html#step-2-calculating-the-estimates-2"><i class="fa fa-check"></i><b>7.6.3</b> Step 2: Calculating the estimates</a></li>
<li class="chapter" data-level="7.6.4" data-path="Complex.html"><a href="Complex.html#mean-per-stratum"><i class="fa fa-check"></i><b>7.6.4</b> Mean per stratum</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="Complex.html"><a href="Complex.html#a-simple-random-sample-design-for-comparison"><i class="fa fa-check"></i><b>7.7</b> A simple random sample design, for comparison</a><ul>
<li class="chapter" data-level="7.7.1" data-path="Complex.html"><a href="Complex.html#preparing-our-data-set-1"><i class="fa fa-check"></i><b>7.7.1</b> Preparing our data set</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="Complex.html"><a href="Complex.html#comparing-all-design-scenarios"><i class="fa fa-check"></i><b>7.8</b> Comparing all design scenarios</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Preparing and Analyzing Survey Data in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="Complex" class="section level1">
<h1><span class="header-section-number">Part 7</span> Introduction to the Analysis of Complex Survey Data</h1>
<p>In a garden variety simple-random-sample design, we randomly sample units from a larger population and then estimate the mean, standard deviation, and confidence intervals to subsequently draw an inference about the larger population. This is the assumption underlying the example and explanations in the previous chapters. In this chapter we examine complex survey data. In survey designs with complex data, we need to make corrections to the standard error, which in turn affects the confidence intervals, which subsequently affects our inference about the statistic—such as the mean—in the population we seek to make claims about.</p>
<div id="packages" class="section level2">
<h2><span class="header-section-number">7.1</span> Packages</h2>
<p>There are two packages that are handy for analyzing complex survey data: The survey package <span class="citation">(Lumley, <a href="#ref-R-survey" role="doc-biblioref">2020</a>)</span> and the similarly named srvyr package <span class="citation">(Freedman Ellis &amp; Schneider, <a href="#ref-R-srvyr" role="doc-biblioref">2021</a>)</span>, which works with the survey package to make the output easier to work with (because why would the survey package on its own make life easy?). Harkening back to a previous chapter, we need to first be sure we have these packages installed. We will also use the dplyr package <span class="citation">(Wickham, François, et al., <a href="#ref-R-dplyr" role="doc-biblioref">2020</a>)</span> again, as this uses the same data-wrangling language that the srvyr package does.<a href="#fn28" class="footnote-ref" id="fnref28"><sup>28</sup></a></p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="Complex.html#cb195-1"></a><span class="kw">library</span>(survey)</span>
<span id="cb195-2"><a href="Complex.html#cb195-2"></a><span class="kw">library</span>(srvyr)</span>
<span id="cb195-3"><a href="Complex.html#cb195-3"></a><span class="kw">library</span>(dplyr)</span></code></pre></div>
</div>
<div id="example-data" class="section level2">
<h2><span class="header-section-number">7.2</span> Example data</h2>
<p>To go through this example, let’s use the data set that is presented in the chapter by Heeringa, West, and Berglund <span class="citation">(<a href="#ref-heeringa_applied_2010" role="doc-biblioref">2010</a>, Chapter 2)</span>, who provide an explanation that we can follow along with as we actually perform these calculations.<a href="#fn29" class="footnote-ref" id="fnref29"><sup>29</sup></a></p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="Complex.html#cb196-1"></a>dat &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;Heeringa.Complex.SampleData.csv&quot;</span>)</span>
<span id="cb196-2"><a href="Complex.html#cb196-2"></a><span class="kw">str</span>(dat)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    32 obs. of  5 variables:
##  $ sid     : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ school  : int  1 1 1 1 2 2 2 2 3 3 ...
##  $ district: int  1 1 1 1 1 1 1 1 2 2 ...
##  $ score   : num  52.8 32.5 56.6 47 37.3 57 54.2 71.5 27.7 42.3 ...
##  $ weight  : int  1 2 2 1 1 1 2 2 1 2 ...</code></pre>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="Complex.html#cb198-1"></a><span class="kw">head</span>(dat)</span></code></pre></div>
<pre><code>##   sid school district score weight
## 1   1      1        1  52.8      1
## 2   2      1        1  32.5      2
## 3   3      1        1  56.6      2
## 4   4      1        1  47.0      1
## 5   5      2        1  37.3      1
## 6   6      2        1  57.0      1</code></pre>
</div>
<div id="the-three-hypothetical-complex-designs" class="section level2">
<h2><span class="header-section-number">7.3</span> The three hypothetical complex designs</h2>
<div id="pretending-we-have-a-cluster-sampled-design" class="section level3">
<h3><span class="header-section-number">7.3.1</span> Pretending we have a cluster-sampled design</h3>
<p>We will use this data set to practice analyzing the data in a cluster-sampled design. This would be the kind of analysis we would conduct if we had randomly sampled schools—that is, our clusters—from a broader population of schools (such as from a sampling frame that listed all of the schools in the country). In this design, our <em>primary sampling unit</em> is schools. Within each school, we have students, whom we had administered the survey to.<a href="#fn30" class="footnote-ref" id="fnref30"><sup>30</sup></a> This design is very convenient because it is easier to randomly sample schools from a list of schools, whereas it is virtually impossible to have a list of all of the individual students in the country. We pay a price for this convenience, though, because students who are nested within schools tend to live in similar neighborhoods, share the same values, have the same learning experiences, and so forth, so if we used a run-of-the-mill standard error (and confidence interval), we will be overly optimistic in how precise we are in estimating the population. When we correctly analyze these data, we pay a penalty because our standard error is corrected to be larger than it would be with a simple random sample.</p>
</div>
<div id="pretending-we-have-a-stratified-design" class="section level3">
<h3><span class="header-section-number">7.3.2</span> Pretending we have a stratified design</h3>
<p>After analyzing the cluster-sampling design data, we’ll erase our memories of that design and pretend we’re analyzing a stratified design. In this type of design, we have have conducted a simple random sample of students within strata. In this case, the students are our <em>primary sampling unit</em>. Let’s say we have a list of school districts—these are our strata. We then have a list of all the students in each district, which is our sampling frame. We randomly selected students from each district, then we estimate the mean of the population. This is a very powerful design if we believe that the strata explain a lot of variation in the variable (in the score, in this case). It helps us to have greater precision in our estimate of the population mean.<a href="#fn31" class="footnote-ref" id="fnref31"><sup>31</sup></a></p>
</div>
<div id="pretending-we-have-a-stratified-cluster-sampled-design" class="section level3">
<h3><span class="header-section-number">7.3.3</span> Pretending we have a stratified cluster-sampled design</h3>
<p>After monkeying around with a stratified design, we wipe our memories of how we had designed that study and pretend we had collected the data using schools as our primary sampling unit, similar to how we did with the cluster-sampled design, but this time we sample schools from within their districts. The districts are strata. So, we have students nested within schools, which were randomly selected, which in turn are nested within strata. This is a very practical and smart design to use. First, we have the convenience of sampling schools, which is far easier than randomly sampling students from lists. Second, we can reduce that penalty to the standard error of this clustering by also using a stratification variable—the districts. This allows us to make claims about the population of schools within these particular districts.</p>
<p>We will also pretend we have a simple random sample, as well, to compare these scenarios with each other in terms of the standard error and confidence intervals.</p>
</div>
</div>
<div id="cluster-sampled-design" class="section level2">
<h2><span class="header-section-number">7.4</span> Cluster-sampled design</h2>
<div id="preparing-the-data" class="section level3">
<h3><span class="header-section-number">7.4.1</span> Preparing the data</h3>
<p>In the example that Heeringa and colleagues provide, they did not use a finite population correction. Another way to think about this is that the population of our primary sampling unit is very large. Let’s say, therefore, that there is a very large number of schools (such as one million) in the population.</p>
<p>For many researchers, they treat the population as an infinitely large number, which is a conservative approach because it does not adjust the standard error to be smaller to account for the proportion of the population being sampled. For other researchers, such as for evaluations in a specific population—such as the schools in a particular state—the population size is finite. For instance, if there are 160 schools in a state and we’re only drawing inferences about schools in that state, we can this number as our population size, which will yield a lower standard error (which will narrow our confidence intervals compared to an infinite population size).</p>
<p>The following example treats the population as infinite (to follow Heeringa’s example), but in your own study, you can specify these sizes to match your needs in your research or evaluation.</p>
<p>To get this to work with the survey package, we create a column in the data that is this cluster <em>N</em>-size. Here, we can use <code>N_cl</code> as this column name to remind us that this is the population size of clusters.</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="Complex.html#cb200-1"></a>dat<span class="op">$</span>N_cl &lt;-<span class="st"> </span><span class="dv">1000000</span></span>
<span id="cb200-2"><a href="Complex.html#cb200-2"></a><span class="kw">head</span>(dat)</span></code></pre></div>
<pre><code>##   sid school district score weight  N_cl
## 1   1      1        1  52.8      1 1e+06
## 2   2      1        1  32.5      2 1e+06
## 3   3      1        1  56.6      2 1e+06
## 4   4      1        1  47.0      1 1e+06
## 5   5      2        1  37.3      1 1e+06
## 6   6      2        1  57.0      1 1e+06</code></pre>
</div>
<div id="step-1-specifying-the-design" class="section level3">
<h3><span class="header-section-number">7.4.2</span> Step 1: Specifying the design</h3>
<p>To use the srvyr package (and the survey package it wraps around), we need to create a survey-design object.<a href="#fn32" class="footnote-ref" id="fnref32"><sup>32</sup></a> This specifies what the survey design was when we collected the data, which in turn determines what kinds of adjustments to the standard error we should make.</p>
<p>Let’s create a survey-design object, with which we can perform subsequent calculations. We do this with the srvyr package’s <code>as_survey_design()</code> function. To remind us that this is a design and that it uses clusters, we can name our object <code>des_cl</code>, but you could call it <code>Bill</code> or <code>mydesign</code>.</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="Complex.html#cb202-1"></a><span class="kw">library</span>(survey)</span>
<span id="cb202-2"><a href="Complex.html#cb202-2"></a><span class="kw">library</span>(srvyr)</span>
<span id="cb202-3"><a href="Complex.html#cb202-3"></a>des_cl &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb202-4"><a href="Complex.html#cb202-4"></a><span class="st">           </span><span class="kw">as_survey_design</span>(<span class="dt">id =</span> school, </span>
<span id="cb202-5"><a href="Complex.html#cb202-5"></a>                           <span class="dt">fpc =</span> N_cl)</span></code></pre></div>
<p>There are two arguments in that design specification. The <code>id =</code> specifies what the primary sampling unit is. In our design, the primary sampling unit (PSU) is the school variable in our data set. The second argument is for the finite population correction. We would think that the <code>fpc =</code> argument specifies the actual finite population correction, but it does NOT! Unintuitively, the default in the survey package is for <code>fpc =</code> to actually refer to the <em>size</em> of the population of primary sampling units. So, this should be called something like <code>pop</code> instead of <code>fpc</code> in the program—that would make it too easy, though, wouldn’t it.<a href="#fn33" class="footnote-ref" id="fnref33"><sup>33</sup></a> If the number of clusters in our population were finite, like 168 schools, we can use the <code>fpc = 168</code> as a value for each case in the data set, which would make our standard error smaller. However, for this hypothetical example, we are saying there are 1 million schools.</p>
<p>We can look at the survey design we created using the <code>summary()</code> function on that object:</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="Complex.html#cb203-1"></a><span class="kw">summary</span>(des_cl) </span></code></pre></div>
<pre><code>## 1 - level Cluster Sampling design
## With (8) clusters.
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   8e-06   8e-06   8e-06   8e-06   8e-06   8e-06 
## Population size (PSUs): 1e+06 
## Data variables:
## [1] &quot;sid&quot;      &quot;school&quot;   &quot;district&quot; &quot;score&quot;    &quot;weight&quot;   &quot;N_cl&quot;</code></pre>
<p>Notice that the probability of being sampled is equal across the quantiles. This is because everyone has the same fpc.</p>
</div>
<div id="step-2-calculating-the-estimates" class="section level3">
<h3><span class="header-section-number">7.4.3</span> Step 2: Calculating the estimates</h3>
<p>We want to know the mean and variance of our sample, as well as the confidence interval of the mean. We cannot use the regular Base R functions like <code>mean()</code> and <code>variance()</code> because they do not correct for the design. Instead, we use the functions from the svyr package. For example, instead of <code>mean()</code>, it uses <code>survey_mean()</code>.<a href="#fn34" class="footnote-ref" id="fnref34"><sup>34</sup></a></p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="Complex.html#cb205-1"></a>des_cl <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb205-2"><a href="Complex.html#cb205-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">survey_mean</span>(score,                                 </span>
<span id="cb205-3"><a href="Complex.html#cb205-3"></a>                        <span class="dt">vartype =</span> <span class="kw">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>), <span class="dt">df =</span> <span class="kw">degf</span>(.),  </span>
<span id="cb205-4"><a href="Complex.html#cb205-4"></a>                        <span class="dt">deff =</span> <span class="ot">TRUE</span> ))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##    coef `_se` `_low` `_upp` `_deff`
##   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1  40.8  3.66   32.1   49.4    2.31</code></pre>
<p>We have the <code>summarize()</code> function around the <code>survey_mean()</code> function. Just as we do in mathematics, we work from inside the parentheses to the outside. The first argument in the <code>survey_mean()</code> function is the variable that we are estimating, <code>score</code> in this case. The second argument specifies the type of sampling-distribution variance we would like to report (not to be confused with the sampling variance). Here, we seek the standard error (<code>"se"</code>) and the upper and lower 95% confidence interval (<code>"ci"</code>) based on the <em>t</em> distribution (based on the <code>df = degf(.)</code> argument). If we wanted the <em>z</em> distribution, we would remove the <code>df =</code> argument. Because <em>t</em> distribution values at the lower and upper 2.5% quantiles are larger in magnitude (depending on the degrees of freedom) than <em>z</em> distribution values (1.96), they are more conservative. We also request the design effect to be reported, <code>deff = TRUE</code>.</p>
<p>The coefficient of interest is the mean. The standard error and the lower- and upper-boundaries of the confidence intervals are reported, as well as the design effect.</p>
<p>We can actually save this output to an object and then use it later on. If you are like me, you think the outputs printed from the srvyr package are ugly. I want to see two decimal places, so I’ll round it to two decimal places, then print it with the <code>print.data.frame()</code> function.<a href="#fn35" class="footnote-ref" id="fnref35"><sup>35</sup></a></p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="Complex.html#cb207-1"></a>rslts_M_cl &lt;-<span class="st"> </span>des_cl <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb207-2"><a href="Complex.html#cb207-2"></a><span class="st">          </span><span class="kw">summarize</span>(<span class="dt">Mn =</span> <span class="kw">survey_mean</span>(score, </span>
<span id="cb207-3"><a href="Complex.html#cb207-3"></a>                         <span class="dt">vartype =</span> <span class="kw">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>), <span class="dt">df =</span> <span class="kw">degf</span>(.), </span>
<span id="cb207-4"><a href="Complex.html#cb207-4"></a>                         <span class="dt">deff =</span> <span class="ot">TRUE</span> ) )</span>
<span id="cb207-5"><a href="Complex.html#cb207-5"></a><span class="kw">print.data.frame</span>( <span class="kw">round</span>(rslts_M_cl, <span class="dv">2</span>) )</span></code></pre></div>
<pre><code>##      Mn Mn_se Mn_low Mn_upp Mn_deff
## 1 40.77  3.66  32.12  49.42    2.31</code></pre>
<p>Now let’s examine the variance and the sampling distribution of the variance.
The function is <code>survey_var()</code>:</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="Complex.html#cb209-1"></a>rslts_V_cl &lt;-<span class="st"> </span>des_cl <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="kw">survey_var</span>(score) )</span>
<span id="cb209-2"><a href="Complex.html#cb209-2"></a><span class="kw">print.data.frame</span>( <span class="kw">round</span>(rslts_V_cl, <span class="dv">2</span>) )</span></code></pre></div>
<pre><code>##     coef   _se
## 1 185.28 40.72</code></pre>
<p>The coefficient is our estimated variance and the standard error is the standard error of the estimated variance.<a href="#fn36" class="footnote-ref" id="fnref36"><sup>36</sup></a></p>
<p>Conveniently, we can perform both the <code>survey_mean()</code> and <code>survey_var()</code> and save these to a report:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="Complex.html#cb211-1"></a>rslts_cl &lt;-<span class="st"> </span>des_cl <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb211-2"><a href="Complex.html#cb211-2"></a><span class="st">          </span><span class="kw">summarize</span>(<span class="dt">Mn =</span> <span class="kw">survey_mean</span>(score, </span>
<span id="cb211-3"><a href="Complex.html#cb211-3"></a>                         <span class="dt">vartype =</span> <span class="kw">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>), <span class="dt">df =</span> <span class="kw">degf</span>(.), </span>
<span id="cb211-4"><a href="Complex.html#cb211-4"></a>                         <span class="dt">deff =</span> <span class="ot">TRUE</span> ),</span>
<span id="cb211-5"><a href="Complex.html#cb211-5"></a>                    <span class="dt">Var=</span> <span class="kw">survey_var</span>(score) )</span>
<span id="cb211-6"><a href="Complex.html#cb211-6"></a><span class="kw">print.data.frame</span>(<span class="kw">round</span>(rslts_cl, <span class="dv">2</span>))</span></code></pre></div>
<pre><code>##      Mn Mn_se Mn_low Mn_upp Mn_deff    Var Var_se
## 1 40.77  3.66  32.12  49.42    2.31 185.28  40.72</code></pre>
<p>So, we have an estimated mean of the score (whatever construct this happens to be, such as students’ judgments of school climate) of <span class="math inline">\(40.77\)</span> and a 95% confidence interval of <span class="math inline">\(( 32.12, 49.42)\)</span>.</p>
</div>
<div id="effective-sample-size" class="section level3">
<h3><span class="header-section-number">7.4.4</span> Effective sample size</h3>
<p>We can calculate the effective sample size from the number of students within the clusters, <em>n</em>, and the design effect. This is helpful for explaining the design effect to folks such as school personnel. First, let’s get the <em>n</em>-size of students.</p>
<p>To specify what the <em>sample</em> size of our smallest units (students) is, we can count the number of rows in the data using <code>nrow(dat)</code>. This is useful if each row is an individual person. We can also use <code>length(unique(dat$sid))</code> to count the number of observations that are unique in the student ID column.<a href="#fn37" class="footnote-ref" id="fnref37"><sup>37</sup></a> Either way, we get the same number.</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="Complex.html#cb213-1"></a>n &lt;-<span class="st"> </span><span class="kw">length</span>(<span class="kw">unique</span>(dat<span class="op">$</span>sid)) </span>
<span id="cb213-2"><a href="Complex.html#cb213-2"></a>n</span></code></pre></div>
<pre><code>## [1] 32</code></pre>
<p>As expected, there are 32 units (students) in our sample. Here’s the effective sample size, which is calculable as <span class="math inline">\(\frac{n}{\text{design effect}}\)</span>.<a href="#fn38" class="footnote-ref" id="fnref38"><sup>38</sup></a></p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="Complex.html#cb215-1"></a>rslts_cl &lt;-<span class="st"> </span>rslts_cl <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">EffSS =</span> n<span class="op">/</span>Mn_deff)</span>
<span id="cb215-2"><a href="Complex.html#cb215-2"></a><span class="kw">print.data.frame</span>(<span class="kw">round</span>(rslts_cl, <span class="dv">2</span>))</span></code></pre></div>
<pre><code>##      Mn Mn_se Mn_low Mn_upp Mn_deff    Var Var_se EffSS
## 1 40.77  3.66  32.12  49.42    2.31 185.28  40.72 13.84</code></pre>
<p>The standard error with this design is about what it would be with a simple random sample of <span class="math inline">\(13.84\)</span> (or rounding up, <span class="math inline">\(14\)</span>) students from the population. This shows the penalizing effect that we have correctly applied to the data.</p>
</div>
<div id="estimating-the-mean-per-cluster" class="section level3">
<h3><span class="header-section-number">7.4.5</span> Estimating the mean per cluster</h3>
<p>Sometimes we want to also report the mean per school. We can use the <code>group_by()</code> function to specify what the grouping is before we apply the functions. Here, we’re grouping by school, then estimating the mean and variance<a href="#fn39" class="footnote-ref" id="fnref39"><sup>39</sup></a>:</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="Complex.html#cb217-1"></a>M_by_schl &lt;-<span class="st"> </span>des_cl <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb217-2"><a href="Complex.html#cb217-2"></a><span class="st">              </span><span class="kw">group_by</span>(school) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb217-3"><a href="Complex.html#cb217-3"></a><span class="st">                </span><span class="kw">summarize</span>(<span class="dt">Mn =</span> <span class="kw">survey_mean</span>(score),</span>
<span id="cb217-4"><a href="Complex.html#cb217-4"></a>                          <span class="dt">Var=</span> <span class="kw">survey_var</span>(score))</span>
<span id="cb217-5"><a href="Complex.html#cb217-5"></a><span class="kw">print.data.frame</span>(<span class="kw">round</span>(M_by_schl,<span class="dv">2</span>))</span></code></pre></div>
<pre><code>##   school    Mn Mn_se    Var Var_se
## 1      1 47.23     0 111.95      0
## 2      2 55.00     0 196.73      0
## 3      3 34.40     0  37.71      0
## 4      4 52.22     0 151.26      0
## 5      5 35.65     0 216.99      0
## 6      6 43.55     0  82.89      0
## 7      7 25.50     0 100.05      0
## 8      8 32.60     0  17.19      0</code></pre>
</div>
<div id="two-stage-cluster-sampled-design" class="section level3">
<h3><span class="header-section-number">7.4.6</span> Two-stage cluster-sampled design</h3>
<p>The method so far has assumed that the units within the clusters were the population within those clusters. For example, if we surveyed all of the students in our selected schools. In a two-stage design, we have the extra step of randomly selecting units within the clusters.</p>
<p>We first have to prepare the data. Let’s pretend we had a <em>population</em> of 100 students within each school from which we had randomly sampled. It is super unlikely that we’d ever have a data set with the same population size in all of the schools. This is only a demonstration—in our actual schools, we will probably know the total number in each school. There are big schools and small schools.</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="Complex.html#cb219-1"></a>dat<span class="op">$</span>N_cl_s &lt;-<span class="st"> </span><span class="dv">100</span></span></code></pre></div>
<p>Now, we can use this column in the data set.</p>
<p>In the design, we specify column that identifies the within-cluster elements that were randomly selected from each cluster. Here it is <code>sid</code> in the <code>id =</code> line. Also, in the <code>fpc =</code> line, we specify the column in the data that includes the <em>n</em>-size within each cluster. For each of these two lines, the first argument is the primary sampling unit (the clusters) and the second is the within-cluster element—the secondary sampling unit.</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="Complex.html#cb220-1"></a>des_cl2 &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb220-2"><a href="Complex.html#cb220-2"></a><span class="st">               </span><span class="kw">as_survey_design</span>(<span class="dt">id =</span> <span class="kw">c</span>(school, sid), </span>
<span id="cb220-3"><a href="Complex.html#cb220-3"></a>                               <span class="dt">fpc =</span> <span class="kw">c</span>(N_cl, N_cl_s))</span>
<span id="cb220-4"><a href="Complex.html#cb220-4"></a><span class="kw">summary</span>(des_cl2) </span></code></pre></div>
<pre><code>## 2 - level Cluster Sampling design
## With (8, 32) clusters.
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 3.2e-07 3.2e-07 3.2e-07 3.2e-07 3.2e-07 3.2e-07 
## Population size (PSUs): 1e+06 
## Data variables:
## [1] &quot;sid&quot;      &quot;school&quot;   &quot;district&quot; &quot;score&quot;    &quot;weight&quot;   &quot;N_cl&quot;     &quot;N_cl_s&quot;</code></pre>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="Complex.html#cb222-1"></a>rslts_cl2 &lt;-<span class="st"> </span>des_cl2 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb222-2"><a href="Complex.html#cb222-2"></a><span class="st">          </span><span class="kw">summarize</span>(<span class="dt">Mn =</span> <span class="kw">survey_mean</span>(score, </span>
<span id="cb222-3"><a href="Complex.html#cb222-3"></a>                         <span class="dt">vartype =</span> <span class="kw">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>), <span class="dt">df =</span> <span class="kw">degf</span>(.), </span>
<span id="cb222-4"><a href="Complex.html#cb222-4"></a>                         <span class="dt">deff =</span> <span class="ot">TRUE</span> ),</span>
<span id="cb222-5"><a href="Complex.html#cb222-5"></a>                    <span class="dt">Var=</span> <span class="kw">survey_var</span>(score) )</span>
<span id="cb222-6"><a href="Complex.html#cb222-6"></a>rslts_cl2 &lt;-<span class="st"> </span>rslts_cl2 <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">EffSS =</span> n<span class="op">/</span>Mn_deff)</span>
<span id="cb222-7"><a href="Complex.html#cb222-7"></a><span class="kw">print.data.frame</span>(<span class="kw">round</span>(rslts_cl2,<span class="dv">2</span>))</span></code></pre></div>
<pre><code>##      Mn Mn_se Mn_low Mn_upp Mn_deff    Var Var_se EffSS
## 1 40.77  3.66  32.12  49.42    2.31 185.28  40.72 13.84</code></pre>
<p>The results are not that different from the single-stage cluster-sample design we just analyzed—in fact, they appear to be identical in this particular case.<a href="#fn40" class="footnote-ref" id="fnref40"><sup>40</sup></a> Again, this is an artificial data set. In a clinical setting, we would expect the results to differ because the number of secondary sampling units will likely differ across clusters. That is the <code>N_cl_s</code> of students within one school will differ from the <code>N_cl_s</code> of students in another school.</p>
</div>
<div id="estimating-the-mean-per-cluster-1" class="section level3">
<h3><span class="header-section-number">7.4.7</span> Estimating the mean per cluster</h3>
<p>We can use the <code>group_by()</code> function, as we did above with the one-stage model, to specify what the grouping is before we apply the functions.</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="Complex.html#cb224-1"></a>M_by_schl2 &lt;-<span class="st"> </span>des_cl2 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb224-2"><a href="Complex.html#cb224-2"></a><span class="st">              </span><span class="kw">group_by</span>(school) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb224-3"><a href="Complex.html#cb224-3"></a><span class="st">                </span><span class="kw">summarize</span>(<span class="dt">Mn =</span> <span class="kw">survey_mean</span>(score),</span>
<span id="cb224-4"><a href="Complex.html#cb224-4"></a>                          <span class="dt">Var=</span> <span class="kw">survey_var</span>(score))</span>
<span id="cb224-5"><a href="Complex.html#cb224-5"></a><span class="kw">print.data.frame</span>(<span class="kw">round</span>(M_by_schl2,<span class="dv">2</span>))</span></code></pre></div>
<pre><code>##   school    Mn Mn_se    Var Var_se
## 1      1 47.23  0.01 111.95   0.18
## 2      2 55.00  0.02 196.73   0.31
## 3      3 34.40  0.01  37.71   0.06
## 4      4 52.22  0.02 151.26   0.22
## 5      5 35.65  0.02 216.99   0.36
## 6      6 43.55  0.01  82.89   0.11
## 7      7 25.50  0.01 100.05   0.17
## 8      8 32.60  0.01  17.19   0.02</code></pre>
<p>Now, the standard errors at the school level are <em>not</em> zero. This is because we randomly sampled 4 students from each school, which had a population of 100 students per school.</p>
</div>
</div>
<div id="stratified-design" class="section level2">
<h2><span class="header-section-number">7.5</span> Stratified design</h2>
<p>The strata are districts. In this sampling design, we are randomly selecting students from each stratum and pretending that the school cluster did not exist when we designed and carried out this sampling plan.</p>
<div id="preparing-our-data-set" class="section level3">
<h3><span class="header-section-number">7.5.1</span> Preparing our data set</h3>
<p>Again, we’ll effectively make the finite population correction negligible and assume that the population is big. This yields a more conservative confidence interval than if we had specified a smaller finite population, which would likely be the case if we were sampling from districts that were small.</p>
<p>Here, our primary sampling unit is the lowest element of our sampling plan. In other words, we had sampled the students from the strata. In the data set, each student is a row.</p>
<p>We need to specify how many sampled units are in each stratum. In other words, how many students are in each district. Normally, there will be a different number of students in a district (some districts are large; some are small). Here, for convenience (and to replicate the results in Heeringa and colleagues’ chapter), we will make them all very large, maybe something like 25,000,000 students in each district. In the column in the data, we can think of the students as coming from their district of this population size.</p>
<p>Traditionally, <em>h</em> stands for stratum in research designs. So, we’ll call our object <code>des_h</code> to help us remember it is a stratified design.</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="Complex.html#cb226-1"></a>dat<span class="op">$</span>N_h &lt;-<span class="st"> </span><span class="dv">25000000</span></span></code></pre></div>
</div>
<div id="step-1-specifying-the-design-1" class="section level3">
<h3><span class="header-section-number">7.5.2</span> Step 1: Specifying the design</h3>
<p>Notice that we have three arguments: <code>id = 1</code> to specify that the primary sampling unit is each row in the data set.<a href="#fn41" class="footnote-ref" id="fnref41"><sup>41</sup></a> The <code>strata = district</code> specifies the stratum. The <code>fpc = N_h</code> specifies the column in our data that includes the population size of each stratum.</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="Complex.html#cb227-1"></a>des_h &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb227-2"><a href="Complex.html#cb227-2"></a><span class="st">  </span><span class="kw">as_survey_design</span>(<span class="dt">id =</span> <span class="dv">1</span>, </span>
<span id="cb227-3"><a href="Complex.html#cb227-3"></a>                   <span class="dt">strata =</span> district,</span>
<span id="cb227-4"><a href="Complex.html#cb227-4"></a>                   <span class="dt">fpc =</span> N_h)</span>
<span id="cb227-5"><a href="Complex.html#cb227-5"></a><span class="kw">summary</span>(des_h) </span></code></pre></div>
<pre><code>## Stratified Independent Sampling design
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 3.2e-07 3.2e-07 3.2e-07 3.2e-07 3.2e-07 3.2e-07 
## Stratum Sizes: 
##            1 2 3 4
## obs        8 8 8 8
## design.PSU 8 8 8 8
## actual.PSU 8 8 8 8
## Population stratum sizes (PSUs): 
##       1       2       3       4 
## 2.5e+07 2.5e+07 2.5e+07 2.5e+07 
## Data variables:
## [1] &quot;sid&quot;      &quot;school&quot;   &quot;district&quot; &quot;score&quot;    &quot;weight&quot;   &quot;N_cl&quot;     &quot;N_cl_s&quot;  
## [8] &quot;N_h&quot;</code></pre>
<p>Again, in our particular example, we’re saying each stratum has the same number of students but if we had a different population size in each stratum, we could specify <code>data$N_h</code> to be that number within each stratum. For example, if District 1’s population were small, with 1,000 students, all the students in our sample would have N_h = 1000; if District 2 were larger, with 20,000 students, the students in this district in our sample have N_h = 20000.</p>
</div>
<div id="step-2-calculating-the-estimates-1" class="section level3">
<h3><span class="header-section-number">7.5.3</span> Step 2: Calculating the estimates</h3>
<p>This step is identical to what we did before with the other example designs above. The difference is the design itself, which we created in the previous step.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="Complex.html#cb229-1"></a>rslts_h &lt;-<span class="st"> </span>des_h <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb229-2"><a href="Complex.html#cb229-2"></a><span class="st">        </span><span class="kw">summarize</span>(<span class="dt">Mn =</span> <span class="kw">survey_mean</span>(score, </span>
<span id="cb229-3"><a href="Complex.html#cb229-3"></a>                       <span class="dt">vartype =</span> <span class="kw">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>), <span class="dt">df =</span> <span class="kw">degf</span>(.), </span>
<span id="cb229-4"><a href="Complex.html#cb229-4"></a>                       <span class="dt">deff =</span> <span class="ot">TRUE</span> ),</span>
<span id="cb229-5"><a href="Complex.html#cb229-5"></a>                  <span class="dt">Var=</span> <span class="kw">survey_var</span>(score) )</span>
<span id="cb229-6"><a href="Complex.html#cb229-6"></a>rslts_h</span></code></pre></div>
<pre><code>##         Mn    Mn_se   Mn_low   Mn_upp   Mn_deff      Var   Var_se
## 1 40.76875 2.039311 36.59141 44.94609 0.7182879 185.2758 47.70248</code></pre>
<p>Here’s the effective sample size from <em>n</em> and the design effect.
First, let’s remember how many observations are in our data:</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="Complex.html#cb231-1"></a>n</span></code></pre></div>
<pre><code>## [1] 32</code></pre>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="Complex.html#cb233-1"></a>rslts_h &lt;-<span class="st"> </span>rslts_h <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">EffSS =</span> n<span class="op">/</span>Mn_deff)</span>
<span id="cb233-2"><a href="Complex.html#cb233-2"></a>rslts_h</span></code></pre></div>
<pre><code>##         Mn    Mn_se   Mn_low   Mn_upp   Mn_deff      Var   Var_se    EffSS
## 1 40.76875 2.039311 36.59141 44.94609 0.7182879 185.2758 47.70248 44.55038</code></pre>
<p>As an extra step, we could report the mean per stratum:</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="Complex.html#cb235-1"></a>M_by_dist &lt;-<span class="st"> </span>des_h <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb235-2"><a href="Complex.html#cb235-2"></a><span class="st">             </span><span class="kw">group_by</span>(district) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb235-3"><a href="Complex.html#cb235-3"></a><span class="st">               </span><span class="kw">summarize</span>(<span class="dt">Mn =</span> <span class="kw">survey_mean</span>(score),</span>
<span id="cb235-4"><a href="Complex.html#cb235-4"></a>                         <span class="dt">Var=</span> <span class="kw">survey_var</span>(score))</span>
<span id="cb235-5"><a href="Complex.html#cb235-5"></a>M_by_dist</span></code></pre></div>
<pre><code>## # A tibble: 4 x 5
##   district    Mn Mn_se   Var Var_se
##      &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1        1  51.1  4.32 150.    67.4
## 2        2  43.3  4.63 172.    73.0
## 3        3  39.6  4.28 146.    84.8
## 4        4  29.0  2.84  64.6   44.4</code></pre>
</div>
</div>
<div id="stratified-cluster-sampled-design" class="section level2">
<h2><span class="header-section-number">7.6</span> Stratified cluster-sampled design</h2>
<p>In this design, the clusters were randomly sampled from each stratum. In this artificial data set, there were four districts and from each district, two schools were randomly selected from the sampling frame that contained the list of all schools in the population (by district).</p>
<div id="preparing-the-data-1" class="section level3">
<h3><span class="header-section-number">7.6.1</span> Preparing the data</h3>
<p>In the data set, we need to specify the number of clusters per stratum. For this example, to make it consistent with what Heeringa and colleagues present in their chapter, we set the population as very high. This results in a negligible (tiny) finite population correction. Let’s use something like <em>n</em>/<em>N</em> = 0.000008 for each stratum, which would occur if we had <em>n</em> = 2 schools in each stratum’s sample and <em>N</em> = 250,000 schools in its population.</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="Complex.html#cb237-1"></a>dat<span class="op">$</span>N_hcl &lt;-<span class="st"> </span><span class="dv">250000</span></span></code></pre></div>
<p>So, we have a column in our data that we will use to say that there are 250,000 schools in each stratum.<a href="#fn42" class="footnote-ref" id="fnref42"><sup>42</sup></a></p>
</div>
<div id="step-1-specifying-the-design-2" class="section level3">
<h3><span class="header-section-number">7.6.2</span> Step 1: Specifying the design</h3>
<p>The design step is similar to what we used in the other cluster-sampled and stratified designs. Here, the variable used as the primary sampling unit is school, which is what <code>id = school</code> refers to. The stratum variable in the data set is district, <code>strata = district</code>, and the population size of each stratum is the column in the data we just created, <code>fpc = N_hcl</code>.</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="Complex.html#cb238-1"></a>des_hcl &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb238-2"><a href="Complex.html#cb238-2"></a><span class="st">  </span><span class="kw">as_survey_design</span>(<span class="dt">id =</span> school,</span>
<span id="cb238-3"><a href="Complex.html#cb238-3"></a>                   <span class="dt">strata =</span> district,</span>
<span id="cb238-4"><a href="Complex.html#cb238-4"></a>                   <span class="dt">fpc =</span> N_hcl)</span>
<span id="cb238-5"><a href="Complex.html#cb238-5"></a><span class="kw">summary</span>(des_hcl) </span></code></pre></div>
<pre><code>## Stratified 1 - level Cluster Sampling design
## With (8) clusters.
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   8e-06   8e-06   8e-06   8e-06   8e-06   8e-06 
## Stratum Sizes: 
##            1 2 3 4
## obs        8 8 8 8
## design.PSU 2 2 2 2
## actual.PSU 2 2 2 2
## Population stratum sizes (PSUs): 
##      1      2      3      4 
## 250000 250000 250000 250000 
## Data variables:
## [1] &quot;sid&quot;      &quot;school&quot;   &quot;district&quot; &quot;score&quot;    &quot;weight&quot;   &quot;N_cl&quot;     &quot;N_cl_s&quot;  
## [8] &quot;N_h&quot;      &quot;N_hcl&quot;</code></pre>
<p>We can see the sample sizes of the strata and the primary sampling unit (PSU) per stratum. This very simple example has only two clusters (schools) within each stratum (district).</p>
</div>
<div id="step-2-calculating-the-estimates-2" class="section level3">
<h3><span class="header-section-number">7.6.3</span> Step 2: Calculating the estimates</h3>
<p>This step is the same as the other designs above. We can also tag on the effective sample size.</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="Complex.html#cb240-1"></a>rslts_hcl &lt;-<span class="st"> </span>des_hcl <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb240-2"><a href="Complex.html#cb240-2"></a><span class="st">        </span><span class="kw">summarize</span>(<span class="dt">Mn =</span> <span class="kw">survey_mean</span>(score, </span>
<span id="cb240-3"><a href="Complex.html#cb240-3"></a>                       <span class="dt">vartype =</span> <span class="kw">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>), <span class="dt">df =</span> <span class="kw">degf</span>(.), </span>
<span id="cb240-4"><a href="Complex.html#cb240-4"></a>                       <span class="dt">deff =</span> <span class="ot">TRUE</span> ),</span>
<span id="cb240-5"><a href="Complex.html#cb240-5"></a>                  <span class="dt">Var=</span> <span class="kw">survey_var</span>(score) )</span>
<span id="cb240-6"><a href="Complex.html#cb240-6"></a><span class="co"># effective sample size</span></span>
<span id="cb240-7"><a href="Complex.html#cb240-7"></a>n &lt;-<span class="st"> </span><span class="kw">length</span>(<span class="kw">unique</span>(dat<span class="op">$</span>sid)) </span>
<span id="cb240-8"><a href="Complex.html#cb240-8"></a>rslts_hcl &lt;-<span class="st"> </span>rslts_hcl <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">EffSS =</span> n<span class="op">/</span>Mn_deff)</span>
<span id="cb240-9"><a href="Complex.html#cb240-9"></a>rslts_hcl</span></code></pre></div>
<pre><code>##         Mn    Mn_se   Mn_low   Mn_upp  Mn_deff      Var   Var_se    EffSS
## 1 40.76875 2.769807 33.07853 48.45897 1.325055 185.2758 49.58831 24.14994</code></pre>
</div>
<div id="mean-per-stratum" class="section level3">
<h3><span class="header-section-number">7.6.4</span> Mean per stratum</h3>
<p>If our only objective is to draw inferences about the population, we can stop there. Sometimes, we also seek to report the mean per stratum. We can group by the stratum variable—district in this case—and estimate the means and variances. These estimates are what were combined in the estimate of the entire population.</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="Complex.html#cb242-1"></a>M_by_Dist_cl &lt;-<span class="st"> </span>des_hcl <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb242-2"><a href="Complex.html#cb242-2"></a><span class="st">             </span><span class="kw">group_by</span>(district) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb242-3"><a href="Complex.html#cb242-3"></a><span class="st">               </span><span class="kw">summarize</span>(<span class="dt">Mn =</span> <span class="kw">survey_mean</span>(score),</span>
<span id="cb242-4"><a href="Complex.html#cb242-4"></a>                         <span class="dt">Var=</span> <span class="kw">survey_var</span>(score))</span>
<span id="cb242-5"><a href="Complex.html#cb242-5"></a>M_by_Dist_cl</span></code></pre></div>
<pre><code>## # A tibble: 4 x 5
##   district    Mn Mn_se   Var Var_se
##      &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1        1  51.1  3.89 150.    36.3
## 2        2  43.3  8.91 172.    48.7
## 3        3  39.6  3.95 146.    57.5
## 4        4  29.0  3.55  64.6   35.5</code></pre>
</div>
</div>
<div id="a-simple-random-sample-design-for-comparison" class="section level2">
<h2><span class="header-section-number">7.7</span> A simple random sample design, for comparison</h2>
<p>The simple random sample design assumes that the students were randomly drawn from a population of students. There is no clustering or stratification in the design or analysis.</p>
<div id="preparing-our-data-set-1" class="section level3">
<h3><span class="header-section-number">7.7.1</span> Preparing our data set</h3>
<p>We can, of course, simply use Base R functions to estimate the mean and variance and then calculate the standard error as <span class="math inline">\(\sqrt{\frac{Var}{n}}\)</span> and then use the calculations we used in the prior chapter. However, the srvyr package also allows us to use the finite population correction.</p>
<p>If we assumed the population were huge, our finite population correction would be negligible. Let’s do this:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="Complex.html#cb244-1"></a>n &lt;-<span class="st"> </span><span class="kw">length</span>(<span class="kw">unique</span>(dat<span class="op">$</span>sid)) <span class="co"># sample n</span></span>
<span id="cb244-2"><a href="Complex.html#cb244-2"></a>dat<span class="op">$</span>N &lt;-<span class="st"> </span><span class="dv">10</span><span class="op">^</span><span class="dv">8</span> <span class="co"># Population N</span></span>
<span id="cb244-3"><a href="Complex.html#cb244-3"></a>des_srs &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb244-4"><a href="Complex.html#cb244-4"></a><span class="st">               </span><span class="kw">as_survey_design</span>(<span class="dt">id =</span> <span class="dv">1</span>, <span class="dt">fpc =</span> N)</span>
<span id="cb244-5"><a href="Complex.html#cb244-5"></a>rslts_srs &lt;-<span class="st"> </span>des_srs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb244-6"><a href="Complex.html#cb244-6"></a><span class="st">        </span><span class="kw">summarize</span>(<span class="dt">Mn =</span> <span class="kw">survey_mean</span>(score, <span class="dt">vartype =</span> <span class="kw">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>), <span class="dt">df =</span> <span class="kw">degf</span>(.)),</span>
<span id="cb244-7"><a href="Complex.html#cb244-7"></a>                  <span class="dt">Var=</span> <span class="kw">survey_var</span>(score)) </span>
<span id="cb244-8"><a href="Complex.html#cb244-8"></a>rslts_srs &lt;-<span class="st"> </span>rslts_srs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb244-9"><a href="Complex.html#cb244-9"></a><span class="st">               </span><span class="kw">mutate</span>(<span class="dt">EffSS   =</span> n,</span>
<span id="cb244-10"><a href="Complex.html#cb244-10"></a>                      <span class="dt">Mn_deff =</span> <span class="dv">1</span>)</span>
<span id="cb244-11"><a href="Complex.html#cb244-11"></a><span class="kw">print.data.frame</span>( <span class="kw">round</span>(rslts_srs, <span class="dv">2</span>) )</span></code></pre></div>
<pre><code>##      Mn Mn_se Mn_low Mn_upp    Var Var_se EffSS Mn_deff
## 1 40.77  2.41  35.86  45.68 185.28  45.96    32       1</code></pre>
<p>Notice that the results are similar to the results we’d get using <a href="Descripts.html#IntrvlDesc">the procedures in the previous chapter</a>.</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="Complex.html#cb246-1"></a>score_M  &lt;-<span class="st"> </span><span class="kw">mean</span>(dat<span class="op">$</span>score)</span>
<span id="cb246-2"><a href="Complex.html#cb246-2"></a>score_sd &lt;-<span class="st"> </span><span class="kw">sd</span>(dat<span class="op">$</span>score)</span>
<span id="cb246-3"><a href="Complex.html#cb246-3"></a>score_n  &lt;-<span class="st"> </span><span class="kw">nrow</span>(dat)</span>
<span id="cb246-4"><a href="Complex.html#cb246-4"></a>score_se &lt;-<span class="st"> </span>score_sd<span class="op">/</span><span class="kw">sqrt</span>(score_n)</span>
<span id="cb246-5"><a href="Complex.html#cb246-5"></a>LB_t     &lt;-<span class="st">  </span>score_M <span class="op">-</span><span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dt">df =</span> score_n <span class="dv">-1</span>)<span class="op">*</span>score_se</span>
<span id="cb246-6"><a href="Complex.html#cb246-6"></a>UB_t     &lt;-<span class="st">  </span>score_M <span class="op">+</span><span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dt">df =</span> score_n <span class="dv">-1</span>)<span class="op">*</span>score_se</span>
<span id="cb246-7"><a href="Complex.html#cb246-7"></a><span class="kw">round</span>((<span class="kw">c</span>(<span class="dt">M =</span> score_M, <span class="dt">var =</span> score_sd<span class="op">^</span><span class="dv">2</span>, <span class="dt">n =</span> score_n, <span class="dt">se =</span> score_se, </span>
<span id="cb246-8"><a href="Complex.html#cb246-8"></a>   <span class="dt">CI_upper =</span> LB_t, <span class="dt">CI_lower =</span> UB_t)), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##        M      var        n       se CI_upper CI_lower 
##    40.77   185.28    32.00     2.41    35.86    45.68</code></pre>
<p>If our finite population were small, such as <em>N</em> = 100, our standard error would be smaller and our confidence interval would be narrower, indicating our estimate of the mean is a more precise measure of a population of size 100.</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="Complex.html#cb248-1"></a>dat<span class="op">$</span>N2 &lt;-<span class="st"> </span><span class="dv">100</span> <span class="co"># Small Population N</span></span>
<span id="cb248-2"><a href="Complex.html#cb248-2"></a>des_srs2 &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">as_survey_design</span>(<span class="dt">id =</span> <span class="dv">1</span>, <span class="dt">fpc =</span> N2)</span>
<span id="cb248-3"><a href="Complex.html#cb248-3"></a>rslts_srs2 &lt;-<span class="st"> </span>des_srs <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb248-4"><a href="Complex.html#cb248-4"></a><span class="st">        </span><span class="kw">summarize</span>(<span class="dt">Mn =</span> <span class="kw">survey_mean</span>(score, <span class="dt">vartype =</span> <span class="kw">c</span>(<span class="st">&quot;se&quot;</span>,<span class="st">&quot;ci&quot;</span>), <span class="dt">df =</span> <span class="kw">degf</span>(.))) </span>
<span id="cb248-5"><a href="Complex.html#cb248-5"></a><span class="kw">print.data.frame</span>( <span class="kw">round</span>(rslts_srs2, <span class="dv">2</span>) )</span></code></pre></div>
<pre><code>##      Mn Mn_se Mn_low Mn_upp
## 1 40.77  2.41  35.86  45.68</code></pre>
<p>So, even though we can use Base R to estimate the confidence interval of a simple random sample, the survey and srvyr packages allow us to account for the finite population correction.</p>
</div>
</div>
<div id="comparing-all-design-scenarios" class="section level2">
<h2><span class="header-section-number">7.8</span> Comparing all design scenarios</h2>
<p>Note that we would <strong>not</strong> do this in practice. In practice, we would select a single design and report the results. This comparison is only for seeing how the designs operate.</p>
<pre><code>##                 Design    Mn Mn_se Mn_low Mn_upp Mn_deff EffSS    Var Var_se
## 1   Simple Rand. Samp. 40.77  2.41  35.86  45.68    1.00 32.00 185.28  45.96
## 2            Clustered 40.77  3.66  32.12  49.42    2.31 13.84 185.28  40.72
## 3  two-stage Clustered 40.77  3.66  32.12  49.42    2.31 13.84 185.28  40.72
## 4           Stratified 40.77  2.04  36.59  44.95    0.72 44.55 185.28  47.70
## 5 Stratified Clustered 40.77  2.77  33.08  48.46    1.33 24.15 185.28  49.59</code></pre>
<p>Compare this to Table 2.2 in Heeringa, et al. <span class="citation">(<a href="#ref-heeringa_applied_2010" role="doc-biblioref">2010</a>)</span>. The small differences (e.g., in the effective n-size) are due to rounding error in their chapter.</p>
<p>Of these designs, which seems to have the most precise estimate of the mean of the population? Which seems to be the provide the best balance between precision and feasibility in carrying out the sampling process?</p>
<hr />
<p>Updated on 2021-04-25.</p>
<hr />

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-R-srvyr">
<p>Freedman Ellis, G., &amp; Schneider, B. (2021). <em>Srvyr: Dplyr-like syntax for summary statistics of survey data</em>. <a href="https://CRAN.R-project.org/package=srvyr">https://CRAN.R-project.org/package=srvyr</a></p>
</div>
<div id="ref-heeringa_applied_2010">
<p>Heeringa, S. G., West, B. T., &amp; Berglund, P. A. (2010). <em>Applied survey data analysis</em>. Chapman &amp; Hall/CRC.</p>
</div>
<div id="ref-R-survey">
<p>Lumley, T. (2020). <em>Survey: Analysis of complex survey samples</em>. <a href="http://r-survey.r-forge.r-project.org/survey/">http://r-survey.r-forge.r-project.org/survey/</a></p>
</div>
<div id="ref-R-dplyr">
<p>Wickham, H., François, R., Henry, L., &amp; Müller, K. (2020). <em>Dplyr: A grammar of data manipulation</em>. <a href="https://CRAN.R-project.org/package=dplyr">https://CRAN.R-project.org/package=dplyr</a></p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="28">
<li id="fn28"><p>Whenever we use a package, it is a good idea to cite it. People work hard to create these (well usually—for some, it is disgustingly easy). To get the citation, we can use the <code>citation()</code> function, usually, as in <code>citation("srvyr")</code>. <a href="Complex.html#fnref28" class="footnote-back">↩︎</a></p></li>
<li id="fn29"><p>In their chapter, their variable of interest is persons’ ratings of the economy. We use the same data but for demonstration call the outcome variable <em>scores</em> and label the cases <em>students</em>, who are nested within the school clusters, which are in districts, serving as strata. For this demo, we will ignore weighting.<a href="Complex.html#fnref29" class="footnote-back">↩︎</a></p></li>
<li id="fn30"><p>Before we got to this step, we had previously calculated each student’s score, which is the <code>score</code> variable in our data set. This score might be a composite score calculated as the mean (or sum) across several items, as was demonstrated in the previous chapter.<a href="Complex.html#fnref30" class="footnote-back">↩︎</a></p></li>
<li id="fn31"><p>Strata serve as a kind of fixed effect or a blocking variable in ANOVA.<a href="Complex.html#fnref31" class="footnote-back">↩︎</a></p></li>
<li id="fn32"><p>For more information on this package, we can use <code>help(package = "srvyr")</code> or <a href="https://cran.r-project.org/web/packages/srvyr/vignettes/srvyr-vs-survey.html" class="uri">https://cran.r-project.org/web/packages/srvyr/vignettes/srvyr-vs-survey.html</a>.<a href="Complex.html#fnref32" class="footnote-back">↩︎</a></p></li>
<li id="fn33"><p>But we can also use the <code>fpctype = "correction"</code> argument to specify the type of fpc discussed in the Heeringa chapter (which was 1 - <em>n</em>/<em>N</em>). Unfortunately, although we get the correct design effect, the estimated standard error is wrong.<a href="Complex.html#fnref33" class="footnote-back">↩︎</a></p></li>
<li id="fn34"><p>We’re using piping, <code>%&gt;%</code> with this particular package just like how we did with the dplyr package. These are part of the tidyverse community of R packages.<a href="Complex.html#fnref34" class="footnote-back">↩︎</a></p></li>
<li id="fn35"><p>We can also use RStudio’s <code>View()</code> function to see it in an extra tab, with <code>View(rslts_M_cl)</code>.<a href="Complex.html#fnref35" class="footnote-back">↩︎</a></p></li>
<li id="fn36"><p>Clinical researchers tend not to report things like standard error of the variance. It is important to realize, however, that any point estimates from a sample, such as the means and variances, are estimates of the population and therefore have some degree of uncertainty, which is what the standard error reveals.<a href="Complex.html#fnref36" class="footnote-back">↩︎</a></p></li>
<li id="fn37"><p>Sometimes data structures, such as those used in longitudinal analyses, have more than one row for each person. The <code>unique()</code> function makes sure we don’t count somebody with the same ID twice.<a href="Complex.html#fnref37" class="footnote-back">↩︎</a></p></li>
<li id="fn38"><p>The code below uses the <code>mutate()</code> function. This is from the dplyr package (for data wrangling) and is the same as this code: <code>rslts_cl$EffSS = n/rslts_cl$Mn_deff</code>. The benefit of <code>mutate()</code> is we can create multiple variables in the mutate function and we don’t have to specify the data frame, such as with <em>rslts_cl$</em>Mn_deff.<a href="Complex.html#fnref38" class="footnote-back">↩︎</a></p></li>
<li id="fn39"><p>This function is part of the tidyverse language in R, which is what the dplyr and srvyr packages use.<a href="Complex.html#fnref39" class="footnote-back">↩︎</a></p></li>
<li id="fn40"><p>In this particular data set, the standard error estimates of the mean and variance in the one-stage and two-stage cluster designs appear to be identical because we have set the population <em>N</em> sizes of the students within the clusters to be the same across all of the clusters. This is not likely what would occur in practice.<a href="Complex.html#fnref40" class="footnote-back">↩︎</a></p></li>
<li id="fn41"><p>The srvyr and survey packages still include an argument for the PSU (<code>id =</code>), and instead of clusters as was done with cluster-sampling, we specify <code>id = 1</code>, where 1 tells R to treat the individual cases as the PSU. If you use the survey package directly, instead of the srvyr package as a wrap around, it is <code>id = ~1</code>, with the tilde added.<a href="Complex.html#fnref41" class="footnote-back">↩︎</a></p></li>
<li id="fn42"><p>Obviously, that is a lot of schools to have in a district. This is does make the error more conservatively estimated. Also, this seems to be in the spirit of model-based inference, where the population is more theoretical. For more on model- and design-based inferences, especially as applied in research, consult Sterba <span class="citation">(<a href="#ref-sterba_alternative_2009" role="doc-biblioref">2009</a>)</span>.<a href="Complex.html#fnref42" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="Reliability.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Getting-started.pdf", "Getting-started.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
