% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Preparing and Analyzing Survey Data in R},
  pdfauthor={George M. Harrison  University of Hawai`i at Mānoa, College of Education},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{amsthm}
\makeatletter
\def\thm@space@setup{%
  \thm@preskip=8pt plus 2pt minus 4pt
  \thm@postskip=\thm@preskip
}
\makeatother
\usepackage[]{natbib}
\bibliographystyle{plainnat}

\title{Preparing and Analyzing Survey Data in R}
\author{George M. Harrison University of Hawai`i at Mānoa, College of Education}
\date{April, 2021}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

This site provides guidance in preparing and analyzing survey data in R. We begin with a chapter on preparing data and managing packages, then practice estimating descriptive statistics and internal-consistency reliability coefficients. We will eventually end with an example of how to analyze complex survey data, such as that collected from clustered and stratified samples.

Along the way, there are explanations about how to use R, including the use of functions and packages. One way to study using this guide is to follow along with your own RStudio file opened while you try out the code. Copying and pasting is one way. You can keep notes for yourself in your R code by preceding your annotations with the hash symbol (\#).

The final assignment will ask you to practice much of what is in this tutorial. It is also wise to keep your R code files for future references when you do use it analyze your own data.

\hypertarget{prior-knowledge}{%
\subsection{Prior knowledge}\label{prior-knowledge}}

Before going through these tutorials, it is necessary to have installed R and RStudio. Also, it is highly recommended that you practice some of the basics, such as those in the introductory tutorial at \url{http://www2.hawaii.edu/~georgeha/surveys/_book/}

\hypertarget{Prepping}{%
\section{Preparing the Data}\label{Prepping}}

In this section, we are using R to prepare data for analysis. We will use mock data from the TIMSS Teacher Questionnaire.

\hypertarget{import-the-data-from-the-csv-file}{%
\subsection{Import the data from the CSV file}\label{import-the-data-from-the-csv-file}}

I generated these mock data as fake responses to the TIMSS math teacher questionnaire \url{https://nces.ed.gov/timss/pdf/2015_8th_grade_Teacher_Questionnaire_Math.pdf}. You can also get real data from their site. We could use the code below with those data (though we would need to address missing values). In other words, this can be part of our data analysis plan and we created data using our best guess about how people would respond. Then, we assume it functions well, and then analyze the real data.

If you've opened this RStudio file from the same folder that contains the CSV file, \texttt{Week13\_Timss\_Mock\_Raw.csv}, your working directory will be that location and you can import data using this code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{'Week13_Timss_Mock_Raw.csv'}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

If you prefer to download the data, it will be temporarily available here:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"http://www2.hawaii.edu/~georgeha/Handouts/Week13_Timss_Mock_Raw.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{examining-the-imported-data-set}{%
\subsubsection{Examining the imported data set}\label{examining-the-imported-data-set}}

We can print the first and last five rows of data using the \texttt{head()} and \texttt{tail()} functions:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(timss)}
\KeywordTok{tail}\NormalTok{(timss)}
\end{Highlighting}
\end{Shaded}

We can also select which rows to print using indexing. Here, it prints only rows 1, 3, 5, 7, and 9:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{7}\NormalTok{,}\DecValTok{9}\NormalTok{), ]}
\end{Highlighting}
\end{Shaded}

We can also print the data set to console or view it in a new tab.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss}
\KeywordTok{View}\NormalTok{(timss)}
\end{Highlighting}
\end{Shaded}

Let's check that the data set has the number of observations we expect. We should have 30 mock teachers. This prints the number of rows in the column labeled \texttt{TID}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{length}\NormalTok{(timss}\OperatorTok{$}\NormalTok{TID)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 30
\end{verbatim}

Good. There are 30. We can also see what how many rows and columns there are with the \texttt{dim()} function, which prints the number of rows then the number of columns.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(timss)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 30 31
\end{verbatim}

Let's see what the names of the variables are:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{names}\NormalTok{(timss)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "TID"            "Q4_Age"         "Q5_Degree"      "Q6_Math"       
##  [5] "Q6_Bio"         "Q6_Phys"        "Q6_Chem"        "Q6_EarthS"     
##  [9] "Q6_EdMat"       "Q6_EdSci"       "Q6_EdGen"       "Q6_Othr"       
## [13] "Q13_NumSs"      "Q15_StCentrd_a" "Q15_StCentrd_b" "Q15_StCentrd_c"
## [17] "Q15_StCentrd_d" "Q15_StCentrd_e" "Q15_StCentrd_f" "Q15_StCentrd_g"
## [21] "Q16_Lims_a"     "Q16_Lims_b"     "Q16_Lims_c"     "Q16_Lims_d"    
## [25] "Q16_Lims_e"     "Q16_Lims_f"     "Q16_Lims_g"     "Q17_Mins"      
## [29] "Q19_Didac_a"    "Q19_Didac_b"    "Q19_Didac_c"
\end{verbatim}

If we enclose this code in the \texttt{dput()} function, we can then copy and paste names into code.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dput}\NormalTok{(}\KeywordTok{names}\NormalTok{(timss)) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## c("TID", "Q4_Age", "Q5_Degree", "Q6_Math", "Q6_Bio", "Q6_Phys", 
## "Q6_Chem", "Q6_EarthS", "Q6_EdMat", "Q6_EdSci", "Q6_EdGen", "Q6_Othr", 
## "Q13_NumSs", "Q15_StCentrd_a", "Q15_StCentrd_b", "Q15_StCentrd_c", 
## "Q15_StCentrd_d", "Q15_StCentrd_e", "Q15_StCentrd_f", "Q15_StCentrd_g", 
## "Q16_Lims_a", "Q16_Lims_b", "Q16_Lims_c", "Q16_Lims_d", "Q16_Lims_e", 
## "Q16_Lims_f", "Q16_Lims_g", "Q17_Mins", "Q19_Didac_a", "Q19_Didac_b", 
## "Q19_Didac_c")
\end{verbatim}

This will be handy if we wish to copy and paste a string of column names from our console into our code because it formats it with quotes around the names and commas in between them, which is what we want to use in the \texttt{c()} function.

\hypertarget{managing-the-structure-of-the-data}{%
\subsection{Managing the structure of the data}\label{managing-the-structure-of-the-data}}

Let's look at the structure of our data set, using the \texttt{str()} function.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(timss)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    30 obs. of  31 variables:
##  $ TID           : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Q4_Age        : num  2 3 3 2 5 6 5 2 4 3 ...
##  $ Q5_Degree     : num  4 4 4 5 3 4 5 4 4 4 ...
##  $ Q6_Math       : chr  "No" "No" "No" "No" ...
##  $ Q6_Bio        : chr  "No" "No" "No" "No" ...
##  $ Q6_Phys       : chr  "No" "No" "Yes" "No" ...
##  $ Q6_Chem       : chr  "No" "No" "No" "No" ...
##  $ Q6_EarthS     : chr  "No" "No" "No" "No" ...
##  $ Q6_EdMat      : chr  "No" "No" "No" "Yes" ...
##  $ Q6_EdSci      : chr  "No" "No" "No" "No" ...
##  $ Q6_EdGen      : chr  "Yes" "Yes" "No" "No" ...
##  $ Q6_Othr       : chr  "No" "No" "Yes" "No" ...
##  $ Q13_NumSs     : int  8 12 19 16 18 26 29 16 30 22 ...
##  $ Q15_StCentrd_a: int  2 3 3 1 2 3 4 1 4 3 ...
##  $ Q15_StCentrd_b: int  2 1 2 1 1 3 2 1 2 2 ...
##  $ Q15_StCentrd_c: int  1 4 2 2 3 3 2 1 2 2 ...
##  $ Q15_StCentrd_d: int  1 2 3 2 2 3 3 1 4 4 ...
##  $ Q15_StCentrd_e: int  2 2 3 1 2 3 4 2 2 2 ...
##  $ Q15_StCentrd_f: int  3 3 3 1 3 4 2 1 1 4 ...
##  $ Q15_StCentrd_g: int  1 2 3 1 2 3 3 1 3 3 ...
##  $ Q16_Lims_a    : int  2 1 2 1 1 2 3 1 3 1 ...
##  $ Q16_Lims_b    : int  1 1 2 2 1 1 2 1 3 2 ...
##  $ Q16_Lims_c    : int  3 3 3 3 3 3 3 2 2 2 ...
##  $ Q16_Lims_d    : int  2 2 2 2 2 2 2 1 2 3 ...
##  $ Q16_Lims_e    : int  1 1 2 2 1 2 2 2 2 2 ...
##  $ Q16_Lims_f    : int  1 1 1 1 1 1 1 1 2 1 ...
##  $ Q16_Lims_g    : int  2 1 2 1 1 1 1 2 1 1 ...
##  $ Q17_Mins      : int  160 180 190 200 210 180 200 240 150 160 ...
##  $ Q19_Didac_a   : int  3 4 2 3 3 3 2 3 2 1 ...
##  $ Q19_Didac_b   : int  3 2 1 4 1 4 2 2 2 2 ...
##  $ Q19_Didac_c   : int  4 3 2 3 2 2 2 1 2 1 ...
\end{verbatim}

We can see that Age and Degree are numeric. We see that the Q6 demographic questions are ``character'', which is appropriate for data that are text in CSV file. The other variables are numeric (integer).\footnote{In earlier versions of R, the \texttt{read.csv()} function read these as factors, which are appropriate for nominal and ordinal level data.}

Let's change a character variable to numeric data. For the Q6 variables, there are ``No'' and ``Yes'' responses. These are \textbf{not} numbers, so we cannot perform mathematical functions on them. We can create a new dichotomous variable from these one or more nominal variables, just like how we did in Excel. Let's create a \texttt{Major\_in\_Educ} variable using the \texttt{ifelse()} function. The vertical bar, \textbar, symbolizes ``or'', so the following code is \emph{if EdMath is \texttt{Yes}, or if EdScience is \texttt{Yes}, or if EdGen is \texttt{Yes}, code the new variable as \texttt{1}; otherwise, code it as \texttt{0}}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q6_Major_in_Edu <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q6_EdMat }\OperatorTok{==}\StringTok{ "Yes"} \OperatorTok{|}
\StringTok{                                }\NormalTok{timss}\OperatorTok{$}\NormalTok{Q6_EdSci }\OperatorTok{==}\StringTok{ "Yes"} \OperatorTok{|}\StringTok{    }
\StringTok{                                }\NormalTok{timss}\OperatorTok{$}\NormalTok{Q6_EdGen }\OperatorTok{==}\StringTok{ "Yes"}\NormalTok{, }\DecValTok{1}\NormalTok{ ,}\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Let's verify it worked by examining some rows of data---here, the first 12 rows and the columns that were used to get our new variable as well as the new variable:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\DecValTok{1}\OperatorTok{:}\DecValTok{12}\NormalTok{, }\KeywordTok{c}\NormalTok{(}\StringTok{"TID"}\NormalTok{, }\StringTok{"Q6_EdMat"}\NormalTok{, }\StringTok{"Q6_EdSci"}\NormalTok{, }\StringTok{"Q6_EdGen"}\NormalTok{, }\StringTok{"Q6_Major_in_Edu"}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    TID Q6_EdMat Q6_EdSci Q6_EdGen Q6_Major_in_Edu
## 1    1       No       No      Yes               1
## 2    2       No       No      Yes               1
## 3    3       No       No       No               0
## 4    4      Yes       No       No               1
## 5    5      Yes       No       No               1
## 6    6       No       No      Yes               1
## 7    7       No       No       No               0
## 8    8      Yes       No       No               1
## 9    9       No       No       No               0
## 10  10       No       No       No               0
## 11  11       No      Yes       No               1
## 12  12       No       No       No               0
\end{verbatim}

The variable we just created is in the rightmost column. We can look at the structure of this selected set of columns and see that the last one is numeric.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(timss[, }\KeywordTok{c}\NormalTok{(}\StringTok{"Q6_EdMat"}\NormalTok{, }\StringTok{"Q6_EdSci"}\NormalTok{, }\StringTok{"Q6_EdGen"}\NormalTok{, }\StringTok{"Q6_Major_in_Edu"}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    30 obs. of  4 variables:
##  $ Q6_EdMat       : chr  "No" "No" "No" "Yes" ...
##  $ Q6_EdSci       : chr  "No" "No" "No" "No" ...
##  $ Q6_EdGen       : chr  "Yes" "Yes" "No" "No" ...
##  $ Q6_Major_in_Edu: num  1 1 0 1 1 1 0 1 0 0 ...
\end{verbatim}

This dummy coding is valuable for analysis. We have prepared this new variable so it can serve as a predictor in a regression model (i.e., a general linear model).

\hypertarget{recoding-response-category-data}{%
\subsection{Recoding response-category data}\label{recoding-response-category-data}}

\hypertarget{reverse-coding-and-rescaling-data}{%
\subsubsection{Reverse-coding and rescaling data}\label{reverse-coding-and-rescaling-data}}

Questions 15a--15g have numeric codes that are not logical. For instance, \emph{Every or almost every lesson} is \(1\) but \emph{Never} is coded as \(4\). Usually, we use higher values for more of a construct and lower values for less.

So, let's change our coding so that \emph{Never} is coded as \(0\), \emph{Some lessons} is \(1\), \emph{About half the lessons} is \(2\), and \emph{Every or almost every lesson} is \(3\). So, we are going from a 4-to-1 scale to a 0-to-3 scale.

The general formula for reverse coding is this:

\begin{itemize}
\tightlist
\item
  newvalue = (num of response options) + (bottom value of new scale) - (observed value in the original scale)
\end{itemize}

So with our data in Questions 15a--15g,

\begin{itemize}
\tightlist
\item
  How many response categories are there? \emph{Answer:} 4
\item
  What's the bottom value on our NEW scale going to be? \emph{Answer:} 0
\item
  What are our original data? \emph{Answer:} all of the data in Q15a through Q15g
\end{itemize}

Maybe we forgot the names of the variables we were investigating. Let's use \texttt{names()} to see what's available.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{names}\NormalTok{(timss) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "TID"             "Q4_Age"          "Q5_Degree"       "Q6_Math"        
##  [5] "Q6_Bio"          "Q6_Phys"         "Q6_Chem"         "Q6_EarthS"      
##  [9] "Q6_EdMat"        "Q6_EdSci"        "Q6_EdGen"        "Q6_Othr"        
## [13] "Q13_NumSs"       "Q15_StCentrd_a"  "Q15_StCentrd_b"  "Q15_StCentrd_c" 
## [17] "Q15_StCentrd_d"  "Q15_StCentrd_e"  "Q15_StCentrd_f"  "Q15_StCentrd_g" 
## [21] "Q16_Lims_a"      "Q16_Lims_b"      "Q16_Lims_c"      "Q16_Lims_d"     
## [25] "Q16_Lims_e"      "Q16_Lims_f"      "Q16_Lims_g"      "Q17_Mins"       
## [29] "Q19_Didac_a"     "Q19_Didac_b"     "Q19_Didac_c"     "Q6_Major_in_Edu"
\end{verbatim}

Let's try the calculation on a single variable and add ``R'' to the new variable name so we can remember this is the reversed version:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q15_StCentrd_aR <-}\StringTok{ }\DecValTok{4} \OperatorTok{+}\StringTok{ }\DecValTok{0} \OperatorTok{-}\StringTok{ }\NormalTok{timss}\OperatorTok{$}\NormalTok{Q15_StCentrd_a}
\end{Highlighting}
\end{Shaded}

Let's verify it worked by comparing the reversed and the original data with first 10 rows.
Any old 4s should now be \(0\) (because 4 + 0 - 4 = 0), 3s should be \(1\), 2s should still be \(2\), and 1s should be \(3\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{, }\KeywordTok{c}\NormalTok{(}\StringTok{"Q15_StCentrd_a"}\NormalTok{,}\StringTok{"Q15_StCentrd_aR"}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Q15_StCentrd_a Q15_StCentrd_aR
## 1               2               2
## 2               3               1
## 3               3               1
## 4               1               3
## 5               2               2
## 6               3               1
## 7               4               0
## 8               1               3
## 9               4               0
## 10              3               1
\end{verbatim}

Let's do this same operation with the remaining 6 items in Q15 (Q15b through Q15g). We could repeat the line above with the new variable names in each line. Or, we can create an R object that contains the names of these 7 variables and then perform the same calculation on this object:

\textbf{Step 1.} Let's create an object that contains the 7 items in Question 15. We'll call this Q15.\footnote{We can shorten this code using the \texttt{paste0()} function and the first 7 letters of the alphabet: \texttt{Q15\ \textless{}-\ paste0("Q15\_StCentrd\_",\ letters{[}1:7{]})}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Q15 <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Q15_StCentrd_a"}\NormalTok{, }\StringTok{"Q15_StCentrd_b"}\NormalTok{, }\StringTok{"Q15_StCentrd_c"}\NormalTok{, }\StringTok{"Q15_StCentrd_d"}\NormalTok{, }
        \StringTok{"Q15_StCentrd_e"}\NormalTok{, }\StringTok{"Q15_StCentrd_f"}\NormalTok{, }\StringTok{"Q15_StCentrd_g"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

This object, Q15, is only a list of names, but we can use it to refer to those data.\footnote{The benefit here is that we can re-use this object, Q15, in other code to reference these columns.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Q15}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Q15_StCentrd_a" "Q15_StCentrd_b" "Q15_StCentrd_c" "Q15_StCentrd_d"
## [5] "Q15_StCentrd_e" "Q15_StCentrd_f" "Q15_StCentrd_g"
\end{verbatim}

Let's use our object, now: Here are the first five people's responses on these items:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\DecValTok{1}\OperatorTok{:}\DecValTok{5}\NormalTok{, Q15]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Q15_StCentrd_a Q15_StCentrd_b Q15_StCentrd_c Q15_StCentrd_d Q15_StCentrd_e
## 1              2              2              1              1              2
## 2              3              1              4              2              2
## 3              3              2              2              3              3
## 4              1              1              2              2              1
## 5              2              1              3              2              2
##   Q15_StCentrd_f Q15_StCentrd_g
## 1              3              1
## 2              3              2
## 3              3              3
## 4              1              1
## 5              3              2
\end{verbatim}

Let's check the range of the original data. The minimum should be 1 and the maxium 4:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{range}\NormalTok{(timss[ , Q15])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1 4
\end{verbatim}

So, we have used the object \texttt{Q15} in two different functions. This is better than retyping this long string: \texttt{c("Q15\_StCentrd\_a",\ "Q15\_StCentrd\_b",\ "Q15\_StCentrd\_c",\ "Q15\_StCentrd\_d",\ \ \ \ \ \ \ \ \ \ "Q15\_StCentrd\_e",\ "Q15\_StCentrd\_f",\ "Q15\_StCentrd\_g")}.

\hypertarget{reverse-coding}{%
\paragraph{Reverse coding}\label{reverse-coding}}

\textbf{Step 2.} Let's do the same thing with the new set of variables that we will create. Let's use an ``R'' to stand for Reversed. We could write out all the names, with R after each variable, or we can take a shortcut and use the \texttt{paste0()} function to concatenate an ``R'' at the end of every element in the Q15 object:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Q15R <-}\StringTok{ }\KeywordTok{paste0}\NormalTok{(Q15,}\StringTok{"R"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Verify that it created the set of names we want:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Q15R}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Q15_StCentrd_aR" "Q15_StCentrd_bR" "Q15_StCentrd_cR" "Q15_StCentrd_dR"
## [5] "Q15_StCentrd_eR" "Q15_StCentrd_fR" "Q15_StCentrd_gR"
\end{verbatim}

Let's create these seven new reverse-coded variables using our formula and these two objects, Q15 and Q15R. Because each object includes the same number of names, it performs the calculation on the first variable, then the next one and so forth.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[ ,Q15R] <-}\StringTok{ }\NormalTok{(}\DecValTok{4} \OperatorTok{+}\StringTok{ }\DecValTok{0} \OperatorTok{-}\StringTok{ }\NormalTok{timss[,Q15]) }
\end{Highlighting}
\end{Shaded}

Take a look at the first 6 rows:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\DecValTok{1}\OperatorTok{:}\DecValTok{6}\NormalTok{, Q15]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Q15_StCentrd_a Q15_StCentrd_b Q15_StCentrd_c Q15_StCentrd_d Q15_StCentrd_e
## 1              2              2              1              1              2
## 2              3              1              4              2              2
## 3              3              2              2              3              3
## 4              1              1              2              2              1
## 5              2              1              3              2              2
## 6              3              3              3              3              3
##   Q15_StCentrd_f Q15_StCentrd_g
## 1              3              1
## 2              3              2
## 3              3              3
## 4              1              1
## 5              3              2
## 6              4              3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\DecValTok{1}\OperatorTok{:}\DecValTok{6}\NormalTok{, Q15R]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Q15_StCentrd_aR Q15_StCentrd_bR Q15_StCentrd_cR Q15_StCentrd_dR
## 1               2               2               3               3
## 2               1               3               0               2
## 3               1               2               2               1
## 4               3               3               2               2
## 5               2               3               1               2
## 6               1               1               1               1
##   Q15_StCentrd_eR Q15_StCentrd_fR Q15_StCentrd_gR
## 1               2               1               3
## 2               2               1               2
## 3               1               1               1
## 4               3               3               3
## 5               2               1               2
## 6               1               0               1
\end{verbatim}

These match our Excel calculations.

Let's look at the first variable side by side:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\DecValTok{1}\OperatorTok{:}\DecValTok{6}\NormalTok{, }\KeywordTok{c}\NormalTok{(Q15[}\DecValTok{1}\NormalTok{], Q15R[}\DecValTok{1}\NormalTok{]) ] }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Q15_StCentrd_a Q15_StCentrd_aR
## 1              2               2
## 2              3               1
## 3              3               1
## 4              1               3
## 5              2               2
## 6              3               1
\end{verbatim}

We used the index {[}1{]} to ask for the first element of the Q15 and Q15R objects. This is the same as if we asked for the names:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\DecValTok{1}\OperatorTok{:}\DecValTok{6}\NormalTok{, }\KeywordTok{c}\NormalTok{(}\StringTok{"Q15_StCentrd_a"}\NormalTok{, }\StringTok{"Q15_StCentrd_aR"}\NormalTok{) ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Q15_StCentrd_a Q15_StCentrd_aR
## 1              2               2
## 2              3               1
## 3              3               1
## 4              1               3
## 5              2               2
## 6              3               1
\end{verbatim}

We could ask for the second element after making a small change to the code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\DecValTok{1}\OperatorTok{:}\DecValTok{6}\NormalTok{, }\KeywordTok{c}\NormalTok{(Q15[}\DecValTok{2}\NormalTok{], Q15R[}\DecValTok{2}\NormalTok{]) ] }
\end{Highlighting}
\end{Shaded}

Let's see whether the minimum and maximum values are outside the bounds of 0, and max is 3.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{range}\NormalTok{(timss[,Q15R]) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0 3
\end{verbatim}

We could also look at each of the 7 questions:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{apply}\NormalTok{(timss[ , Q15R], }\DecValTok{2}\NormalTok{, }\DataTypeTok{FUN =}\NormalTok{ range)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Q15_StCentrd_aR Q15_StCentrd_bR Q15_StCentrd_cR Q15_StCentrd_dR
## [1,]               0               1               0               0
## [2,]               3               3               3               3
##      Q15_StCentrd_eR Q15_StCentrd_fR Q15_StCentrd_gR
## [1,]               0               0               0
## [2,]               3               3               3
\end{verbatim}

None of the values is lower than 0 or higher than 3, which is what we expected.

\hypertarget{rescaling-q16-so-zero-is-meaningful}{%
\paragraph{Rescaling Q16 so zero is meaningful}\label{rescaling-q16-so-zero-is-meaningful}}

Question 16 has the numeric codes in a logical direction (where a smaller numeric value represents a lower amount on the concept), but let's change the scale from a 1-to-3 scale to 0-to-2 so that ``Not at all'' is zero.\footnote{This recoding is helpful if we use these as predictors in a regression because we can interpret the intercept as a meaningful number.} For this, we have to subtract 1 from the original value.

Let's remember what these Q16 variable names are:\footnote{The \texttt{dput()} function creates an output that is easy to copy and paste into the \texttt{c()} function in our next step.}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dput}\NormalTok{(}\KeywordTok{names}\NormalTok{(timss)) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## c("TID", "Q4_Age", "Q5_Degree", "Q6_Math", "Q6_Bio", "Q6_Phys", 
## "Q6_Chem", "Q6_EarthS", "Q6_EdMat", "Q6_EdSci", "Q6_EdGen", "Q6_Othr", 
## "Q13_NumSs", "Q15_StCentrd_a", "Q15_StCentrd_b", "Q15_StCentrd_c", 
## "Q15_StCentrd_d", "Q15_StCentrd_e", "Q15_StCentrd_f", "Q15_StCentrd_g", 
## "Q16_Lims_a", "Q16_Lims_b", "Q16_Lims_c", "Q16_Lims_d", "Q16_Lims_e", 
## "Q16_Lims_f", "Q16_Lims_g", "Q17_Mins", "Q19_Didac_a", "Q19_Didac_b", 
## "Q19_Didac_c", "Q6_Major_in_Edu", "Q15_StCentrd_aR", "Q15_StCentrd_bR", 
## "Q15_StCentrd_cR", "Q15_StCentrd_dR", "Q15_StCentrd_eR", "Q15_StCentrd_fR", 
## "Q15_StCentrd_gR")
\end{verbatim}

Let's assign them to the object Q16:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Q16 <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Q16_Lims_a"}\NormalTok{, }\StringTok{"Q16_Lims_b"}\NormalTok{, }\StringTok{"Q16_Lims_c"}\NormalTok{, }\StringTok{"Q16_Lims_d"}\NormalTok{, }\StringTok{"Q16_Lims_e"}\NormalTok{, }
        \StringTok{"Q16_Lims_f"}\NormalTok{, }\StringTok{"Q16_Lims_g"}\NormalTok{)}
\KeywordTok{range}\NormalTok{(timss[ , Q16])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1 3
\end{verbatim}

Because Q16 only needs to be lowered so that \emph{Not at all} = \(0\), we might use ``Z'' in the names to remind us they are rescaled to have a meaningful zero.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Q16Z <-}\StringTok{ }\KeywordTok{paste0}\NormalTok{(Q16,}\StringTok{"Z"}\NormalTok{)}
\NormalTok{Q16Z }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Q16_Lims_aZ" "Q16_Lims_bZ" "Q16_Lims_cZ" "Q16_Lims_dZ" "Q16_Lims_eZ"
## [6] "Q16_Lims_fZ" "Q16_Lims_gZ"
\end{verbatim}

Now, let's subtract 1 from the original response and create our new variables in the data frame:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[ ,Q16Z] <-}\StringTok{ }\NormalTok{(timss[ ,Q16] }\OperatorTok{-}\StringTok{ }\DecValTok{1}\NormalTok{) }
\KeywordTok{range}\NormalTok{(timss[,Q16Z])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0 2
\end{verbatim}

We can see these new variables are appended at the end of the data set:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(timss) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    30 obs. of  46 variables:
##  $ TID            : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Q4_Age         : num  2 3 3 2 5 6 5 2 4 3 ...
##  $ Q5_Degree      : num  4 4 4 5 3 4 5 4 4 4 ...
##  $ Q6_Math        : chr  "No" "No" "No" "No" ...
##  $ Q6_Bio         : chr  "No" "No" "No" "No" ...
##  $ Q6_Phys        : chr  "No" "No" "Yes" "No" ...
##  $ Q6_Chem        : chr  "No" "No" "No" "No" ...
##  $ Q6_EarthS      : chr  "No" "No" "No" "No" ...
##  $ Q6_EdMat       : chr  "No" "No" "No" "Yes" ...
##  $ Q6_EdSci       : chr  "No" "No" "No" "No" ...
##  $ Q6_EdGen       : chr  "Yes" "Yes" "No" "No" ...
##  $ Q6_Othr        : chr  "No" "No" "Yes" "No" ...
##  $ Q13_NumSs      : int  8 12 19 16 18 26 29 16 30 22 ...
##  $ Q15_StCentrd_a : int  2 3 3 1 2 3 4 1 4 3 ...
##  $ Q15_StCentrd_b : int  2 1 2 1 1 3 2 1 2 2 ...
##  $ Q15_StCentrd_c : int  1 4 2 2 3 3 2 1 2 2 ...
##  $ Q15_StCentrd_d : int  1 2 3 2 2 3 3 1 4 4 ...
##  $ Q15_StCentrd_e : int  2 2 3 1 2 3 4 2 2 2 ...
##  $ Q15_StCentrd_f : int  3 3 3 1 3 4 2 1 1 4 ...
##  $ Q15_StCentrd_g : int  1 2 3 1 2 3 3 1 3 3 ...
##  $ Q16_Lims_a     : int  2 1 2 1 1 2 3 1 3 1 ...
##  $ Q16_Lims_b     : int  1 1 2 2 1 1 2 1 3 2 ...
##  $ Q16_Lims_c     : int  3 3 3 3 3 3 3 2 2 2 ...
##  $ Q16_Lims_d     : int  2 2 2 2 2 2 2 1 2 3 ...
##  $ Q16_Lims_e     : int  1 1 2 2 1 2 2 2 2 2 ...
##  $ Q16_Lims_f     : int  1 1 1 1 1 1 1 1 2 1 ...
##  $ Q16_Lims_g     : int  2 1 2 1 1 1 1 2 1 1 ...
##  $ Q17_Mins       : int  160 180 190 200 210 180 200 240 150 160 ...
##  $ Q19_Didac_a    : int  3 4 2 3 3 3 2 3 2 1 ...
##  $ Q19_Didac_b    : int  3 2 1 4 1 4 2 2 2 2 ...
##  $ Q19_Didac_c    : int  4 3 2 3 2 2 2 1 2 1 ...
##  $ Q6_Major_in_Edu: num  1 1 0 1 1 1 0 1 0 0 ...
##  $ Q15_StCentrd_aR: num  2 1 1 3 2 1 0 3 0 1 ...
##  $ Q15_StCentrd_bR: num  2 3 2 3 3 1 2 3 2 2 ...
##  $ Q15_StCentrd_cR: num  3 0 2 2 1 1 2 3 2 2 ...
##  $ Q15_StCentrd_dR: num  3 2 1 2 2 1 1 3 0 0 ...
##  $ Q15_StCentrd_eR: num  2 2 1 3 2 1 0 2 2 2 ...
##  $ Q15_StCentrd_fR: num  1 1 1 3 1 0 2 3 3 0 ...
##  $ Q15_StCentrd_gR: num  3 2 1 3 2 1 1 3 1 1 ...
##  $ Q16_Lims_aZ    : num  1 0 1 0 0 1 2 0 2 0 ...
##  $ Q16_Lims_bZ    : num  0 0 1 1 0 0 1 0 2 1 ...
##  $ Q16_Lims_cZ    : num  2 2 2 2 2 2 2 1 1 1 ...
##  $ Q16_Lims_dZ    : num  1 1 1 1 1 1 1 0 1 2 ...
##  $ Q16_Lims_eZ    : num  0 0 1 1 0 1 1 1 1 1 ...
##  $ Q16_Lims_fZ    : num  0 0 0 0 0 0 0 0 1 0 ...
##  $ Q16_Lims_gZ    : num  1 0 1 0 0 0 0 1 0 0 ...
\end{verbatim}

Let's check that it worked with the first and 7th variable.\footnote{We could also copy and paste the code and replace the numbers with any within the range of 1 through 7 because there are 7 items in this question.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\DecValTok{7}\OperatorTok{:}\DecValTok{12}\NormalTok{, }\KeywordTok{c}\NormalTok{(Q16[}\DecValTok{1}\NormalTok{], Q16Z[}\DecValTok{1}\NormalTok{])]}
\NormalTok{timss[}\DecValTok{7}\OperatorTok{:}\DecValTok{12}\NormalTok{, }\KeywordTok{c}\NormalTok{(Q16[}\DecValTok{7}\NormalTok{], Q16Z[}\DecValTok{7}\NormalTok{])]}
\end{Highlighting}
\end{Shaded}

\hypertarget{rescaling-q19}{%
\paragraph{Rescaling Q19}\label{rescaling-q19}}

Similar to Question 15, Question 19's response scale categories are in an illogical direction. Let's do the same thing we did for Question 15.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(timss) }

\NormalTok{Q19 <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Q19_Didac_a"}\NormalTok{,  }\StringTok{"Q19_Didac_b"}\NormalTok{,  }\StringTok{"Q19_Didac_c"}\NormalTok{)}
\NormalTok{Q19R<-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Q19_Didac_aR"}\NormalTok{, }\StringTok{"Q19_Didac_bR"}\NormalTok{, }\StringTok{"Q19_Didac_cR"}\NormalTok{) }

\NormalTok{timss[,Q19R] <-}\StringTok{ }\NormalTok{(}\DecValTok{4} \OperatorTok{+}\StringTok{ }\DecValTok{0} \OperatorTok{-}\StringTok{ }\NormalTok{timss[,Q19]) }
\end{Highlighting}
\end{Shaded}

\hypertarget{creating-composite-scores-aka-indexes}{%
\subsection{Creating Composite Scores (AKA Indexes)}\label{creating-composite-scores-aka-indexes}}

\textbf{1)} Let's create an index (AKA scale or composite) variable from the 7 numeric items in Q15. Let's name our new variable \texttt{Q15\_Stdnt\_Centred\_Index}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q15_Index <-}\StringTok{ }\KeywordTok{apply}\NormalTok{(timss[ ,Q15R],}\DecValTok{1}\NormalTok{, mean, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

Applying the mean function across columns ``1'' directs R to apply this function to the first margin, i.e.~to the rows (and across columns). See \url{http://www2.hawaii.edu/~georgeha/surveys/_book/appending.html}.
So we get each person's mean score across the 7 items in Q15R. \texttt{na.rm\ =\ TRUE} is used in case we have any missing data.

Let's look at the index scores for the first 5 or so observations:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\DecValTok{1}\OperatorTok{:}\DecValTok{5}\NormalTok{, }\KeywordTok{c}\NormalTok{(Q15R,}\StringTok{"Q15_Index"}\NormalTok{)]  }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Q15_StCentrd_aR Q15_StCentrd_bR Q15_StCentrd_cR Q15_StCentrd_dR
## 1               2               2               3               3
## 2               1               3               0               2
## 3               1               2               2               1
## 4               3               3               2               2
## 5               2               3               1               2
##   Q15_StCentrd_eR Q15_StCentrd_fR Q15_StCentrd_gR Q15_Index
## 1               2               1               3  2.285714
## 2               2               1               2  1.571429
## 3               1               1               1  1.285714
## 4               3               3               3  2.714286
## 5               2               1               2  1.857143
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q15_Index)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.5714  1.2857  1.5714  1.7190  2.0000  3.0000
\end{verbatim}

We can use the structure function, \texttt{str()}, with the same subset of data:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(timss[, }\KeywordTok{c}\NormalTok{(Q15R,}\StringTok{"Q15_Index"}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    30 obs. of  8 variables:
##  $ Q15_StCentrd_aR: num  2 1 1 3 2 1 0 3 0 1 ...
##  $ Q15_StCentrd_bR: num  2 3 2 3 3 1 2 3 2 2 ...
##  $ Q15_StCentrd_cR: num  3 0 2 2 1 1 2 3 2 2 ...
##  $ Q15_StCentrd_dR: num  3 2 1 2 2 1 1 3 0 0 ...
##  $ Q15_StCentrd_eR: num  2 2 1 3 2 1 0 2 2 2 ...
##  $ Q15_StCentrd_fR: num  1 1 1 3 1 0 2 3 3 0 ...
##  $ Q15_StCentrd_gR: num  3 2 1 3 2 1 1 3 1 1 ...
##  $ Q15_Index      : num  2.29 1.57 1.29 2.71 1.86 ...
\end{verbatim}

\textbf{2)} Let's do the same thing with Q16 and Q19:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q19_Index <-}\StringTok{ }\KeywordTok{apply}\NormalTok{(timss[,Q19R], }\DecValTok{1}\NormalTok{, mean, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q16_Index <-}\StringTok{ }\KeywordTok{apply}\NormalTok{(timss[,Q16Z], }\DecValTok{1}\NormalTok{, mean, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Take a look at the new composite variables:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\DecValTok{1}\OperatorTok{:}\DecValTok{5}\NormalTok{,}\KeywordTok{c}\NormalTok{(Q19R,}\StringTok{"Q19_Index"}\NormalTok{)]  }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Q19_Didac_aR Q19_Didac_bR Q19_Didac_cR Q19_Index
## 1            1            1            0 0.6666667
## 2            0            2            1 1.0000000
## 3            2            3            2 2.3333333
## 4            1            0            1 0.6666667
## 5            1            3            2 2.0000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\DecValTok{1}\OperatorTok{:}\DecValTok{5}\NormalTok{,}\KeywordTok{c}\NormalTok{(Q16Z,}\StringTok{"Q16_Index"}\NormalTok{)]  }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Q16_Lims_aZ Q16_Lims_bZ Q16_Lims_cZ Q16_Lims_dZ Q16_Lims_eZ Q16_Lims_fZ
## 1           1           0           2           1           0           0
## 2           0           0           2           1           0           0
## 3           1           1           2           1           1           0
## 4           0           1           2           1           1           0
## 5           0           0           2           1           0           0
##   Q16_Lims_gZ Q16_Index
## 1           1 0.7142857
## 2           0 0.4285714
## 3           1 1.0000000
## 4           0 0.7142857
## 5           0 0.4285714
\end{verbatim}

\hypertarget{a-general-formula-for-rescaling-data}{%
\subsection{A general formula for rescaling data}\label{a-general-formula-for-rescaling-data}}

Here's a more general formula for rescaling:

Sometimes, we want to rescale data. For example, if we want to create an index based on several variables, but some of these variables are on a 1-to-5 scale while others are on a 1-to-6 scale and we want to give equal weight to the variables, we would rescale one type to be on the other's scale.

We can use this general formula, with the ``bottom'' and the ``top'' referring to the bottom and top of the scale and the ``value'' referring to the response of interest (a person's response): new.value = new.bottom + (old.value - old.bottom)*(new.top - new.bottom)/(old.top - old.bottom) but first we have to assign values to each of the objects on the right side (or we could just plug them in). Here is an example of rescaling a response of 3 that was on a scale of 1 to 6 to the new scale of 1 to 5:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{old.value <-}\StringTok{  }\DecValTok{3}  \CommentTok{#This is our original data point. }
\NormalTok{old.bottom<-}\StringTok{  }\DecValTok{1}  \CommentTok{#This is the lowest possible point on the original scale}
\NormalTok{old.top   <-}\StringTok{  }\DecValTok{6}  \CommentTok{#This is the highest possible point on the original scale}
\NormalTok{new.bottom<-}\StringTok{  }\DecValTok{1}  \CommentTok{#This is the lowest possible point on the new scale}
\NormalTok{new.top   <-}\StringTok{  }\DecValTok{5}  \CommentTok{#This is the highest possible point on the new scale}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{new.bottom }\OperatorTok{+}\StringTok{ }\NormalTok{(old.value }\OperatorTok{-}\StringTok{ }\NormalTok{old.bottom)}\OperatorTok{*}\NormalTok{(new.top }\OperatorTok{-}\StringTok{ }\NormalTok{new.bottom)}\OperatorTok{/}\NormalTok{(old.top }\OperatorTok{-}\StringTok{ }\NormalTok{old.bottom)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.6
\end{verbatim}

which is the same as this if we weren't using object names:

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1} \OperatorTok{+}\StringTok{ }\NormalTok{(}\DecValTok{3} \OperatorTok{-}\StringTok{ }\DecValTok{1}\NormalTok{)}\OperatorTok{*}\NormalTok{(}\DecValTok{5-1}\NormalTok{)}\OperatorTok{/}\NormalTok{(}\DecValTok{6-1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.6
\end{verbatim}

Seems like too much work, right. However, we can use this in a custom function.

\hypertarget{create-and-use-a-custom-function}{%
\subsection{Create and use a custom function}\label{create-and-use-a-custom-function}}

It's convenient to create a custom function using that formula. Let's name our custom function something that does not already exist in base R. We can check this using the help() function to see if something comes up:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{help}\NormalTok{(}\StringTok{"myrescale"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

Seems like ``myrescale'' is a good name because nothing comes up in help. After the function(), we specify the argument names and their order. Then, we enclose the operations in the curly brackets. The final object, \texttt{new.value}, is what is produced.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{myrescale <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(old.value, old.bottom, old.top, new.bottom, new.top)\{}
\NormalTok{ new.value <-}\StringTok{ }\NormalTok{new.bottom }\OperatorTok{+}\StringTok{ }\NormalTok{(old.value }\OperatorTok{-}\StringTok{ }\NormalTok{old.bottom)}\OperatorTok{*}\NormalTok{(new.top }\OperatorTok{-}\StringTok{ }\NormalTok{new.bottom)}\OperatorTok{/}\NormalTok{(old.top }\OperatorTok{-}\StringTok{ }\NormalTok{old.bottom)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Now we can use that custom function. Let's make up some arbitrary original data,
within our original 1 to 6 scale:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{olddat <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{6}\NormalTok{, }\DecValTok{5}\NormalTok{)}

\NormalTok{new1to5 <-}\StringTok{ }\KeywordTok{myrescale}\NormalTok{(}\DataTypeTok{old.value  =}\NormalTok{ olddat, }
                     \DataTypeTok{old.bottom =} \DecValTok{1}\NormalTok{, }
                     \DataTypeTok{old.top    =} \DecValTok{6}\NormalTok{, }
                     \DataTypeTok{new.bottom =} \DecValTok{1}\NormalTok{, }
                     \DataTypeTok{new.top    =} \DecValTok{5}\NormalTok{)}
\NormalTok{new1to5}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.4 2.6 1.8 1.0 5.0 4.2
\end{verbatim}

So, we used our homemade function, \texttt{myrescale()}, by specifying the arguments. We can re-use this function in our R session.

Here's another example with our data set:
Maybe for some reason we want to transform all of our Q15R variables to a 5 point scale that is centered at the midpoint, so from -2 to 2:

First let's create a name for our new set of variables Maybe we use ``C5'' to remind ourselves it's centered and on five points:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Q15Centr5 <-}\StringTok{ }\KeywordTok{paste0}\NormalTok{(Q15, }\StringTok{"_C5"}\NormalTok{)}
\NormalTok{Q15Centr5}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Q15_StCentrd_a_C5" "Q15_StCentrd_b_C5" "Q15_StCentrd_c_C5"
## [4] "Q15_StCentrd_d_C5" "Q15_StCentrd_e_C5" "Q15_StCentrd_f_C5"
## [7] "Q15_StCentrd_g_C5"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[ ,Q15Centr5]<-}\StringTok{ }\KeywordTok{myrescale}\NormalTok{(}\DataTypeTok{old.value  =}\NormalTok{ timss[, Q15R], }
                      \DataTypeTok{old.bottom =}  \DecValTok{0}\NormalTok{, }
                      \DataTypeTok{old.top    =}  \DecValTok{3}\NormalTok{, }
                      \DataTypeTok{new.bottom =} \DecValTok{-2}\NormalTok{, }
                      \DataTypeTok{new.top    =}  \DecValTok{2}\NormalTok{)}
\NormalTok{timss[}\DecValTok{1}\OperatorTok{:}\DecValTok{6}\NormalTok{, }\KeywordTok{c}\NormalTok{(Q15R[}\DecValTok{3}\NormalTok{], Q15Centr5[}\DecValTok{3}\NormalTok{]) ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Q15_StCentrd_cR Q15_StCentrd_c_C5
## 1               3         2.0000000
## 2               0        -2.0000000
## 3               2         0.6666667
## 4               2         0.6666667
## 5               1        -0.6666667
## 6               1        -0.6666667
\end{verbatim}

We can use this general formula to reverse scale, too. To reverse the scale, the new top and bottom are just reversed:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newReversed <-}\StringTok{ }\KeywordTok{myrescale}\NormalTok{(olddat, }
                         \DataTypeTok{old.bottom =} \DecValTok{1}\NormalTok{, }
                         \DataTypeTok{old.top    =} \DecValTok{6}\NormalTok{, }
                         \DataTypeTok{new.bottom =} \DecValTok{6}\NormalTok{, }
                         \DataTypeTok{new.top    =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Let's compare our newly reversed scale to our original scale:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newReversed}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3 4 5 6 1 2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{olddat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4 3 2 1 6 5
\end{verbatim}

\hypertarget{the-code-in-one-place-for-one-of-the-composite-scores}{%
\subsection{The code in one place for one of the composite scores}\label{the-code-in-one-place-for-one-of-the-composite-scores}}

Here is the code again for one of the scales---the Q15 index---but without the extra steps above. This shows the core steps:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Reading in the CSV file,
\item
  Examining the structure of the data frame,
\item
  Assigning the names of the columns to an object, \texttt{Q15}, so we can use that object in subsequent code,
\item
  Creating a new object, \texttt{Q15R} that includes the names of the \texttt{Q15} items but with an ``R'' so we can create a new set of columns that are rescaled,
\item
  The actual recscaling of the items,
\item
  Calculating the composite score from the rescaled items, and
\item
  Examining the structure of our rescaled items and our composite score.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{'Week13_Timss_Mock_Raw.csv'}\NormalTok{) }
\KeywordTok{str}\NormalTok{(timss)}
\NormalTok{Q15   <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Q15_StCentrd_a"}\NormalTok{, }\StringTok{"Q15_StCentrd_b"}\NormalTok{, }\StringTok{"Q15_StCentrd_c"}\NormalTok{, }\StringTok{"Q15_StCentrd_d"}\NormalTok{, }
        \StringTok{"Q15_StCentrd_e"}\NormalTok{, }\StringTok{"Q15_StCentrd_f"}\NormalTok{, }\StringTok{"Q15_StCentrd_g"}\NormalTok{)}
\NormalTok{Q15R  <-}\StringTok{ }\KeywordTok{paste0}\NormalTok{(Q15,}\StringTok{"R"}\NormalTok{)}
\NormalTok{timss[ ,Q15R]   <-}\StringTok{ }\NormalTok{(}\DecValTok{4} \OperatorTok{+}\StringTok{ }\DecValTok{0} \OperatorTok{-}\StringTok{ }\NormalTok{timss[,Q15]) }
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q15_Index <-}\StringTok{ }\KeywordTok{apply}\NormalTok{(timss[ ,Q15R],}\DecValTok{1}\NormalTok{, mean, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{) }
\KeywordTok{str}\NormalTok{(timss[, }\KeywordTok{c}\NormalTok{(Q15R,}\StringTok{"Q15_Index"}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\hypertarget{a-shortcut-when-all-of-the-items-are-on-the-same-scale}{%
\subsection{A shortcut, when all of the items are on the same scale}\label{a-shortcut-when-all-of-the-items-are-on-the-same-scale}}

So far, we have been practicing rescaling items before we use them to create a composite score. That was worth learning because sometimes we find ourselves needing to recode only some of the items (e.g., if we need to reverse-code items that are phrased in the opposite direction to the other items in the scale).

When we do not have that situation, we can take a simpler approach: We can create the composite variable and then rescale that. Here's an example with Q15.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Q15 <-}\StringTok{ }\KeywordTok{paste0}\NormalTok{(}\StringTok{"Q15_StCentrd_"}\NormalTok{, letters[}\DecValTok{1}\OperatorTok{:}\DecValTok{7}\NormalTok{])}
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q15_Index_raw  <-}\StringTok{ }\KeywordTok{apply}\NormalTok{(timss[ ,Q15],}\DecValTok{1}\NormalTok{, mean, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{) }
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q15_Index_easy <-}\StringTok{ }\DecValTok{4} \OperatorTok{+}\StringTok{ }\DecValTok{0} \OperatorTok{-}\StringTok{ }\NormalTok{timss}\OperatorTok{$}\NormalTok{Q15_Index_raw}
\end{Highlighting}
\end{Shaded}

Annoying, huh. We did all of the work above when we could have achieved the same result with three lines of code. Just to verify, in this demo, let's eyeball the first 10 people's scores on this variable (timss\$Q15\_Index\_easy) and the one we had created earlier using after rescaling the individual items (Q15\_Index):

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss[}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{, }\KeywordTok{c}\NormalTok{(}\StringTok{"TID"}\NormalTok{, }\StringTok{"Q15_Index"}\NormalTok{, }\StringTok{"Q15_Index_easy"}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    TID Q15_Index Q15_Index_easy
## 1    1 2.2857143      2.2857143
## 2    2 1.5714286      1.5714286
## 3    3 1.2857143      1.2857143
## 4    4 2.7142857      2.7142857
## 5    5 1.8571429      1.8571429
## 6    6 0.8571429      0.8571429
## 7    7 1.1428571      1.1428571
## 8    8 2.8571429      2.8571429
## 9    9 1.4285714      1.4285714
## 10  10 1.1428571      1.1428571
\end{verbatim}

\hypertarget{summary}{%
\subsection{Summary}\label{summary}}

In this chapter, we created variables (dummy codes and composite scores), recoded and rescaled variables (items and composite variables), created a custom function, and practiced looking at our data and the structure of our data.

\hypertarget{Packages}{%
\section{Installing and Using Packages}\label{Packages}}

In R, we use packages that are developed by nerdy people (whom I admire) and made available for the rest of us to use. Often a package is for a specific purpose or a family of analyses. To analyze simple survey data, we will use the psych package \citep{R-psych} to perform descriptive statistics and estimate reliability coefficients, the ggplot2 package \citep{R-ggplot2} to create pretty plots, and the dplyr \citep{R-dplyr} package to wrangle our data.

\hypertarget{seeing-if-we-need-to-install-a-package}{%
\subsection{Seeing if we need to install a package}\label{seeing-if-we-need-to-install-a-package}}

First, we need to see if the packages we need for this session are installed on our machine. To do this, we can either

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  see if each of these packages is listed in the ``Packages'' tab in the lower right pane, or
\item
  use the \texttt{require()} function with each package to see if we get the result ``there is no package called `{[}package name{]}'\,''. Let's say we think there's a package called PackageNot on our machine. (You can plug in any random name for this.) We can verify this with this code:
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{require}\NormalTok{(}\StringTok{"PackageNot"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: PackageNot
\end{verbatim}

\begin{verbatim}
## Warning in library(package, lib.loc = lib.loc, character.only = TRUE,
## logical.return = TRUE, : there is no package called 'PackageNot'
\end{verbatim}

Do the same thing with the psych package. If you do \emph{not} have it installed, it will give you the same result. If you do have it installed, it will generate an output that says \texttt{Loading\ required\ package:\ psych}:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{require}\NormalTok{(}\StringTok{"psych"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: psych
\end{verbatim}

You might also see a warning that the package was built under a newer version of R. There are R updates every few months or so. If you find the package is not working, you might need to update R, which we won't address right now.

\hypertarget{installing-a-package}{%
\subsection{Installing a package}\label{installing-a-package}}

The \texttt{install.packages()} function is handy for installing packages:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{install.packages}\NormalTok{(}\StringTok{"psych"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Once a package is installed on a machine, we do not need to install it again.\footnote{It is a good idea, however, to update the packages every once in a while. In RStudio, we can click on the Packages tab and click Update.} But, you might want to keep your code as a record of what you did or make the \texttt{install.packages()} line of your code accessible to your friends if you wish to share it with others.\footnote{Talking about R functions in social situations is a great way to ensure you get more alone time.} You can comment out the code if you want R to ignore it. In R, anything after a \texttt{\#} symbol is commented out:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# install.packages("psych")}
\end{Highlighting}
\end{Shaded}

Now, let's bring the package into our working library so we can use a function from that package.\footnote{Base R has a lot of inconsistencies. You may notice that we need quotes around the package name when we use the \texttt{install.packages()} function but we don't when we use the \texttt{library()} function. This is part of the so-called fun in R.}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(psych)}
\end{Highlighting}
\end{Shaded}

We can also find out what functions are available in a package with the \texttt{help()} function and the package name:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{help}\NormalTok{(}\DataTypeTok{package =} \StringTok{"psych"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The functions are in alphabetical order. We can see the \texttt{alpha()} function listed second in the alphabet (under \texttt{-\/-\ A\ -\/-}). We will use this function for estimating internal consistency reliability. If you click on the function, there will be a lot of information to sort through. The \texttt{Usage}and \texttt{Arguments} sections near the top and the \texttt{Examples} section at the bottom are usually useful.

\hypertarget{using-a-function-from-a-package}{%
\subsection{Using a function from a package}\label{using-a-function-from-a-package}}

After we bring the package into our library, during our R session, we can use its functions.

One that we will use is the \texttt{describe()} function. First, let's review some code that we learned last week:\footnote{Also, note that because all of our items require the same rescaling procedure, we could use a shorter version of this code, discussed at the end of the last chapter.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{'Week13_Timss_Mock_Raw.csv'}\NormalTok{) }

\NormalTok{Q15 <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Q15_StCentrd_a"}\NormalTok{, }\StringTok{"Q15_StCentrd_b"}\NormalTok{, }\StringTok{"Q15_StCentrd_c"}\NormalTok{, }\StringTok{"Q15_StCentrd_d"}\NormalTok{, }
        \StringTok{"Q15_StCentrd_e"}\NormalTok{, }\StringTok{"Q15_StCentrd_f"}\NormalTok{, }\StringTok{"Q15_StCentrd_g"}\NormalTok{)}

\NormalTok{Q15R <-}\StringTok{ }\KeywordTok{paste0}\NormalTok{(Q15,}\StringTok{"R"}\NormalTok{)}

\NormalTok{timss[ ,Q15R] <-}\StringTok{ }\NormalTok{(}\DecValTok{4} \OperatorTok{+}\StringTok{ }\DecValTok{0} \OperatorTok{-}\StringTok{ }\NormalTok{timss[,Q15]) }

\NormalTok{timss}\OperatorTok{$}\NormalTok{Q15_Index <-}\StringTok{ }\KeywordTok{apply}\NormalTok{(timss[ ,Q15R],}\DecValTok{1}\NormalTok{, mean, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

We could use the \texttt{summary()} function from Base R to get some descriptive statistics of this variable, Q15\_Index.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q15_Index)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.5714  1.2857  1.5714  1.7190  2.0000  3.0000
\end{verbatim}

This does not show the standard deviation or the \emph{n}-size. Now, let's try the \texttt{describe()} function from the psych package:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{describe}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q15_Index)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    vars  n mean   sd median trimmed  mad  min max range skew kurtosis   se
## X1    1 30 1.72 0.61   1.57    1.68 0.64 0.57   3  2.43 0.43    -0.62 0.11
\end{verbatim}

With this, we get the \emph{n}-size (\texttt{n}), the standard deviation (\texttt{sd}), and some other handy estimates, such as the standard error of the mean (\texttt{se} in this output). We might not wish to report all of these numbers from the output, but this is certainly more informative than Base R's \texttt{summary()} function.

\hypertarget{Descripts}{%
\section{Estimating Descriptive Statistics}\label{Descripts}}

With surveys, we typically report the descriptive statistics of the individual items and of the scales---the composite variables---that we calculated from those items. There are many ways in R to go about estimating the descriptive statistics.\footnote{Notice that I said ``\emph{\emph{estimate}} descriptive statistics.'' There is always some degree of uncertainty about how closely our estimates reflect the true status in the population.} An easy way is to use the \texttt{describe()} function from the psych package. We will play with that. Another way is to use Base R's functions and create our own function.\footnote{The term \emph{Base R} is used to describe the functions that come with R rather than those that are part of packages that we install and use.} This is handy, particularly if a descriptive statistic is not available to us in a package. We will use this approach, too, because we need to report the confidence intervals of the mean estimate--which is not something that seems to be available with the psych package's \texttt{describe()} function.

We also need to remember that there are different levels of data. For categorical data, such as those on nominal and ordinal level scales, it is a good idea to report the frequency (and percentages) of responses in each category. For interval level data, we can report the means, standard deviations, standard error of the mean, and so forth.

\hypertarget{descriptive-statistics-of-categorical-data}{%
\subsection{Descriptive statistics of categorical data}\label{descriptive-statistics-of-categorical-data}}

After we've imported the data, we can examine the frequency counts of the categorical variables. With our data, we can see some variables are numeric (\texttt{int} or \texttt{num}) and some are character (\texttt{chr}) in type:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{'Week13_Timss_Mock_Raw.csv'}\NormalTok{) }
\KeywordTok{str}\NormalTok{(timss)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    30 obs. of  31 variables:
##  $ TID           : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Q4_Age        : num  2 3 3 2 5 6 5 2 4 3 ...
##  $ Q5_Degree     : num  4 4 4 5 3 4 5 4 4 4 ...
##  $ Q6_Math       : chr  "No" "No" "No" "No" ...
##  $ Q6_Bio        : chr  "No" "No" "No" "No" ...
##  $ Q6_Phys       : chr  "No" "No" "Yes" "No" ...
##  $ Q6_Chem       : chr  "No" "No" "No" "No" ...
##  $ Q6_EarthS     : chr  "No" "No" "No" "No" ...
##  $ Q6_EdMat      : chr  "No" "No" "No" "Yes" ...
##  $ Q6_EdSci      : chr  "No" "No" "No" "No" ...
##  $ Q6_EdGen      : chr  "Yes" "Yes" "No" "No" ...
##  $ Q6_Othr       : chr  "No" "No" "Yes" "No" ...
##  $ Q13_NumSs     : int  8 12 19 16 18 26 29 16 30 22 ...
##  $ Q15_StCentrd_a: int  2 3 3 1 2 3 4 1 4 3 ...
##  $ Q15_StCentrd_b: int  2 1 2 1 1 3 2 1 2 2 ...
##  $ Q15_StCentrd_c: int  1 4 2 2 3 3 2 1 2 2 ...
##  $ Q15_StCentrd_d: int  1 2 3 2 2 3 3 1 4 4 ...
##  $ Q15_StCentrd_e: int  2 2 3 1 2 3 4 2 2 2 ...
##  $ Q15_StCentrd_f: int  3 3 3 1 3 4 2 1 1 4 ...
##  $ Q15_StCentrd_g: int  1 2 3 1 2 3 3 1 3 3 ...
##  $ Q16_Lims_a    : int  2 1 2 1 1 2 3 1 3 1 ...
##  $ Q16_Lims_b    : int  1 1 2 2 1 1 2 1 3 2 ...
##  $ Q16_Lims_c    : int  3 3 3 3 3 3 3 2 2 2 ...
##  $ Q16_Lims_d    : int  2 2 2 2 2 2 2 1 2 3 ...
##  $ Q16_Lims_e    : int  1 1 2 2 1 2 2 2 2 2 ...
##  $ Q16_Lims_f    : int  1 1 1 1 1 1 1 1 2 1 ...
##  $ Q16_Lims_g    : int  2 1 2 1 1 1 1 2 1 1 ...
##  $ Q17_Mins      : int  160 180 190 200 210 180 200 240 150 160 ...
##  $ Q19_Didac_a   : int  3 4 2 3 3 3 2 3 2 1 ...
##  $ Q19_Didac_b   : int  3 2 1 4 1 4 2 2 2 2 ...
##  $ Q19_Didac_c   : int  4 3 2 3 2 2 2 1 2 1 ...
\end{verbatim}

One of the variables in our data set is Q5\_Degree, but it is coded as having numeric values. This is an ordinal level variable. The numbers in the data correspond to these categories on the survey instrument:

\begin{itemize}
\tightlist
\item
  1 = \emph{Did not complete high school}
\item
  2 = \emph{High school graduate}
\item
  3 = \emph{Associate's degree}
\item
  4 = \emph{Bachelor's degree}
\item
  5 = \emph{Master's degree}
\item
  6 = \emph{Doctorate}
\end{itemize}

To get the frequency counts of the responses in our data, we can use the \texttt{table()} function on the item:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q5_Degree)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  3  4  5  6 
##  1 20  8  1
\end{verbatim}

So, there was 1 person whose highest degree was at the associate's level, 20 with a bachelor's degree as their highest, 8 with at least a master's degree, and 1 with a doctorate.

We can calculate the proportion (or percentage) of the responses that are in each category using the \texttt{prop.table()} function around the table function.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q5_Degree))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##          3          4          5          6 
## 0.03333333 0.66666667 0.26666667 0.03333333
\end{verbatim}

We can see that \(2/3\) of the teachers (\(0.67\)) have a bachelor's as their highest degree.

\hypertarget{creating-factors}{%
\subsubsection{Creating factors}\label{creating-factors}}

Instead of having R treat these as numeric data, which would incorrectly permit calculation of the means and other types of operations that assume an interval level scale, we can change the variable type to be an \emph{ordered factor}. We can use the \texttt{factor()} function.\footnote{This term \emph{factor} comes from the ANOVA framework, in which a factor has levels. This is \emph{not} the same thing as a factor in factor analysis, which correponds to a dimension or latent construct in the data.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q5_Degree_F <-}\StringTok{ }\KeywordTok{factor}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q5_Degree, }
                            \DataTypeTok{ordered =} \OtherTok{TRUE}\NormalTok{, }
                            \DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\StringTok{"1"}\NormalTok{, }
                                       \StringTok{"2"}\NormalTok{, }
                                       \StringTok{"3"}\NormalTok{, }
                                       \StringTok{"4"}\NormalTok{, }
                                       \StringTok{"5"}\NormalTok{, }
                                       \StringTok{"6"}\NormalTok{),}
                            \DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"No_HS"}\NormalTok{, }
                                       \StringTok{"HS"}\NormalTok{, }
                                       \StringTok{"Associates"}\NormalTok{, }
                                       \StringTok{"Bachelors"}\NormalTok{, }
                                       \StringTok{"Masters"}\NormalTok{, }
                                       \StringTok{"Doctorate"}\NormalTok{))}
\KeywordTok{str}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q5_Degree_F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Ord.factor w/ 6 levels "No_HS"<"HS"<"Associates"<..: 4 4 4 5 3 4 5 4 4 4 ...
\end{verbatim}

Now that we have labeled the levels in the factor, the output from the \texttt{table()} and \texttt{prop.table()} functions is easier to interpret.\footnote{Here, we're using the \texttt{round()} function to make the output even easier to read.} Factors have a specific set of categories (levels), so when we ask for the frequency of responses in a factor level and zero observations are present, it will still report it (as \(0\)).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q5_Degree_F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##      No_HS         HS Associates  Bachelors    Masters  Doctorate 
##          0          0          1         20          8          1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{round}\NormalTok{( }\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q5_Degree_F)), }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##      No_HS         HS Associates  Bachelors    Masters  Doctorate 
##       0.00       0.00       0.03       0.67       0.27       0.03
\end{verbatim}

Specifying our variables as factors is not always required for simple analyses. It's a good idea to have two versions, one that is a numeric, dummy-coded, version that we can include in a regression and another that is a factor, which shows up nicely in plots.

\hypertarget{plotting-the-frequency-data}{%
\subsubsection{Plotting the frequency data}\label{plotting-the-frequency-data}}

Let's use the ggplot2 package to plot the data. First be sure to install the package, which you can do by running \texttt{install.packages("ggplot2")}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ timss, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Q5_Degree_F) ) }\OperatorTok{+}
\StringTok{ }\KeywordTok{geom_bar}\NormalTok{() }
\end{Highlighting}
\end{Shaded}

\includegraphics{Getting-started_files/figure-latex/unnamed-chunk-70-1.pdf}

The \texttt{ggplot()} function includes the data frame in the \texttt{data\ =} argument, which in this case is \texttt{timss}. Then, there's the \texttt{aes()} argument, which refers to the aesthetics. This is where we would identify the X and Y axes. Here, we're only using an X axis. That first line creates the plotting area but does not create the plot yet because we have to specify which type of plot, which is what the \texttt{geom\_bar()} in the second line does. Notice that after each line in ggplot, we add a \texttt{+}. This tells ggplot to add the next line to the plot.

We can make modify the plot. One thing we might do is place the scale of the Y axis from 0 to the total number of observations (\texttt{nrow(timss))}), which is 30 in our data. For this, we can use \texttt{ylim(0,\ 30)} or \texttt{ylim(0,\ nrow(timss))}. We can change the labels of the x and y axis and change the angle of the text on the x axis.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ timss, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Q5_Degree_F)) }\OperatorTok{+}
\StringTok{ }\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}
\StringTok{ }\KeywordTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\KeywordTok{nrow}\NormalTok{(timss)) }\OperatorTok{+}
\StringTok{ }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Highest degree"}\NormalTok{ ) }\OperatorTok{+}\StringTok{ }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Count"}\NormalTok{) }\OperatorTok{+}
\StringTok{ }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Getting-started_files/figure-latex/unnamed-chunk-71-1.pdf}

We can plot the proportions on the Y axis, too, if we think that is important. Notice that we can include an \texttt{aes()} argument in the \texttt{geom\_bar()} line. I found the \texttt{(..count..)/sum(..count..))} part of the code in an online post rather than recalling it from memory but this is an example of how we can modify the y axis.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ timss, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Q5_Degree_F)) }\OperatorTok{+}
\StringTok{ }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ (..count..)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(..count..))) }\OperatorTok{+}
\StringTok{ }\KeywordTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{ }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Highest degree"}\NormalTok{ ) }\OperatorTok{+}\StringTok{ }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Proportion"}\NormalTok{) }\OperatorTok{+}
\StringTok{ }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Getting-started_files/figure-latex/unnamed-chunk-72-1.pdf}

There are many ways to accomplish the same thing in ggplot. It is powerful but the details are hard to remember.\footnote{If you remember the main function, the aesthetics argument and the geoms, you're in good shape because we often find examples rather quickly in online searches.} Here, we can change the Y axis to be percentages. If we wanted to include ``Percentage'' on the Y axis label, we would change \texttt{name\ =\ NULL} to \texttt{name\ =\ "Percentage"} in the code below:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ timss, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Q5_Degree_F)) }\OperatorTok{+}
\StringTok{ }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ (..count..)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(..count..))) }\OperatorTok{+}
\StringTok{ }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Highest degree"}\NormalTok{ ) }\OperatorTok{+}\StringTok{ }
\StringTok{ }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels =}\NormalTok{ scales}\OperatorTok{::}\NormalTok{percent, }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{), }\DataTypeTok{name =} \OtherTok{NULL}\NormalTok{) }\OperatorTok{+}\StringTok{ }\CommentTok{# This line formats the Y axis as percentages, replaces the ylim(0,1) from before, and removes the Y axis label.}
\StringTok{ }\KeywordTok{scale_x_discrete}\NormalTok{(}\DataTypeTok{drop =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}\StringTok{ }\CommentTok{# You can keep this line if you want to include categories that have zero observations.}
\StringTok{ }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Getting-started_files/figure-latex/unnamed-chunk-73-1.pdf}

\hypertarget{cross-tabulations}{%
\subsubsection{Cross-tabulations}\label{cross-tabulations}}

We can also create cross-tabulations---also called contingency tables---of categorical data. For instance, in the first chapter, we created a variable that identified whether the respondent had majored in education or not. We can see what the education level breakdowns are within each of these two categories:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q6_Major_in_Edu <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q6_EdMat }\OperatorTok{==}\StringTok{ "Yes"} \OperatorTok{|}
\StringTok{                                }\NormalTok{timss}\OperatorTok{$}\NormalTok{Q6_EdSci }\OperatorTok{==}\StringTok{ "Yes"} \OperatorTok{|}\StringTok{    }
\StringTok{                                }\NormalTok{timss}\OperatorTok{$}\NormalTok{Q6_EdGen }\OperatorTok{==}\StringTok{ "Yes"}\NormalTok{, }\DecValTok{1}\NormalTok{ ,}\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Optionally, we can create a factor version of this variable:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q6_Major_in_Edu_F <-}\StringTok{ }\KeywordTok{factor}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q6_Major_in_Edu,}
                                  \DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{),}
                                  \DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"Not_education"}\NormalTok{,}
                                             \StringTok{"Education"}\NormalTok{) )}
\end{Highlighting}
\end{Shaded}

The simplest function is to use the \texttt{table()} function again. We see two rows, one for each unique value in the first variable.\footnote{We could have used the regular dummy variable with 0 and 1 values, too. The factor labeling makes it easier to interpret.} We see the six categories of the second variable as the columns:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q6_Major_in_Edu_F, timss}\OperatorTok{$}\NormalTok{Q5_Degree_F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                
##                 No_HS HS Associates Bachelors Masters Doctorate
##   Not_education     0  0          0         7       5         1
##   Education         0  0          1        13       3         0
\end{verbatim}

We can create a facet plot to display these side by side. Here, we add a \texttt{facet\_grid()} line with the categorical variable that we want the facets to be split up by. Don't worry if you cannot remember the details of all of this code---the purpose here is to understand what is possible. Often we search for this syntax when we need it.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ timss, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Q5_Degree_F)) }\OperatorTok{+}
\StringTok{ }\KeywordTok{geom_bar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ (..count..)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(..count..))) }\OperatorTok{+}
\StringTok{ }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Highest degree"}\NormalTok{ ) }\OperatorTok{+}\StringTok{ }
\StringTok{ }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels =}\NormalTok{ scales}\OperatorTok{::}\NormalTok{percent, }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{), }\DataTypeTok{name =} \OtherTok{NULL}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{ }\KeywordTok{scale_x_discrete}\NormalTok{(}\DataTypeTok{drop =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{ }\KeywordTok{facet_grid}\NormalTok{(}\OperatorTok{~}\StringTok{ }\NormalTok{Q6_Major_in_Edu_F) }\OperatorTok{+}
\StringTok{ }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Getting-started_files/figure-latex/unnamed-chunk-77-1.pdf}

\hypertarget{IntrvlDesc}{%
\subsection{Descriptive statistics of interval-level data}\label{IntrvlDesc}}

For this part, let's use the composite variables we created in the first chapter. Here's the shortcut version of that code:\footnote{This shortcut code is calculating the composite scores on the raw scale and \emph{then} rescaling that composite score, as demonstrated at the end of the last chapter. This works because all of the individual items required the same rescaling procedure. If some items in a composite scale require one type of rescaling, such as reverse coding, while others require other scaling, we would need to do this at the item level---which is the longer version presented in the earlier chapter.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Reverse scoring the composite Q15 scale:}
\NormalTok{Q15 <-}\StringTok{ }\KeywordTok{paste0}\NormalTok{(}\StringTok{"Q15_StCentrd_"}\NormalTok{, letters[}\DecValTok{1}\OperatorTok{:}\DecValTok{7}\NormalTok{])}
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q15_Index_raw  <-}\StringTok{ }\KeywordTok{apply}\NormalTok{(timss[ ,Q15],}\DecValTok{1}\NormalTok{, mean, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{) }
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q15_Index <-}\StringTok{ }\DecValTok{4} \OperatorTok{+}\StringTok{ }\DecValTok{0} \OperatorTok{-}\StringTok{ }\NormalTok{timss}\OperatorTok{$}\NormalTok{Q15_Index_raw}

\CommentTok{# Lower the composite Q16 scale by 1 point so zero has meaning}
\NormalTok{Q16 <-}\StringTok{ }\KeywordTok{paste0}\NormalTok{(}\StringTok{"Q16_Lims_"}\NormalTok{, letters[}\DecValTok{1}\OperatorTok{:}\DecValTok{7}\NormalTok{])}
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q16_Index_raw  <-}\StringTok{ }\KeywordTok{apply}\NormalTok{(timss[ ,Q16],}\DecValTok{1}\NormalTok{, mean, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{) }
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q16_Index <-}\StringTok{ }\NormalTok{timss}\OperatorTok{$}\NormalTok{Q16_Index_raw }\OperatorTok{-}\StringTok{ }\DecValTok{1} 

\CommentTok{# Reverse scoring the composite Q19 scale:}
\NormalTok{Q19 <-}\StringTok{ }\KeywordTok{paste0}\NormalTok{(}\StringTok{"Q19_Didac_"}\NormalTok{, letters[}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{])}
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q19_Index_raw  <-}\StringTok{ }\KeywordTok{apply}\NormalTok{(timss[ ,Q19],}\DecValTok{1}\NormalTok{, mean, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{) }
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q19_Index <-}\StringTok{ }\DecValTok{4} \OperatorTok{+}\StringTok{ }\DecValTok{0} \OperatorTok{-}\StringTok{ }\NormalTok{timss}\OperatorTok{$}\NormalTok{Q19_Index_raw }

\KeywordTok{str}\NormalTok{(timss)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    30 obs. of  40 variables:
##  $ TID              : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Q4_Age           : num  2 3 3 2 5 6 5 2 4 3 ...
##  $ Q5_Degree        : num  4 4 4 5 3 4 5 4 4 4 ...
##  $ Q6_Math          : chr  "No" "No" "No" "No" ...
##  $ Q6_Bio           : chr  "No" "No" "No" "No" ...
##  $ Q6_Phys          : chr  "No" "No" "Yes" "No" ...
##  $ Q6_Chem          : chr  "No" "No" "No" "No" ...
##  $ Q6_EarthS        : chr  "No" "No" "No" "No" ...
##  $ Q6_EdMat         : chr  "No" "No" "No" "Yes" ...
##  $ Q6_EdSci         : chr  "No" "No" "No" "No" ...
##  $ Q6_EdGen         : chr  "Yes" "Yes" "No" "No" ...
##  $ Q6_Othr          : chr  "No" "No" "Yes" "No" ...
##  $ Q13_NumSs        : int  8 12 19 16 18 26 29 16 30 22 ...
##  $ Q15_StCentrd_a   : int  2 3 3 1 2 3 4 1 4 3 ...
##  $ Q15_StCentrd_b   : int  2 1 2 1 1 3 2 1 2 2 ...
##  $ Q15_StCentrd_c   : int  1 4 2 2 3 3 2 1 2 2 ...
##  $ Q15_StCentrd_d   : int  1 2 3 2 2 3 3 1 4 4 ...
##  $ Q15_StCentrd_e   : int  2 2 3 1 2 3 4 2 2 2 ...
##  $ Q15_StCentrd_f   : int  3 3 3 1 3 4 2 1 1 4 ...
##  $ Q15_StCentrd_g   : int  1 2 3 1 2 3 3 1 3 3 ...
##  $ Q16_Lims_a       : int  2 1 2 1 1 2 3 1 3 1 ...
##  $ Q16_Lims_b       : int  1 1 2 2 1 1 2 1 3 2 ...
##  $ Q16_Lims_c       : int  3 3 3 3 3 3 3 2 2 2 ...
##  $ Q16_Lims_d       : int  2 2 2 2 2 2 2 1 2 3 ...
##  $ Q16_Lims_e       : int  1 1 2 2 1 2 2 2 2 2 ...
##  $ Q16_Lims_f       : int  1 1 1 1 1 1 1 1 2 1 ...
##  $ Q16_Lims_g       : int  2 1 2 1 1 1 1 2 1 1 ...
##  $ Q17_Mins         : int  160 180 190 200 210 180 200 240 150 160 ...
##  $ Q19_Didac_a      : int  3 4 2 3 3 3 2 3 2 1 ...
##  $ Q19_Didac_b      : int  3 2 1 4 1 4 2 2 2 2 ...
##  $ Q19_Didac_c      : int  4 3 2 3 2 2 2 1 2 1 ...
##  $ Q5_Degree_F      : Ord.factor w/ 6 levels "No_HS"<"HS"<"Associates"<..: 4 4 4 5 3 4 5 4 4 4 ...
##  $ Q6_Major_in_Edu  : num  1 1 0 1 1 1 0 1 0 0 ...
##  $ Q6_Major_in_Edu_F: Factor w/ 2 levels "Not_education",..: 2 2 1 2 2 2 1 2 1 1 ...
##  $ Q15_Index_raw    : num  1.71 2.43 2.71 1.29 2.14 ...
##  $ Q15_Index        : num  2.29 1.57 1.29 2.71 1.86 ...
##  $ Q16_Index_raw    : num  1.71 1.43 2 1.71 1.43 ...
##  $ Q16_Index        : num  0.714 0.429 1 0.714 0.429 ...
##  $ Q19_Index_raw    : num  3.33 3 1.67 3.33 2 ...
##  $ Q19_Index        : num  0.667 1 2.333 0.667 2 ...
\end{verbatim}

While we are at this, we might as well estimate the descriptive statistics of two more variables, Q13\_NumSs, and Q17\_Mins, which are the number of students in the teacher's math class and the number of minutes in a typical week that the teacher spends teaching math to those students. So, we have five continuous variables we need to report on.

We could use the \texttt{summary()} function for each one, but this is pretty limiting. For example, it does not include standard deviation the or the standard error of the mean.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q15_Index)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.5714  1.2857  1.5714  1.7190  2.0000  3.0000
\end{verbatim}

We can use specific functions for the statistics that are missing from \texttt{summary()}, such as \texttt{sd()}:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sd}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q15_Index, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.6054913
\end{verbatim}

The \texttt{na.rm\ =\ TRUE} tells R to calculate the value even if there are missing data (i.e., remove an observation before the calculation). Most other programs, like SPSS do this by default, but R is making us think twice about this, which is actually a good thing.

We could also use our own function to calculate the standard error of the mean, \(\frac{s_x}{\sqrt{n_x}}\):\footnote{If there were missing data, we would specify \texttt{na.rm\ =\ TRUE} for the \texttt{sd()} function and use \texttt{Q15\_n\ \ \textless{}-\ sum(!is.na(Q15\_Index))} for the \emph{n}-size calculation, which is a function that counts the number of observations that are not missing.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Q15_sd <-}\StringTok{ }\KeywordTok{sd}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q15_Index)}
\NormalTok{Q15_n  <-}\StringTok{ }\KeywordTok{nrow}\NormalTok{(timss)}
\NormalTok{Q15_se <-}\StringTok{ }\NormalTok{Q15_sd}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(Q15_n)}
\NormalTok{Q15_se}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1105471
\end{verbatim}

However, we can also use the \texttt{describe()} function from the psych package to do this work for us.

Let's pull the psych package from our ``library'' of packages into our current session so we can use its functions and then put it to use:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(psych)}
\KeywordTok{describe}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q15_Index)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    vars  n mean   sd median trimmed  mad  min max range skew kurtosis   se
## X1    1 30 1.72 0.61   1.57    1.68 0.64 0.57   3  2.43 0.43    -0.62 0.11
\end{verbatim}

We can do this with multiple variables at the same time and create a report:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{report1 <-}\StringTok{ }\KeywordTok{describe}\NormalTok{(timss[,}\KeywordTok{c}\NormalTok{(}\StringTok{"Q15_Index"}\NormalTok{,}
                             \StringTok{"Q16_Index"}\NormalTok{,}
                             \StringTok{"Q19_Index"}\NormalTok{,}
                             \StringTok{"Q13_NumSs"}\NormalTok{,}
                             \StringTok{"Q17_Mins"}\NormalTok{)])}
\NormalTok{report1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           vars  n   mean    sd median trimmed   mad    min    max range  skew
## Q15_Index    1 30   1.72  0.61   1.57    1.68  0.64   0.57   3.00  2.43  0.43
## Q16_Index    2 30   0.72  0.27   0.71    0.71  0.21   0.14   1.43  1.29  0.39
## Q19_Index    3 30   1.56  0.83   1.83    1.57  0.74   0.00   3.00  3.00 -0.22
## Q13_NumSs    4 30  23.13  5.75  24.00   23.46  4.45   8.00  35.00 27.00 -0.51
## Q17_Mins     5 30 193.67 29.30 190.00  192.92 29.65 150.00 240.00 90.00  0.31
##           kurtosis   se
## Q15_Index    -0.62 0.11
## Q16_Index     0.14 0.05
## Q19_Index    -1.27 0.15
## Q13_NumSs     0.14 1.05
## Q17_Mins     -1.25 5.35
\end{verbatim}

This is great. We have a lot of statistics here that we can include in our write-up. One thing we need, however, that is not included is the confidence interval of the estimated mean. We can create two new columns for this, the lower bound and upper bound of the interval using the formula \(mean \pm z(SE_{mean})\) or \(mean \pm t(SE_{mean})\) depending on whether we want to use a \emph{z}- or a \emph{t}-distribution.

However, I stumbled into a problem. The psych package seems to assign attributes to objects we create with the \texttt{describe()} function, which I found was causing a problem when I wanted to perform operations and create new variables in the data frame. I am adding this code here because my code below (which worked in earlier versions of the psych package) was throwing me an error. In looking at the outputted object's type, which we could see with the \texttt{str()} function or more clearly with the \texttt{class()} function, we see that this is not just a data frame, which is probably the source of my coding problems when I tried to add a new column:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{class}\NormalTok{(report1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "psych"      "describe"   "data.frame"
\end{verbatim}

This shows that the object is not just a data frame. Let's coerce to be \emph{just} a data frame by using the \texttt{data.frame()} function on it:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{report1 <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(report1)}
\KeywordTok{class}\NormalTok{(report1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "data.frame"
\end{verbatim}

That's better. I wish the psych package were friendlier. In this next section, we'll calculate the confidence interval and attach it to this report data frame.

\hypertarget{calculating-the-confidence-interval}{%
\subsubsection{Calculating the confidence interval}\label{calculating-the-confidence-interval}}

We can calculate the estimated 95\% confidence interval from the information from the report. Let's use a \emph{t}-distribution to multiple by the standard error. This requires the degrees of freedom, which is \(n - 1\) here. The \texttt{qt()} function can be used to get this distribution with the 30 respondents:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qt}\NormalTok{(.}\DecValTok{975}\NormalTok{, }\DataTypeTok{df =} \DecValTok{29}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.04523
\end{verbatim}

This is one tail of the distribution. The other tail would be the negative of this, \(-2.0452\). If we wanted to use the normal (\emph{z}) distribution, we can use the \texttt{qnorm()} function:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qnorm}\NormalTok{(.}\DecValTok{975}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.959964
\end{verbatim}

The \emph{t} distribution is more conservative, which increases the credibility of our inferences about the confidence interval, though it does result in a broader confidence interval than with the \emph{z} distribution.

With the first variable, the confidence interval is this (with some rounding error):\footnote{A shorter code for these two lines is \texttt{1.72\ +\ c(-1,\ 1)\ *\ qt(0.975,\ df\ =\ 30\ -1)*0.11}.}

\begin{Shaded}
\begin{Highlighting}[]
\FloatTok{1.72} \OperatorTok{-}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DataTypeTok{df =} \DecValTok{30} \DecValTok{-1}\NormalTok{)}\OperatorTok{*}\FloatTok{0.11}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.495025
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FloatTok{1.72} \OperatorTok{+}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DataTypeTok{df =} \DecValTok{30} \DecValTok{-1}\NormalTok{)}\OperatorTok{*}\FloatTok{0.11}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.944975
\end{verbatim}

\hypertarget{generating-and-exporting-a-report}{%
\subsubsection{Generating and exporting a report}\label{generating-and-exporting-a-report}}

We can use the dplyr package to create the new variables and reorder the variables The \texttt{\%\textgreater{}\%} symbol means that we take the object before it, \texttt{report1}, and do the following things. Here, we're using the \texttt{mutate()} function to create new variables for the upper and lower 95\% confidence interval boundaries. We also use \texttt{select()} to select which variables we want in our final data set and their order.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# install.packages("dplyr") # Run this line if you need to install it}
\KeywordTok{library}\NormalTok{(dplyr)}
\NormalTok{MyReport1 <-}\StringTok{ }\NormalTok{report1 }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{LB_t =}\NormalTok{  mean }\OperatorTok{-}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DataTypeTok{df =}\NormalTok{ n }\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{se,}
         \DataTypeTok{UB_t =}\NormalTok{  mean }\OperatorTok{+}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DataTypeTok{df =}\NormalTok{ n }\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{se,}
         \DataTypeTok{varb =} \KeywordTok{rownames}\NormalTok{(.) ) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(varb, n, mean, sd, min, max, se, LB_t, UB_t)}
\NormalTok{MyReport1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        varb  n        mean         sd         min        max         se
## 1 Q15_Index 30   1.7190476  0.6054913   0.5714286   3.000000 0.11054709
## 2 Q16_Index 30   0.7190476  0.2717870   0.1428571   1.428571 0.04962129
## 3 Q19_Index 30   1.5555556  0.8319913   0.0000000   3.000000 0.15190013
## 4 Q13_NumSs 30  23.1333333  5.7519612   8.0000000  35.000000 1.05015963
## 5  Q17_Mins 30 193.6666667 29.3002687 150.0000000 240.000000 5.34947271
##          LB_t        UB_t
## 1   1.4929534   1.9451418
## 2   0.6175607   0.8205345
## 3   1.2448849   1.8662262
## 4  20.9855157  25.2811509
## 5 182.7257665 204.6075668
\end{verbatim}

We can export this to a CSV file, open it in a spreadsheet program like Excel, format the numbers, and then copy and paste the cells into a table in Word or some other word processor.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{write.csv}\NormalTok{(MyReport1,}\StringTok{"report1.csv"}\NormalTok{, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{but-really-its-inferential}{%
\subsection{But really, it's inferential}\label{but-really-its-inferential}}

This chapter introduced some ways to calculate and report descriptive statistics. We included in our reports the standard error and the confidence intervals around the mean. However, strictly speaking, any time we seek to draw inferences about a larger population, we are actually estimating \emph{inferential} statistics, because---well---we are drawing an inference about a larger group of people (the population) based on our sample.\footnote{The reason for this discrepancy seems to be that in many studies in education and psychology, our research questions are about differences between groups, changes over time, or the relationship among variables, such as in a regression. We perform inferential statistical analyses to answer these questions---things like \emph{t}-tests, repeated-measures ANOVA (including paired \emph{t}-tests) or regression, and estimates of correlation or regression parameters. Traditionally, before we present those inferential-statistics results, we tend to present the descriptive statistics of the groups or time points we are measuring. In those scenarios, they are called descriptive statistics and are not intended to address inferential questions about the population because that part is reserved for our research questions. In contrast, in survey methods, our research questions might simply be about the mean of the population, in which case, the confidence intervals around those means help us to draw conclusions about how precise our estimates of the means are.} Whenever we estimate a statistic, such as the mean (or the variance), we have a point estimate. It is very unlikely that this point estimate is the exact mean that is present in the population. The confidence intervals help us to judge how well we can infer from our actual data what the population mean is.

\hypertarget{ByDescripts}{%
\section{Descriptive Statistics by Group}\label{ByDescripts}}

\hypertarget{using-the-describeby-function}{%
\subsection{\texorpdfstring{Using the \texttt{describeBy()} function}{Using the describeBy() function}}\label{using-the-describeby-function}}

We can get descriptive statistics by group using the psych package's \texttt{describeBy()} function. In this case, we are interested in two groups: whether the teachers majored in education or not. In this chapter, we will estimate these, export them to a report, and plot the by-group data for one of the variables.

In the previous chapter, we had created a factor using this code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timss}\OperatorTok{$}\NormalTok{Q6_Major_in_Edu_F <-}\StringTok{ }\KeywordTok{factor}\NormalTok{(timss}\OperatorTok{$}\NormalTok{Q6_Major_in_Edu,}
                                  \DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{),}
                                  \DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"Not_education"}\NormalTok{,}
                                             \StringTok{"Education"}\NormalTok{) )}
\end{Highlighting}
\end{Shaded}

We will use this column in the data frame as our by-variable.

We can see that the \texttt{describeBy()} function is very similar to the \texttt{describe()} function, except in its name and in the addition of the \texttt{group\ =} argument:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(psych)}
\NormalTok{report2 <-}\StringTok{ }\KeywordTok{describeBy}\NormalTok{(timss[,}\KeywordTok{c}\NormalTok{(}\StringTok{"Q15_Index"}\NormalTok{,}
                               \StringTok{"Q16_Index"}\NormalTok{,}
                               \StringTok{"Q19_Index"}\NormalTok{,}
                               \StringTok{"Q13_NumSs"}\NormalTok{,}
                               \StringTok{"Q17_Mins"}\NormalTok{)], }
                              \DataTypeTok{group =}\NormalTok{ timss}\OperatorTok{$}\NormalTok{Q6_Major_in_Edu_F)}
\end{Highlighting}
\end{Shaded}

Let's take a look at the output:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{report2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Descriptive statistics by group 
## group: Not_education
##           vars  n   mean    sd median trimmed   mad    min    max range  skew
## Q15_Index    1 13   1.24  0.24   1.29    1.27  0.21   0.57   1.57  1.00 -1.33
## Q16_Index    2 13   0.88  0.27   0.86    0.86  0.21   0.57   1.43  0.86  0.44
## Q19_Index    3 13   1.95  0.73   2.00    2.06  0.49   0.00   2.67  2.67 -1.44
## Q13_NumSs    4 13  25.77  4.71  26.00   25.64  4.45  18.00  35.00 17.00  0.09
## Q17_Mins     5 13 182.31 23.86 170.00  180.91 29.65 150.00 230.00 80.00  0.60
##           kurtosis   se
## Q15_Index     1.79 0.07
## Q16_Index    -1.00 0.07
## Q19_Index     1.27 0.20
## Q13_NumSs    -0.81 1.31
## Q17_Mins     -0.87 6.62
## ------------------------------------------------------------ 
## group: Education
##           vars  n   mean    sd median trimmed   mad    min max range  skew
## Q15_Index    1 17   2.08  0.54   2.00    2.10  0.42   0.86   3  2.14 -0.15
## Q16_Index    2 17   0.60  0.21   0.57    0.60  0.21   0.14   1  0.86 -0.29
## Q19_Index    3 17   1.25  0.80   1.00    1.20  0.99   0.33   3  2.67  0.55
## Q13_NumSs    4 17  21.12  5.78  21.00   21.47  7.41   8.00  29 21.00 -0.62
## Q17_Mins     5 17 202.35 30.73 200.00  203.33 29.65 150.00 240 90.00 -0.05
##           kurtosis   se
## Q15_Index    -0.39 0.13
## Q16_Index    -0.37 0.05
## Q19_Index    -0.91 0.19
## Q13_NumSs    -0.54 1.40
## Q17_Mins     -1.48 7.45
\end{verbatim}

\hypertarget{confidence-intervals-for-each-groups-estimated-mean}{%
\subsection{Confidence intervals for each group's estimated mean}\label{confidence-intervals-for-each-groups-estimated-mean}}

For the by-group report, we can copy and paste the code we used in the previous chapter for the confidence intervals, but we have to do this separately with each group's report. So, we need to separate the report into two data frames, estimate the confidence intervals, and then glue them (bind them) back together.

\hypertarget{separating-the-report-by-group}{%
\subsubsection{Separating the report by group}\label{separating-the-report-by-group}}

The output from the \texttt{describeBy()} function we used has ``Not\_education'' and ``Education'' for the group. We use that to subset the data. For example, to get the descriptive statistics for those teachers who did not major in education, we use this code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{report2}\OperatorTok{$}\NormalTok{Not_education}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           vars  n   mean    sd median trimmed   mad    min    max range  skew
## Q15_Index    1 13   1.24  0.24   1.29    1.27  0.21   0.57   1.57  1.00 -1.33
## Q16_Index    2 13   0.88  0.27   0.86    0.86  0.21   0.57   1.43  0.86  0.44
## Q19_Index    3 13   1.95  0.73   2.00    2.06  0.49   0.00   2.67  2.67 -1.44
## Q13_NumSs    4 13  25.77  4.71  26.00   25.64  4.45  18.00  35.00 17.00  0.09
## Q17_Mins     5 13 182.31 23.86 170.00  180.91 29.65 150.00 230.00 80.00  0.60
##           kurtosis   se
## Q15_Index     1.79 0.07
## Q16_Index    -1.00 0.07
## Q19_Index     1.27 0.20
## Q13_NumSs    -0.81 1.31
## Q17_Mins     -0.87 6.62
\end{verbatim}

Here are the stats for teachers who did major in education:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{report2}\OperatorTok{$}\NormalTok{Education }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           vars  n   mean    sd median trimmed   mad    min max range  skew
## Q15_Index    1 17   2.08  0.54   2.00    2.10  0.42   0.86   3  2.14 -0.15
## Q16_Index    2 17   0.60  0.21   0.57    0.60  0.21   0.14   1  0.86 -0.29
## Q19_Index    3 17   1.25  0.80   1.00    1.20  0.99   0.33   3  2.67  0.55
## Q13_NumSs    4 17  21.12  5.78  21.00   21.47  7.41   8.00  29 21.00 -0.62
## Q17_Mins     5 17 202.35 30.73 200.00  203.33 29.65 150.00 240 90.00 -0.05
##           kurtosis   se
## Q15_Index    -0.39 0.13
## Q16_Index    -0.37 0.05
## Q19_Index    -0.91 0.19
## Q13_NumSs    -0.54 1.40
## Q17_Mins     -1.48 7.45
\end{verbatim}

\hypertarget{calculating-the-confidence-interval-1}{%
\subsubsection{Calculating the confidence interval}\label{calculating-the-confidence-interval-1}}

Let's start with the teachers who did not major in education. Also, notice that there is a new variable that we are creating called EduMajor. For this group, we set it to ``No''.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(dplyr)}
\NormalTok{report2_}\DecValTok{0}\NormalTok{ <-}\StringTok{ }\NormalTok{report2}\OperatorTok{$}\NormalTok{Not_education }\OperatorTok{%>%}\StringTok{ }
\StringTok{   }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{EduMajor =} \StringTok{"No"}\NormalTok{,}
              \DataTypeTok{LB_t =}\NormalTok{  mean }\OperatorTok{-}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DataTypeTok{df =}\NormalTok{ n }\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{se,}
              \DataTypeTok{UB_t =}\NormalTok{  mean }\OperatorTok{+}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DataTypeTok{df =}\NormalTok{ n }\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{se,}
              \DataTypeTok{varb =} \KeywordTok{rownames}\NormalTok{(.)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{data.frame}\NormalTok{() }\OperatorTok{%>%}\StringTok{ }\CommentTok{# have to add this because the psych package messed up the format (described in the previous chapter)}
\StringTok{  }\KeywordTok{select}\NormalTok{(varb, EduMajor, n, mean, sd, min, max, se, LB_t, UB_t)}
\end{Highlighting}
\end{Shaded}

Now, for the education majors:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{report2_}\DecValTok{1}\NormalTok{<-}\StringTok{ }\NormalTok{report2}\OperatorTok{$}\NormalTok{Education }\OperatorTok{%>%}\StringTok{ }
\StringTok{   }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{EduMajor =} \StringTok{"Yes"}\NormalTok{,}
              \DataTypeTok{LB_t =}\NormalTok{  mean }\OperatorTok{-}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DataTypeTok{df =}\NormalTok{ n }\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{se,}
              \DataTypeTok{UB_t =}\NormalTok{  mean }\OperatorTok{+}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DataTypeTok{df =}\NormalTok{ n }\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{se,}
              \DataTypeTok{varb =} \KeywordTok{rownames}\NormalTok{(.)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{data.frame}\NormalTok{() }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(varb, EduMajor, n, mean, sd, min, max, se, LB_t, UB_t)}
\end{Highlighting}
\end{Shaded}

We can stack these two data frames on top of each other with the \texttt{rbind()} function, which binds the rows together. We can do this because the two different data frames have precisely the same column names and types of data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MyReport2 <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(report2_}\DecValTok{0}\NormalTok{, report2_}\DecValTok{1}\NormalTok{)}
\NormalTok{MyReport2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         varb EduMajor  n        mean         sd         min        max
## 1  Q15_Index       No 13   1.2417582  0.2431694   0.5714286   1.571429
## 2  Q16_Index       No 13   0.8791209  0.2662805   0.5714286   1.428571
## 3  Q19_Index       No 13   1.9487179  0.7308817   0.0000000   2.666667
## 4  Q13_NumSs       No 13  25.7692308  4.7108712  18.0000000  35.000000
## 5   Q17_Mins       No 13 182.3076923 23.8585576 150.0000000 230.000000
## 6  Q15_Index      Yes 17   2.0840336  0.5417725   0.8571429   3.000000
## 7  Q16_Index      Yes 17   0.5966387  0.2096845   0.1428571   1.000000
## 8  Q19_Index      Yes 17   1.2549020  0.7952062   0.3333333   3.000000
## 9  Q13_NumSs      Yes 17  21.1176471  5.7758371   8.0000000  29.000000
## 10  Q17_Mins      Yes 17 202.3529412 30.7264975 150.0000000 240.000000
##            se        LB_t        UB_t
## 1  0.06744305   1.0948125   1.3887040
## 2  0.07385291   0.7182092   1.0400326
## 3  0.20271011   1.5070506   2.3903853
## 4  1.30656060  22.9224798  28.6159818
## 5  6.61717328 167.8901103 196.7252744
## 6  0.13139912   1.8054799   2.3625873
## 7  0.05085596   0.4888288   0.7044485
## 8  0.19286584   0.8460446   1.6637593
## 9  1.40084626  18.1479857  24.0873085
## 10 7.45227027 186.5548339 218.1510484
\end{verbatim}

We can use the \texttt{arrange()} function from the dplyr package to order the data by their variables. This way we can see the estimates of each group on a particular variable in adjacent rows.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(dplyr)}
\NormalTok{MyReport2 <-}\StringTok{ }\KeywordTok{arrange}\NormalTok{(MyReport2, varb)}
\NormalTok{MyReport2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         varb EduMajor  n        mean         sd         min        max
## 1  Q13_NumSs       No 13  25.7692308  4.7108712  18.0000000  35.000000
## 2  Q13_NumSs      Yes 17  21.1176471  5.7758371   8.0000000  29.000000
## 3  Q15_Index       No 13   1.2417582  0.2431694   0.5714286   1.571429
## 4  Q15_Index      Yes 17   2.0840336  0.5417725   0.8571429   3.000000
## 5  Q16_Index       No 13   0.8791209  0.2662805   0.5714286   1.428571
## 6  Q16_Index      Yes 17   0.5966387  0.2096845   0.1428571   1.000000
## 7   Q17_Mins       No 13 182.3076923 23.8585576 150.0000000 230.000000
## 8   Q17_Mins      Yes 17 202.3529412 30.7264975 150.0000000 240.000000
## 9  Q19_Index       No 13   1.9487179  0.7308817   0.0000000   2.666667
## 10 Q19_Index      Yes 17   1.2549020  0.7952062   0.3333333   3.000000
##            se        LB_t        UB_t
## 1  1.30656060  22.9224798  28.6159818
## 2  1.40084626  18.1479857  24.0873085
## 3  0.06744305   1.0948125   1.3887040
## 4  0.13139912   1.8054799   2.3625873
## 5  0.07385291   0.7182092   1.0400326
## 6  0.05085596   0.4888288   0.7044485
## 7  6.61717328 167.8901103 196.7252744
## 8  7.45227027 186.5548339 218.1510484
## 9  0.20271011   1.5070506   2.3903853
## 10 0.19286584   0.8460446   1.6637593
\end{verbatim}

Now we have a report with a column that identifies the group. We can export this to a CSV file and then open it with our spreadsheet program to round the numbers to our preferred decimal places before we export it into our word processor's table.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{write.csv}\NormalTok{(MyReport2, }\StringTok{"report2.csv"}\NormalTok{, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{plotting-the-by-group-means-and-confidence-intervals}{%
\subsection{Plotting the by-group means and confidence intervals}\label{plotting-the-by-group-means-and-confidence-intervals}}

Let's create a plot of two variables side by side: Q15 and Q19, by whether they got their degree in education or not. First, let's subset our data. We can use the \texttt{filter()} function from dplyr:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(dplyr)}
\NormalTok{ForPlot <-}\StringTok{ }\NormalTok{MyReport2 }\OperatorTok{%>%}\StringTok{ }
\StringTok{               }\KeywordTok{filter}\NormalTok{(varb }\OperatorTok{==}\StringTok{ "Q15_Index"} \OperatorTok{|}\StringTok{ }\NormalTok{varb }\OperatorTok{==}\StringTok{ "Q19_Index"}\NormalTok{)}
\NormalTok{ForPlot }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        varb EduMajor  n     mean        sd       min      max         se
## 1 Q15_Index       No 13 1.241758 0.2431694 0.5714286 1.571429 0.06744305
## 2 Q15_Index      Yes 17 2.084034 0.5417725 0.8571429 3.000000 0.13139912
## 3 Q19_Index       No 13 1.948718 0.7308817 0.0000000 2.666667 0.20271011
## 4 Q19_Index      Yes 17 1.254902 0.7952062 0.3333333 3.000000 0.19286584
##        LB_t     UB_t
## 1 1.0948125 1.388704
## 2 1.8054799 2.362587
## 3 1.5070506 2.390385
## 4 0.8460446 1.663759
\end{verbatim}

Now, we have a data frame of our report that contains only these two variables. Let's use the ggplot2 package and a geom called \texttt{geom\_col}, which makes columns and allows us to position groups' scores adjacent to each other (with the \texttt{position\ =\ "dodge"} argument):

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ ForPlot, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ varb, }\DataTypeTok{y =}\NormalTok{ mean, }\DataTypeTok{fill=}\NormalTok{EduMajor)) }\OperatorTok{+}
\StringTok{ }\KeywordTok{geom_col}\NormalTok{(}\DataTypeTok{position =} \StringTok{"dodge"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{Getting-started_files/figure-latex/unnamed-chunk-103-1.pdf}

Let's add confidence intervals to the plot. The \texttt{geom\_errorbar()} part of the code displays a band around the mean, which is the top of our bars. This allows us to eyeball whether the two groups are likely to be statistically different or not. Notice that we are using the lower bound and upper bound estimates that we had calculated earlier.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Myplot <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(ForPlot, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ varb, }\DataTypeTok{y =}\NormalTok{ mean, }\DataTypeTok{fill=}\NormalTok{EduMajor)) }\OperatorTok{+}
\StringTok{ }\KeywordTok{geom_col}\NormalTok{(}\DataTypeTok{width =} \FloatTok{0.9}\NormalTok{, }\DataTypeTok{position =} \StringTok{"dodge"}\NormalTok{) }\OperatorTok{+}
\StringTok{ }\KeywordTok{geom_errorbar}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{ymin =}\NormalTok{ LB_t, }\DataTypeTok{ymax =}\NormalTok{ UB_t),}
              \DataTypeTok{position =} \KeywordTok{position_dodge}\NormalTok{(}\FloatTok{0.9}\NormalTok{), }\DataTypeTok{width =} \FloatTok{0.2}\NormalTok{)}
\NormalTok{Myplot}
\end{Highlighting}
\end{Shaded}

\includegraphics{Getting-started_files/figure-latex/unnamed-chunk-104-1.pdf}

This plot says a lot. The two groups clearly differ on the Q15\_Index. Their confidence intervals don't overlap at all. On the Q19\_Index, they might still statistically significantly differ. With 95\% confidence intervals that overlap less than about 25\%, we can still observe statistically significant difference.\footnote{Note that it is a misconception that statistically significant different results only occur when confidence intervals do not overlap. Nope. Not true.}

\hypertarget{making-a-pretty-plot-maybe}{%
\subsubsection{Making a pretty plot, maybe}\label{making-a-pretty-plot-maybe}}

The following code generates a plot that is more informative and perhaps more pleasing in format:\footnote{The viridis color palette is included in this plot. Viridis color pallettes are designed to be a little more accessible to people with colorblindness.} Notice that the scale of the composite scores is the same as that used in the items. This helps us interpret the meaning of these composite scores. For instance, with the teachers who majored in education when they were in college, the estimated mean on the Q15 index is \(2.08\), which slightly more frequent than \emph{About half the lessons} on the original Likert-type scale.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MyPretty <-}\StringTok{ }\NormalTok{Myplot }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_grey}\NormalTok{(}\DataTypeTok{base_size =} \DecValTok{16}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.title.x.bottom=}\KeywordTok{element_blank}\NormalTok{() ) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_fill_viridis_d}\NormalTok{(}\DataTypeTok{option =} \StringTok{"cividis"}\NormalTok{, }\DataTypeTok{begin=}\FloatTok{0.2}\NormalTok{,}\DataTypeTok{end=}\FloatTok{0.6}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Mean score"}\NormalTok{)   }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_x_discrete}\NormalTok{(}\DataTypeTok{labels=}\KeywordTok{c}\NormalTok{(}\StringTok{"Student centered}\CharTok{\textbackslash{}n}\StringTok{teaching approach"}\NormalTok{,}
                            \StringTok{"Didactic}\CharTok{\textbackslash{}n}\StringTok{teaching approach"}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{guides}\NormalTok{(}\DataTypeTok{fill =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\DataTypeTok{x =} \FloatTok{.65}\NormalTok{, }\DataTypeTok{y =} \FloatTok{0.10}\NormalTok{, }\DataTypeTok{size =} \DecValTok{5}\NormalTok{, }\DataTypeTok{color=}\StringTok{"white"}\NormalTok{, }
            \DataTypeTok{label =} \StringTok{"Did not major}\CharTok{\textbackslash{}n}\StringTok{in education"}\NormalTok{,}
            \DataTypeTok{hjust =} \DecValTok{0}\NormalTok{, }\DataTypeTok{vjust=}\DecValTok{1}\NormalTok{,  }\DataTypeTok{angle =} \DecValTok{90}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\DataTypeTok{x =} \FloatTok{1.05}\NormalTok{, }\DataTypeTok{y =} \FloatTok{0.10}\NormalTok{, }\DataTypeTok{size =}\DecValTok{5}\NormalTok{,  }\DataTypeTok{color=}\StringTok{"white"}\NormalTok{,}
            \DataTypeTok{label =} \StringTok{"Majored in education"}\NormalTok{,}
            \DataTypeTok{hjust =} \DecValTok{0}\NormalTok{, }\DataTypeTok{vjust=}\DecValTok{1}\NormalTok{, }\DataTypeTok{angle =} \DecValTok{90}\NormalTok{) }\OperatorTok{+}
\StringTok{   }
\StringTok{  }\KeywordTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\DataTypeTok{x =} \DecValTok{0}\NormalTok{, }\DataTypeTok{y =} \DecValTok{0}\NormalTok{, }\DataTypeTok{fontface=}\StringTok{"italic"}\NormalTok{, }\DataTypeTok{size =} \DecValTok{3}\NormalTok{,}
            \DataTypeTok{label =} \StringTok{"Never"}\NormalTok{, }\DataTypeTok{hjust=}\DecValTok{0}\NormalTok{, }\DataTypeTok{vjust=}\OperatorTok{-}\NormalTok{.}\DecValTok{2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\DataTypeTok{x =} \DecValTok{0}\NormalTok{, }\DataTypeTok{y =} \DecValTok{1}\NormalTok{, }\DataTypeTok{fontface=}\StringTok{"italic"}\NormalTok{, }\DataTypeTok{size =} \DecValTok{3}\NormalTok{, }
            \DataTypeTok{label =} \StringTok{"Some}\CharTok{\textbackslash{}n}\StringTok{lessons"}\NormalTok{, }\DataTypeTok{hjust=}\DecValTok{0}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\DataTypeTok{x =} \DecValTok{0}\NormalTok{, }\DataTypeTok{y =} \DecValTok{2}\NormalTok{, }\DataTypeTok{fontface=}\StringTok{"italic"}\NormalTok{, }\DataTypeTok{size =} \DecValTok{3}\NormalTok{,}
            \DataTypeTok{label =} \StringTok{"About half}\CharTok{\textbackslash{}n}\StringTok{the lessons"}\NormalTok{, }\DataTypeTok{hjust=}\DecValTok{0}\NormalTok{)}

\NormalTok{MyPretty}
\end{Highlighting}
\end{Shaded}

\includegraphics{Getting-started_files/figure-latex/unnamed-chunk-106-1.pdf}

\hypertarget{saving-plots}{%
\subsubsection{Saving plots}\label{saving-plots}}

We can save plots to objects and then export them to .png or .pdf formats. The image, in .png format, is easy to paste into a word processor slide show for your report:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggsave}\NormalTok{(}\StringTok{"MyPrettyPlot.png"}\NormalTok{, MyPretty, }\DataTypeTok{width =} \DecValTok{6}\NormalTok{, }\DataTypeTok{height =} \DecValTok{5}\NormalTok{)}
\KeywordTok{ggsave}\NormalTok{(}\StringTok{"MyPrettyPlot.pdf"}\NormalTok{, MyPretty, }\DataTypeTok{width =} \DecValTok{6}\NormalTok{, }\DataTypeTok{height =} \DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{Reliability}{%
\section{Internal Consistency Reliability}\label{Reliability}}

\hypertarget{doing-it-manually}{%
\subsection{Doing it manually}\label{doing-it-manually}}

Let's hand calculate it for one of our scales, Q15, using the formula for coefficient alpha in the slides. Here's the covariance matrix:\footnote{The term \emph{covariance matrix} is an abbreviation of \emph{variance-covariance matrix}, which is more accurate but more cumbersome to say and write. The matrix includes the item variances on the diagonal and the covariances on the off diagonal.}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{round}\NormalTok{(}\KeywordTok{cov}\NormalTok{(timss[,Q15]),}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                Q15_StCentrd_a Q15_StCentrd_b Q15_StCentrd_c Q15_StCentrd_d
## Q15_StCentrd_a           0.74           0.32           0.04           0.51
## Q15_StCentrd_b           0.32           0.56          -0.02           0.26
## Q15_StCentrd_c           0.04          -0.02           0.84           0.21
## Q15_StCentrd_d           0.51           0.26           0.21           0.85
## Q15_StCentrd_e           0.50           0.36          -0.05           0.36
## Q15_StCentrd_f           0.30           0.28           0.22           0.20
## Q15_StCentrd_g           0.55           0.41           0.16           0.60
##                Q15_StCentrd_e Q15_StCentrd_f Q15_StCentrd_g
## Q15_StCentrd_a           0.50           0.30           0.55
## Q15_StCentrd_b           0.36           0.28           0.41
## Q15_StCentrd_c          -0.05           0.22           0.16
## Q15_StCentrd_d           0.36           0.20           0.60
## Q15_StCentrd_e           0.62           0.31           0.47
## Q15_StCentrd_f           0.31           0.79           0.41
## Q15_StCentrd_g           0.47           0.41           0.83
\end{verbatim}

Here's the total variance. Notice that this is the sum of all of the cells in the variance-covariance matrix:\footnote{Note that this total variance calculated as the sum of the matrix's cells is the same as the variance of the composite score when that score is calculated as the sum of the item scores, which is often what we do in tests---we add up each person's points across the items to get their total score. However, to make our composite score easier to interpret on our survey scale, we have calculated each person's score as their mean across the \emph{k} items making up that scale, as this allows us to see each person's composite score on the same scale as the meaningful points in the Likert-type scale that is used with all \emph{k} of the items. For example, the first teacher's score on the Q15 composite scale was \(2.29\), which somewhat more frequent than \emph{About half the lessons} on the original Likert-type scale. That is easier to interpret than a sum score would be---it is harder to relate the person's sum score of \(16.03\) back to a meaningful scale. Because our scale score is now divided by the number of items (\(k = 7\) in this case), this total variance differs from that of the sum of the variance-covariance cells---it is smaller because we have divided by the constant 7. By the rules of algebra of expectation, we can multiply the variance of this, which is \texttt{var(timss\$Q15\_Index)} \(= 0.37\), by this constant squared to retrieve the same variance as if the composite score were calculated as the sum across the items: \texttt{var(timss\$Q15\_Index)*ncol(timss{[},Q15{]})\^{}2} \(=17.96\). This value is the same as the sum of the cells in the covariance matrix.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(totvar <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\KeywordTok{cov}\NormalTok{(timss[,Q15])))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 17.96437
\end{verbatim}

Here's the unique variance of the items:\footnote{Placing parentheses around R code forces it to be printed to the console. It's simply a shortcut so we don't have to type the object (\texttt{totvar} in this example) to view the result.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(itemvarsum <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\KeywordTok{apply}\NormalTok{(timss[,Q15],}\DecValTok{2}\NormalTok{,var)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.224138
\end{verbatim}

Here's \emph{k}, which is the number of items in the scale:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(k <-}\StringTok{ }\KeywordTok{ncol}\NormalTok{(timss[,Q15]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7
\end{verbatim}

And, here's the alpha coefficient:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MyAlpha <-}\StringTok{ }\NormalTok{k}\OperatorTok{/}\NormalTok{(k}\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{(totvar }\OperatorTok{-}\StringTok{ }\NormalTok{itemvarsum)}\OperatorTok{/}\NormalTok{totvar}
\NormalTok{MyAlpha}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8273935
\end{verbatim}

\hypertarget{doing-it-with-the-psych-package}{%
\subsection{Doing it with the psych package}\label{doing-it-with-the-psych-package}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(psych)}
\CommentTok{# help(package = "psych")}
\end{Highlighting}
\end{Shaded}

To get coefficient alpha, we use the \texttt{alpha()} function.\footnote{Here, we're using the double colon before the function because the function \texttt{alpha()} shares the same name with an argument in the ggplot package, so this \texttt{psych::alpha()} ensures that the function comes from the psych package.} Take a look at the \texttt{raw\_alpha} column under the \texttt{Reliability\ if\ an\ item\ is\ dropped} section. What is this? Note where it is reported in our Word document that was shared on Laulima. In looking at this particular part of the output, what can we conclude about Item Q15\_StCentrd\_c?\footnote{The answer is that the item is functioning inconsistently with the other items in the scale. We can see the reliability of the scale would be \emph{higher} if we had eliminated the item from our calculation of the composite score.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{psych}\OperatorTok{::}\KeywordTok{alpha}\NormalTok{(timss[,Q15])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Reliability analysis   
## Call: psych::alpha(x = timss[, Q15])
## 
##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean   sd median_r
##       0.83      0.83    0.86      0.41 4.9 0.048  2.3 0.61     0.44
## 
##  lower alpha upper     95% confidence boundaries
## 0.73 0.83 0.92 
## 
##  Reliability if an item is dropped:
##                raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
## Q15_StCentrd_a      0.78      0.78    0.82      0.38 3.6    0.062 0.055  0.42
## Q15_StCentrd_b      0.81      0.81    0.85      0.41 4.2    0.055 0.064  0.44
## Q15_StCentrd_c      0.87      0.87    0.88      0.53 6.9    0.036 0.021  0.50
## Q15_StCentrd_d      0.79      0.80    0.83      0.40 4.0    0.059 0.069  0.44
## Q15_StCentrd_e      0.79      0.79    0.82      0.39 3.8    0.059 0.051  0.40
## Q15_StCentrd_f      0.81      0.82    0.85      0.43 4.5    0.052 0.079  0.49
## Q15_StCentrd_g      0.76      0.77    0.81      0.36 3.3    0.069 0.057  0.40
## 
##  Item statistics 
##                 n raw.r std.r r.cor r.drop mean   sd
## Q15_StCentrd_a 30  0.81  0.81  0.80   0.72  2.4 0.86
## Q15_StCentrd_b 30  0.68  0.71  0.64   0.57  1.8 0.75
## Q15_StCentrd_c 30  0.36  0.34  0.19   0.15  2.3 0.92
## Q15_StCentrd_d 30  0.76  0.75  0.72   0.64  2.3 0.92
## Q15_StCentrd_e 30  0.77  0.79  0.77   0.68  2.3 0.78
## Q15_StCentrd_f 30  0.66  0.66  0.58   0.52  2.6 0.89
## Q15_StCentrd_g 30  0.88  0.88  0.89   0.82  2.2 0.91
## 
## Non missing response frequency for each item
##                   1    2    3    4 miss
## Q15_StCentrd_a 0.13 0.40 0.37 0.10    0
## Q15_StCentrd_b 0.37 0.43 0.20 0.00    0
## Q15_StCentrd_c 0.23 0.30 0.40 0.07    0
## Q15_StCentrd_d 0.23 0.27 0.43 0.07    0
## Q15_StCentrd_e 0.13 0.53 0.27 0.07    0
## Q15_StCentrd_f 0.13 0.23 0.50 0.13    0
## Q15_StCentrd_g 0.27 0.37 0.30 0.07    0
\end{verbatim}

Does the estimate for alpha match our hand calculation? It should (though there the output here is rounded to two decimal places).

What's the internal consistency reliability of the other two composite scales (AKA indexes)?

\hypertarget{omega-reliability-using-the-psych-package}{%
\subsubsection{Omega reliability using the psych package}\label{omega-reliability-using-the-psych-package}}

For omega reliability use the omega function. Because we have only one score, the number of factors is 1 and we report the result in Omega Total. Omega is appropriate for reflective scoring models,
which was described in the validity PDF.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{psych}\OperatorTok{::}\KeywordTok{omega}\NormalTok{(timss[,Q15], }\DataTypeTok{nfactors=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Omega 
## Call: omegah(m = m, nfactors = nfactors, fm = fm, key = key, flip = flip, 
##     digits = digits, title = title, sl = sl, labels = labels, 
##     plot = plot, n.obs = n.obs, rotate = rotate, Phi = Phi, option = option, 
##     covar = covar)
## Alpha:                 0.83 
## G.6:                   0.86 
## Omega Hierarchical:    0.85 
## Omega H asymptotic:    1 
## Omega Total            0.85 
## 
## Schmid Leiman Factor loadings greater than  0.2 
##                   g  F1*   h2   u2 p2
## Q15_StCentrd_a 0.83      0.69 0.31  1
## Q15_StCentrd_b 0.66      0.44 0.56  1
## Q15_StCentrd_c           0.02 0.98  1
## Q15_StCentrd_d 0.69      0.47 0.53  1
## Q15_StCentrd_e 0.80      0.65 0.35  1
## Q15_StCentrd_f 0.53      0.28 0.72  1
## Q15_StCentrd_g 0.90      0.81 0.19  1
## 
## With eigenvalues of:
##   g F1* 
## 3.3 0.0 
## 
## general/max  6.025027e+16   max/min =   1
## mean percent general =  1    with sd =  0 and cv of  0 
## Explained Common Variance of the general factor =  1 
## 
## The degrees of freedom are 14  and the fit is  0.65 
## The number of observations was  30  with Chi Square =  16.25  with prob <  0.3
## The root mean square of the residuals is  0.09 
## The df corrected root mean square of the residuals is  0.11
## RMSEA index =  0.065  and the 10 % confidence intervals are  0 0.202
## BIC =  -31.37
## 
## Compare this with the adequacy of just a general factor and no group factors
## The degrees of freedom for just the general factor are 14  and the fit is  0.65 
## The number of observations was  30  with Chi Square =  16.25  with prob <  0.3
## The root mean square of the residuals is  0.09 
## The df corrected root mean square of the residuals is  0.11 
## 
## RMSEA index =  0.065  and the 10 % confidence intervals are  0 0.202
## BIC =  -31.37 
## 
## Measures of factor score adequacy             
##                                                  g F1*
## Correlation of scores with factors            0.96   0
## Multiple R square of scores with factors      0.92   0
## Minimum correlation of factor score estimates 0.84  -1
## 
##  Total, General and Subset omega for each subset
##                                                  g  F1*
## Omega total for total scores and subscales    0.85 0.85
## Omega general for total scores and subscales  0.85 0.85
## Omega group for total scores and subscales    0.00 0.00
\end{verbatim}

If you came across an error that said \texttt{"Failed\ with\ error:\ \textquotesingle{}there\ is\ no\ package\ called\ \textquotesingle{}GPArotation\textquotesingle{}\textquotesingle{}"}, install that package
and run the previous line again.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{install.packages}\NormalTok{(}\StringTok{"GPArotation"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Look at the bottom part of the output. We are not working with more than one factor, or subscale, so we can report the estimate under the \emph{g} column (``g'' stands for general). The first or second line, ``Omega general for total scores and subscales'' under g is \textbf{.85}. That's what we can report for this scale.

\hypertarget{summary-1}{%
\subsection{Summary}\label{summary-1}}

There are several types of reliability coefficients. Coefficients alpha and omega are for internal consistency. Coefficient alpha is the most popular. Coefficient omega is becoming more popular because it handles some of the problems that alpha ignores.

Other coefficients, such as for estimates of stability over time, with the intra-class correlation and generalizability coefficients are addressed in measurement primers and in EDEP 616.

\hypertarget{Complex}{%
\section{Introduction to the Analysis of Complex Survey Data}\label{Complex}}

In a garden variety simple-random-sample design, we randomly sample units from a larger population and then estimate the mean, standard deviation, and confidence intervals to subsequently draw an inference about the larger population. This is the assumption underlying the example and explanations in the previous chapters. In this chapter we examine complex survey data. In survey designs with complex data, we need to make corrections to the standard error, which in turn affects the confidence intervals, which subsequently affects our inference about the statistic---such as the mean---in the population we seek to make claims about.

\hypertarget{packages}{%
\subsection{Packages}\label{packages}}

There are two packages that are handy for analyzing complex survey data: The survey package \citep{R-survey} and the similarly named srvyr package \citep{R-srvyr}, which works with the survey package to make the output easier to work with (because why would the survey package on its own make life easy?). Harkening back to a previous chapter, we need to first be sure we have these packages installed. We will also use the dplyr package \citep{R-dplyr} again, as this uses the same data-wrangling language that the srvyr package does.\footnote{Whenever we use a package, it is a good idea to cite it. People work hard to create these (well usually---for some, it is disgustingly easy). To get the citation, we can use the \texttt{citation()} function, usually, as in \texttt{citation("srvyr")}. }

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(survey)}
\KeywordTok{library}\NormalTok{(srvyr)}
\KeywordTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\hypertarget{example-data}{%
\subsection{Example data}\label{example-data}}

To go through this example, let's use the data set that is presented in the chapter by Heeringa, West, and Berglund \citeyearpar[Chapter 2]{heeringa_applied_2010}, who provide an explanation that we can follow along with as we actually perform these calculations.\footnote{In their chapter, their variable of interest is persons' ratings of the economy. We use the same data but for demonstration call the outcome variable \emph{scores} and label the cases \emph{students}, who are nested within the school clusters, which are in districts, serving as strata. For this demo, we will ignore weighting.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"Heeringa.Complex.SampleData.csv"}\NormalTok{)}
\KeywordTok{str}\NormalTok{(dat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    32 obs. of  5 variables:
##  $ sid     : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ school  : int  1 1 1 1 2 2 2 2 3 3 ...
##  $ district: int  1 1 1 1 1 1 1 1 2 2 ...
##  $ score   : num  52.8 32.5 56.6 47 37.3 57 54.2 71.5 27.7 42.3 ...
##  $ weight  : int  1 2 2 1 1 1 2 2 1 2 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(dat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   sid school district score weight
## 1   1      1        1  52.8      1
## 2   2      1        1  32.5      2
## 3   3      1        1  56.6      2
## 4   4      1        1  47.0      1
## 5   5      2        1  37.3      1
## 6   6      2        1  57.0      1
\end{verbatim}

\hypertarget{the-three-hypothetical-complex-designs}{%
\subsection{The three hypothetical complex designs}\label{the-three-hypothetical-complex-designs}}

\hypertarget{pretending-we-have-a-cluster-sampled-design}{%
\subsubsection{Pretending we have a cluster-sampled design}\label{pretending-we-have-a-cluster-sampled-design}}

We will use this data set to practice analyzing the data in a cluster-sampled design. This would be the kind of analysis we would conduct if we had randomly sampled schools---that is, our clusters---from a broader population of schools (such as from a sampling frame that listed all of the schools in the country). In this design, our \emph{primary sampling unit} is schools. Within each school, we have students, whom we had administered the survey to.\footnote{Before we got to this step, we had previously calculated each student's score, which is the \texttt{score} variable in our data set. This score might be a composite score calculated as the mean (or sum) across several items, as was demonstrated in the previous chapter.} This design is very convenient because it is easier to randomly sample schools from a list of schools, whereas it is virtually impossible to have a list of all of the individual students in the country. We pay a price for this convenience, though, because students who are nested within schools tend to live in similar neighborhoods, share the same values, have the same learning experiences, and so forth, so if we used a run-of-the-mill standard error (and confidence interval), we will be overly optimistic in how precise we are in estimating the population. When we correctly analyze these data, we pay a penalty because our standard error is corrected to be larger than it would be with a simple random sample.

\hypertarget{pretending-we-have-a-stratified-design}{%
\subsubsection{Pretending we have a stratified design}\label{pretending-we-have-a-stratified-design}}

After analyzing the cluster-sampling design data, we'll erase our memories of that design and pretend we're analyzing a stratified design. In this type of design, we have have conducted a simple random sample of students within strata. In this case, the students are our \emph{primary sampling unit}. Let's say we have a list of school districts---these are our strata. We then have a list of all the students in each district, which is our sampling frame. We randomly selected students from each district, then we estimate the mean of the population. This is a very powerful design if we believe that the strata explain a lot of variation in the variable (in the score, in this case). It helps us to have greater precision in our estimate of the population mean.\footnote{Strata serve as a kind of fixed effect or a blocking variable in ANOVA.}

\hypertarget{pretending-we-have-a-stratified-cluster-sampled-design}{%
\subsubsection{Pretending we have a stratified cluster-sampled design}\label{pretending-we-have-a-stratified-cluster-sampled-design}}

After monkeying around with a stratified design, we wipe our memories of how we had designed that study and pretend we had collected the data using schools as our primary sampling unit, similar to how we did with the cluster-sampled design, but this time we sample schools from within their districts. The districts are strata. So, we have students nested within schools, which were randomly selected, which in turn are nested within strata. This is a very practical and smart design to use. First, we have the convenience of sampling schools, which is far easier than randomly sampling students from lists. Second, we can reduce that penalty to the standard error of this clustering by also using a stratification variable---the districts. This allows us to make claims about the population of schools within these particular districts.

We will also pretend we have a simple random sample, as well, to compare these scenarios with each other in terms of the standard error and confidence intervals.

\hypertarget{cluster-sampled-design}{%
\subsection{Cluster-sampled design}\label{cluster-sampled-design}}

\hypertarget{preparing-the-data}{%
\subsubsection{Preparing the data}\label{preparing-the-data}}

In the example that Heeringa and colleagues provide, they did not use a finite population correction. Another way to think about this is that the population of our primary sampling unit is very large. Let's say, therefore, that there is a very large number of schools (such as one million) in the population.

For many researchers, they treat the population as an infinitely large number, which is a conservative approach because it does not adjust the standard error to be smaller to account for the proportion of the population being sampled. For other researchers, such as for evaluations in a specific population---such as the schools in a particular state---the population size is finite. For instance, if there are 160 schools in a state and we're only drawing inferences about schools in that state, we can this number as our population size, which will yield a lower standard error (which will narrow our confidence intervals compared to an infinite population size).

The following example treats the population as infinite (to follow Heeringa's example), but in your own study, you can specify these sizes to match your needs in your research or evaluation.

To get this to work with the survey package, we create a column in the data that is this cluster \emph{N}-size. Here, we can use \texttt{N\_cl} as this column name to remind us that this is the population size of clusters.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat}\OperatorTok{$}\NormalTok{N_cl <-}\StringTok{ }\DecValTok{1000000}
\KeywordTok{head}\NormalTok{(dat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   sid school district score weight  N_cl
## 1   1      1        1  52.8      1 1e+06
## 2   2      1        1  32.5      2 1e+06
## 3   3      1        1  56.6      2 1e+06
## 4   4      1        1  47.0      1 1e+06
## 5   5      2        1  37.3      1 1e+06
## 6   6      2        1  57.0      1 1e+06
\end{verbatim}

\hypertarget{step-1-specifying-the-design}{%
\subsubsection{Step 1: Specifying the design}\label{step-1-specifying-the-design}}

To use the srvyr package (and the survey package it wraps around), we need to create a survey-design object.\footnote{For more information on this package, we can use \texttt{help(package\ =\ "srvyr")} or \url{https://cran.r-project.org/web/packages/srvyr/vignettes/srvyr-vs-survey.html}.} This specifies what the survey design was when we collected the data, which in turn determines what kinds of adjustments to the standard error we should make.

Let's create a survey-design object, with which we can perform subsequent calculations. We do this with the srvyr package's \texttt{as\_survey\_design()} function. To remind us that this is a design and that it uses clusters, we can name our object \texttt{des\_cl}, but you could call it \texttt{Bill} or \texttt{mydesign}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(survey)}
\KeywordTok{library}\NormalTok{(srvyr)}
\NormalTok{des_cl <-}\StringTok{ }\NormalTok{dat }\OperatorTok{%>%}\StringTok{ }
\StringTok{           }\KeywordTok{as_survey_design}\NormalTok{(}\DataTypeTok{id =}\NormalTok{ school, }
                           \DataTypeTok{fpc =}\NormalTok{ N_cl)}
\end{Highlighting}
\end{Shaded}

There are two arguments in that design specification. The \texttt{id\ =} specifies what the primary sampling unit is. In our design, the primary sampling unit (PSU) is the school variable in our data set. The second argument is for the finite population correction. We would think that the \texttt{fpc\ =} argument specifies the actual finite population correction, but it does NOT! Unintuitively, the default in the survey package is for \texttt{fpc\ =} to actually refer to the \emph{size} of the population of primary sampling units. So, this should be called something like \texttt{pop} instead of \texttt{fpc} in the program---that would make it too easy, though, wouldn't it.\footnote{But we can also use the \texttt{fpctype\ =\ "correction"} argument to specify the type of fpc discussed in the Heeringa chapter (which was 1 - \emph{n}/\emph{N}). Unfortunately, although we get the correct design effect, the estimated standard error is wrong.} If the number of clusters in our population were finite, like 168 schools, we can use the \texttt{fpc\ =\ 168} as a value for each case in the data set, which would make our standard error smaller. However, for this hypothetical example, we are saying there are 1 million schools.

We can look at the survey design we created using the \texttt{summary()} function on that object:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(des_cl) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 1 - level Cluster Sampling design
## With (8) clusters.
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   8e-06   8e-06   8e-06   8e-06   8e-06   8e-06 
## Population size (PSUs): 1e+06 
## Data variables:
## [1] "sid"      "school"   "district" "score"    "weight"   "N_cl"
\end{verbatim}

Notice that the probability of being sampled is equal across the quantiles. This is because everyone has the same fpc.

\hypertarget{step-2-calculating-the-estimates}{%
\subsubsection{Step 2: Calculating the estimates}\label{step-2-calculating-the-estimates}}

We want to know the mean and variance of our sample, as well as the confidence interval of the mean. We cannot use the regular Base R functions like \texttt{mean()} and \texttt{variance()} because they do not correct for the design. Instead, we use the functions from the svyr package. For example, instead of \texttt{mean()}, it uses \texttt{survey\_mean()}.\footnote{We're using piping, \texttt{\%\textgreater{}\%} with this particular package just like how we did with the dplyr package. These are part of the tidyverse community of R packages.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{des_cl }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\KeywordTok{survey_mean}\NormalTok{(score,                                 }
                        \DataTypeTok{vartype =} \KeywordTok{c}\NormalTok{(}\StringTok{"se"}\NormalTok{,}\StringTok{"ci"}\NormalTok{), }\DataTypeTok{df =} \KeywordTok{degf}\NormalTok{(.),  }
                        \DataTypeTok{deff =} \OtherTok{TRUE}\NormalTok{ ))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 5
##    coef `_se` `_low` `_upp` `_deff`
##   <dbl> <dbl>  <dbl>  <dbl>   <dbl>
## 1  40.8  3.66   32.1   49.4    2.31
\end{verbatim}

We have the \texttt{summarize()} function around the \texttt{survey\_mean()} function. Just as we do in mathematics, we work from inside the parentheses to the outside. The first argument in the \texttt{survey\_mean()} function is the variable that we are estimating, \texttt{score} in this case. The second argument specifies the type of sampling-distribution variance we would like to report (not to be confused with the sampling variance). Here, we seek the standard error (\texttt{"se"}) and the upper and lower 95\% confidence interval (\texttt{"ci"}) based on the \emph{t} distribution (based on the \texttt{df\ =\ degf(.)} argument). If we wanted the \emph{z} distribution, we would remove the \texttt{df\ =} argument. Because \emph{t} distribution values at the lower and upper 2.5\% quantiles are larger in magnitude (depending on the degrees of freedom) than \emph{z} distribution values (1.96), they are more conservative. We also request the design effect to be reported, \texttt{deff\ =\ TRUE}.

The coefficient of interest is the mean. The standard error and the lower- and upper-boundaries of the confidence intervals are reported, as well as the design effect.

We can actually save this output to an object and then use it later on. If you are like me, you think the outputs printed from the srvyr package are ugly. I want to see two decimal places, so I'll round it to two decimal places, then print it with the \texttt{print.data.frame()} function.\footnote{We can also use RStudio's \texttt{View()} function to see it in an extra tab, with \texttt{View(rslts\_M\_cl)}.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rslts_M_cl <-}\StringTok{ }\NormalTok{des_cl }\OperatorTok{%>%}\StringTok{ }
\StringTok{          }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{Mn =} \KeywordTok{survey_mean}\NormalTok{(score, }
                         \DataTypeTok{vartype =} \KeywordTok{c}\NormalTok{(}\StringTok{"se"}\NormalTok{,}\StringTok{"ci"}\NormalTok{), }\DataTypeTok{df =} \KeywordTok{degf}\NormalTok{(.), }
                         \DataTypeTok{deff =} \OtherTok{TRUE}\NormalTok{ ) )}
\KeywordTok{print.data.frame}\NormalTok{( }\KeywordTok{round}\NormalTok{(rslts_M_cl, }\DecValTok{2}\NormalTok{) )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Mn Mn_se Mn_low Mn_upp Mn_deff
## 1 40.77  3.66  32.12  49.42    2.31
\end{verbatim}

Now let's examine the variance and the sampling distribution of the variance.
The function is \texttt{survey\_var()}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rslts_V_cl <-}\StringTok{ }\NormalTok{des_cl }\OperatorTok{%>%}\StringTok{ }\KeywordTok{summarize}\NormalTok{(}\KeywordTok{survey_var}\NormalTok{(score) )}
\KeywordTok{print.data.frame}\NormalTok{( }\KeywordTok{round}\NormalTok{(rslts_V_cl, }\DecValTok{2}\NormalTok{) )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     coef   _se
## 1 185.28 40.72
\end{verbatim}

The coefficient is our estimated variance and the standard error is the standard error of the estimated variance.\footnote{Clinical researchers tend not to report things like standard error of the variance. It is important to realize, however, that any point estimates from a sample, such as the means and variances, are estimates of the population and therefore have some degree of uncertainty, which is what the standard error reveals.}

Conveniently, we can perform both the \texttt{survey\_mean()} and \texttt{survey\_var()} and save these to a report:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rslts_cl <-}\StringTok{ }\NormalTok{des_cl }\OperatorTok{%>%}\StringTok{ }
\StringTok{          }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{Mn =} \KeywordTok{survey_mean}\NormalTok{(score, }
                         \DataTypeTok{vartype =} \KeywordTok{c}\NormalTok{(}\StringTok{"se"}\NormalTok{,}\StringTok{"ci"}\NormalTok{), }\DataTypeTok{df =} \KeywordTok{degf}\NormalTok{(.), }
                         \DataTypeTok{deff =} \OtherTok{TRUE}\NormalTok{ ),}
                    \DataTypeTok{Var=} \KeywordTok{survey_var}\NormalTok{(score) )}
\KeywordTok{print.data.frame}\NormalTok{(}\KeywordTok{round}\NormalTok{(rslts_cl, }\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Mn Mn_se Mn_low Mn_upp Mn_deff    Var Var_se
## 1 40.77  3.66  32.12  49.42    2.31 185.28  40.72
\end{verbatim}

So, we have an estimated mean of the score (whatever construct this happens to be, such as students' judgments of school climate) of \(40.77\) and a 95\% confidence interval of \(( 32.12, 49.42)\).

\hypertarget{effective-sample-size}{%
\subsubsection{Effective sample size}\label{effective-sample-size}}

We can calculate the effective sample size from the number of students within the clusters, \emph{n}, and the design effect. This is helpful for explaining the design effect to folks such as school personnel. First, let's get the \emph{n}-size of students.

To specify what the \emph{sample} size of our smallest units (students) is, we can count the number of rows in the data using \texttt{nrow(dat)}. This is useful if each row is an individual person. We can also use \texttt{length(unique(dat\$sid))} to count the number of observations that are unique in the student ID column.\footnote{Sometimes data structures, such as those used in longitudinal analyses, have more than one row for each person. The \texttt{unique()} function makes sure we don't count somebody with the same ID twice.} Either way, we get the same number.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n <-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(dat}\OperatorTok{$}\NormalTok{sid)) }
\NormalTok{n}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 32
\end{verbatim}

As expected, there are 32 units (students) in our sample. Here's the effective sample size, which is calculable as \(\frac{n}{\text{design effect}}\).\footnote{The code below uses the \texttt{mutate()} function. This is from the dplyr package (for data wrangling) and is the same as this code: \texttt{rslts\_cl\$EffSS\ =\ n/rslts\_cl\$Mn\_deff}. The benefit of \texttt{mutate()} is we can create multiple variables in the mutate function and we don't have to specify the data frame, such as with \emph{rslts\_cl\$}Mn\_deff.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rslts_cl <-}\StringTok{ }\NormalTok{rslts_cl }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{EffSS =}\NormalTok{ n}\OperatorTok{/}\NormalTok{Mn_deff)}
\KeywordTok{print.data.frame}\NormalTok{(}\KeywordTok{round}\NormalTok{(rslts_cl, }\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Mn Mn_se Mn_low Mn_upp Mn_deff    Var Var_se EffSS
## 1 40.77  3.66  32.12  49.42    2.31 185.28  40.72 13.84
\end{verbatim}

The standard error with this design is about what it would be with a simple random sample of \(13.84\) (or rounding up, \(14\)) students from the population. This shows the penalizing effect that we have correctly applied to the data.

\hypertarget{reporting-the-mean-per-cluster}{%
\subsubsection{Reporting the mean per cluster}\label{reporting-the-mean-per-cluster}}

Sometimes we want to also report the mean per school. We can use the \texttt{group\_by()} function to specify what the grouping is before we apply the functions. Here, we're grouping by school, then estimating the mean and variance\footnote{This function is part of the tidyverse language in R, which is what the dplyr and srvyr packages use.}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{M_by_schl <-}\StringTok{ }\NormalTok{des_cl }\OperatorTok{%>%}\StringTok{ }
\StringTok{              }\KeywordTok{group_by}\NormalTok{(school) }\OperatorTok{%>%}\StringTok{ }
\StringTok{                }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{Mn =} \KeywordTok{survey_mean}\NormalTok{(score),}
                          \DataTypeTok{Var=} \KeywordTok{survey_var}\NormalTok{(score))}
\KeywordTok{print.data.frame}\NormalTok{(}\KeywordTok{round}\NormalTok{(M_by_schl,}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   school    Mn Mn_se    Var Var_se
## 1      1 47.23     0 111.95      0
## 2      2 55.00     0 196.73      0
## 3      3 34.40     0  37.71      0
## 4      4 52.22     0 151.26      0
## 5      5 35.65     0 216.99      0
## 6      6 43.55     0  82.89      0
## 7      7 25.50     0 100.05      0
## 8      8 32.60     0  17.19      0
\end{verbatim}

\hypertarget{two-stage-cluster-sampled-design}{%
\subsubsection{Two-stage cluster-sampled design}\label{two-stage-cluster-sampled-design}}

The method so far has assumed that the units within the clusters were the population within those clusters. For example, if we surveyed all of the students in our selected schools. In a two-stage design, we have the extra step of randomly selecting units within the clusters.

We first have to prepare the data. Let's pretend we had a \emph{population} of 100 students within each school from which we had randomly sampled. It is super unlikely that we'd ever have a data set with the same population size in all of the schools. This is only a demonstration---in our actual schools, we will probably know the total number in each school. There are big schools and small schools.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat}\OperatorTok{$}\NormalTok{N_cl_s <-}\StringTok{ }\DecValTok{100}
\end{Highlighting}
\end{Shaded}

Now, we can use this column in the data set.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{des_cl2 <-}\StringTok{ }\NormalTok{dat }\OperatorTok{%>%}\StringTok{ }
\StringTok{               }\KeywordTok{as_survey_design}\NormalTok{(}\DataTypeTok{id =} \KeywordTok{c}\NormalTok{(school, sid), }
                               \DataTypeTok{fpc =} \KeywordTok{c}\NormalTok{(N_cl, N_cl_s))}
\KeywordTok{summary}\NormalTok{(des_cl2) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 2 - level Cluster Sampling design
## With (8, 32) clusters.
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 3.2e-07 3.2e-07 3.2e-07 3.2e-07 3.2e-07 3.2e-07 
## Population size (PSUs): 1e+06 
## Data variables:
## [1] "sid"      "school"   "district" "score"    "weight"   "N_cl"     "N_cl_s"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rslts_cl2 <-}\StringTok{ }\NormalTok{des_cl2 }\OperatorTok{%>%}\StringTok{ }
\StringTok{          }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{Mn =} \KeywordTok{survey_mean}\NormalTok{(score, }
                         \DataTypeTok{vartype =} \KeywordTok{c}\NormalTok{(}\StringTok{"se"}\NormalTok{,}\StringTok{"ci"}\NormalTok{), }\DataTypeTok{df =} \KeywordTok{degf}\NormalTok{(.), }
                         \DataTypeTok{deff =} \OtherTok{TRUE}\NormalTok{ ),}
                    \DataTypeTok{Var=} \KeywordTok{survey_var}\NormalTok{(score) )}
\NormalTok{rslts_cl2 <-}\StringTok{ }\NormalTok{rslts_cl2 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{EffSS =}\NormalTok{ n}\OperatorTok{/}\NormalTok{Mn_deff)}
\KeywordTok{print.data.frame}\NormalTok{(}\KeywordTok{round}\NormalTok{(rslts_cl2,}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Mn Mn_se Mn_low Mn_upp Mn_deff    Var Var_se EffSS
## 1 40.77  3.66  32.12  49.42    2.31 185.28  40.72 13.84
\end{verbatim}

The results are not that different from the single-stage cluster-sample design we just analyzed. Again, this is an artificial data set and we would likely specify \texttt{N\_cl\_s} for each person within a school the same but different across schools (of different sizes).

\hypertarget{stratified-design}{%
\subsection{Stratified design}\label{stratified-design}}

The strata are districts. In this sampling design, we are randomly selecting students from each stratum and pretending that the school cluster did not exist when we designed and carried out this sampling plan.

\hypertarget{preparing-our-data-set}{%
\subsubsection{Preparing our data set}\label{preparing-our-data-set}}

Again, we'll effectively make the finite population correction negligible and assume that the population is big. This yields a more conservative confidence interval than if we had specified a smaller finite population, which would likely be the case if we were sampling from districts that were small.

Here, our primary sampling unit is the lowest element of our sampling plan. In other words, we had sampled the students from the strata. In the data set, each student is a row.

We need to specify how many sampled units are in each stratum. In other words, how many students are in each district. Normally, there will be a different number of students in a district (some districts are large; some are small). Here, for convenience (and to replicate the results in Heeringa and colleagues' chapter), we will make them all very large, maybe something like 25,000,000 students in each district. In the column in the data, we can think of the students as coming from their district of this population size.

Traditionally, \emph{h} stands for stratum in research designs. So, we'll call our object \texttt{des\_h} to help us remember it is a stratified design.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat}\OperatorTok{$}\NormalTok{N_h   =}\StringTok{ }\DecValTok{25000000}
\end{Highlighting}
\end{Shaded}

\hypertarget{step-1-specifying-the-design-1}{%
\subsubsection{Step 1: Specifying the design}\label{step-1-specifying-the-design-1}}

Notice that we have three arguments: \texttt{id\ =\ 1} to specify that the primary sampling unit is each row in the data set.\footnote{The srvyr and survey packages still include an argument for the PSU (\texttt{id\ =}), and instead of clusters as was done with cluster-sampling, we specify \texttt{id\ =\ 1}, where 1 tells R to treat the individual cases as the PSU. If you use the survey package directly, instead of the srvyr package as a wrap around, it is \texttt{id\ =\ \textasciitilde{}1}, with the tilde added.} The \texttt{strata\ =\ district} specifies the stratum. The \texttt{fpc\ =\ N\_h} specifies the column in our data that includes the population size of each stratum.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{des_h <-}\StringTok{ }\NormalTok{dat }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{as_survey_design}\NormalTok{(}\DataTypeTok{id =} \DecValTok{1}\NormalTok{, }
                   \DataTypeTok{strata =}\NormalTok{ district,}
                   \DataTypeTok{fpc =}\NormalTok{ N_h)}
\KeywordTok{summary}\NormalTok{(des_h) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Stratified Independent Sampling design
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 3.2e-07 3.2e-07 3.2e-07 3.2e-07 3.2e-07 3.2e-07 
## Stratum Sizes: 
##            1 2 3 4
## obs        8 8 8 8
## design.PSU 8 8 8 8
## actual.PSU 8 8 8 8
## Population stratum sizes (PSUs): 
##       1       2       3       4 
## 2.5e+07 2.5e+07 2.5e+07 2.5e+07 
## Data variables:
## [1] "sid"      "school"   "district" "score"    "weight"   "N_cl"     "N_cl_s"  
## [8] "N_h"
\end{verbatim}

Again, in our particular example, we're saying each stratum has the same number of students but if we had a different population size in each stratum, we could specify \texttt{data\$N\_h} to be that number within each stratum. For example, if District 1's population were small, with 1,000 students, all the students in our sample would have N\_h = 1000; if District 2 were larger, with 20,000 students, the students in this district in our sample have N\_h = 20000.

\hypertarget{step-2-calculating-the-estimates-1}{%
\subsubsection{Step 2: Calculating the estimates}\label{step-2-calculating-the-estimates-1}}

This step is identical to what we did before with the other example designs above. The difference is the design itself, which we created in the previous step.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rslts_h <-}\StringTok{ }\NormalTok{des_h }\OperatorTok{%>%}\StringTok{ }
\StringTok{        }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{Mn =} \KeywordTok{survey_mean}\NormalTok{(score, }
                       \DataTypeTok{vartype =} \KeywordTok{c}\NormalTok{(}\StringTok{"se"}\NormalTok{,}\StringTok{"ci"}\NormalTok{), }\DataTypeTok{df =} \KeywordTok{degf}\NormalTok{(.), }
                       \DataTypeTok{deff =} \OtherTok{TRUE}\NormalTok{ ),}
                  \DataTypeTok{Var=} \KeywordTok{survey_var}\NormalTok{(score) )}
\NormalTok{rslts_h}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Mn    Mn_se   Mn_low   Mn_upp   Mn_deff      Var   Var_se
## 1 40.76875 2.039311 36.59141 44.94609 0.7182879 185.2758 47.70248
\end{verbatim}

Here's the effective sample size from \emph{n} and the design effect.
First, let's remember how many observations are in our data:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 32
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rslts_h <-}\StringTok{ }\NormalTok{rslts_h }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{EffSS =}\NormalTok{ n}\OperatorTok{/}\NormalTok{Mn_deff)}
\NormalTok{rslts_h}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Mn    Mn_se   Mn_low   Mn_upp   Mn_deff      Var   Var_se    EffSS
## 1 40.76875 2.039311 36.59141 44.94609 0.7182879 185.2758 47.70248 44.55038
\end{verbatim}

As an extra step, we could report the mean per stratum:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{M_by_dist <-}\StringTok{ }\NormalTok{des_h }\OperatorTok{%>%}\StringTok{ }
\StringTok{             }\KeywordTok{group_by}\NormalTok{(district) }\OperatorTok{%>%}\StringTok{ }
\StringTok{               }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{Mn =} \KeywordTok{survey_mean}\NormalTok{(score),}
                         \DataTypeTok{Var=} \KeywordTok{survey_var}\NormalTok{(score))}
\NormalTok{M_by_dist}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 5
##   district    Mn Mn_se   Var Var_se
##      <int> <dbl> <dbl> <dbl>  <dbl>
## 1        1  51.1  4.32 150.    67.4
## 2        2  43.3  4.63 172.    73.0
## 3        3  39.6  4.28 146.    84.8
## 4        4  29.0  2.84  64.6   44.4
\end{verbatim}

\hypertarget{stratified-cluster-sampled-design}{%
\subsection{Stratified cluster-sampled design}\label{stratified-cluster-sampled-design}}

In this design, the clusters were randomly sampled from each stratum. In this artificial data set, there were four districts and from each district, two schools were randomly selected from the sampling frame that contained the list of all schools in the population (by district).

\hypertarget{preparing-the-data-1}{%
\subsubsection{Preparing the data}\label{preparing-the-data-1}}

In the data set, we need to specify the number of clusters per stratum. For this example, to make it consistent with what Heeringa and colleagues present in their chapter, we set the population as very high. This results in a negligible (tiny) finite population correction. Let's use something like \emph{n}/\emph{N} = 0.000008 for each stratum, which would occur if we had \emph{n} = 2 schools in each stratum's sample and \emph{N} = 250,000 schools in its population.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat}\OperatorTok{$}\NormalTok{N_hcl <-}\StringTok{ }\DecValTok{250000}
\end{Highlighting}
\end{Shaded}

So, we have a column in our data that we will use to say that there are 250,000 schools in each stratum.\footnote{Obviously, that is a lot of schools to have in a district. This is does make the error more conservatively estimated. Also, this seems to be in the spirit of model-based inference, where the population is more theoretical.}

\hypertarget{step-1-specifying-the-design-2}{%
\subsubsection{Step 1: Specifying the design}\label{step-1-specifying-the-design-2}}

The design step is similar to what we used in the other cluster-sampled and stratified designs. Here, the variable used as the primary sampling unit is school, which is what \texttt{id\ =\ school} refers to. The stratum variable in the data set is district, \texttt{strata\ =\ district}, and the population size of each stratum is the column in the data we just created, \texttt{fpc\ =\ N\_hcl}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{des_hcl <-}\StringTok{ }\NormalTok{dat }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{as_survey_design}\NormalTok{(}\DataTypeTok{id =}\NormalTok{ school,}
                   \DataTypeTok{strata =}\NormalTok{ district,}
                   \DataTypeTok{fpc =}\NormalTok{ N_hcl)}
\KeywordTok{summary}\NormalTok{(des_hcl) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Stratified 1 - level Cluster Sampling design
## With (8) clusters.
## Called via srvyr
## Probabilities:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   8e-06   8e-06   8e-06   8e-06   8e-06   8e-06 
## Stratum Sizes: 
##            1 2 3 4
## obs        8 8 8 8
## design.PSU 2 2 2 2
## actual.PSU 2 2 2 2
## Population stratum sizes (PSUs): 
##      1      2      3      4 
## 250000 250000 250000 250000 
## Data variables:
## [1] "sid"      "school"   "district" "score"    "weight"   "N_cl"     "N_cl_s"  
## [8] "N_h"      "N_hcl"
\end{verbatim}

We can see the sample sizes of the strata and the primary sampling unit (PSU) per stratum. This very simple example has only two clusters (schools) within each stratum (district).

\hypertarget{step-2-calculating-the-estimates-2}{%
\subsubsection{Step 2: Calculating the estimates}\label{step-2-calculating-the-estimates-2}}

This step is the same as the other designs above. We can also tag on the effective sample size.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rslts_hcl <-}\StringTok{ }\NormalTok{des_hcl }\OperatorTok{%>%}\StringTok{ }
\StringTok{        }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{Mn =} \KeywordTok{survey_mean}\NormalTok{(score, }
                       \DataTypeTok{vartype =} \KeywordTok{c}\NormalTok{(}\StringTok{"se"}\NormalTok{,}\StringTok{"ci"}\NormalTok{), }\DataTypeTok{df =} \KeywordTok{degf}\NormalTok{(.), }
                       \DataTypeTok{deff =} \OtherTok{TRUE}\NormalTok{ ),}
                  \DataTypeTok{Var=} \KeywordTok{survey_var}\NormalTok{(score) )}
\CommentTok{# effective sample size}
\NormalTok{n <-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(dat}\OperatorTok{$}\NormalTok{sid)) }
\NormalTok{rslts_hcl <-}\StringTok{ }\NormalTok{rslts_hcl }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{EffSS =}\NormalTok{ n}\OperatorTok{/}\NormalTok{Mn_deff)}
\NormalTok{rslts_hcl}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Mn    Mn_se   Mn_low   Mn_upp  Mn_deff      Var   Var_se    EffSS
## 1 40.76875 2.769807 33.07853 48.45897 1.325055 185.2758 49.58831 24.14994
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#------------}
\CommentTok{# Extra step: }
\CommentTok{# We can look at the mean per stratum :}

\NormalTok{M_by_Dist_cl <-}\StringTok{ }\NormalTok{des_hcl }\OperatorTok{%>%}\StringTok{ }
\StringTok{             }\KeywordTok{group_by}\NormalTok{(district) }\OperatorTok{%>%}\StringTok{ }
\StringTok{               }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{Mn =} \KeywordTok{survey_mean}\NormalTok{(score),}
                         \DataTypeTok{Var=} \KeywordTok{survey_var}\NormalTok{(score))}
\NormalTok{M_by_Dist_cl}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 5
##   district    Mn Mn_se   Var Var_se
##      <int> <dbl> <dbl> <dbl>  <dbl>
## 1        1  51.1  3.89 150.    36.3
## 2        2  43.3  8.91 172.    48.7
## 3        3  39.6  3.95 146.    57.5
## 4        4  29.0  3.55  64.6   35.5
\end{verbatim}

\hypertarget{a-simple-random-sample-design-for-comparison}{%
\subsection{A simple random sample design, for comparison}\label{a-simple-random-sample-design-for-comparison}}

The simple random sample design assumes that the students were randomly drawn from a population of students. There is no clustering or stratification in the design or analysis.

\hypertarget{preparing-our-data-set-1}{%
\subsubsection{Preparing our data set}\label{preparing-our-data-set-1}}

We can, of course, simply use Base R functions to estimate the mean and variance and then calculate the standard error as \(\sqrt{\frac{Var}{n}}\) and then use the calculations we used in the prior chapter. However, the srvyr package also allows us to use the finite population correction.

If we assumed the population were huge, our finite population correction would be negligible. Let's do this:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n <-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(dat}\OperatorTok{$}\NormalTok{sid)) }\CommentTok{# sample n}
\NormalTok{dat}\OperatorTok{$}\NormalTok{N <-}\StringTok{ }\DecValTok{10}\OperatorTok{^}\DecValTok{8} \CommentTok{# Population N}
\NormalTok{des_srs <-}\StringTok{ }\NormalTok{dat }\OperatorTok{%>%}\StringTok{ }
\StringTok{               }\KeywordTok{as_survey_design}\NormalTok{(}\DataTypeTok{id =} \DecValTok{1}\NormalTok{, }\DataTypeTok{fpc =}\NormalTok{ N)}
\NormalTok{rslts_srs <-}\StringTok{ }\NormalTok{des_srs }\OperatorTok{%>%}\StringTok{ }
\StringTok{        }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{Mn =} \KeywordTok{survey_mean}\NormalTok{(score, }\DataTypeTok{vartype =} \KeywordTok{c}\NormalTok{(}\StringTok{"se"}\NormalTok{,}\StringTok{"ci"}\NormalTok{), }\DataTypeTok{df =} \KeywordTok{degf}\NormalTok{(.)),}
                  \DataTypeTok{Var=} \KeywordTok{survey_var}\NormalTok{(score)) }
\NormalTok{rslts_srs <-}\StringTok{ }\NormalTok{rslts_srs }\OperatorTok{%>%}\StringTok{ }
\StringTok{               }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{EffSS   =}\NormalTok{ n,}
                      \DataTypeTok{Mn_deff =} \DecValTok{1}\NormalTok{)}
\KeywordTok{print.data.frame}\NormalTok{( }\KeywordTok{round}\NormalTok{(rslts_srs, }\DecValTok{2}\NormalTok{) )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Mn Mn_se Mn_low Mn_upp    Var Var_se EffSS Mn_deff
## 1 40.77  2.41  35.86  45.68 185.28  45.96    32       1
\end{verbatim}

Notice that the results are similar to the results we'd get using \protect\hyperlink{IntrvlDesc}{the procedures in the previous chapter}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{score_M  <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(dat}\OperatorTok{$}\NormalTok{score)}
\NormalTok{score_sd <-}\StringTok{ }\KeywordTok{sd}\NormalTok{(dat}\OperatorTok{$}\NormalTok{score)}
\NormalTok{score_n  <-}\StringTok{ }\KeywordTok{nrow}\NormalTok{(dat)}
\NormalTok{score_se <-}\StringTok{ }\NormalTok{score_sd}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(score_n)}
\NormalTok{LB_t     <-}\StringTok{  }\NormalTok{score_M }\OperatorTok{-}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DataTypeTok{df =}\NormalTok{ score_n }\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{score_se}
\NormalTok{UB_t     <-}\StringTok{  }\NormalTok{score_M }\OperatorTok{+}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DataTypeTok{df =}\NormalTok{ score_n }\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{score_se}
\KeywordTok{round}\NormalTok{((}\KeywordTok{c}\NormalTok{(}\DataTypeTok{M =}\NormalTok{ score_M, }\DataTypeTok{var =}\NormalTok{ score_sd}\OperatorTok{^}\DecValTok{2}\NormalTok{, }\DataTypeTok{n =}\NormalTok{ score_n, }\DataTypeTok{se =}\NormalTok{ score_se, }
   \DataTypeTok{CI_upper =}\NormalTok{ LB_t, }\DataTypeTok{CI_lower =}\NormalTok{ UB_t)), }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        M      var        n       se CI_upper CI_lower 
##    40.77   185.28    32.00     2.41    35.86    45.68
\end{verbatim}

If our finite population were small, such as \emph{N} = 100, our standard error would be smaller and our confidence interval would be narrower, indicating our estimate of the mean is a more precise measure of a population of size 100.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat}\OperatorTok{$}\NormalTok{N2 <-}\StringTok{ }\DecValTok{100} \CommentTok{# Small Population N}
\NormalTok{des_srs2 <-}\StringTok{ }\NormalTok{dat }\OperatorTok{%>%}\StringTok{ }\KeywordTok{as_survey_design}\NormalTok{(}\DataTypeTok{id =} \DecValTok{1}\NormalTok{, }\DataTypeTok{fpc =}\NormalTok{ N2)}
\NormalTok{rslts_srs2 <-}\StringTok{ }\NormalTok{des_srs }\OperatorTok{%>%}\StringTok{ }
\StringTok{        }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{Mn =} \KeywordTok{survey_mean}\NormalTok{(score, }\DataTypeTok{vartype =} \KeywordTok{c}\NormalTok{(}\StringTok{"se"}\NormalTok{,}\StringTok{"ci"}\NormalTok{), }\DataTypeTok{df =} \KeywordTok{degf}\NormalTok{(.))) }
\KeywordTok{print.data.frame}\NormalTok{( }\KeywordTok{round}\NormalTok{(rslts_srs2, }\DecValTok{2}\NormalTok{) )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Mn Mn_se Mn_low Mn_upp
## 1 40.77  2.41  35.86  45.68
\end{verbatim}

So, even though we can use Base R to estimate the confidence interval of a simple random sample, the survey and srvyr packages allow us to account for the finite population correction.

\hypertarget{comparing-all-design-scenarios}{%
\subsubsection{Comparing all design scenarios}\label{comparing-all-design-scenarios}}

Note that we would \textbf{not} do this in practice. In practice, we would select a single design and report the results. This comparison is only for seeing how the designs operate.

\begin{verbatim}
##                 Design    Mn Mn_se Mn_low Mn_upp Mn_deff EffSS    Var Var_se
## 1   Simple Rand. Samp. 40.77  2.41  35.86  45.68    1.00 32.00 185.28  45.96
## 2            Clustered 40.77  3.66  32.12  49.42    2.31 13.84 185.28  40.72
## 3  two-stage Clustered 40.77  3.66  32.12  49.42    2.31 13.84 185.28  40.72
## 4           Stratified 40.77  2.04  36.59  44.95    0.72 44.55 185.28  47.70
## 5 Stratified Clustered 40.77  2.77  33.08  48.46    1.33 24.15 185.28  49.59
\end{verbatim}

Compare this to Table 2.2 in Heeringa, et al.~\citeyearpar{heeringa_applied_2010}. The small differences (e.g., in the effective n-size) are due to rounding error in their chapter.

Of these designs, which seems to have the most precise estimate of the mean of the population? Which seems to be the provide the best balance between precision and feasibility in carrying out the sampling process?

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Updated on 2021-04-21.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

  \bibliography{book.bib,packages.bib}

\end{document}
