--- 
title: "Preparing and Analyzing Survey Data in R"
author: "George M. Harrison <br>University of Hawai‘i at Mānoa, College of Education"
date: "April, 2021"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    fig_caption: false
bibliography: [book.bib, packages.bib]
csl: apa.csl
link-citations: yes
description: "Provides guidance for preparing and analyzing survey data in R."
---

# Introduction

This site provides guidance in preparing and analyzing survey data in R. We begin with a chapter on preparing data and managing packages, then practice estimating descriptive statistics and internal-consistency reliability coefficients. We will eventually end with an example of how to analyze complex survey data, such as that collected from clustered and stratified samples.

Along the way, there are explanations about how to use R, including the use of functions and packages. One way to study using this guide is to follow along with your own RStudio file opened while you try out the code. Copying and pasting is one way. You can keep notes for yourself in your R code by preceding your annotations with the hash symbol (#). 

The final assignment will ask you to practice much of what is in this tutorial. It is also wise to keep your R code files for future references when you do use it analyze your own data.

## Prior knowledge

Before going through these tutorials, it is necessary to have installed R and RStudio. Also, it is highly recommended that you practice some of the basics, such as those in the introductory tutorial at http://www2.hawaii.edu/~georgeha/surveys/_book/ 

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'dplyr', 'knitr', 'rmarkdown', 'psych', 'ggplot2', 'srvyr', 'survey'
), 'packages.bib')
```
