<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Part 9 Practice with Instrumental Variable Estimation | Using R for Quasi-Experimental Designs</title>
  <meta name="description" content="QEDs in R" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Part 9 Practice with Instrumental Variable Estimation | Using R for Quasi-Experimental Designs" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="QEDs in R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Part 9 Practice with Instrumental Variable Estimation | Using R for Quasi-Experimental Designs" />
  
  <meta name="twitter:description" content="QEDs in R" />
  

<meta name="author" content="George M. Harrison  University of Hawai‘i at Mānoa, College of Education" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="IVE.html"/>
<link rel="next" href="PScore1.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 1em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#what-is-r"><i class="fa fa-check"></i><b>1.1</b> What is R</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basics.html"><a href="basics.html"><i class="fa fa-check"></i><b>2</b> Some Fundamentals of Coding in R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basics.html"><a href="basics.html#objectives"><i class="fa fa-check"></i><b>2.1</b> Objectives</a></li>
<li class="chapter" data-level="2.2" data-path="basics.html"><a href="basics.html#creating-an-r-script-file"><i class="fa fa-check"></i><b>2.2</b> Creating an R Script File</a></li>
<li class="chapter" data-level="2.3" data-path="basics.html"><a href="basics.html#creating-objects-by-assigning-information-to-them"><i class="fa fa-check"></i><b>2.3</b> Creating objects by assigning information to them</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="basics.html"><a href="basics.html#assigning-character-strings-to-an-object"><i class="fa fa-check"></i><b>2.3.1</b> Assigning Character Strings to an Object</a></li>
<li class="chapter" data-level="2.3.2" data-path="basics.html"><a href="basics.html#assigning-numeric-elements-to-an-object"><i class="fa fa-check"></i><b>2.3.2</b> Assigning Numeric Elements to an Object</a></li>
<li class="chapter" data-level="2.3.3" data-path="basics.html"><a href="basics.html#creating-vectors"><i class="fa fa-check"></i><b>2.3.3</b> Creating Vectors</a></li>
<li class="chapter" data-level="2.3.4" data-path="basics.html"><a href="basics.html#performing-operations-on-vectors"><i class="fa fa-check"></i><b>2.3.4</b> Performing Operations on Vectors</a></li>
<li class="chapter" data-level="2.3.5" data-path="basics.html"><a href="basics.html#using-functions"><i class="fa fa-check"></i><b>2.3.5</b> Using Functions</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="basics.html"><a href="basics.html#create-a-data-frame-from-code"><i class="fa fa-check"></i><b>2.4</b> Create a data frame from code</a></li>
<li class="chapter" data-level="2.5" data-path="basics.html"><a href="basics.html#working-with-matrices"><i class="fa fa-check"></i><b>2.5</b> Working with Matrices</a></li>
<li class="chapter" data-level="2.6" data-path="basics.html"><a href="basics.html#dffromcsv"><i class="fa fa-check"></i><b>2.6</b> Creating a Data Frame from a CSV File</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="examine.html"><a href="examine.html"><i class="fa fa-check"></i><b>3</b> Examining and Summarizing Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="examine.html"><a href="examine.html#objectives-1"><i class="fa fa-check"></i><b>3.1</b> Objectives</a></li>
<li class="chapter" data-level="3.2" data-path="examine.html"><a href="examine.html#examining-the-data"><i class="fa fa-check"></i><b>3.2</b> Examining the Data</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="examine.html"><a href="examine.html#the-data-frame"><i class="fa fa-check"></i><b>3.2.1</b> The Data Frame</a></li>
<li class="chapter" data-level="3.2.2" data-path="examine.html"><a href="examine.html#subsetting-by-rows"><i class="fa fa-check"></i><b>3.2.2</b> Subsetting by Rows</a></li>
<li class="chapter" data-level="3.2.3" data-path="examine.html"><a href="examine.html#subsetting-by-columns"><i class="fa fa-check"></i><b>3.2.3</b> Subsetting by Columns</a></li>
<li class="chapter" data-level="3.2.4" data-path="examine.html"><a href="examine.html#descriptive-statistics"><i class="fa fa-check"></i><b>3.2.4</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="3.2.5" data-path="examine.html"><a href="examine.html#creating-a-custom-function-to-estimate-the-confidence-interval-of-the-mean"><i class="fa fa-check"></i><b>3.2.5</b> Creating a Custom Function to Estimate the Confidence Interval of the Mean</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="examine.html"><a href="examine.html#summarizing-data-by-group-and-an-introduction-to-lists"><i class="fa fa-check"></i><b>3.3</b> Summarizing Data by Group (and an introduction to lists)</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="examine.html"><a href="examine.html#calculating-standardized-mean-difference-and-variance-ratio-of-a-covariate"><i class="fa fa-check"></i><b>3.3.1</b> Calculating Standardized Mean Difference and Variance Ratio of a Covariate</a></li>
<li class="chapter" data-level="3.3.2" data-path="examine.html"><a href="examine.html#creating-a-factor-variable-from-a-numeric-variable"><i class="fa fa-check"></i><b>3.3.2</b> Creating a Factor Variable from a Numeric Variable</a></li>
<li class="chapter" data-level="3.3.3" data-path="examine.html"><a href="examine.html#aggregate_explain"><i class="fa fa-check"></i><b>3.3.3</b> The <code>aggregate()</code> function</a></li>
<li class="chapter" data-level="3.3.4" data-path="examine.html"><a href="examine.html#plotting-data-by-group"><i class="fa fa-check"></i><b>3.3.4</b> Plotting data by group</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="examine.html"><a href="examine.html#extra-stuff"><i class="fa fa-check"></i><b>3.4</b> Extra Stuff</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="examine.html"><a href="examine.html#using-ggplot"><i class="fa fa-check"></i><b>3.4.1</b> Using ggplot</a></li>
<li class="chapter" data-level="3.4.2" data-path="examine.html"><a href="examine.html#subsetting-data-and-separately-analyzing-each-group"><i class="fa fa-check"></i><b>3.4.2</b> Subsetting data and separately analyzing each group</a></li>
<li class="chapter" data-level="3.4.3" data-path="examine.html"><a href="examine.html#the-tidyverse-approach-to-by-group-analyses"><i class="fa fa-check"></i><b>3.4.3</b> The Tidyverse Approach to By-Group Analyses</a></li>
<li class="chapter" data-level="3.4.4" data-path="examine.html"><a href="examine.html#plotting-summary-statistics"><i class="fa fa-check"></i><b>3.4.4</b> Plotting summary statistics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="rct.html"><a href="rct.html"><i class="fa fa-check"></i><b>4</b> Examples with Randomized Experiments</a>
<ul>
<li class="chapter" data-level="4.1" data-path="rct.html"><a href="rct.html#objectives-2"><i class="fa fa-check"></i><b>4.1</b> Objectives</a></li>
<li class="chapter" data-level="4.2" data-path="rct.html"><a href="rct.html#preparation"><i class="fa fa-check"></i><b>4.2</b> Preparation</a></li>
<li class="chapter" data-level="4.3" data-path="rct.html"><a href="rct.html#analysis-of-linear-models"><i class="fa fa-check"></i><b>4.3</b> Analysis of Linear Models</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="rct.html"><a href="rct.html#independent-samples-t-test-approach"><i class="fa fa-check"></i><b>4.3.1</b> Independent samples <em>t</em>-test approach</a></li>
<li class="chapter" data-level="4.3.2" data-path="rct.html"><a href="rct.html#simple-linear-regression"><i class="fa fa-check"></i><b>4.3.2</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="4.3.3" data-path="rct.html"><a href="rct.html#multiple-linear-regression"><i class="fa fa-check"></i><b>4.3.3</b> Multiple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="rct.html"><a href="rct.html#bootstrapping-to-get-confidence-intervals"><i class="fa fa-check"></i><b>4.4</b> Bootstrapping to Get Confidence Intervals</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="rct.html"><a href="rct.html#the-value-of-bootstrapping"><i class="fa fa-check"></i><b>4.4.1</b> The value of bootstrapping</a></li>
<li class="chapter" data-level="4.4.2" data-path="rct.html"><a href="rct.html#another-way-to-bootstrap-the-standard-error-of-mean-differences"><i class="fa fa-check"></i><b>4.4.2</b> Another way to bootstrap the standard error of mean differences</a></li>
<li class="chapter" data-level="4.4.3" data-path="rct.html"><a href="rct.html#simple-regression"><i class="fa fa-check"></i><b>4.4.3</b> Simple regression</a></li>
<li class="chapter" data-level="4.4.4" data-path="rct.html"><a href="rct.html#multiple-regression"><i class="fa fa-check"></i><b>4.4.4</b> Multiple regression</a></li>
<li class="chapter" data-level="4.4.5" data-path="rct.html"><a href="rct.html#summary-on-bootstrapping"><i class="fa fa-check"></i><b>4.4.5</b> Summary on Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="rct.html"><a href="rct.html#estimating-the-average-treatment-on-the-treated-att"><i class="fa fa-check"></i><b>4.5</b> Estimating the Average Treatment on the Treated (ATT)</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="rct.html"><a href="rct.html#artificially-introducing-no-shows"><i class="fa fa-check"></i><b>4.5.1</b> Artificially Introducing No-shows</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="DID.html"><a href="DID.html"><i class="fa fa-check"></i><b>5</b> Difference in Differences</a>
<ul>
<li class="chapter" data-level="5.1" data-path="DID.html"><a href="DID.html#objectives-3"><i class="fa fa-check"></i><b>5.1</b> Objectives</a></li>
<li class="chapter" data-level="5.2" data-path="DID.html"><a href="DID.html#import-and-prepare-the-data"><i class="fa fa-check"></i><b>5.2</b> Import and Prepare the Data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="DID.html"><a href="DID.html#prepare-the-data"><i class="fa fa-check"></i><b>5.2.1</b> Prepare the data</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="DID.html"><a href="DID.html#using-the-survey-package"><i class="fa fa-check"></i><b>5.3</b> Using the survey package</a></li>
<li class="chapter" data-level="5.4" data-path="DID.html"><a href="DID.html#direct-estimates-as-shown-in-table-8.1-on-page-143"><i class="fa fa-check"></i><b>5.4</b> Direct estimates, as shown in Table 8.1 on page 143</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="DID.html"><a href="DID.html#first-difference-direct-estimate-in-panel-a."><i class="fa fa-check"></i><b>5.4.1</b> First difference, direct estimate in Panel A.</a></li>
<li class="chapter" data-level="5.4.2" data-path="DID.html"><a href="DID.html#estimate-from-the-linear-probability-model-ols-estimate-shown-in-table-8.1-on-page-143-panel-b."><i class="fa fa-check"></i><b>5.4.2</b> Estimate from the linear-probability model (OLS) estimate shown in Table 8.1 on page 143, Panel B.</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="DID.html"><a href="DID.html#difference-in-differences-simple-approach-table-8.2-p.-157"><i class="fa fa-check"></i><b>5.5</b> Difference in differences, simple approach (Table 8.2, p. 157)</a></li>
<li class="chapter" data-level="5.6" data-path="DID.html"><a href="DID.html#difference-in-differences-using-regression"><i class="fa fa-check"></i><b>5.6</b> Difference in differences using regression</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="DID.html"><a href="DID.html#compare-the-results-from-the-four-different-strategies"><i class="fa fa-check"></i><b>5.6.1</b> Compare the results from the four different strategies</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="DID.html"><a href="DID.html#summary-of-the-did-model-strategy"><i class="fa fa-check"></i><b>5.7</b> Summary of the DID model strategy</a></li>
<li class="chapter" data-level="5.8" data-path="DID.html"><a href="DID.html#accounting-for-the-binary-y-variable"><i class="fa fa-check"></i><b>5.8</b> Accounting for the binary Y variable</a></li>
<li class="chapter" data-level="5.9" data-path="DID.html"><a href="DID.html#plotting-the-difference-in-differences"><i class="fa fa-check"></i><b>5.9</b> Plotting the difference in differences</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="DID.html"><a href="DID.html#plotfrompred"><i class="fa fa-check"></i><b>5.9.1</b> Plotting from the predicted values of the model</a></li>
<li class="chapter" data-level="5.9.2" data-path="DID.html"><a href="DID.html#doing-it-in-ggplot2"><i class="fa fa-check"></i><b>5.9.2</b> Doing it in ggplot2</a></li>
<li class="chapter" data-level="5.9.3" data-path="DID.html"><a href="DID.html#seeing-where-the-regression-estimate-is-in-the-plot"><i class="fa fa-check"></i><b>5.9.3</b> Seeing where the regression estimate is in the plot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="RD1.html"><a href="RD1.html"><i class="fa fa-check"></i><b>6</b> Regression Discontinuity, Part 1</a>
<ul>
<li class="chapter" data-level="6.1" data-path="RD1.html"><a href="RD1.html#objectives-4"><i class="fa fa-check"></i><b>6.1</b> Objectives</a></li>
<li class="chapter" data-level="6.2" data-path="RD1.html"><a href="RD1.html#import-and-prepare-the-data-1"><i class="fa fa-check"></i><b>6.2</b> Import and Prepare the Data</a></li>
<li class="chapter" data-level="6.3" data-path="RD1.html"><a href="RD1.html#different-difference-in-differences"><i class="fa fa-check"></i><b>6.3</b> Different Difference in Differences</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="RD1.html"><a href="RD1.html#our-first-difference"><i class="fa fa-check"></i><b>6.3.1</b> Our first difference</a></li>
<li class="chapter" data-level="6.3.2" data-path="RD1.html"><a href="RD1.html#a-plausible-second-difference"><i class="fa fa-check"></i><b>6.3.2</b> A plausible second difference</a></li>
<li class="chapter" data-level="6.3.3" data-path="RD1.html"><a href="RD1.html#another-plausible-second-difference"><i class="fa fa-check"></i><b>6.3.3</b> Another plausible second difference</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="RD1.html"><a href="RD1.html#mread3640"><i class="fa fa-check"></i><b>6.4</b> Broadening the bandwidth</a></li>
<li class="chapter" data-level="6.5" data-path="RD1.html"><a href="RD1.html#summary-up-to-this-point"><i class="fa fa-check"></i><b>6.5</b> Summary up to this point</a></li>
<li class="chapter" data-level="6.6" data-path="RD1.html"><a href="RD1.html#examining-if-the-results-are-consistent-with-different-bandwidths"><i class="fa fa-check"></i><b>6.6</b> Examining if the results are consistent with different bandwidths</a></li>
<li class="chapter" data-level="6.7" data-path="RD1.html"><a href="RD1.html#functional-form-in-rdd"><i class="fa fa-check"></i><b>6.7</b> Functional Form in RDD</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="RD1.html"><a href="RD1.html#plotting-the-two-sides-allowing-different-slopes"><i class="fa fa-check"></i><b>6.7.1</b> Plotting the two sides, allowing different slopes</a></li>
<li class="chapter" data-level="6.7.2" data-path="RD1.html"><a href="RD1.html#broader-analytic-windows"><i class="fa fa-check"></i><b>6.7.2</b> Broader analytic windows</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="RD1.html"><a href="RD1.html#using-the-rddtools-package"><i class="fa fa-check"></i><b>6.8</b> Using the rddtools Package</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="RD1.html"><a href="RD1.html#examining-the-bandwidth-identified-by-the-package"><i class="fa fa-check"></i><b>6.8.1</b> Examining the bandwidth identified by the package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="RD2.html"><a href="RD2.html"><i class="fa fa-check"></i><b>7</b> Regression Discontinuity, Part 2</a>
<ul>
<li class="chapter" data-level="7.1" data-path="RD2.html"><a href="RD2.html#here-are-the-steps-we-will-take"><i class="fa fa-check"></i><b>7.1</b> Here are the steps we will take:</a></li>
<li class="chapter" data-level="7.2" data-path="RD2.html"><a href="RD2.html#the-data"><i class="fa fa-check"></i><b>7.2</b> The Data</a></li>
<li class="chapter" data-level="7.3" data-path="RD2.html"><a href="RD2.html#examine-the-data-the-assignment-rule-adherence-and-compliance"><i class="fa fa-check"></i><b>7.3</b> Examine the Data, the Assignment-rule Adherence, and Compliance</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="RD2.html"><a href="RD2.html#assignment-rule-adherence"><i class="fa fa-check"></i><b>7.3.1</b> Assignment-rule adherence</a></li>
<li class="chapter" data-level="7.3.2" data-path="RD2.html"><a href="RD2.html#compliance"><i class="fa fa-check"></i><b>7.3.2</b> Compliance</a></li>
<li class="chapter" data-level="7.3.3" data-path="RD2.html"><a href="RD2.html#create-bins-of-the-assignment-variable"><i class="fa fa-check"></i><b>7.3.3</b> Create Bins of the Assignment Variable</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="RD2.html"><a href="RD2.html#examining-assumptions"><i class="fa fa-check"></i><b>7.4</b> Examining Assumptions</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="RD2.html"><a href="RD2.html#assumption-1the-continuity-assumption"><i class="fa fa-check"></i><b>7.4.1</b> Assumption 1—the continuity assumption</a></li>
<li class="chapter" data-level="7.4.2" data-path="RD2.html"><a href="RD2.html#assumption-2discontinuities-in-the-covariates"><i class="fa fa-check"></i><b>7.4.2</b> Assumption 2—Discontinuities in the covariates</a></li>
<li class="chapter" data-level="7.4.3" data-path="RD2.html"><a href="RD2.html#assumption-3checking-for-pseudo-cut-offs-in-the-outcome"><i class="fa fa-check"></i><b>7.4.3</b> Assumption 3—Checking for pseudo-cut-offs in the outcome</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="RD2.html"><a href="RD2.html#examining-the-parametric-functional-form"><i class="fa fa-check"></i><b>7.5</b> Examining the Parametric Functional Form</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="RD2.html"><a href="RD2.html#restricting-bandwidth"><i class="fa fa-check"></i><b>7.5.1</b> Restricting bandwidth</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="RD2.html"><a href="RD2.html#restband"><i class="fa fa-check"></i><b>7.6</b> Estimating the Effect</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="RD2.html"><a href="RD2.html#parametric-model"><i class="fa fa-check"></i><b>7.6.1</b> Parametric Model</a></li>
<li class="chapter" data-level="7.6.2" data-path="RD2.html"><a href="RD2.html#non-parametric-model-local-linear-estimation"><i class="fa fa-check"></i><b>7.6.2</b> Non-parametric Model: Local Linear Estimation</a></li>
<li class="chapter" data-level="7.6.3" data-path="RD2.html"><a href="RD2.html#including-covariates"><i class="fa fa-check"></i><b>7.6.3</b> Including covariates</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="RD2.html"><a href="RD2.html#sensitivity-analysis"><i class="fa fa-check"></i><b>7.7</b> Sensitivity Analysis</a></li>
<li class="chapter" data-level="7.8" data-path="RD2.html"><a href="RD2.html#accounting-for-fuzziness"><i class="fa fa-check"></i><b>7.8</b> Accounting for Fuzziness</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="RD2.html"><a href="RD2.html#fuzzy-non-parametric-model"><i class="fa fa-check"></i><b>7.8.1</b> Fuzzy non-parametric model</a></li>
<li class="chapter" data-level="7.8.2" data-path="RD2.html"><a href="RD2.html#summary-about-fuzzy-rdd"><i class="fa fa-check"></i><b>7.8.2</b> Summary about fuzzy RDD</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="IVE.html"><a href="IVE.html"><i class="fa fa-check"></i><b>8</b> Instrumental Variable Estimation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="IVE.html"><a href="IVE.html#objectives-5"><i class="fa fa-check"></i><b>8.1</b> Objectives</a></li>
<li class="chapter" data-level="8.2" data-path="IVE.html"><a href="IVE.html#preparation-1"><i class="fa fa-check"></i><b>8.2</b> Preparation</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="IVE.html"><a href="IVE.html#examining-the-data-1"><i class="fa fa-check"></i><b>8.2.1</b> Examining the data</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="IVE.html"><a href="IVE.html#moments-reported-in-table-10.2-p.-219"><i class="fa fa-check"></i><b>8.3</b> Moments reported in Table 10.2 (p. 219)</a></li>
<li class="chapter" data-level="8.4" data-path="IVE.html"><a href="IVE.html#two-stage-least-squares-1"><i class="fa fa-check"></i><b>8.4</b> Two-stage Least Squares</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="IVE.html"><a href="IVE.html#first-stage"><i class="fa fa-check"></i><b>8.4.1</b> First stage</a></li>
<li class="chapter" data-level="8.4.2" data-path="IVE.html"><a href="IVE.html#second-stage"><i class="fa fa-check"></i><b>8.4.2</b> Second stage</a></li>
<li class="chapter" data-level="8.4.3" data-path="IVE.html"><a href="IVE.html#obtaining-the-correct-standard-errors"><i class="fa fa-check"></i><b>8.4.3</b> Obtaining the correct standard errors</a></li>
<li class="chapter" data-level="8.4.4" data-path="IVE.html"><a href="IVE.html#letting-the-software-do-the-work"><i class="fa fa-check"></i><b>8.4.4</b> Letting the software do the work</a></li>
<li class="chapter" data-level="8.4.5" data-path="IVE.html"><a href="IVE.html#noticing-the-covariance-between-errors"><i class="fa fa-check"></i><b>8.4.5</b> Noticing the covariance between errors</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="IVE.html"><a href="IVE.html#two-stage-least-squares-with-covariates"><i class="fa fa-check"></i><b>8.5</b> Two-Stage Least Squares with Covariates</a></li>
<li class="chapter" data-level="8.6" data-path="IVE.html"><a href="IVE.html#using-multiple-instruments"><i class="fa fa-check"></i><b>8.6</b> Using Multiple Instruments</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="IVE.html"><a href="IVE.html#system-of-equations"><i class="fa fa-check"></i><b>8.6.1</b> System of equations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="IVE2.html"><a href="IVE2.html"><i class="fa fa-check"></i><b>9</b> Practice with Instrumental Variable Estimation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="IVE2.html"><a href="IVE2.html#objectives-6"><i class="fa fa-check"></i><b>9.1</b> Objectives</a></li>
<li class="chapter" data-level="9.2" data-path="IVE2.html"><a href="IVE2.html#import-and-prepare-the-data-2"><i class="fa fa-check"></i><b>9.2</b> Import and Prepare the Data</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="IVE2.html"><a href="IVE2.html#descriptive-statistics-1"><i class="fa fa-check"></i><b>9.2.1</b> Descriptive statistics</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="IVE2.html"><a href="IVE2.html#covariate-balance"><i class="fa fa-check"></i><b>9.3</b> Covariate Balance</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="IVE2.html"><a href="IVE2.html#covariate-balance-on-d"><i class="fa fa-check"></i><b>9.3.1</b> Covariate balance on <span class="math inline">\(D\)</span></a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="IVE2.html"><a href="IVE2.html#compliance-table-1"><i class="fa fa-check"></i><b>9.4</b> Compliance Table</a></li>
<li class="chapter" data-level="9.5" data-path="IVE2.html"><a href="IVE2.html#estimating-the-causal-effect"><i class="fa fa-check"></i><b>9.5</b> Estimating the Causal Effect</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="IVE2.html"><a href="IVE2.html#the-naïve-estimate"><i class="fa fa-check"></i><b>9.5.1</b> The naïve estimate</a></li>
<li class="chapter" data-level="9.5.2" data-path="IVE2.html"><a href="IVE2.html#the-late-estimate-from-ive"><i class="fa fa-check"></i><b>9.5.2</b> The LATE estimate from IVE</a></li>
<li class="chapter" data-level="9.5.3" data-path="IVE2.html"><a href="IVE2.html#making-the-intercept-meaningful"><i class="fa fa-check"></i><b>9.5.3</b> Making the intercept meaningful</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="PScore1.html"><a href="PScore1.html"><i class="fa fa-check"></i><b>10</b> Propensity Score Analysis 1: The underlying logic</a>
<ul>
<li class="chapter" data-level="10.1" data-path="PScore1.html"><a href="PScore1.html#import-the-data-and-prepare-for-analysis"><i class="fa fa-check"></i><b>10.1</b> Import the Data and Prepare for Analysis</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="PScore1.html"><a href="PScore1.html#creating-a-numeric-version-of-the-base-income-variables"><i class="fa fa-check"></i><b>10.1.1</b> Creating a numeric version of the base-income variables</a></li>
<li class="chapter" data-level="10.1.2" data-path="PScore1.html"><a href="PScore1.html#creating-some-custom-functions"><i class="fa fa-check"></i><b>10.1.2</b> Creating some custom functions</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="PScore1.html"><a href="PScore1.html#stratifying-on-a-covariate"><i class="fa fa-check"></i><b>10.2</b> Stratifying on a Covariate</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="PScore1.html"><a href="PScore1.html#checking-the-imbalance-in-the-treatment-status"><i class="fa fa-check"></i><b>10.2.1</b> Checking the imbalance in the treatment status</a></li>
<li class="chapter" data-level="10.2.2" data-path="PScore1.html"><a href="PScore1.html#creating-the-strata-from-the-covariate"><i class="fa fa-check"></i><b>10.2.2</b> Creating the strata from the covariate</a></li>
<li class="chapter" data-level="10.2.3" data-path="PScore1.html"><a href="PScore1.html#checking-for-imbalance-within-each-stratum"><i class="fa fa-check"></i><b>10.2.3</b> Checking for imbalance within each stratum</a></li>
<li class="chapter" data-level="10.2.4" data-path="PScore1.html"><a href="PScore1.html#using-tidyverse-to-check-imbalance"><i class="fa fa-check"></i><b>10.2.4</b> Using Tidyverse to check imbalance</a></li>
<li class="chapter" data-level="10.2.5" data-path="PScore1.html"><a href="PScore1.html#ate-and-att"><i class="fa fa-check"></i><b>10.2.5</b> ATE and ATT</a></li>
<li class="chapter" data-level="10.2.6" data-path="PScore1.html"><a href="PScore1.html#pooling-across-strata-to-calculate-the-ate-and-att"><i class="fa fa-check"></i><b>10.2.6</b> Pooling across strata to calculate the ATE and ATT</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="PScore1.html"><a href="PScore1.html#stratifying-on-two-covariates"><i class="fa fa-check"></i><b>10.3</b> Stratifying on Two Covariates</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="PScore1.html"><a href="PScore1.html#calculating-the-ate-and-att"><i class="fa fa-check"></i><b>10.3.1</b> Calculating the ATE and ATT</a></li>
<li class="chapter" data-level="10.3.2" data-path="PScore1.html"><a href="PScore1.html#tidyverse-approach"><i class="fa fa-check"></i><b>10.3.2</b> Tidyverse approach</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="PScore1.html"><a href="PScore1.html#estimating-propensity-scores"><i class="fa fa-check"></i><b>10.4</b> Estimating Propensity Scores</a></li>
<li class="chapter" data-level="10.5" data-path="PScore1.html"><a href="PScore1.html#creating-strata-from-propensity-scores"><i class="fa fa-check"></i><b>10.5</b> Creating Strata from Propensity Scores</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="PScore1.html"><a href="PScore1.html#adding-more-covariates"><i class="fa fa-check"></i><b>10.5.1</b> Adding more covariates</a></li>
<li class="chapter" data-level="10.5.2" data-path="PScore1.html"><a href="PScore1.html#ate-and-att-for-the-five-stratum-model"><i class="fa fa-check"></i><b>10.5.2</b> ATE and ATT for the five-stratum model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="PScore2.html"><a href="PScore2.html"><i class="fa fa-check"></i><b>11</b> Propensity Score Analysis 2: Weighting</a>
<ul>
<li class="chapter" data-level="11.1" data-path="PScore2.html"><a href="PScore2.html#import-the-data-and-prepare-for-analysis-1"><i class="fa fa-check"></i><b>11.1</b> Import the Data and Prepare for Analysis</a></li>
<li class="chapter" data-level="11.2" data-path="PScore2.html"><a href="PScore2.html#specify-custom-functions"><i class="fa fa-check"></i><b>11.2</b> Specify Custom Functions</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="PScore2.html"><a href="PScore2.html#imbalance-functions"><i class="fa fa-check"></i><b>11.2.1</b> Imbalance functions</a></li>
<li class="chapter" data-level="11.2.2" data-path="PScore2.html"><a href="PScore2.html#overlap-functions"><i class="fa fa-check"></i><b>11.2.2</b> Overlap functions</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="PScore2.html"><a href="PScore2.html#assess-imbalance-in-observed-covariates"><i class="fa fa-check"></i><b>11.3</b> Assess Imbalance in Observed Covariates</a></li>
<li class="chapter" data-level="11.4" data-path="PScore2.html"><a href="PScore2.html#check-overlap"><i class="fa fa-check"></i><b>11.4</b> Check Overlap</a></li>
<li class="chapter" data-level="11.5" data-path="PScore2.html"><a href="PScore2.html#calculate-the-weights"><i class="fa fa-check"></i><b>11.5</b> Calculate the Weights</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="PScore2.html"><a href="PScore2.html#dealing-with-extreme-weights"><i class="fa fa-check"></i><b>11.5.1</b> Dealing with extreme weights</a></li>
<li class="chapter" data-level="11.5.2" data-path="PScore2.html"><a href="PScore2.html#specifying-whether-to-estimate-ate-or-att"><i class="fa fa-check"></i><b>11.5.2</b> Specifying whether to estimate ATE or ATT</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="PScore2.html"><a href="PScore2.html#conduct-balance-checks-after-weighting"><i class="fa fa-check"></i><b>11.6</b> Conduct balance checks after weighting</a></li>
<li class="chapter" data-level="11.7" data-path="PScore2.html"><a href="PScore2.html#estimate-the-treatment-effect"><i class="fa fa-check"></i><b>11.7</b> Estimate the Treatment Effect</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="PScore2.html"><a href="PScore2.html#estimating-the-correct-standard-error"><i class="fa fa-check"></i><b>11.7.1</b> Estimating the correct standard error</a></li>
<li class="chapter" data-level="11.7.2" data-path="PScore2.html"><a href="PScore2.html#use-a-doubly-robust-estimate"><i class="fa fa-check"></i><b>11.7.2</b> Use a doubly robust estimate</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="PScore2.html"><a href="PScore2.html#using-the-twang-package"><i class="fa fa-check"></i><b>11.8</b> Using the Twang Package</a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="PScore2.html"><a href="PScore2.html#examining-covariate-balance"><i class="fa fa-check"></i><b>11.8.1</b> Examining covariate balance</a></li>
<li class="chapter" data-level="11.8.2" data-path="PScore2.html"><a href="PScore2.html#estimating-the-propensity-scores-and-getting-the-weights"><i class="fa fa-check"></i><b>11.8.2</b> Estimating the propensity scores and getting the weights</a></li>
<li class="chapter" data-level="11.8.3" data-path="PScore2.html"><a href="PScore2.html#estimating-the-effect"><i class="fa fa-check"></i><b>11.8.3</b> Estimating the effect</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="PScore3.html"><a href="PScore3.html"><i class="fa fa-check"></i><b>12</b> Propensity Score Analysis 3: Stratification and Matching</a>
<ul>
<li class="chapter" data-level="12.1" data-path="PScore3.html"><a href="PScore3.html#calculate-the-mmwss-from-the-propensity-scores"><i class="fa fa-check"></i><b>12.1</b> Calculate the MMWSs from the propensity scores</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="PScore3.html"><a href="PScore3.html#estimate-the-propensity-scores"><i class="fa fa-check"></i><b>12.1.1</b> Estimate the propensity scores</a></li>
<li class="chapter" data-level="12.1.2" data-path="PScore3.html"><a href="PScore3.html#calculate-the-quintiles"><i class="fa fa-check"></i><b>12.1.2</b> Calculate the quintiles</a></li>
<li class="chapter" data-level="12.1.3" data-path="PScore3.html"><a href="PScore3.html#examine-the-strata"><i class="fa fa-check"></i><b>12.1.3</b> Examine the strata</a></li>
<li class="chapter" data-level="12.1.4" data-path="PScore3.html"><a href="PScore3.html#calculate-the-mmwss"><i class="fa fa-check"></i><b>12.1.4</b> Calculate the MMWSs</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="PScore3.html"><a href="PScore3.html#conduct-balance-checks-after-weighting-1"><i class="fa fa-check"></i><b>12.2</b> Conduct balance checks after weighting</a></li>
<li class="chapter" data-level="12.3" data-path="PScore3.html"><a href="PScore3.html#estimate-the-ate"><i class="fa fa-check"></i><b>12.3</b> Estimate the ATE</a></li>
<li class="chapter" data-level="12.4" data-path="PScore3.html"><a href="PScore3.html#using-the-matchit-package"><i class="fa fa-check"></i><b>12.4</b> Using the MatchIt Package</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="PScore3.html"><a href="PScore3.html#examining-balance"><i class="fa fa-check"></i><b>12.4.1</b> Examining Balance</a></li>
<li class="chapter" data-level="12.4.2" data-path="PScore3.html"><a href="PScore3.html#estimate-the-effect"><i class="fa fa-check"></i><b>12.4.2</b> Estimate the Effect</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="PScore3.html"><a href="PScore3.html#matching"><i class="fa fa-check"></i><b>12.5</b> Matching</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="PScore3.html"><a href="PScore3.html#estimate-the-effect-1"><i class="fa fa-check"></i><b>12.5.1</b> Estimate the Effect</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Using R for Quasi-Experimental Designs</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="IVE2" class="section level1" number="9">
<h1><span class="header-section-number">Part 9</span> Practice with Instrumental Variable Estimation</h1>
<p>In this continuation of the instrument variable estimation (IVE), we use data from Chapter 11 of Murnane and Willett <span class="citation">(<a href="#ref-murnane_methods_2011" role="doc-biblioref">2011</a>)</span>.</p>
<div id="objectives-6" class="section level2" number="9.1">
<h2><span class="header-section-number">9.1</span> Objectives</h2>
<ol style="list-style-type: decimal">
<li>Compare the covariate balance on the instrumental variable with that on the endogenous question predictor</li>
<li>Generate the compliance table and see again that this is the estimate in the first stage</li>
<li>Practice estimating LATE.</li>
</ol>
<p>For parts of this lesson, the code is omitted so you can use it yourself and compare your results. You can use the sem <span class="citation">(<a href="#ref-R-sem" role="doc-biblioref">Fox et al., 2020</a>)</span>, AER <span class="citation">(<a href="#ref-R-AER" role="doc-biblioref">Kleiber &amp; Zeileis, 2020</a>)</span>, and systemfit <span class="citation">(<a href="#ref-R-systemfit" role="doc-biblioref">Henningsen &amp; Hamann, 2019</a>)</span> packages, which we used in the previous lesson.</p>
</div>
<div id="import-and-prepare-the-data-2" class="section level2" number="9.2">
<h2><span class="header-section-number">9.2</span> Import and Prepare the Data</h2>
<p>The data were available as a SAS data set from UCLA’s site, which I had then saved to a CSV file <em>Ch11_colvoucher</em> using the following code.</p>
<div class="sourceCode" id="cb822"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb822-1"><a href="IVE2.html#cb822-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(sas7bdat) <span class="co"># package for reading SAS files</span></span>
<span id="cb822-2"><a href="IVE2.html#cb822-2" aria-hidden="true" tabindex="-1"></a>  cv <span class="ot">&lt;-</span> <span class="fu">read.sas7bdat</span>(<span class="st">&quot;https://stats.idre.ucla.edu/wp-content/uploads/2016/02/colvoucher.sas7bdat&quot;</span>)</span>
<span id="cb822-3"><a href="IVE2.html#cb822-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write.csv</span>(cv, <span class="at">file =</span> <span class="st">&quot;Ch11_colvoucher&quot;</span>, <span class="at">row.names =</span> F)</span></code></pre></div>
<p>If we are starting from the csv file on your local machine, we can read it in:</p>
<div class="sourceCode" id="cb823"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb823-1"><a href="IVE2.html#cb823-1" aria-hidden="true" tabindex="-1"></a>cv <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;Ch11_colvoucher.csv&quot;</span>)</span></code></pre></div>
<p>Let’s see if there are any missing data and make sure the variables are numeric.</p>
<div class="sourceCode" id="cb824"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb824-1"><a href="IVE2.html#cb824-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(cv, <span class="dv">2</span>, <span class="cf">function</span>(x){<span class="fu">sum</span>(<span class="fu">is.na</span>(x))})</span></code></pre></div>
<pre><code>##          id  won_lottry        male    base_age   finish8th use_fin_aid 
##           0           0           0           0           0           0</code></pre>
<div class="sourceCode" id="cb826"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb826-1"><a href="IVE2.html#cb826-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(cv)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    1171 obs. of  6 variables:
##  $ id         : int  3 4 5 6 10 11 12 15 16 17 ...
##  $ won_lottry : int  1 0 0 0 1 1 0 1 0 0 ...
##  $ male       : int  0 1 1 0 1 0 0 0 1 0 ...
##  $ base_age   : int  11 11 11 9 11 11 11 12 12 14 ...
##  $ finish8th  : int  1 1 1 0 1 1 1 1 0 1 ...
##  $ use_fin_aid: int  1 1 0 0 1 1 0 1 0 1 ...</code></pre>
<p>We can look at the names of the columns. Here, we’re wrapping <code>data.frame()</code> around the <code>names()</code> function to also see the number of column index.</p>
<div class="sourceCode" id="cb828"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb828-1"><a href="IVE2.html#cb828-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="fu">names</span>(cv)) </span></code></pre></div>
<pre><code>##     names.cv.
## 1          id
## 2  won_lottry
## 3        male
## 4    base_age
## 5   finish8th
## 6 use_fin_aid</code></pre>
<p>We can save our variable names in an object.</p>
<div class="sourceCode" id="cb830"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb830-1"><a href="IVE2.html#cb830-1" aria-hidden="true" tabindex="-1"></a>(vnames<span class="ot">&lt;-</span> <span class="fu">names</span>(cv[,<span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">4</span>,<span class="dv">3</span>)])) </span></code></pre></div>
<pre><code>## [1] &quot;finish8th&quot;   &quot;use_fin_aid&quot; &quot;base_age&quot;    &quot;male&quot;</code></pre>
<div id="descriptive-statistics-1" class="section level3" number="9.2.1">
<h3><span class="header-section-number">9.2.1</span> Descriptive statistics</h3>
<p>Here are the descriptive statistics, matching those in Table 11.1 (p. 270).</p>
<div class="sourceCode" id="cb832"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb832-1"><a href="IVE2.html#cb832-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(cv[, <span class="fu">c</span>(vnames, <span class="st">&quot;won_lottry&quot;</span> )],<span class="dv">2</span>, mean)</span></code></pre></div>
<pre><code>##   finish8th use_fin_aid    base_age        male  won_lottry 
##   0.6814688   0.5815542  12.0042699   0.5046968   0.5055508</code></pre>
<p>We can use a custom function to get the rest of the table.</p>
<div class="sourceCode" id="cb834"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb834-1"><a href="IVE2.html#cb834-1" aria-hidden="true" tabindex="-1"></a>mydesc <span class="ot">&lt;-</span> <span class="cf">function</span>(x,grp){</span>
<span id="cb834-2"><a href="IVE2.html#cb834-2" aria-hidden="true" tabindex="-1"></a>   Mby  <span class="ot">&lt;-</span> <span class="fu">by</span>(x,grp, mean)</span>
<span id="cb834-3"><a href="IVE2.html#cb834-3" aria-hidden="true" tabindex="-1"></a>   Meanc <span class="ot">&lt;-</span> Mby[[<span class="dv">1</span>]]</span>
<span id="cb834-4"><a href="IVE2.html#cb834-4" aria-hidden="true" tabindex="-1"></a>   Meant <span class="ot">&lt;-</span> Mby[[<span class="dv">2</span>]]</span>
<span id="cb834-5"><a href="IVE2.html#cb834-5" aria-hidden="true" tabindex="-1"></a>   SDby  <span class="ot">&lt;-</span><span class="fu">by</span>(x,grp, sd)</span>
<span id="cb834-6"><a href="IVE2.html#cb834-6" aria-hidden="true" tabindex="-1"></a>   SDc   <span class="ot">&lt;-</span> SDby[[<span class="dv">1</span>]]</span>
<span id="cb834-7"><a href="IVE2.html#cb834-7" aria-hidden="true" tabindex="-1"></a>   SDt   <span class="ot">&lt;-</span> SDby[[<span class="dv">2</span>]]</span>
<span id="cb834-8"><a href="IVE2.html#cb834-8" aria-hidden="true" tabindex="-1"></a>   fit   <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(x <span class="sc">~</span> grp))</span>
<span id="cb834-9"><a href="IVE2.html#cb834-9" aria-hidden="true" tabindex="-1"></a>   est   <span class="ot">&lt;-</span> <span class="fu">coef</span>(fit)[<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb834-10"><a href="IVE2.html#cb834-10" aria-hidden="true" tabindex="-1"></a>   stderr<span class="ot">&lt;-</span> <span class="fu">coef</span>(fit)[<span class="dv">2</span>,<span class="dv">2</span>]</span>
<span id="cb834-11"><a href="IVE2.html#cb834-11" aria-hidden="true" tabindex="-1"></a>   t     <span class="ot">&lt;-</span> <span class="fu">coef</span>(fit)[<span class="dv">2</span>,<span class="dv">3</span>]</span>
<span id="cb834-12"><a href="IVE2.html#cb834-12" aria-hidden="true" tabindex="-1"></a>   p     <span class="ot">&lt;-</span> <span class="fu">coef</span>(fit)[<span class="dv">2</span>,<span class="dv">4</span>]</span>
<span id="cb834-13"><a href="IVE2.html#cb834-13" aria-hidden="true" tabindex="-1"></a>   out  <span class="ot">&lt;-</span><span class="fu">c</span>(<span class="at">Mt=</span>Meant, <span class="at">SDt=</span>SDt, <span class="at">Mc=</span>Meanc, <span class="at">SDc=</span>SDc, </span>
<span id="cb834-14"><a href="IVE2.html#cb834-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">diff=</span> est, <span class="at">se=</span>stderr, <span class="at">tstat=</span> t, <span class="at">pr=</span>p)</span>
<span id="cb834-15"><a href="IVE2.html#cb834-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(out,<span class="dv">3</span>)</span>
<span id="cb834-16"><a href="IVE2.html#cb834-16" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb835"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb835-1"><a href="IVE2.html#cb835-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">t</span>(<span class="fu">round</span>(<span class="fu">sapply</span>(cv[, vnames], </span>
<span id="cb835-2"><a href="IVE2.html#cb835-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">FUN =</span> mydesc, </span>
<span id="cb835-3"><a href="IVE2.html#cb835-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">grp =</span> cv<span class="sc">$</span>won_lottry),<span class="dv">2</span>))</span></code></pre></div>
<pre><code>##                Mt  SDt    Mc  SDc  diff   se tstat   pr
## finish8th    0.74 0.44  0.62 0.48  0.11 0.03  4.11 0.00
## use_fin_aid  0.92 0.28  0.24 0.43  0.68 0.02 32.11 0.00
## base_age    11.97 1.34 12.04 1.35 -0.06 0.08 -0.80 0.42
## male         0.50 0.50  0.50 0.50  0.00 0.03  0.03 0.98</code></pre>
</div>
</div>
<div id="covariate-balance" class="section level2" number="9.3">
<h2><span class="header-section-number">9.3</span> Covariate Balance</h2>
<p>Let’s check the balance of the two covariates on the instrument. First, let’s put the names of our covariates in an object so we don’t have to keep retyping them:</p>
<div class="sourceCode" id="cb837"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb837-1"><a href="IVE2.html#cb837-1" aria-hidden="true" tabindex="-1"></a>mycovs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;male&quot;</span>, <span class="st">&quot;base_age&quot;</span>)</span>
<span id="cb837-2"><a href="IVE2.html#cb837-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb837-3"><a href="IVE2.html#cb837-3" aria-hidden="true" tabindex="-1"></a>select.diff <span class="ot">&lt;-</span> <span class="cf">function</span>(x, grp) {</span>
<span id="cb837-4"><a href="IVE2.html#cb837-4" aria-hidden="true" tabindex="-1"></a>  mby <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">by</span>(x, grp, mean, <span class="at">na.rm=</span>T))</span>
<span id="cb837-5"><a href="IVE2.html#cb837-5" aria-hidden="true" tabindex="-1"></a>  vby <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">by</span>(x, grp, var , <span class="at">na.rm=</span>T))</span>
<span id="cb837-6"><a href="IVE2.html#cb837-6" aria-hidden="true" tabindex="-1"></a>  mc   <span class="ot">&lt;-</span> mby[<span class="dv">1</span>]</span>
<span id="cb837-7"><a href="IVE2.html#cb837-7" aria-hidden="true" tabindex="-1"></a>  mt   <span class="ot">&lt;-</span> mby[<span class="dv">2</span>]</span>
<span id="cb837-8"><a href="IVE2.html#cb837-8" aria-hidden="true" tabindex="-1"></a>  vc   <span class="ot">&lt;-</span> vby[<span class="dv">1</span>]</span>
<span id="cb837-9"><a href="IVE2.html#cb837-9" aria-hidden="true" tabindex="-1"></a>  vt   <span class="ot">&lt;-</span> vby[<span class="dv">2</span>]</span>
<span id="cb837-10"><a href="IVE2.html#cb837-10" aria-hidden="true" tabindex="-1"></a>  B  <span class="ot">&lt;-</span> (mt<span class="sc">-</span>mc)<span class="sc">/</span><span class="fu">sqrt</span>((vt<span class="sc">+</span>vc)<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb837-11"><a href="IVE2.html#cb837-11" aria-hidden="true" tabindex="-1"></a>  R  <span class="ot">&lt;-</span> vt<span class="sc">/</span>vc</span>
<span id="cb837-12"><a href="IVE2.html#cb837-12" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(x <span class="sc">~</span> grp))</span>
<span id="cb837-13"><a href="IVE2.html#cb837-13" aria-hidden="true" tabindex="-1"></a>  out2 <span class="ot">&lt;-</span> <span class="fu">c</span>(out<span class="sc">$</span>coef[<span class="dv">2</span>, <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">4</span>)], B, R)</span>
<span id="cb837-14"><a href="IVE2.html#cb837-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(out2)<span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;MeanDiff&quot;</span>, <span class="st">&quot;StdError&quot;</span>, <span class="st">&quot;p-value&quot;</span>, <span class="st">&quot;StdMeanDiff&quot;</span>, <span class="st">&quot;VarRatio&quot;</span>)</span>
<span id="cb837-15"><a href="IVE2.html#cb837-15" aria-hidden="true" tabindex="-1"></a>  out2</span>
<span id="cb837-16"><a href="IVE2.html#cb837-16" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb837-17"><a href="IVE2.html#cb837-17" aria-hidden="true" tabindex="-1"></a>bal <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">sapply</span>(cv[, mycovs], select.diff, <span class="at">grp =</span> cv<span class="sc">$</span>won_lottry)) <span class="co">#our grp is the won_lottery IV</span></span>
<span id="cb837-18"><a href="IVE2.html#cb837-18" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(bal, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##          MeanDiff StdError p-value StdMeanDiff VarRatio
## male        0.001    0.029   0.980       0.001    1.000
## base_age   -0.063    0.079   0.422      -0.047    0.987</code></pre>
<p>We can plot these imbalance data:<a href="#fn55" class="footnote-ref" id="fnref55"><sup>55</sup></a></p>
<div class="sourceCode" id="cb839"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb839-1"><a href="IVE2.html#cb839-1" aria-hidden="true" tabindex="-1"></a> B <span class="ot">&lt;-</span> bal[, <span class="st">&quot;StdMeanDiff&quot;</span>]</span>
<span id="cb839-2"><a href="IVE2.html#cb839-2" aria-hidden="true" tabindex="-1"></a>  R <span class="ot">&lt;-</span> bal[, <span class="st">&quot;VarRatio&quot;</span>]</span>
<span id="cb839-3"><a href="IVE2.html#cb839-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(B, R, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>), <span class="at">ylim =</span> <span class="fu">c</span>(.<span class="dv">6</span>, <span class="fl">1.6</span>), <span class="at">pch =</span> <span class="dv">16</span>, </span>
<span id="cb839-4"><a href="IVE2.html#cb839-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&#39;Covariate Imbalance on the Instrument&#39;</span>, <span class="at">xlab =</span> <span class="st">&#39;Std. Mean Difference&#39;</span>, <span class="at">ylab =</span> <span class="st">&#39;Variance Ratio&#39;</span>)</span>
<span id="cb839-5"><a href="IVE2.html#cb839-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">1</span>, <span class="at">v =</span> <span class="dv">0</span>)</span>
<span id="cb839-6"><a href="IVE2.html#cb839-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">c</span>(<span class="dv">4</span><span class="sc">/</span><span class="dv">5</span>, <span class="dv">5</span><span class="sc">/</span><span class="dv">4</span>), <span class="at">v =</span> <span class="fu">c</span>(<span class="sc">-</span>.<span class="dv">1</span>, .<span class="dv">1</span>), <span class="at">lty =</span> <span class="dv">3</span>) <span class="co">#Adding Rubin&#39;s benchmarks</span></span>
<span id="cb839-7"><a href="IVE2.html#cb839-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">c</span>(<span class="sc">-</span>.<span class="dv">2</span>, .<span class="dv">2</span>), <span class="at">lty =</span> <span class="dv">15</span>, <span class="at">col=</span><span class="st">&quot;brown&quot;</span>)    <span class="co">#More lenient (but common) std.M-diff benchmarks</span></span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-444-1.png" width="672" /></p>
<div class="sourceCode" id="cb840"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb840-1"><a href="IVE2.html#cb840-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Labels of the imbalanced covariates</span></span>
<span id="cb840-2"><a href="IVE2.html#cb840-2" aria-hidden="true" tabindex="-1"></a>  ind <span class="ot">&lt;-</span> (<span class="fu">abs</span>(B) <span class="sc">&gt;</span> .<span class="dv">1</span> <span class="sc">|</span> R <span class="sc">&lt;</span> <span class="dv">4</span><span class="sc">/</span><span class="dv">5</span> <span class="sc">|</span> R <span class="sc">&gt;</span> <span class="dv">5</span><span class="sc">/</span><span class="dv">4</span>) </span>
<span id="cb840-3"><a href="IVE2.html#cb840-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">sum</span>(ind) <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="fu">text</span>(<span class="at">x =</span> B[ind],<span class="at">y =</span> R[ind],<span class="at">labels =</span> mycovs[ind], <span class="at">pos =</span> <span class="dv">2</span> <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>(B[ind] <span class="sc">&gt;</span> <span class="dv">0</span>), <span class="at">offset =</span> .<span class="dv">4</span>, <span class="at">cex =</span> .<span class="dv">7</span>)</span></code></pre></div>
<p><em><em>Conclusion.</em></em> Neither of the covariates is imbalanced. This is consistent with the lottery being a random award among the same population. It adds support to our claim that our instrument (symbolized as <span class="math inline">\(Z\)</span> or <span class="math inline">\(I)\)</span> is exogenous. If we had found some imbalance, it might have been due to chance or it might have been due to some other third-path mechanism (and we would be sure to include those out-of-balance covariates in our first-stage model). This is evidence is only slightly comforting, however, because there still may be bias through coviariates we have not measured. Again, the exclusion restriction is hard to prove unless our instrument is by nature not related to the outcome variable, such as a random lottery.<a href="#fn56" class="footnote-ref" id="fnref56"><sup>56</sup></a></p>
<div id="covariate-balance-on-d" class="section level3" number="9.3.1">
<h3><span class="header-section-number">9.3.1</span> Covariate balance on <span class="math inline">\(D\)</span></h3>
<p>Let’s examine covariate balance with our endogenous question predictor. We don’t need to do this because we already believe that <span class="math inline">\(D\)</span> is endogenous; it is likely related to our observed or unobserved variables. This is simply for demonstration that we might observe imbalance here because unlike the lottery, <code>use_fin_aid</code> is a choice.</p>
<div class="sourceCode" id="cb841"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb841-1"><a href="IVE2.html#cb841-1" aria-hidden="true" tabindex="-1"></a>bal <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">sapply</span>(cv[, mycovs], select.diff, </span>
<span id="cb841-2"><a href="IVE2.html#cb841-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">grp =</span> cv<span class="sc">$</span>use_fin_aid)) <span class="co"># our grp is the won_lottery IV</span></span>
<span id="cb841-3"><a href="IVE2.html#cb841-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">round</span>(bal, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##          MeanDiff StdError p-value StdMeanDiff VarRatio
## male       -0.024     0.03   0.428      -0.047    1.001
## base_age   -0.161     0.08   0.043      -0.119    0.894</code></pre>
<p>Sure enough, we have one covariate out of balance, <code>base_age</code>. The group that used the financial aid had children who were younger. Looking at it from the other direction, the older children were less likely to use fin aid than younger students—about 16% less likely to use financial aid per one year of age. This might be by chance, but it is noteworthy that this covariate was not unbalanced with the instrumental variable but that it is with the question predictor.</p>
<p>We can view the plot by reusing the plot code.</p>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-446-1.png" width="672" /></p>
</div>
</div>
<div id="compliance-table-1" class="section level2" number="9.4">
<h2><span class="header-section-number">9.4</span> Compliance Table</h2>
<p>Let’s report the compliance table of the the relationship between the instrument, <code>won_lottry</code>, and the question predictor, <code>use_fin_aid</code>. The code is withheld here so you can practice this.</p>
<pre><code>##           use_fin_aid
## won_lottry   0   1
##          0 440 139
##          1  50 542</code></pre>
<pre><code>##           use_fin_aid
## won_lottry     0     1
##          0 0.760 0.240
##          1 0.084 0.916</code></pre>
<p>Among the children who won the lottery, 91.6% used financial aid. 8.4% did not take it up. This is assumed to represent the proportion in the population who are never takers; presumably, the control group has this same proportion of this type of children. Similarly, the 24% of crossovers from the control group represents the proportion of the population who are always takers; it is assumed that this same proportion is present in the treatment group.</p>
<!-- This proportion minus those who found financial aid even though they were not offered aid through the lottery is 0.676. This is pretty close to the first-stage estimate of`won_lottry` reported in Table 11.2.^[The covariates in the first stage model were significant but not strong enough to make this OLS estimate of `won_lottry` much different from that calculated .] -->
</div>
<div id="estimating-the-causal-effect" class="section level2" number="9.5">
<h2><span class="header-section-number">9.5</span> Estimating the Causal Effect</h2>
<div id="the-naïve-estimate" class="section level3" number="9.5.1">
<h3><span class="header-section-number">9.5.1</span> The naïve estimate</h3>
<p>Let’s estimate the effect of the endogenous question predictor on the outcome variable, which is what is reported on the bottom right of Table 11.2 (p. 273). This is the naïve (prima facie) estimate because we are not accounting for bias and therefore can<strong>not</strong> claim that this is an estimate of the causal effect. The code is suppressed here so you can do it on your own.</p>
<pre><code>##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)    1.410      0.121  11.694    0.000
## use_fin_aid    0.121      0.027   4.511    0.000
## base_age      -0.063      0.010  -6.395    0.000
## male          -0.086      0.026  -3.243    0.001</code></pre>
</div>
<div id="the-late-estimate-from-ive" class="section level3" number="9.5.2">
<h3><span class="header-section-number">9.5.2</span> The LATE estimate from IVE</h3>
<p>Let’s compare this with the LATE from instrumental-variable estimation.</p>
<p>Here’s the first stage. The code is suppressed here so you can recreate it.</p>
<pre><code>##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)    0.433      0.095   4.548    0.000
## won_lottry     0.675      0.021  32.099    0.000
## base_age      -0.015      0.008  -1.937    0.053
## male          -0.020      0.021  -0.961    0.337</code></pre>
<p>Here’s the second stage, with the estimate of <code>use_fin_aid</code> being the parameter of interest in our causal claim:</p>
<pre><code>##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)    1.378      0.123  11.196    0.000
## use_fin_aid    0.159      0.039   4.059    0.000
## base_age      -0.062      0.010  -6.296    0.000
## male          -0.085      0.027  -3.213    0.001</code></pre>
<p>If you use the AER package, you can get the same results and the <span class="math inline">\(R^2\)</span>.</p>
<pre><code>## [1] 0.062</code></pre>
<p>If you use the systemfit package, you can see these results:</p>
<pre><code>## [[1]]
## 
## 2SLS estimates for &#39;eq1&#39; (equation 1)
## Model Formula: use_fin_aid ~ won_lottry + base_age + male
## Instruments: ~won_lottry + base_age + male
## 
##                Estimate  Std. Error  t value   Pr(&gt;|t|)    
## (Intercept)  0.43275985  0.09515937  4.54774  5.988e-06 ***
## won_lottry   0.67452704  0.02101411 32.09877 &lt; 2.22e-16 ***
## base_age    -0.01516041  0.00782603 -1.93718   0.052965 .  
## male        -0.02025709  0.02107003 -0.96142   0.336542    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.359427 on 1167 degrees of freedom
## Number of observations: 1171 Degrees of Freedom: 1167 
## SSR: 150.76248 MSE: 0.129188 Root MSE: 0.359427 
## Multiple R-Squared: 0.470938 Adjusted R-Squared: 0.469577 
## 
## 
## [[2]]
## 
## 2SLS estimates for &#39;eq2&#39; (equation 2)
## Model Formula: finish8th ~ use_fin_aid + base_age + male
## Instruments: ~won_lottry + base_age + male
## 
##                Estimate  Std. Error  t value   Pr(&gt;|t|)    
## (Intercept)  1.37812758  0.12308958 11.19614 &lt; 2.22e-16 ***
## use_fin_aid  0.15900020  0.03917327  4.05890 5.2589e-05 ***
## base_age    -0.06215735  0.00987246 -6.29603 4.3146e-10 ***
## male        -0.08514482  0.02650360 -3.21258  0.0013515 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.451949 on 1167 degrees of freedom
## Number of observations: 1171 Degrees of Freedom: 1167 
## SSR: 238.369037 MSE: 0.204258 Root MSE: 0.451949 
## Multiple R-Squared: 0.062233 Adjusted R-Squared: 0.059822</code></pre>
</div>
<div id="making-the-intercept-meaningful" class="section level3" number="9.5.3">
<h3><span class="header-section-number">9.5.3</span> Making the intercept meaningful</h3>
<p>Another thing we could do is make the intercept more meaningful. Notice that the intercept in our Table 11.2 models was out of logical bounds (not between 0 and 1). Let’s re-center age so that the intercept is no longer when students are Age 0, but when they’re 12. That will give us an intercept that estimates students who did not use financial aid, were not offered the lottery, were female, and were Age 12.</p>
<pre><code>##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)    0.632      0.030  21.203    0.000
## use_fin_aid    0.159      0.039   4.059    0.000
## ageC          -0.062      0.010  -6.296    0.000
## male          -0.085      0.027  -3.213    0.001</code></pre>
<p>Now, the intercept makes sense. The test statistics for the question predictor and the covariates are unchanged.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="1">
<div id="ref-R-sem" class="csl-entry">
Fox, J., Nie, Z., &amp; Byrnes, J. (2020). <em>Sem: Structural equation models</em>. <a href="https://CRAN.R-project.org/package=sem">https://CRAN.R-project.org/package=sem</a>
</div>
<div id="ref-R-systemfit" class="csl-entry">
Henningsen, A., &amp; Hamann, J. D. (2019). <em>Systemfit: Estimating systems of simultaneous equations</em>. <a href="http://www.systemfit.org">http://www.systemfit.org</a>
</div>
<div id="ref-R-AER" class="csl-entry">
Kleiber, C., &amp; Zeileis, A. (2020). <em>AER: Applied econometrics with r</em>. <a href="https://CRAN.R-project.org/package=AER">https://CRAN.R-project.org/package=AER</a>
</div>
<div id="ref-murnane_methods_2011" class="csl-entry">
Murnane, R. J., &amp; Willett, J. B. (2011). <em>Methods matter: <span>Improving</span> causal inference in educational and social science research</em>. Oxford University Press.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="55">
<li id="fn55"><p>We added the <code>if(sum(ind) &gt; 0)</code> because without it, an error is printed in the console because in this case the number of covariates out of balance is 0.<a href="IVE2.html#fnref55" class="footnote-back">↩︎</a></p></li>
<li id="fn56"><p>Still, as with any randomized experiment, we may encounter SUTVA violations. There may be mechanisms such as resentful demoralization or John Henry effect due to the treatment-group assignment. These mechanisms would directly relate assignment to <span class="math inline">\(Z\)</span> with the outcome, <span class="math inline">\(Y\)</span>, violating the exclusion principle. We could use reasoning to argue that these effects on <span class="math inline">\(Y\)</span> not likely, however, if our treatment is very long in duration, as it is in this study. Most people who hold grudges or over-compensate would probably not be able to sustain their response to Z through the life of the experiment.<a href="IVE2.html#fnref56" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="IVE.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="PScore1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
