<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Part 12 Propensity Score Analysis 3: Stratification and Matching | Using R for Quasi-Experimental Designs</title>
  <meta name="description" content="QEDs in R" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Part 12 Propensity Score Analysis 3: Stratification and Matching | Using R for Quasi-Experimental Designs" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="QEDs in R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Part 12 Propensity Score Analysis 3: Stratification and Matching | Using R for Quasi-Experimental Designs" />
  
  <meta name="twitter:description" content="QEDs in R" />
  

<meta name="author" content="George M. Harrison  University of Hawai‘i at Mānoa, College of Education" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="PScore2.html"/>
<link rel="next" href="references.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 1em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#what-is-r"><i class="fa fa-check"></i><b>1.1</b> What is R</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basics.html"><a href="basics.html"><i class="fa fa-check"></i><b>2</b> Some Fundamentals of Coding in R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basics.html"><a href="basics.html#objectives"><i class="fa fa-check"></i><b>2.1</b> Objectives</a></li>
<li class="chapter" data-level="2.2" data-path="basics.html"><a href="basics.html#creating-an-r-script-file"><i class="fa fa-check"></i><b>2.2</b> Creating an R Script File</a></li>
<li class="chapter" data-level="2.3" data-path="basics.html"><a href="basics.html#creating-objects-by-assigning-information-to-them"><i class="fa fa-check"></i><b>2.3</b> Creating objects by assigning information to them</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="basics.html"><a href="basics.html#assigning-character-strings-to-an-object"><i class="fa fa-check"></i><b>2.3.1</b> Assigning Character Strings to an Object</a></li>
<li class="chapter" data-level="2.3.2" data-path="basics.html"><a href="basics.html#assigning-numeric-elements-to-an-object"><i class="fa fa-check"></i><b>2.3.2</b> Assigning Numeric Elements to an Object</a></li>
<li class="chapter" data-level="2.3.3" data-path="basics.html"><a href="basics.html#creating-vectors"><i class="fa fa-check"></i><b>2.3.3</b> Creating Vectors</a></li>
<li class="chapter" data-level="2.3.4" data-path="basics.html"><a href="basics.html#performing-operations-on-vectors"><i class="fa fa-check"></i><b>2.3.4</b> Performing Operations on Vectors</a></li>
<li class="chapter" data-level="2.3.5" data-path="basics.html"><a href="basics.html#using-functions"><i class="fa fa-check"></i><b>2.3.5</b> Using Functions</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="basics.html"><a href="basics.html#create-a-data-frame-from-code"><i class="fa fa-check"></i><b>2.4</b> Create a data frame from code</a></li>
<li class="chapter" data-level="2.5" data-path="basics.html"><a href="basics.html#working-with-matrices"><i class="fa fa-check"></i><b>2.5</b> Working with Matrices</a></li>
<li class="chapter" data-level="2.6" data-path="basics.html"><a href="basics.html#dffromcsv"><i class="fa fa-check"></i><b>2.6</b> Creating a Data Frame from a CSV File</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="examine.html"><a href="examine.html"><i class="fa fa-check"></i><b>3</b> Examining and Summarizing Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="examine.html"><a href="examine.html#objectives-1"><i class="fa fa-check"></i><b>3.1</b> Objectives</a></li>
<li class="chapter" data-level="3.2" data-path="examine.html"><a href="examine.html#examining-the-data"><i class="fa fa-check"></i><b>3.2</b> Examining the Data</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="examine.html"><a href="examine.html#the-data-frame"><i class="fa fa-check"></i><b>3.2.1</b> The Data Frame</a></li>
<li class="chapter" data-level="3.2.2" data-path="examine.html"><a href="examine.html#subsetting-by-rows"><i class="fa fa-check"></i><b>3.2.2</b> Subsetting by Rows</a></li>
<li class="chapter" data-level="3.2.3" data-path="examine.html"><a href="examine.html#subsetting-by-columns"><i class="fa fa-check"></i><b>3.2.3</b> Subsetting by Columns</a></li>
<li class="chapter" data-level="3.2.4" data-path="examine.html"><a href="examine.html#descriptive-statistics"><i class="fa fa-check"></i><b>3.2.4</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="3.2.5" data-path="examine.html"><a href="examine.html#creating-a-custom-function-to-estimate-the-confidence-interval-of-the-mean"><i class="fa fa-check"></i><b>3.2.5</b> Creating a Custom Function to Estimate the Confidence Interval of the Mean</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="examine.html"><a href="examine.html#summarizing-data-by-group-and-an-introduction-to-lists"><i class="fa fa-check"></i><b>3.3</b> Summarizing Data by Group (and an introduction to lists)</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="examine.html"><a href="examine.html#calculating-standardized-mean-difference-and-variance-ratio-of-a-covariate"><i class="fa fa-check"></i><b>3.3.1</b> Calculating Standardized Mean Difference and Variance Ratio of a Covariate</a></li>
<li class="chapter" data-level="3.3.2" data-path="examine.html"><a href="examine.html#creating-a-factor-variable-from-a-numeric-variable"><i class="fa fa-check"></i><b>3.3.2</b> Creating a Factor Variable from a Numeric Variable</a></li>
<li class="chapter" data-level="3.3.3" data-path="examine.html"><a href="examine.html#aggregate_explain"><i class="fa fa-check"></i><b>3.3.3</b> The <code>aggregate()</code> function</a></li>
<li class="chapter" data-level="3.3.4" data-path="examine.html"><a href="examine.html#plotting-data-by-group"><i class="fa fa-check"></i><b>3.3.4</b> Plotting data by group</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="examine.html"><a href="examine.html#extra-stuff"><i class="fa fa-check"></i><b>3.4</b> Extra Stuff</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="examine.html"><a href="examine.html#using-ggplot"><i class="fa fa-check"></i><b>3.4.1</b> Using ggplot</a></li>
<li class="chapter" data-level="3.4.2" data-path="examine.html"><a href="examine.html#subsetting-data-and-separately-analyzing-each-group"><i class="fa fa-check"></i><b>3.4.2</b> Subsetting data and separately analyzing each group</a></li>
<li class="chapter" data-level="3.4.3" data-path="examine.html"><a href="examine.html#the-tidyverse-approach-to-by-group-analyses"><i class="fa fa-check"></i><b>3.4.3</b> The Tidyverse Approach to By-Group Analyses</a></li>
<li class="chapter" data-level="3.4.4" data-path="examine.html"><a href="examine.html#plotting-summary-statistics"><i class="fa fa-check"></i><b>3.4.4</b> Plotting summary statistics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="rct.html"><a href="rct.html"><i class="fa fa-check"></i><b>4</b> Examples with Randomized Experiments</a>
<ul>
<li class="chapter" data-level="4.1" data-path="rct.html"><a href="rct.html#objectives-2"><i class="fa fa-check"></i><b>4.1</b> Objectives</a></li>
<li class="chapter" data-level="4.2" data-path="rct.html"><a href="rct.html#preparation"><i class="fa fa-check"></i><b>4.2</b> Preparation</a></li>
<li class="chapter" data-level="4.3" data-path="rct.html"><a href="rct.html#analysis-of-linear-models"><i class="fa fa-check"></i><b>4.3</b> Analysis of Linear Models</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="rct.html"><a href="rct.html#independent-samples-t-test-approach"><i class="fa fa-check"></i><b>4.3.1</b> Independent samples <em>t</em>-test approach</a></li>
<li class="chapter" data-level="4.3.2" data-path="rct.html"><a href="rct.html#simple-linear-regression"><i class="fa fa-check"></i><b>4.3.2</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="4.3.3" data-path="rct.html"><a href="rct.html#multiple-linear-regression"><i class="fa fa-check"></i><b>4.3.3</b> Multiple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="rct.html"><a href="rct.html#bootstrapping-to-get-confidence-intervals"><i class="fa fa-check"></i><b>4.4</b> Bootstrapping to Get Confidence Intervals</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="rct.html"><a href="rct.html#the-value-of-bootstrapping"><i class="fa fa-check"></i><b>4.4.1</b> The value of bootstrapping</a></li>
<li class="chapter" data-level="4.4.2" data-path="rct.html"><a href="rct.html#another-way-to-bootstrap-the-standard-error-of-mean-differences"><i class="fa fa-check"></i><b>4.4.2</b> Another way to bootstrap the standard error of mean differences</a></li>
<li class="chapter" data-level="4.4.3" data-path="rct.html"><a href="rct.html#simple-regression"><i class="fa fa-check"></i><b>4.4.3</b> Simple regression</a></li>
<li class="chapter" data-level="4.4.4" data-path="rct.html"><a href="rct.html#multiple-regression"><i class="fa fa-check"></i><b>4.4.4</b> Multiple regression</a></li>
<li class="chapter" data-level="4.4.5" data-path="rct.html"><a href="rct.html#summary-on-bootstrapping"><i class="fa fa-check"></i><b>4.4.5</b> Summary on Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="rct.html"><a href="rct.html#estimating-the-average-treatment-on-the-treated-att"><i class="fa fa-check"></i><b>4.5</b> Estimating the Average Treatment on the Treated (ATT)</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="rct.html"><a href="rct.html#artificially-introducing-no-shows"><i class="fa fa-check"></i><b>4.5.1</b> Artificially Introducing No-shows</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="DID.html"><a href="DID.html"><i class="fa fa-check"></i><b>5</b> Difference in Differences</a>
<ul>
<li class="chapter" data-level="5.1" data-path="DID.html"><a href="DID.html#objectives-3"><i class="fa fa-check"></i><b>5.1</b> Objectives</a></li>
<li class="chapter" data-level="5.2" data-path="DID.html"><a href="DID.html#import-and-prepare-the-data"><i class="fa fa-check"></i><b>5.2</b> Import and Prepare the Data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="DID.html"><a href="DID.html#prepare-the-data"><i class="fa fa-check"></i><b>5.2.1</b> Prepare the data</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="DID.html"><a href="DID.html#using-the-survey-package"><i class="fa fa-check"></i><b>5.3</b> Using the survey package</a></li>
<li class="chapter" data-level="5.4" data-path="DID.html"><a href="DID.html#direct-estimates-as-shown-in-table-8.1-on-page-143"><i class="fa fa-check"></i><b>5.4</b> Direct estimates, as shown in Table 8.1 on page 143</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="DID.html"><a href="DID.html#first-difference-direct-estimate-in-panel-a."><i class="fa fa-check"></i><b>5.4.1</b> First difference, direct estimate in Panel A.</a></li>
<li class="chapter" data-level="5.4.2" data-path="DID.html"><a href="DID.html#estimate-from-the-linear-probability-model-ols-estimate-shown-in-table-8.1-on-page-143-panel-b."><i class="fa fa-check"></i><b>5.4.2</b> Estimate from the linear-probability model (OLS) estimate shown in Table 8.1 on page 143, Panel B.</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="DID.html"><a href="DID.html#difference-in-differences-simple-approach-table-8.2-p.-157"><i class="fa fa-check"></i><b>5.5</b> Difference in differences, simple approach (Table 8.2, p. 157)</a></li>
<li class="chapter" data-level="5.6" data-path="DID.html"><a href="DID.html#difference-in-differences-using-regression"><i class="fa fa-check"></i><b>5.6</b> Difference in differences using regression</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="DID.html"><a href="DID.html#compare-the-results-from-the-four-different-strategies"><i class="fa fa-check"></i><b>5.6.1</b> Compare the results from the four different strategies</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="DID.html"><a href="DID.html#summary-of-the-did-model-strategy"><i class="fa fa-check"></i><b>5.7</b> Summary of the DID model strategy</a></li>
<li class="chapter" data-level="5.8" data-path="DID.html"><a href="DID.html#accounting-for-the-binary-y-variable"><i class="fa fa-check"></i><b>5.8</b> Accounting for the binary Y variable</a></li>
<li class="chapter" data-level="5.9" data-path="DID.html"><a href="DID.html#plotting-the-difference-in-differences"><i class="fa fa-check"></i><b>5.9</b> Plotting the difference in differences</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="DID.html"><a href="DID.html#plotfrompred"><i class="fa fa-check"></i><b>5.9.1</b> Plotting from the predicted values of the model</a></li>
<li class="chapter" data-level="5.9.2" data-path="DID.html"><a href="DID.html#doing-it-in-ggplot2"><i class="fa fa-check"></i><b>5.9.2</b> Doing it in ggplot2</a></li>
<li class="chapter" data-level="5.9.3" data-path="DID.html"><a href="DID.html#seeing-where-the-regression-estimate-is-in-the-plot"><i class="fa fa-check"></i><b>5.9.3</b> Seeing where the regression estimate is in the plot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="RD1.html"><a href="RD1.html"><i class="fa fa-check"></i><b>6</b> Regression Discontinuity, Part 1</a>
<ul>
<li class="chapter" data-level="6.1" data-path="RD1.html"><a href="RD1.html#objectives-4"><i class="fa fa-check"></i><b>6.1</b> Objectives</a></li>
<li class="chapter" data-level="6.2" data-path="RD1.html"><a href="RD1.html#import-and-prepare-the-data-1"><i class="fa fa-check"></i><b>6.2</b> Import and Prepare the Data</a></li>
<li class="chapter" data-level="6.3" data-path="RD1.html"><a href="RD1.html#different-difference-in-differences"><i class="fa fa-check"></i><b>6.3</b> Different Difference in Differences</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="RD1.html"><a href="RD1.html#our-first-difference"><i class="fa fa-check"></i><b>6.3.1</b> Our first difference</a></li>
<li class="chapter" data-level="6.3.2" data-path="RD1.html"><a href="RD1.html#a-plausible-second-difference"><i class="fa fa-check"></i><b>6.3.2</b> A plausible second difference</a></li>
<li class="chapter" data-level="6.3.3" data-path="RD1.html"><a href="RD1.html#another-plausible-second-difference"><i class="fa fa-check"></i><b>6.3.3</b> Another plausible second difference</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="RD1.html"><a href="RD1.html#mread3640"><i class="fa fa-check"></i><b>6.4</b> Broadening the bandwidth</a></li>
<li class="chapter" data-level="6.5" data-path="RD1.html"><a href="RD1.html#summary-up-to-this-point"><i class="fa fa-check"></i><b>6.5</b> Summary up to this point</a></li>
<li class="chapter" data-level="6.6" data-path="RD1.html"><a href="RD1.html#examining-if-the-results-are-consistent-with-different-bandwidths"><i class="fa fa-check"></i><b>6.6</b> Examining if the results are consistent with different bandwidths</a></li>
<li class="chapter" data-level="6.7" data-path="RD1.html"><a href="RD1.html#functional-form-in-rdd"><i class="fa fa-check"></i><b>6.7</b> Functional Form in RDD</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="RD1.html"><a href="RD1.html#plotting-the-two-sides-allowing-different-slopes"><i class="fa fa-check"></i><b>6.7.1</b> Plotting the two sides, allowing different slopes</a></li>
<li class="chapter" data-level="6.7.2" data-path="RD1.html"><a href="RD1.html#broader-analytic-windows"><i class="fa fa-check"></i><b>6.7.2</b> Broader analytic windows</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="RD1.html"><a href="RD1.html#using-the-rddtools-package"><i class="fa fa-check"></i><b>6.8</b> Using the rddtools Package</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="RD1.html"><a href="RD1.html#examining-the-bandwidth-identified-by-the-package"><i class="fa fa-check"></i><b>6.8.1</b> Examining the bandwidth identified by the package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="RD2.html"><a href="RD2.html"><i class="fa fa-check"></i><b>7</b> Regression Discontinuity, Part 2</a>
<ul>
<li class="chapter" data-level="7.1" data-path="RD2.html"><a href="RD2.html#here-are-the-steps-we-will-take"><i class="fa fa-check"></i><b>7.1</b> Here are the steps we will take:</a></li>
<li class="chapter" data-level="7.2" data-path="RD2.html"><a href="RD2.html#the-data"><i class="fa fa-check"></i><b>7.2</b> The Data</a></li>
<li class="chapter" data-level="7.3" data-path="RD2.html"><a href="RD2.html#examine-the-data-the-assignment-rule-adherence-and-compliance"><i class="fa fa-check"></i><b>7.3</b> Examine the Data, the Assignment-rule Adherence, and Compliance</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="RD2.html"><a href="RD2.html#assignment-rule-adherence"><i class="fa fa-check"></i><b>7.3.1</b> Assignment-rule adherence</a></li>
<li class="chapter" data-level="7.3.2" data-path="RD2.html"><a href="RD2.html#compliance"><i class="fa fa-check"></i><b>7.3.2</b> Compliance</a></li>
<li class="chapter" data-level="7.3.3" data-path="RD2.html"><a href="RD2.html#create-bins-of-the-assignment-variable"><i class="fa fa-check"></i><b>7.3.3</b> Create Bins of the Assignment Variable</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="RD2.html"><a href="RD2.html#examining-assumptions"><i class="fa fa-check"></i><b>7.4</b> Examining Assumptions</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="RD2.html"><a href="RD2.html#assumption-1the-continuity-assumption"><i class="fa fa-check"></i><b>7.4.1</b> Assumption 1—the continuity assumption</a></li>
<li class="chapter" data-level="7.4.2" data-path="RD2.html"><a href="RD2.html#assumption-2discontinuities-in-the-covariates"><i class="fa fa-check"></i><b>7.4.2</b> Assumption 2—Discontinuities in the covariates</a></li>
<li class="chapter" data-level="7.4.3" data-path="RD2.html"><a href="RD2.html#assumption-3checking-for-pseudo-cut-offs-in-the-outcome"><i class="fa fa-check"></i><b>7.4.3</b> Assumption 3—Checking for pseudo-cut-offs in the outcome</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="RD2.html"><a href="RD2.html#examining-the-parametric-functional-form"><i class="fa fa-check"></i><b>7.5</b> Examining the Parametric Functional Form</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="RD2.html"><a href="RD2.html#restricting-bandwidth"><i class="fa fa-check"></i><b>7.5.1</b> Restricting bandwidth</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="RD2.html"><a href="RD2.html#restband"><i class="fa fa-check"></i><b>7.6</b> Estimating the Effect</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="RD2.html"><a href="RD2.html#parametric-model"><i class="fa fa-check"></i><b>7.6.1</b> Parametric Model</a></li>
<li class="chapter" data-level="7.6.2" data-path="RD2.html"><a href="RD2.html#non-parametric-model-local-linear-estimation"><i class="fa fa-check"></i><b>7.6.2</b> Non-parametric Model: Local Linear Estimation</a></li>
<li class="chapter" data-level="7.6.3" data-path="RD2.html"><a href="RD2.html#including-covariates"><i class="fa fa-check"></i><b>7.6.3</b> Including covariates</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="RD2.html"><a href="RD2.html#sensitivity-analysis"><i class="fa fa-check"></i><b>7.7</b> Sensitivity Analysis</a></li>
<li class="chapter" data-level="7.8" data-path="RD2.html"><a href="RD2.html#accounting-for-fuzziness"><i class="fa fa-check"></i><b>7.8</b> Accounting for Fuzziness</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="RD2.html"><a href="RD2.html#fuzzy-non-parametric-model"><i class="fa fa-check"></i><b>7.8.1</b> Fuzzy non-parametric model</a></li>
<li class="chapter" data-level="7.8.2" data-path="RD2.html"><a href="RD2.html#summary-about-fuzzy-rdd"><i class="fa fa-check"></i><b>7.8.2</b> Summary about fuzzy RDD</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="IVE.html"><a href="IVE.html"><i class="fa fa-check"></i><b>8</b> Instrumental Variable Estimation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="IVE.html"><a href="IVE.html#objectives-5"><i class="fa fa-check"></i><b>8.1</b> Objectives</a></li>
<li class="chapter" data-level="8.2" data-path="IVE.html"><a href="IVE.html#preparation-1"><i class="fa fa-check"></i><b>8.2</b> Preparation</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="IVE.html"><a href="IVE.html#examining-the-data-1"><i class="fa fa-check"></i><b>8.2.1</b> Examining the data</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="IVE.html"><a href="IVE.html#moments-reported-in-table-10.2-p.-219"><i class="fa fa-check"></i><b>8.3</b> Moments reported in Table 10.2 (p. 219)</a></li>
<li class="chapter" data-level="8.4" data-path="IVE.html"><a href="IVE.html#two-stage-least-squares-1"><i class="fa fa-check"></i><b>8.4</b> Two-stage Least Squares</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="IVE.html"><a href="IVE.html#first-stage"><i class="fa fa-check"></i><b>8.4.1</b> First stage</a></li>
<li class="chapter" data-level="8.4.2" data-path="IVE.html"><a href="IVE.html#second-stage"><i class="fa fa-check"></i><b>8.4.2</b> Second stage</a></li>
<li class="chapter" data-level="8.4.3" data-path="IVE.html"><a href="IVE.html#obtaining-the-correct-standard-errors"><i class="fa fa-check"></i><b>8.4.3</b> Obtaining the correct standard errors</a></li>
<li class="chapter" data-level="8.4.4" data-path="IVE.html"><a href="IVE.html#letting-the-software-do-the-work"><i class="fa fa-check"></i><b>8.4.4</b> Letting the software do the work</a></li>
<li class="chapter" data-level="8.4.5" data-path="IVE.html"><a href="IVE.html#noticing-the-covariance-between-errors"><i class="fa fa-check"></i><b>8.4.5</b> Noticing the covariance between errors</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="IVE.html"><a href="IVE.html#two-stage-least-squares-with-covariates"><i class="fa fa-check"></i><b>8.5</b> Two-Stage Least Squares with Covariates</a></li>
<li class="chapter" data-level="8.6" data-path="IVE.html"><a href="IVE.html#using-multiple-instruments"><i class="fa fa-check"></i><b>8.6</b> Using Multiple Instruments</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="IVE.html"><a href="IVE.html#system-of-equations"><i class="fa fa-check"></i><b>8.6.1</b> System of equations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="IVE2.html"><a href="IVE2.html"><i class="fa fa-check"></i><b>9</b> Practice with Instrumental Variable Estimation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="IVE2.html"><a href="IVE2.html#objectives-6"><i class="fa fa-check"></i><b>9.1</b> Objectives</a></li>
<li class="chapter" data-level="9.2" data-path="IVE2.html"><a href="IVE2.html#import-and-prepare-the-data-2"><i class="fa fa-check"></i><b>9.2</b> Import and Prepare the Data</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="IVE2.html"><a href="IVE2.html#descriptive-statistics-1"><i class="fa fa-check"></i><b>9.2.1</b> Descriptive statistics</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="IVE2.html"><a href="IVE2.html#covariate-balance"><i class="fa fa-check"></i><b>9.3</b> Covariate Balance</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="IVE2.html"><a href="IVE2.html#covariate-balance-on-d"><i class="fa fa-check"></i><b>9.3.1</b> Covariate balance on <span class="math inline">\(D\)</span></a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="IVE2.html"><a href="IVE2.html#compliance-table-1"><i class="fa fa-check"></i><b>9.4</b> Compliance Table</a></li>
<li class="chapter" data-level="9.5" data-path="IVE2.html"><a href="IVE2.html#estimating-the-causal-effect"><i class="fa fa-check"></i><b>9.5</b> Estimating the Causal Effect</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="IVE2.html"><a href="IVE2.html#the-naïve-estimate"><i class="fa fa-check"></i><b>9.5.1</b> The naïve estimate</a></li>
<li class="chapter" data-level="9.5.2" data-path="IVE2.html"><a href="IVE2.html#the-late-estimate-from-ive"><i class="fa fa-check"></i><b>9.5.2</b> The LATE estimate from IVE</a></li>
<li class="chapter" data-level="9.5.3" data-path="IVE2.html"><a href="IVE2.html#making-the-intercept-meaningful"><i class="fa fa-check"></i><b>9.5.3</b> Making the intercept meaningful</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="PScore1.html"><a href="PScore1.html"><i class="fa fa-check"></i><b>10</b> Propensity Score Analysis 1: The underlying logic</a>
<ul>
<li class="chapter" data-level="10.1" data-path="PScore1.html"><a href="PScore1.html#import-the-data-and-prepare-for-analysis"><i class="fa fa-check"></i><b>10.1</b> Import the Data and Prepare for Analysis</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="PScore1.html"><a href="PScore1.html#creating-a-numeric-version-of-the-base-income-variables"><i class="fa fa-check"></i><b>10.1.1</b> Creating a numeric version of the base-income variables</a></li>
<li class="chapter" data-level="10.1.2" data-path="PScore1.html"><a href="PScore1.html#creating-some-custom-functions"><i class="fa fa-check"></i><b>10.1.2</b> Creating some custom functions</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="PScore1.html"><a href="PScore1.html#stratifying-on-a-covariate"><i class="fa fa-check"></i><b>10.2</b> Stratifying on a Covariate</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="PScore1.html"><a href="PScore1.html#checking-the-imbalance-in-the-treatment-status"><i class="fa fa-check"></i><b>10.2.1</b> Checking the imbalance in the treatment status</a></li>
<li class="chapter" data-level="10.2.2" data-path="PScore1.html"><a href="PScore1.html#creating-the-strata-from-the-covariate"><i class="fa fa-check"></i><b>10.2.2</b> Creating the strata from the covariate</a></li>
<li class="chapter" data-level="10.2.3" data-path="PScore1.html"><a href="PScore1.html#checking-for-imbalance-within-each-stratum"><i class="fa fa-check"></i><b>10.2.3</b> Checking for imbalance within each stratum</a></li>
<li class="chapter" data-level="10.2.4" data-path="PScore1.html"><a href="PScore1.html#using-tidyverse-to-check-imbalance"><i class="fa fa-check"></i><b>10.2.4</b> Using Tidyverse to check imbalance</a></li>
<li class="chapter" data-level="10.2.5" data-path="PScore1.html"><a href="PScore1.html#ate-and-att"><i class="fa fa-check"></i><b>10.2.5</b> ATE and ATT</a></li>
<li class="chapter" data-level="10.2.6" data-path="PScore1.html"><a href="PScore1.html#pooling-across-strata-to-calculate-the-ate-and-att"><i class="fa fa-check"></i><b>10.2.6</b> Pooling across strata to calculate the ATE and ATT</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="PScore1.html"><a href="PScore1.html#stratifying-on-two-covariates"><i class="fa fa-check"></i><b>10.3</b> Stratifying on Two Covariates</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="PScore1.html"><a href="PScore1.html#calculating-the-ate-and-att"><i class="fa fa-check"></i><b>10.3.1</b> Calculating the ATE and ATT</a></li>
<li class="chapter" data-level="10.3.2" data-path="PScore1.html"><a href="PScore1.html#tidyverse-approach"><i class="fa fa-check"></i><b>10.3.2</b> Tidyverse approach</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="PScore1.html"><a href="PScore1.html#estimating-propensity-scores"><i class="fa fa-check"></i><b>10.4</b> Estimating Propensity Scores</a></li>
<li class="chapter" data-level="10.5" data-path="PScore1.html"><a href="PScore1.html#creating-strata-from-propensity-scores"><i class="fa fa-check"></i><b>10.5</b> Creating Strata from Propensity Scores</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="PScore1.html"><a href="PScore1.html#adding-more-covariates"><i class="fa fa-check"></i><b>10.5.1</b> Adding more covariates</a></li>
<li class="chapter" data-level="10.5.2" data-path="PScore1.html"><a href="PScore1.html#ate-and-att-for-the-five-stratum-model"><i class="fa fa-check"></i><b>10.5.2</b> ATE and ATT for the five-stratum model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="PScore2.html"><a href="PScore2.html"><i class="fa fa-check"></i><b>11</b> Propensity Score Analysis 2: Weighting</a>
<ul>
<li class="chapter" data-level="11.1" data-path="PScore2.html"><a href="PScore2.html#import-the-data-and-prepare-for-analysis-1"><i class="fa fa-check"></i><b>11.1</b> Import the Data and Prepare for Analysis</a></li>
<li class="chapter" data-level="11.2" data-path="PScore2.html"><a href="PScore2.html#specify-custom-functions"><i class="fa fa-check"></i><b>11.2</b> Specify Custom Functions</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="PScore2.html"><a href="PScore2.html#imbalance-functions"><i class="fa fa-check"></i><b>11.2.1</b> Imbalance functions</a></li>
<li class="chapter" data-level="11.2.2" data-path="PScore2.html"><a href="PScore2.html#overlap-functions"><i class="fa fa-check"></i><b>11.2.2</b> Overlap functions</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="PScore2.html"><a href="PScore2.html#assess-imbalance-in-observed-covariates"><i class="fa fa-check"></i><b>11.3</b> Assess Imbalance in Observed Covariates</a></li>
<li class="chapter" data-level="11.4" data-path="PScore2.html"><a href="PScore2.html#check-overlap"><i class="fa fa-check"></i><b>11.4</b> Check Overlap</a></li>
<li class="chapter" data-level="11.5" data-path="PScore2.html"><a href="PScore2.html#calculate-the-weights"><i class="fa fa-check"></i><b>11.5</b> Calculate the Weights</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="PScore2.html"><a href="PScore2.html#dealing-with-extreme-weights"><i class="fa fa-check"></i><b>11.5.1</b> Dealing with extreme weights</a></li>
<li class="chapter" data-level="11.5.2" data-path="PScore2.html"><a href="PScore2.html#specifying-whether-to-estimate-ate-or-att"><i class="fa fa-check"></i><b>11.5.2</b> Specifying whether to estimate ATE or ATT</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="PScore2.html"><a href="PScore2.html#conduct-balance-checks-after-weighting"><i class="fa fa-check"></i><b>11.6</b> Conduct balance checks after weighting</a></li>
<li class="chapter" data-level="11.7" data-path="PScore2.html"><a href="PScore2.html#estimate-the-treatment-effect"><i class="fa fa-check"></i><b>11.7</b> Estimate the Treatment Effect</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="PScore2.html"><a href="PScore2.html#estimating-the-correct-standard-error"><i class="fa fa-check"></i><b>11.7.1</b> Estimating the correct standard error</a></li>
<li class="chapter" data-level="11.7.2" data-path="PScore2.html"><a href="PScore2.html#use-a-doubly-robust-estimate"><i class="fa fa-check"></i><b>11.7.2</b> Use a doubly robust estimate</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="PScore2.html"><a href="PScore2.html#using-the-twang-package"><i class="fa fa-check"></i><b>11.8</b> Using the Twang Package</a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="PScore2.html"><a href="PScore2.html#examining-covariate-balance"><i class="fa fa-check"></i><b>11.8.1</b> Examining covariate balance</a></li>
<li class="chapter" data-level="11.8.2" data-path="PScore2.html"><a href="PScore2.html#estimating-the-propensity-scores-and-getting-the-weights"><i class="fa fa-check"></i><b>11.8.2</b> Estimating the propensity scores and getting the weights</a></li>
<li class="chapter" data-level="11.8.3" data-path="PScore2.html"><a href="PScore2.html#estimating-the-effect"><i class="fa fa-check"></i><b>11.8.3</b> Estimating the effect</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="PScore3.html"><a href="PScore3.html"><i class="fa fa-check"></i><b>12</b> Propensity Score Analysis 3: Stratification and Matching</a>
<ul>
<li class="chapter" data-level="12.1" data-path="PScore3.html"><a href="PScore3.html#calculate-the-mmwss-from-the-propensity-scores"><i class="fa fa-check"></i><b>12.1</b> Calculate the MMWSs from the propensity scores</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="PScore3.html"><a href="PScore3.html#estimate-the-propensity-scores"><i class="fa fa-check"></i><b>12.1.1</b> Estimate the propensity scores</a></li>
<li class="chapter" data-level="12.1.2" data-path="PScore3.html"><a href="PScore3.html#calculate-the-quintiles"><i class="fa fa-check"></i><b>12.1.2</b> Calculate the quintiles</a></li>
<li class="chapter" data-level="12.1.3" data-path="PScore3.html"><a href="PScore3.html#examine-the-strata"><i class="fa fa-check"></i><b>12.1.3</b> Examine the strata</a></li>
<li class="chapter" data-level="12.1.4" data-path="PScore3.html"><a href="PScore3.html#calculate-the-mmwss"><i class="fa fa-check"></i><b>12.1.4</b> Calculate the MMWSs</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="PScore3.html"><a href="PScore3.html#conduct-balance-checks-after-weighting-1"><i class="fa fa-check"></i><b>12.2</b> Conduct balance checks after weighting</a></li>
<li class="chapter" data-level="12.3" data-path="PScore3.html"><a href="PScore3.html#estimate-the-ate"><i class="fa fa-check"></i><b>12.3</b> Estimate the ATE</a></li>
<li class="chapter" data-level="12.4" data-path="PScore3.html"><a href="PScore3.html#using-the-matchit-package"><i class="fa fa-check"></i><b>12.4</b> Using the MatchIt Package</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="PScore3.html"><a href="PScore3.html#examining-balance"><i class="fa fa-check"></i><b>12.4.1</b> Examining Balance</a></li>
<li class="chapter" data-level="12.4.2" data-path="PScore3.html"><a href="PScore3.html#estimate-the-effect"><i class="fa fa-check"></i><b>12.4.2</b> Estimate the Effect</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="PScore3.html"><a href="PScore3.html#matching"><i class="fa fa-check"></i><b>12.5</b> Matching</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="PScore3.html"><a href="PScore3.html#estimate-the-effect-1"><i class="fa fa-check"></i><b>12.5.1</b> Estimate the Effect</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Using R for Quasi-Experimental Designs</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="PScore3" class="section level1" number="12">
<h1><span class="header-section-number">Part 12</span> Propensity Score Analysis 3: Stratification and Matching</h1>
<p>In this unit, we begin by calculating the weights of five strata using <strong>marginal mean weighting through stratification</strong> (MMWS). We work through this process manually, then we use the MatchIt package <span class="citation">(<a href="#ref-R-MatchIt" role="doc-biblioref">Ho et al., 2021</a>)</span> to do the same thing using less code. After that, we continue with the MatchIt package and apply one of the matching methods, <strong>full (optimal distance) matching</strong>, to our data.</p>
<p>We will use the same data set and custom functions as those used in the previous unit. Also, as we did in the last unit, the analysis will be organized in two broad steps: (a) estimating the propensity scores and examining how well the adjustment method worked, and (b) estimating the effect. Conducting the first step on a data set that excludes the outcome variables is important for avoiding the temptation of selecting a method that yields the estimated effect we desire. For pedagogical purposes, we do the first and second step with each method—in other words, we implement the stratification, then attach the outcome variables and estimate the effect. However, in operational settings, we would allocate much more attention to the first step by trying out the various methods of adjustment and their variations. We would use theory and evidence to select the best combination of covariates and we might examine IP weighting, stratification (perhaps also varying the number of strata), and various matching methods that align with the expectations in our discipline in our effort to find the best approach for dealing with selection bias. Only after committing to the best adjustment method, would we then proceed to estimate the effects.</p>
<p>Let’s get started with stratification. One of the benefits of using stratification over the inverse-propensity score weights, which was the method we examined in our previous unit, is that we reduce the likelihood that we get extreme weights. However, this comes at a cost in that we can lose precision in our effort to correct for selection bias because we may still have imbalance within each stratum.</p>
<div id="calculate-the-mmwss-from-the-propensity-scores" class="section level2" number="12.1">
<h2><span class="header-section-number">12.1</span> Calculate the MMWSs from the propensity scores</h2>
<div id="estimate-the-propensity-scores" class="section level3" number="12.1.1">
<h3><span class="header-section-number">12.1.1</span> Estimate the propensity scores</h3>
<p>Let’s use the same logistic-regression we used in the previous unit to estimate the propensity scores.</p>
<div class="sourceCode" id="cb1081"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1081-1"><a href="PScore3.html#cb1081-1" aria-hidden="true" tabindex="-1"></a>ps_mdl1 <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">&#39;catholic&#39;</span>, <span class="st">&#39;~&#39;</span>, <span class="fu">paste</span>(covnames, <span class="at">collapse =</span> <span class="st">&#39; + &#39;</span>)))</span>
<span id="cb1081-2"><a href="PScore3.html#cb1081-2" aria-hidden="true" tabindex="-1"></a>out1    <span class="ot">&lt;-</span> <span class="fu">glm</span>(ps_mdl1, <span class="at">data =</span> ca, <span class="at">family =</span> <span class="st">&#39;binomial&#39;</span>)</span>
<span id="cb1081-3"><a href="PScore3.html#cb1081-3" aria-hidden="true" tabindex="-1"></a>ca<span class="sc">$</span>ps   <span class="ot">&lt;-</span> out1<span class="sc">$</span>fitted</span></code></pre></div>
</div>
<div id="calculate-the-quintiles" class="section level3" number="12.1.2">
<h3><span class="header-section-number">12.1.2</span> Calculate the quintiles</h3>
<p>Using quantiles of the propensity scores, <span class="math inline">\(\hat{e}(x_i)\)</span>, we will create five strata. This process sorts the cases from low to high and splits the observations into five intervals. Applying this procedure to the entire data set is appropriate for the ATE; for the ATT, we might be better off creating the strata based on the treated group’s propensity scores and then classifying the untreated-group (i.e., control-group) observations into those strata within those defined quintiles. We will also do this later in this section.</p>
<p>Here, we’ll use the <code>quantile()</code> and <code>cut()</code> functions. (Because we are creating five intervals, we can call them qu<strong>i</strong>ntiles.) Within the <code>quantile()</code> function, the <code>seq(0, 1, by = .2)</code> code creates a sequence of numbers (0, 0.2, 0.4, 0.6, 0.8, 1), that represent the breaks to use.</p>
<div class="sourceCode" id="cb1082"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1082-1"><a href="PScore3.html#cb1082-1" aria-hidden="true" tabindex="-1"></a>ca<span class="sc">$</span>strat5 <span class="ot">&lt;-</span> <span class="fu">cut</span>(ca<span class="sc">$</span>ps, </span>
<span id="cb1082-2"><a href="PScore3.html#cb1082-2" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">quantile</span>(ca<span class="sc">$</span>ps, <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> .<span class="dv">2</span>)), </span>
<span id="cb1082-3"><a href="PScore3.html#cb1082-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">include.lowest =</span> <span class="cn">TRUE</span>) </span></code></pre></div>
<p>The <code>cut()</code> function creates a factor. This is our stratification variable. The names of the levels are generated from the values in the propensity score variable that define the interval in each quintile. For example, we can see that the first quintile included the <span class="math inline">\(\hat{e}(x_i)\)</span> scores 0.0026 and 0.0504 and everything in between. This is why we included the <code>include.lowest = TRUE</code> argument in the <code>cut()</code> function—to be sure we included cases at the lowest break value (in this case, making the interval closed, as <code>[0.0026,0.0504]</code>, instead of half open, as <code>(0.0026,0.0504]</code>, which would have excluded cases with <span class="math inline">\(\hat{e}(x_i) = 0.0026\)</span>.). The second level of our factor includes observations in the half-open interval, <code>(0.0504,0.088]</code>, which includes cases with <span class="math inline">\(0.0504 &lt; \hat{e}(x_i) \le 0.088\)</span>.</p>
<div class="sourceCode" id="cb1083"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1083-1"><a href="PScore3.html#cb1083-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(ca<span class="sc">$</span>strat5)</span></code></pre></div>
<pre><code>## [1] &quot;[0.0026,0.0504]&quot; &quot;(0.0504,0.088]&quot;  &quot;(0.088,0.12]&quot;    &quot;(0.12,0.151]&quot;   
## [5] &quot;(0.151,0.263]&quot;</code></pre>
<p>We don’t really need these interval labels. So, to make it easier to display the stratum variable in the output, we can change these level labels to 1 through 5:</p>
<div class="sourceCode" id="cb1085"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1085-1"><a href="PScore3.html#cb1085-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(ca<span class="sc">$</span>strat5) <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span></span></code></pre></div>
</div>
<div id="examine-the-strata" class="section level3" number="12.1.3">
<h3><span class="header-section-number">12.1.3</span> Examine the strata</h3>
<p>We can take look at the number of observations per treatment-group status in each stratum. This is a preliminary examination of common support.</p>
<div class="sourceCode" id="cb1086"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1086-1"><a href="PScore3.html#cb1086-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(ca, <span class="fu">table</span>(catholic, strat5))</span></code></pre></div>
<pre><code>##         strat5
## catholic    1    2    3    4    5
##      no  1100 1054 1017  967  941
##      yes   35   80  117  167  193</code></pre>
<p>Further evidence of common support can be with a histogram of the treated and untreated groups, within each stratum. We can use our custom function, <code>overlap()</code>, from our previous unit for this. We are adding vertical lines to show where the stratum cuts are and help us see whether the common support assumption seems to hold.</p>
<div class="sourceCode" id="cb1088"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1088-1"><a href="PScore3.html#cb1088-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(ca, <span class="fu">overlap</span>(ps, catholic, </span>
<span id="cb1088-2"><a href="PScore3.html#cb1088-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bin=</span><span class="dv">30</span>, </span>
<span id="cb1088-3"><a href="PScore3.html#cb1088-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">&quot;Propensity scores by group and stratum&quot;</span>,</span>
<span id="cb1088-4"><a href="PScore3.html#cb1088-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">xlab  =</span> <span class="st">&quot;PS&quot;</span>))</span>
<span id="cb1088-5"><a href="PScore3.html#cb1088-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">quantile</span>(ca<span class="sc">$</span>ps, <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> .<span class="dv">2</span>)), <span class="at">col =</span> <span class="st">&#39;blue&#39;</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-586-1.png" width="672" /></p>
<p>It appears that regions on the ends—the very low end of the first stratum and the very high end of the fifth stratum—are not well represented by the treated group. The frequencies of observations in the other bins reveal that we will probably achieve adequate common support using these strata. We can further examine common support using density plots of each treatment-condition after we have applied the weights to the data, which is what we do next.</p>
</div>
<div id="calculate-the-mmwss" class="section level3" number="12.1.4">
<h3><span class="header-section-number">12.1.4</span> Calculate the MMWSs</h3>
<p>Similar to what we did in an earlier lesson with strata, we will use the <em>n</em>-sizes of each stratum, the <em>n</em>-sizes of each of the two conditions in the treatment variable, and the <em>n</em>-sizes of the treatment conditions within each stratum. Hong <span class="citation">(<a href="#ref-hong_causality_2015" role="doc-biblioref">2015</a>)</span> provides a thorough description of MMWS weighting.</p>
<div id="ate-mmws-equation" class="section level4" number="12.1.4.1">
<h4><span class="header-section-number">12.1.4.1</span> ATE MMWS equation</h4>
<p>In investigations of the ATE, the formula for the MMWS weights that Hong provides is</p>
<p><span class="math display">\[\begin{equation}
\text{MMWS}_{ATE}  = \frac{n_s}{n_{z,s}} \times \text{pr}(Z = z) \text{ ,}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(n_s\)</span> is the number of cases in stratum <span class="math inline">\(s\)</span>, <span class="math inline">\(n_{z,s}\)</span> is the number of cases in treatment-condition <span class="math inline">\(z\)</span> in stratum <span class="math inline">\(s\)</span>, and <span class="math inline">\(\text{pr}(Z = z)\)</span> is the proportion of cases in treatment condition <span class="math inline">\(Z\)</span> in the entire data set (ignoring strata). For the treated group, this is</p>
<p><span class="math display">\[
\text{MMWS}_{ATE,z=1}  = \frac{n_s}{n_{z,s}} \times \text{pr}(Z = 1) \text{ ,}
\]</span>
and for the untreated group, it is</p>
<p><span class="math display">\[
\text{MMWS}_{ATE,z=0}  = \frac{n_s}{n_{z,s}} \times \text{pr}(Z = 0) \text{ .}
\]</span></p>
<p>We can also think of this as a single ratio, with the numerator representing the expected <em>n</em>-size of the treatment-group condition in the stratum and the denominator representing its corresponding observed <em>n</em>-size.</p>
<p><span class="math display" id="eq:MMWSATEEq">\[\begin{equation}
\text{MMWS}_{ATE}  = \frac{n_s \times \text{pr}(Z = z)}{n_{z,s}}
 \tag{12.1}
\end{equation}\]</span></p>
</div>
<div id="att-mmws-equation" class="section level4" number="12.1.4.2">
<h4><span class="header-section-number">12.1.4.2</span> ATT MMWS equation</h4>
<p>For research questions investigating the ATT, the MMWS is 1 for the treated condition. For the untreated condition, is</p>
<p><span class="math display" id="eq:MMWSATTEq">\[\begin{equation}
\text{MMWS}_{ATT,z=0}  = \frac{n_{z=1,s} \times \text{pr}(Z = 0)}{n_{z=0,s} \times \text{pr}(Z = 1) }\text{ ,}
 \tag{12.2}
\end{equation}\]</span></p>
<p>which we can further simplify to
<span class="math display">\[\text{MMWS}_{ATT,z=0}  = \frac{n_{z = 1,s}}{n_{z=0,s}} \times \frac{n_{z=0}}{n_{z=1}} \text{ .}\]</span>
Let’s think about this equation. With the ATT, our treated cases are our interest. But, we need to get a good counterfactual before we can get an unbiased estimate of the effect of the treatment on the treated. One way to think about the equation for the ATT weighting on the untreated is to consider that <span class="math inline">\(\frac{n_{z=1,s}}{n_{z=0,s}}\)</span> is a simplification of the ratio of the observed proportions of treated and untreated cases in the stratum:
<span class="math display">\[\frac{\text{pr}(z = 1)_s}{\text{pr}(z = 0)_s} = \frac{\frac{n_{z=1,s}}{n_{s}}}{\frac{n_{z=0,s}}{n_{s}}} = \frac{n_{z=1,s}}{n_{z=0,s}}\]</span>
For example, if there are many fewer treated than untreated cases in this stratum, this is a small number (as we see with Stratum 1 in our data, with 35 treated and 1100 untreated cases). However, this ratio may reflect the same proportion of treated-to-untreated cases in our total sample. If that’s the case, then the adjustment that we multiply this by, as in
<span class="math display">\[\frac{\text{pr}(z = 1)_s}{\text{pr}(z = 0)_s} \times \frac{\text{pr}(z = 0)} {\text{pr}(z = 1)} \text{ ,}\]</span>
will result in a weight of <span class="math inline">\(1\)</span> for this stratum’s untreated cases. This would make sense because the proportion in the stratum is the same as that across all the strata. However, if our stratum’s low treated-to-untreated proportion is much lower than that of our total sample, our adjustment down-weights the untreated cases in this stratum to account for this stratum’s weirdness (which is what we have to do with our first stratum in this data set).</p>
</div>
<div id="mmws-for-the-ate" class="section level4" number="12.1.4.3">
<h4><span class="header-section-number">12.1.4.3</span> MMWS for the ATE</h4>
<p>Let’s calculate the MMWSs for the ATE. For this, we will use Base R’s <code>table()</code> function. First, we get the <em>n</em>-sizes of the two factors—the stratification variable, <code>strat5</code>, and the treatment variable, <code>catholic</code>—as well as the observed cell size of each treatment condition in each stratum, <code>obs_n_s</code>, which is the denominator in our ATE equation, Equation <a href="PScore3.html#eq:MMWSATEEq">(12.1)</a>.</p>
<div class="sourceCode" id="cb1089"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1089-1"><a href="PScore3.html#cb1089-1" aria-hidden="true" tabindex="-1"></a>n_s <span class="ot">&lt;-</span> <span class="fu">table</span>(ca<span class="sc">$</span>strat5)   <span class="co"># n per stratum</span></span>
<span id="cb1089-2"><a href="PScore3.html#cb1089-2" aria-hidden="true" tabindex="-1"></a>n_t <span class="ot">&lt;-</span> <span class="fu">table</span>(ca<span class="sc">$</span>catholic) <span class="co"># n per treatment condition</span></span>
<span id="cb1089-3"><a href="PScore3.html#cb1089-3" aria-hidden="true" tabindex="-1"></a>obs_n_s <span class="ot">&lt;-</span> <span class="fu">with</span>(ca, <span class="fu">table</span>(catholic, strat5)) <span class="co"># Observed n per treatment condition in each stratum</span></span></code></pre></div>
<p>The <code>prop.table()</code> is our friend for calculating the proportions; <code>exp_props</code> is the expected proportion per group in each stratum, which is the same as marginal probability. <code>exp_prop_0</code> and <code>exp_prop_1</code> are the expected proportions for the untreated and treated groups, respectively. From this, we can get the numerator in our ATE equation, Equation <a href="PScore3.html#eq:MMWSATEEq">(12.1)</a>.</p>
<div class="sourceCode" id="cb1090"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1090-1"><a href="PScore3.html#cb1090-1" aria-hidden="true" tabindex="-1"></a>exp_props  <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(n_t) <span class="co"># </span></span>
<span id="cb1090-2"><a href="PScore3.html#cb1090-2" aria-hidden="true" tabindex="-1"></a>exp_prop_0 <span class="ot">&lt;-</span> exp_props[<span class="dv">1</span>]</span>
<span id="cb1090-3"><a href="PScore3.html#cb1090-3" aria-hidden="true" tabindex="-1"></a>exp_prop_1 <span class="ot">&lt;-</span> exp_props[<span class="dv">2</span>] </span>
<span id="cb1090-4"><a href="PScore3.html#cb1090-4" aria-hidden="true" tabindex="-1"></a>exp_n_s    <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="at">no =</span> (exp_prop_0 <span class="sc">*</span> n_s), <span class="co"># &quot;no&quot;  is factor label of untreated grp in each strat</span></span>
<span id="cb1090-5"><a href="PScore3.html#cb1090-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">yes=</span> (exp_prop_1 <span class="sc">*</span> n_s)) <span class="co"># &quot;yes&quot; is factor label of treated   grp in each strat</span></span></code></pre></div>
<p>The MMSW is the ratio of the expected to observed <em>n</em>-size per cell.</p>
<div class="sourceCode" id="cb1091"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1091-1"><a href="PScore3.html#cb1091-1" aria-hidden="true" tabindex="-1"></a>(wts_ATE <span class="ot">&lt;-</span> exp_n_s <span class="sc">/</span> obs_n_s)</span></code></pre></div>
<pre><code>##             1         2         3         4         5
## no  0.9241059 0.9635872 0.9986439 1.0502801 1.0792996
## yes 3.3852432 1.4797390 1.0117874 0.7088570 0.6133633</code></pre>
<p>We see that the treated cases in the first stratum have much more weight compared to their counterparts in the untreated group. We see the reverse pattern in stratum 5.</p>
<p>Let’s merge these weights with the data. This requires a little data wrangling. We need to create a data frame that has the same variable names, <code>catholic</code> and <code>strat5</code>, and be sure the variables are the same types in this small MMWS data frame and our full data set. We also need to be sure the factors have exactly the same factor levels. These operate as keys when we merge this small data set with the large one so that each observation has the correct weight.</p>
<p>Let’s change our table object, <code>wts_ATE</code> into a data frame:</p>
<div class="sourceCode" id="cb1093"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1093-1"><a href="PScore3.html#cb1093-1" aria-hidden="true" tabindex="-1"></a>MMWS_ATE <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(wts_ATE)</span>
<span id="cb1093-2"><a href="PScore3.html#cb1093-2" aria-hidden="true" tabindex="-1"></a>MMWS_ATE</span></code></pre></div>
<pre><code>##    Var1 Var2      Freq
## 1    no    1 0.9241059
## 2   yes    1 3.3852432
## 3    no    2 0.9635872
## 4   yes    2 1.4797390
## 5    no    3 0.9986439
## 6   yes    3 1.0117874
## 7    no    4 1.0502801
## 8   yes    4 0.7088570
## 9    no    5 1.0792996
## 10  yes    5 0.6133633</code></pre>
<p>Notice that <code>Var1</code> corresponds with our treatment group variable,; <code>Var2</code> with our stratum variable, and <code>Freq</code> with our weight.<a href="#fn72" class="footnote-ref" id="fnref72"><sup>72</sup></a> Let’s rename these so that the first two are the same as in our data:</p>
<div class="sourceCode" id="cb1095"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1095-1"><a href="PScore3.html#cb1095-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(MMWS_ATE) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;catholic&quot;</span>, <span class="st">&quot;strat5&quot;</span>, <span class="st">&quot;MMWS_ATE&quot;</span>)</span></code></pre></div>
<p>We need to make sure our two variables <code>catholic</code> and <code>strat5</code> are the same type as those in our data set:</p>
<div class="sourceCode" id="cb1096"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1096-1"><a href="PScore3.html#cb1096-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(MMWS_ATE)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    10 obs. of  3 variables:
##  $ catholic: Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 1 2 1 2 1 2 1 2 1 2
##  $ strat5  : Factor w/ 5 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 1 1 2 2 3 3 4 4 5 5
##  $ MMWS_ATE: num  0.924 3.385 0.964 1.48 0.999 ...</code></pre>
<div class="sourceCode" id="cb1098"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1098-1"><a href="PScore3.html#cb1098-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ca[, <span class="fu">c</span>(<span class="st">&quot;catholic&quot;</span>, <span class="st">&quot;strat5&quot;</span>)])</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    5671 obs. of  2 variables:
##  $ catholic: Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 2 2 2 2 2 2 2 2 2 2 ...
##  $ strat5  : Factor w/ 5 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 2 3 3 2 3 2 3 3 4 1 ...</code></pre>
<p>The seem to be. We could also use the <code>levels()</code> function each variable in both data sets if we wanted to be more thorough.</p>
<p>Let’s use the <code>left_join()</code> function from the dplyr package to merge the data.<a href="#fn73" class="footnote-ref" id="fnref73"><sup>73</sup></a> By including our large data set first, <code>ca</code>, we are ensuring that all observations in that data set are retained. The <code>MMWS_ATE</code> merges with that data set based on our two shared variables, <code>catholic</code> and <code>strat5</code>, so what gets added is the <code>MMWS_ATE</code> variable. For instance, each observation in our <code>ca</code> data frame that is in the treated condition (<code>catholic = yes</code>) in the first stratum (<code>strat5 = 1</code>) will have the weight 3.385.</p>
<div class="sourceCode" id="cb1100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1100-1"><a href="PScore3.html#cb1100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1100-2"><a href="PScore3.html#cb1100-2" aria-hidden="true" tabindex="-1"></a>ca <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(ca, MMWS_ATE)</span></code></pre></div>
<p>Let’s take a look at the weights per treatment condition in each stratum to verify these are what we expect. Here, we’re using functions from the dplyr package (in tidyverse).<a href="#fn74" class="footnote-ref" id="fnref74"><sup>74</sup></a> The <code>select()</code> function is a way to restrict our analysis to the specified columns. Here, we’re keeping it simple and examining only three variables. The <code>arrange()</code> function orders the data from low to high, first by <code>strat5</code>, then by <code>catholic</code> in our code. The <code>unique()</code> function (which is part of Base R) returns only those rows that are unique in any combination of variables. This is why we restricted our examination using the <code>select()</code> function. The <code>data.frame()</code> function is an optional preference for viewing the output.</p>
<div class="sourceCode" id="cb1101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1101-1"><a href="PScore3.html#cb1101-1" aria-hidden="true" tabindex="-1"></a>ca <span class="sc">%&gt;%</span> <span class="fu">select</span>(catholic, strat5, MMWS_ATE) <span class="sc">%&gt;%</span> </span>
<span id="cb1101-2"><a href="PScore3.html#cb1101-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">arrange</span>(strat5, catholic) <span class="sc">%&gt;%</span> </span>
<span id="cb1101-3"><a href="PScore3.html#cb1101-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">unique</span>() <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>(<span class="at">row.names =</span> <span class="cn">NULL</span>)</span></code></pre></div>
<pre><code>##    catholic strat5  MMWS_ATE
## 1        no      1 0.9241059
## 2       yes      1 3.3852432
## 3        no      2 0.9635872
## 4       yes      2 1.4797390
## 5        no      3 0.9986439
## 6       yes      3 1.0117874
## 7        no      4 1.0502801
## 8       yes      4 0.7088570
## 9        no      5 1.0792996
## 10      yes      5 0.6133633</code></pre>
<p>We see that the result is similar to our object, <code>wts_ATE</code>, which we had earlier calculated and saved as an independent object.</p>
<div class="sourceCode" id="cb1103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1103-1"><a href="PScore3.html#cb1103-1" aria-hidden="true" tabindex="-1"></a>wts_ATE</span></code></pre></div>
<pre><code>##             1         2         3         4         5
## no  0.9241059 0.9635872 0.9986439 1.0502801 1.0792996
## yes 3.3852432 1.4797390 1.0117874 0.7088570 0.6133633</code></pre>
<p>These ATE MMWSs take the observed <em>n</em>-size in each treatment group, in each stratum, and weight the observations to reflect the expected <em>n</em>-size. For instance, the treatment condition in stratum 1 (catholic = yes) is under-represented if we consider that about 10.4% of the total sample is in this condition; this proportion of the stratum’s <em>n</em>-size yields an expected <em>n</em> of 118. With our MMWS, each of these 35 observations is weighted by 3.39 times more so that they represent 118 people when we estimate the ATE.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-596">Table 12.1: </span>MMWS weights from expected and observed cell sizes
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Expected proportion
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Expected <em>n</em>
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Observed <em>n</em>
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
MMWS (ATE)
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Stratum
</th>
<th style="text-align:right;">
Publ
</th>
<th style="text-align:right;">
Cath
</th>
<th style="text-align:right;">
Publ
</th>
<th style="text-align:right;">
Cath
</th>
<th style="text-align:right;">
Publ
</th>
<th style="text-align:right;">
Cath
</th>
<th style="text-align:right;">
Publ
</th>
<th style="text-align:right;">
Cath
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
0.896
</td>
<td style="text-align:right;">
0.104
</td>
<td style="text-align:right;">
1016.52
</td>
<td style="text-align:right;">
118.48
</td>
<td style="text-align:right;">
1100
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:right;">
3.39
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
0.896
</td>
<td style="text-align:right;">
0.104
</td>
<td style="text-align:right;">
1015.62
</td>
<td style="text-align:right;">
118.38
</td>
<td style="text-align:right;">
1054
</td>
<td style="text-align:right;">
80
</td>
<td style="text-align:right;">
0.96
</td>
<td style="text-align:right;">
1.48
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
0.896
</td>
<td style="text-align:right;">
0.104
</td>
<td style="text-align:right;">
1015.62
</td>
<td style="text-align:right;">
118.38
</td>
<td style="text-align:right;">
1017
</td>
<td style="text-align:right;">
117
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
1.01
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:right;">
0.896
</td>
<td style="text-align:right;">
0.104
</td>
<td style="text-align:right;">
1015.62
</td>
<td style="text-align:right;">
118.38
</td>
<td style="text-align:right;">
967
</td>
<td style="text-align:right;">
167
</td>
<td style="text-align:right;">
1.05
</td>
<td style="text-align:right;">
0.71
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:right;">
0.896
</td>
<td style="text-align:right;">
0.104
</td>
<td style="text-align:right;">
1015.62
</td>
<td style="text-align:right;">
118.38
</td>
<td style="text-align:right;">
941
</td>
<td style="text-align:right;">
193
</td>
<td style="text-align:right;">
1.08
</td>
<td style="text-align:right;">
0.61
</td>
</tr>
</tbody>
</table>
</div>
<div id="mmws-for-the-att" class="section level4" number="12.1.4.4">
<h4><span class="header-section-number">12.1.4.4</span> MMWS for the ATT</h4>
<p>If our research question were about the ATT, we would do something similar. We could use the strata that we defined above with the propensity scores of the entire sample. Instead, let’s define the strata based on the propensity scores of the cases in the <em><em>treated</em></em> condition. This ensures that each stratum has about the same number of treated cases. After that, let’s use the MMWS equation and connect the weights to the data.</p>
<div id="create-the-strata-based-on-att-quintiles" class="section level5" number="12.1.4.4.1">
<h5><span class="header-section-number">12.1.4.4.1</span> Create the strata based on ATT quintiles</h5>
<p>To get the quintiles based on the treated group, we can subset the data and use the <code>quantiles()</code> function we used before (which previously was part of our <code>cut()</code> function):</p>
<div class="sourceCode" id="cb1105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1105-1"><a href="PScore3.html#cb1105-1" aria-hidden="true" tabindex="-1"></a>strat5_ATT <span class="ot">&lt;-</span> <span class="fu">quantile</span>(<span class="fu">subset</span>(ca, catholic <span class="sc">==</span> <span class="st">&quot;yes&quot;</span>)<span class="sc">$</span>ps, <span class="co"># treated group only</span></span>
<span id="cb1105-2"><a href="PScore3.html#cb1105-2" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> .<span class="dv">2</span>))</span>
<span id="cb1105-3"><a href="PScore3.html#cb1105-3" aria-hidden="true" tabindex="-1"></a>strat5_ATT</span></code></pre></div>
<pre><code>##          0%         20%         40%         60%         80%        100% 
## 0.009990315 0.089461609 0.121409721 0.145534449 0.172387157 0.246263734</code></pre>
<p>To avoid excluding non-treated cases with <span class="math inline">\(\hat{e}(x_i) &lt; 0.0099903\)</span> or <span class="math inline">\(\hat{e}(x_i) &gt; 0.2462637\)</span>, we can replace these with <code>0</code> and <code>1</code> or with the minimum and maximum of the propensity scores in the total data set:</p>
<div class="sourceCode" id="cb1107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1107-1"><a href="PScore3.html#cb1107-1" aria-hidden="true" tabindex="-1"></a>strat5_ATT[<span class="fu">c</span>(<span class="dv">1</span>, <span class="fu">length</span>(strat5_ATT))] <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">min</span>(ca<span class="sc">$</span>ps), <span class="fu">max</span>(ca<span class="sc">$</span>ps))</span>
<span id="cb1107-2"><a href="PScore3.html#cb1107-2" aria-hidden="true" tabindex="-1"></a>strat5_ATT</span></code></pre></div>
<pre><code>##          0%         20%         40%         60%         80%        100% 
## 0.002595558 0.089461609 0.121409721 0.145534449 0.172387157 0.262511031</code></pre>
<p>We can now assign cases to the strata based on these breaks of the five quintiles. To do this, we can use the <code>findInterval()</code> function with the full data:</p>
<div class="sourceCode" id="cb1109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1109-1"><a href="PScore3.html#cb1109-1" aria-hidden="true" tabindex="-1"></a>ca<span class="sc">$</span>strat5_ATT <span class="ot">&lt;-</span> <span class="fu">findInterval</span>(ca<span class="sc">$</span>ps, strat5_ATT, <span class="at">rightmost.closed =</span> <span class="cn">TRUE</span>, <span class="at">left.open =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>We need to make the stratification variable a factor:</p>
<div class="sourceCode" id="cb1110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1110-1"><a href="PScore3.html#cb1110-1" aria-hidden="true" tabindex="-1"></a>ca<span class="sc">$</span>strat5_ATT <span class="ot">&lt;-</span> <span class="fu">factor</span>(ca<span class="sc">$</span>strat5_ATT)</span></code></pre></div>
<p>Out of curiosity, we might wish to see how many treated cases are in each stratum.</p>
<div class="sourceCode" id="cb1111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1111-1"><a href="PScore3.html#cb1111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(<span class="fu">subset</span>(ca, catholic <span class="sc">==</span> <span class="st">&quot;yes&quot;</span>), <span class="fu">table</span>(strat5_ATT))</span></code></pre></div>
<pre><code>## strat5_ATT
##   1   2   3   4   5 
## 119 118 118 118 119</code></pre>
<p>We see roughly the same number of treated cases across the strata.</p>
<p>We may also examine a crosstab of these strata and those used for the ATE:</p>
<div class="sourceCode" id="cb1113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1113-1"><a href="PScore3.html#cb1113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(ca, <span class="fu">table</span>(strat5, strat5_ATT))</span></code></pre></div>
<pre><code>##       strat5_ATT
## strat5    1    2    3    4    5
##      1 1135    0    0    0    0
##      2 1134    0    0    0    0
##      3   48 1086    0    0    0
##      4    0   48  820  266    0
##      5    0    0    0  468  666</code></pre>
<p>We can see that the lowest stratum has a lot more cases compared to the stratification based on the entire sample. We can see this with the by-group histogram (from our custom <code>overlap()</code> function), too:</p>
<div class="sourceCode" id="cb1115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1115-1"><a href="PScore3.html#cb1115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(ca, <span class="fu">overlap</span>(ps, catholic, </span>
<span id="cb1115-2"><a href="PScore3.html#cb1115-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bin=</span><span class="dv">30</span>, </span>
<span id="cb1115-3"><a href="PScore3.html#cb1115-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">&quot;Propensity scores by ATT-defined strata&quot;</span>,</span>
<span id="cb1115-4"><a href="PScore3.html#cb1115-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">xlab  =</span> <span class="st">&quot;PS&quot;</span>))</span>
<span id="cb1115-5"><a href="PScore3.html#cb1115-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> strat5_ATT, <span class="at">col =</span> <span class="st">&#39;brown&#39;</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-604-1.png" width="672" /></p>
<p>For the MMWS Weights for ATT, the weight is 1 for the treated group and uses Equation <a href="PScore3.html#eq:MMWSATTEq">(12.2)</a> for the untreated group. We need to use the <em>n</em>-size of the untreated and treated groups per stratum in separate parts of the equation. We can take those from the <code>obs_n_s</code> object but first we should make sure our <em>n</em>-sizes per stratum are now based on the ATT strata. The code right here is copied from the previous code, but we have replaced <code>strat5_ATT</code> with <code>strat5_ATT</code> to get the <code>n_s</code> and <code>obs_n_s</code>.</p>
<div class="sourceCode" id="cb1116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1116-1"><a href="PScore3.html#cb1116-1" aria-hidden="true" tabindex="-1"></a>n_s <span class="ot">&lt;-</span> <span class="fu">table</span>(ca<span class="sc">$</span>strat5_ATT)   <span class="co"># n per ATT-defined stratum</span></span>
<span id="cb1116-2"><a href="PScore3.html#cb1116-2" aria-hidden="true" tabindex="-1"></a>n_t <span class="ot">&lt;-</span> <span class="fu">table</span>(ca<span class="sc">$</span>catholic)     <span class="co"># n per treatment condition</span></span>
<span id="cb1116-3"><a href="PScore3.html#cb1116-3" aria-hidden="true" tabindex="-1"></a>obs_n_s <span class="ot">&lt;-</span> <span class="fu">with</span>(ca, <span class="fu">table</span>(catholic, strat5_ATT)) <span class="co"># cell size (treatment &amp; ATT-defined stratum)</span></span>
<span id="cb1116-4"><a href="PScore3.html#cb1116-4" aria-hidden="true" tabindex="-1"></a>n_0s <span class="ot">&lt;-</span> obs_n_s[<span class="dv">1</span>,] <span class="co"># n-size of untreated group per stratum</span></span>
<span id="cb1116-5"><a href="PScore3.html#cb1116-5" aria-hidden="true" tabindex="-1"></a>n_1s <span class="ot">&lt;-</span> obs_n_s[<span class="dv">2</span>,] <span class="co"># n-size of treated group per stratum</span></span></code></pre></div>
<p>Let’s plug the <code>n_0s</code> and <code>n_1s</code> into the equation for the untreated group, where <span class="math inline">\(z = 0\)</span>.</p>
<div class="sourceCode" id="cb1117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1117-1"><a href="PScore3.html#cb1117-1" aria-hidden="true" tabindex="-1"></a>MMWS_ATT_0 <span class="ot">&lt;-</span> (n_1s <span class="sc">*</span> exp_prop_0 ) <span class="sc">/</span> (n_0s <span class="sc">*</span> exp_prop_1)</span></code></pre></div>
<p>For the treated group, we can replicate a series of <span class="math inline">\(1\)</span>s for the same number of strata that are in the treatment group. (We could have just as easily written <code>rep(1, 5)</code> or <code>c(1,1,1,1,1)</code>. We juxtapose these weights per condition and stratum with the <code>rbind()</code> function, which is just for examining the result of our calculations per stratum.</p>
<div class="sourceCode" id="cb1118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1118-1"><a href="PScore3.html#cb1118-1" aria-hidden="true" tabindex="-1"></a>MMWS_ATT_1 <span class="ot">&lt;-</span>  <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">length</span>(MMWS_ATT_0))</span>
<span id="cb1118-2"><a href="PScore3.html#cb1118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(MMWS_ATT_0, MMWS_ATT_1)</span></code></pre></div>
<pre><code>##                    1         2       3        4        5
## MMWS_ATT_0 0.4644894 0.9964254 1.44212 1.643455 1.866449
## MMWS_ATT_1 1.0000000 1.0000000 1.00000 1.000000 1.000000</code></pre>
<p>We see that in the lowest stratum, the untreated cases are weighted very low, less than half of that of their treated counterparts. Those in the highest stratum have higher weights.</p>
<p>If we plan on merging these with the data, we should create a data frame. Notice that the <code>rep()</code> function uses <code>each =</code> for our <code>catholic</code> variable but <code>times =</code> for our <code>strat5</code> variable. If we monkey around with those, we can see how things can go wrong. We want to be sure these two factors correctly line up with the weights.</p>
<div class="sourceCode" id="cb1120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1120-1"><a href="PScore3.html#cb1120-1" aria-hidden="true" tabindex="-1"></a>MMWS_ATT <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">catholic =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;no&quot;</span>,<span class="st">&quot;yes&quot;</span>), <span class="at">each =</span> <span class="fu">length</span>(MMWS_ATT_0)),</span>
<span id="cb1120-2"><a href="PScore3.html#cb1120-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">strat5_ATT =</span> <span class="fu">rep</span>(<span class="fu">names</span>(MMWS_ATT_0), <span class="at">times =</span> <span class="dv">2</span>),</span>
<span id="cb1120-3"><a href="PScore3.html#cb1120-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">MMWS_ATT =</span> <span class="fu">c</span>( MMWS_ATT_0, MMWS_ATT_1)  )</span>
<span id="cb1120-4"><a href="PScore3.html#cb1120-4" aria-hidden="true" tabindex="-1"></a>MMWS_ATT</span></code></pre></div>
<pre><code>##    catholic strat5_ATT  MMWS_ATT
## 1        no          1 0.4644894
## 2        no          2 0.9964254
## 3        no          3 1.4421200
## 4        no          4 1.6434549
## 5        no          5 1.8664491
## 6       yes          1 1.0000000
## 7       yes          2 1.0000000
## 8       yes          3 1.0000000
## 9       yes          4 1.0000000
## 10      yes          5 1.0000000</code></pre>
<p>If we look at the structure, we see we need to change these two key variables into factors:</p>
<div class="sourceCode" id="cb1122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1122-1"><a href="PScore3.html#cb1122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(MMWS_ATT)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    10 obs. of  3 variables:
##  $ catholic  : chr  &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ strat5_ATT: chr  &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
##  $ MMWS_ATT  : num  0.464 0.996 1.442 1.643 1.866 ...</code></pre>
<div class="sourceCode" id="cb1124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1124-1"><a href="PScore3.html#cb1124-1" aria-hidden="true" tabindex="-1"></a>MMWS_ATT<span class="sc">$</span>catholic <span class="ot">&lt;-</span> <span class="fu">factor</span>(MMWS_ATT<span class="sc">$</span>catholic)</span>
<span id="cb1124-2"><a href="PScore3.html#cb1124-2" aria-hidden="true" tabindex="-1"></a>MMWS_ATT<span class="sc">$</span>strat5_ATT   <span class="ot">&lt;-</span> <span class="fu">factor</span>(MMWS_ATT<span class="sc">$</span>strat5_ATT)</span>
<span id="cb1124-3"><a href="PScore3.html#cb1124-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(MMWS_ATT)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    10 obs. of  3 variables:
##  $ catholic  : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 1 1 1 1 1 2 2 2 2 2
##  $ strat5_ATT: Factor w/ 5 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 1 2 3 4 5 1 2 3 4 5
##  $ MMWS_ATT  : num  0.464 0.996 1.442 1.643 1.866 ...</code></pre>
<div class="sourceCode" id="cb1126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1126-1"><a href="PScore3.html#cb1126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1126-2"><a href="PScore3.html#cb1126-2" aria-hidden="true" tabindex="-1"></a>ca <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(ca, MMWS_ATT)</span>
<span id="cb1126-3"><a href="PScore3.html#cb1126-3" aria-hidden="true" tabindex="-1"></a>ca <span class="sc">%&gt;%</span> <span class="fu">select</span>(catholic, strat5_ATT, MMWS_ATT) <span class="sc">%&gt;%</span> </span>
<span id="cb1126-4"><a href="PScore3.html#cb1126-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">arrange</span>(strat5_ATT, catholic) <span class="sc">%&gt;%</span> </span>
<span id="cb1126-5"><a href="PScore3.html#cb1126-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">unique</span>() <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>(<span class="at">row.names =</span> <span class="cn">NULL</span>)</span></code></pre></div>
<pre><code>##    catholic strat5_ATT  MMWS_ATT
## 1        no          1 0.4644894
## 2       yes          1 1.0000000
## 3        no          2 0.9964254
## 4       yes          2 1.0000000
## 5        no          3 1.4421200
## 6       yes          3 1.0000000
## 7        no          4 1.6434549
## 8       yes          4 1.0000000
## 9        no          5 1.8664491
## 10      yes          5 1.0000000</code></pre>
<p>We have successfully calculated the weights and connected them to the data frame.</p>
</div>
</div>
</div>
</div>
<div id="conduct-balance-checks-after-weighting-1" class="section level2" number="12.2">
<h2><span class="header-section-number">12.2</span> Conduct balance checks after weighting</h2>
<p>For the code to investigate the balance checks and overlap, we will use the variable <code>MMWS</code> in case we want to switch it and examine the ATT. Here, we’ll use the ATE:</p>
<div class="sourceCode" id="cb1128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1128-1"><a href="PScore3.html#cb1128-1" aria-hidden="true" tabindex="-1"></a>ca<span class="sc">$</span>MMWS <span class="ot">&lt;-</span> ca<span class="sc">$</span>MMWS_ATE <span class="co"># change to ca$MMWS_ATT to examine the ATT.</span></span></code></pre></div>
<p>Let’s use our <code>wselect.diff()</code> to examine the imbalance statistics in the covariates after we have weighted the observations.</p>
<div class="sourceCode" id="cb1129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1129-1"><a href="PScore3.html#cb1129-1" aria-hidden="true" tabindex="-1"></a>imbal_adj <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">sapply</span>(ca[, covnames], </span>
<span id="cb1129-2"><a href="PScore3.html#cb1129-2" aria-hidden="true" tabindex="-1"></a>                      wselect.diff, <span class="at">grp =</span> ca<span class="sc">$</span>catholic, <span class="at">wt =</span> ca<span class="sc">$</span>MMWS))</span>
<span id="cb1129-3"><a href="PScore3.html#cb1129-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(imbal_adj,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##           Mean.Diff Std.Error p-value Std.Mean.Diff Var.Ratio
## inc8          0.512     0.753   0.496         0.029     1.019
## inc8Sq       38.604    54.467   0.479         0.031     1.027
## math8         0.398     0.421   0.344         0.043     0.821
## mathfam      30.848    45.340   0.496         0.030     0.998
## fhowfarN      0.053     0.048   0.271         0.049     0.867
## mhowfarN      0.047     0.046   0.316         0.046     0.790
## fight8N      -0.018     0.022   0.406        -0.036     0.955
## nohw8N       -0.017     0.015   0.254        -0.051     0.900
## disrupt8N    -0.017     0.017   0.295        -0.046     0.924
## riskdrop8    -0.074     0.039   0.056        -0.089     0.683</code></pre>
<p>We have achieved pretty good balance. The IPWs balance the distributions of the observed covariates pretty well. There are two covariates with borderline imbalance in their variance ratios, but this may be acceptable.</p>
<div class="sourceCode" id="cb1131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1131-1"><a href="PScore3.html#cb1131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">imbal_plotter</span>(imbal_adj, <span class="at">subtitle =</span> <span class="st">&quot;(MMWS for the ATE)&quot;</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-614-1.png" width="672" /></p>
<p>It seems like our IPW approach in the previous lesson did a better job of balancing on the covariates.</p>
<p>Let’s check the overlap using density plots for each covariate. The vertical lines also show the balance in the mean on the covariate for each group.</p>
<div class="sourceCode" id="cb1132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1132-1"><a href="PScore3.html#cb1132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnsty_plotter</span>(ca, covnames, <span class="at">grp =</span> ca<span class="sc">$</span>catholic, </span>
<span id="cb1132-2"><a href="PScore3.html#cb1132-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">wt =</span> ca<span class="sc">$</span>MMWS, </span>
<span id="cb1132-3"><a href="PScore3.html#cb1132-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">subtitle =</span> <span class="st">&quot;(after MMWS adjustment for the ATE)&quot;</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-615-1.png" width="672" /><img src="QEDs-in-R_files/figure-html/unnamed-chunk-615-2.png" width="672" /><img src="QEDs-in-R_files/figure-html/unnamed-chunk-615-3.png" width="672" /></p>
<p>We can check the balance and overlap of the (logit of the) propensity score estimates:</p>
<div class="sourceCode" id="cb1133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1133-1"><a href="PScore3.html#cb1133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnsty</span>(ca<span class="sc">$</span>ps, ca<span class="sc">$</span>catholic, </span>
<span id="cb1133-2"><a href="PScore3.html#cb1133-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">&quot;PS (unadjusted)&quot;</span>, </span>
<span id="cb1133-3"><a href="PScore3.html#cb1133-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">legtitle=</span><span class="st">&quot;Catholic&quot;</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-616-1.png" width="672" /></p>
<div class="sourceCode" id="cb1134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1134-1"><a href="PScore3.html#cb1134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnsty</span>(ca<span class="sc">$</span>ps, ca<span class="sc">$</span>catholic, </span>
<span id="cb1134-2"><a href="PScore3.html#cb1134-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">wt =</span> ca<span class="sc">$</span>MMWS, </span>
<span id="cb1134-3"><a href="PScore3.html#cb1134-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">&quot;PS after MMWS weights (for ATE)&quot;</span>, </span>
<span id="cb1134-4"><a href="PScore3.html#cb1134-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">legtitle=</span><span class="st">&quot;Catholic&quot;</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-616-2.png" width="672" /></p>
<p>The MMWS does improve common support but maybe not as well as the IPW did in our last lesson.</p>
</div>
<div id="estimate-the-ate" class="section level2" number="12.3">
<h2><span class="header-section-number">12.3</span> Estimate the ATE</h2>
<p>As we did in the previous lesson, we estimated the propensity scores, calculated the weights, and examined the functioning of our weighting with a data set that excluded our outcome variables. Let’s attach them to our data set and estimate the effect. Again, we are using the survey package <span class="citation">(<a href="#ref-R-survey" role="doc-biblioref">Lumley, 2021</a>)</span>.</p>
<div class="sourceCode" id="cb1135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1135-1"><a href="PScore3.html#cb1135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1135-2"><a href="PScore3.html#cb1135-2" aria-hidden="true" tabindex="-1"></a>outcome <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;ch12_cath_outcomes_only.csv&quot;</span>)</span>
<span id="cb1135-3"><a href="PScore3.html#cb1135-3" aria-hidden="true" tabindex="-1"></a>ca2     <span class="ot">&lt;-</span> <span class="fu">left_join</span>(ca, outcome, <span class="at">by =</span> <span class="st">&quot;id&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb1136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1136-1"><a href="PScore3.html#cb1136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey)</span>
<span id="cb1136-2"><a href="PScore3.html#cb1136-2" aria-hidden="true" tabindex="-1"></a>sdesign_MMWS_ATE <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">ids =</span> <span class="sc">~</span><span class="dv">1</span>, <span class="at">weights =</span> <span class="sc">~</span>MMWS_ATE, <span class="at">data =</span> ca2)</span>
<span id="cb1136-3"><a href="PScore3.html#cb1136-3" aria-hidden="true" tabindex="-1"></a>fit_MMWS_ATE     <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(math12 <span class="sc">~</span> catholic, <span class="at">design =</span> sdesign_MMWS_ATE)</span>
<span id="cb1136-4"><a href="PScore3.html#cb1136-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_MMWS_ATE)</span></code></pre></div>
<pre><code>## 
## Call:
## svyglm(formula = ..1, design = ..2)
## 
## Survey design:
## survey::svydesign(...)
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  50.8987     0.1339  380.22  &lt; 2e-16 ***
## catholicyes   1.8103     0.4715    3.84 0.000125 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 89.46427)
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<div class="sourceCode" id="cb1138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1138-1"><a href="PScore3.html#cb1138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(fit_MMWS_ATE)</span></code></pre></div>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) 50.636263 51.161126
## catholicyes  0.885994  2.734606</code></pre>
<p>Compared to our inverse-propensity weight approach, we see a slightly higher effect being estimated. The statistical conclusion is the same.</p>
<p>If we had already conducted the balance checks and overlap with the ATT weighting, we could estimate the ATT effect.</p>
<div class="sourceCode" id="cb1140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1140-1"><a href="PScore3.html#cb1140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey)</span>
<span id="cb1140-2"><a href="PScore3.html#cb1140-2" aria-hidden="true" tabindex="-1"></a>sdesign_MMWS_ATT <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">ids =</span> <span class="sc">~</span><span class="dv">1</span>, <span class="at">weights =</span> <span class="sc">~</span>MMWS_ATT, <span class="at">data =</span> ca2)</span>
<span id="cb1140-3"><a href="PScore3.html#cb1140-3" aria-hidden="true" tabindex="-1"></a>fit_MMWS_ATT     <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(math12 <span class="sc">~</span> catholic, <span class="at">design =</span> sdesign_MMWS_ATT)</span>
<span id="cb1140-4"><a href="PScore3.html#cb1140-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_MMWS_ATT)</span></code></pre></div>
<pre><code>## 
## Call:
## svyglm(formula = ..1, design = ..2)
## 
## Survey design:
## survey::svydesign(...)
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  52.9288     0.1441 367.207  &lt; 2e-16 ***
## catholicyes   1.6107     0.3763   4.281 1.89e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 85.36604)
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<div class="sourceCode" id="cb1142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1142-1"><a href="PScore3.html#cb1142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(fit_MMWS_ATT)</span></code></pre></div>
<pre><code>##                  2.5 %    97.5 %
## (Intercept) 52.6461997 53.211334
## catholicyes  0.8731054  2.348381</code></pre>
</div>
<div id="using-the-matchit-package" class="section level2" number="12.4">
<h2><span class="header-section-number">12.4</span> Using the MatchIt Package</h2>
<p>All of that work helps us to understand how MMWS works and how we can estimate effects. Fortunately, we can use packages to conduct these steps with far less code. Let’s use the MatchIt <span class="citation">(<a href="#ref-R-MatchIt" role="doc-biblioref">Ho et al., 2021</a>)</span> package. The following code is based on that provided by <a href="https://cran.r-project.org/web/packages/MatchIt/vignettes/estimating-effects.html#after-stratum-matching" target="_blank">the package’s vignette</a>.</p>
<p>Let’s use the package’s <code>matchit()</code> function. We are using our propensity-score formula, <code>ps_mdl1</code>, which we had created before to include in the <code>glm()</code> function to create our propensity scores. Here, <code>matchit()</code> does the work for us. We specify the estimand as the ATE. For stratification, we use the <code>method = "subclass"</code> argument and specify the number of strata with <code>subclass = 5</code>. Notice that we are using the data set that excludes the outcome variable.</p>
<div class="sourceCode" id="cb1144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1144-1"><a href="PScore3.html#cb1144-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MatchIt)</span>
<span id="cb1144-2"><a href="PScore3.html#cb1144-2" aria-hidden="true" tabindex="-1"></a>mS <span class="ot">&lt;-</span> <span class="fu">matchit</span>(ps_mdl1, </span>
<span id="cb1144-3"><a href="PScore3.html#cb1144-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">estimand =</span> <span class="st">&quot;ATE&quot;</span>,</span>
<span id="cb1144-4"><a href="PScore3.html#cb1144-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">method =</span> <span class="st">&quot;subclass&quot;</span>,</span>
<span id="cb1144-5"><a href="PScore3.html#cb1144-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">subclass =</span> <span class="dv">5</span>,</span>
<span id="cb1144-6"><a href="PScore3.html#cb1144-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> ca)</span>
<span id="cb1144-7"><a href="PScore3.html#cb1144-7" aria-hidden="true" tabindex="-1"></a>mS</span></code></pre></div>
<pre><code>## A matchit object
##  - method: Subclassification (5 subclasses)
##  - distance: Propensity score
##              - estimated with logistic regression
##  - number of obs.: 5671 (original), 5671 (matched)
##  - target estimand: ATE
##  - covariates: inc8, inc8Sq, math8, mathfam, fhowfarN, mhowfarN, fight8N, nohw8N, disrupt8N, riskdrop8</code></pre>
<p>Printing the object helps us to verify the method, the propensity score, the number of observations, the estimand, and the list of covariates.</p>
<div id="examining-balance" class="section level3" number="12.4.1">
<h3><span class="header-section-number">12.4.1</span> Examining Balance</h3>
<p>We can examine the balance statistics with the <code>summary()</code> function on the output from the <code>matchit()</code> function. The rows include the covariates along with the propensity score, which is at the top, labeled as <code>distance</code>.</p>
<div class="sourceCode" id="cb1146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1146-1"><a href="PScore3.html#cb1146-1" aria-hidden="true" tabindex="-1"></a>(bal_mS <span class="ot">&lt;-</span> <span class="fu">summary</span>(mS, <span class="at">standardize =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## 
## Call:
## matchit(formula = ps_mdl1, data = ca, method = &quot;subclass&quot;, estimand = &quot;ATE&quot;, 
##     subclass = 5)
## 
## Summary of Balance for All Data:
##           Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
## distance         0.1311        0.1013          0.6027     0.7459    0.1620
## inc8            39.5346       31.8548          0.4573     0.8886    0.0777
## inc8Sq        1827.9603     1313.3742          0.4038     1.1250    0.0777
## math8           53.6604       51.2365          0.2607     0.8201    0.0751
## mathfam       2146.7122     1679.9225          0.4562     0.9442    0.1343
## fhowfarN         4.1030        3.7850          0.3197     0.5577    0.0530
## mhowfarN         4.1064        3.8293          0.2868     0.5518    0.0462
## fight8N          0.1824        0.2235         -0.0868     0.7380    0.0137
## nohw8N           0.0659        0.1524         -0.2802          .    0.0865
## disrupt8N        0.1622        0.1815         -0.0514          .    0.0194
## riskdrop8        0.3108        0.6602         -0.4530     0.3834    0.0582
##           eCDF Max
## distance    0.2601
## inc8        0.1934
## inc8Sq      0.1934
## math8       0.1550
## mathfam     0.2182
## fhowfarN    0.1082
## mhowfarN    0.1019
## fight8N     0.0217
## nohw8N      0.0865
## disrupt8N   0.0194
## riskdrop8   0.1647
## 
## Summary of Balance Across Subclasses
##           Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
## distance         0.1069        0.1042          0.0553     0.9575    0.0138
## inc8            33.0923       32.5865          0.0301     1.0177    0.0064
## inc8Sq        1399.6377     1361.7856          0.0297     1.0258    0.0064
## math8           51.8829       51.4885          0.0424     0.8201    0.0305
## mathfam       1755.4396     1725.1521          0.0296     0.9963    0.0108
## fhowfarN         3.8679        3.8153          0.0529     0.8664    0.0088
## mhowfarN         3.9023        3.8558          0.0481     0.7900    0.0117
## fight8N          0.2009        0.2190         -0.0383     0.9546    0.0060
## nohw8N           0.1266        0.1439         -0.0562          .    0.0173
## disrupt8N        0.1617        0.1791         -0.0462          .    0.0174
## riskdrop8        0.5519        0.6261         -0.0963     0.6831    0.0145
##           eCDF Max
## distance    0.0472
## inc8        0.0206
## inc8Sq      0.0206
## math8       0.0619
## mathfam     0.0338
## fhowfarN    0.0228
## mhowfarN    0.0287
## fight8N     0.0174
## nohw8N      0.0173
## disrupt8N   0.0174
## riskdrop8   0.0364
## 
## Percent Balance Improvement:
##           Std. Mean Diff. Var. Ratio eCDF Mean eCDF Max
## distance             90.8      -28.4      91.5     81.9
## inc8                 93.4      -14.5      91.7     89.4
## inc8Sq               92.6        8.8      91.7     89.4
## math8                83.7       -0.0      59.5     60.1
## mathfam              93.5       -5.5      91.9     84.5
## fhowfarN             83.5      -55.4      83.5     79.0
## mhowfarN             83.2      -43.2      74.6     71.9
## fight8N              55.8      -29.3      55.8     19.6
## nohw8N               80.0          .      80.0     80.0
## disrupt8N            10.1          .      10.1     10.1
## riskdrop8            78.8      -78.2      75.2     77.9
## 
## Sample Sizes:
##               Control Treated
## All           5079.    592.  
## Matched (ESS) 5062.93  411.28
## Matched       5079.    592.  
## Unmatched        0.      0.  
## Discarded        0.      0.</code></pre>
<!-- I tried to use our custom plot on the output. It works but only if there are no missing values. In this case, there are, which causes the name indexes to get messed up. -->
<!-- ```{r eval = F, echo = F} -->
<!-- bal_to_plot <- data.frame(bal_mS$sum.across[c(2:8), c("Std. Mean Diff.", "Var. Ratio")]) -->
<!-- names(bal_to_plot) <- c("Std.Mean.Diff", "Var.Ratio") -->
<!-- imbal_plotter(bal_to_plot, subtitle = "(after MMWS ATE in MatchIt)") -->
<!-- ``` -->
<p>In that output, we are most interested in the section labeled <code>Summary of Balance Across Subclasses</code>. We can see that the standardized mean differences are below our .10 criterion. The last variance ratios for <code>mhowfarN</code> and <code>riskdrop8</code> seem to be outside of our desired range of .80 to 1.25 (4/5 to 5/4). With these two covariates, even after the stratification adjustment, there is noticeably more variability in the untreated group than there is in the treated group. Two covariates’ variance ratios are not reported. They likely have too few cases in one of the conditional cells. For example, with the <code>nohw8N</code> covariate, there are zero cases in the treatment group in Strata 4 and 5:<a href="#fn75" class="footnote-ref" id="fnref75"><sup>75</sup></a></p>
<div class="sourceCode" id="cb1148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1148-1"><a href="PScore3.html#cb1148-1" aria-hidden="true" tabindex="-1"></a>md   <span class="ot">&lt;-</span> <span class="fu">match.data</span>(mS)</span>
<span id="cb1148-2"><a href="PScore3.html#cb1148-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(md, <span class="fu">table</span>(subclass, nohw8N, catholic))</span></code></pre></div>
<pre><code>## , , catholic = no
## 
##         nohw8N
## subclass   0   1
##        1 651 448
##        2 802 252
##        3 949  69
##        4 960   5
##        5 943   0
## 
## , , catholic = yes
## 
##         nohw8N
## subclass   0   1
##        1  23  12
##        2  65  15
##        3 105  12
##        4 166   0
##        5 194   0</code></pre>
<p>In the package’s documentation, such as in <a href="https://cran.r-project.org/web/packages/MatchIt/vignettes/assessing-balance.html" target="_blank">one of its vignettes</a>, it is explained that variance ratios are not reported for binary variables and that the empirical cumulative density function (eCDF) statistics provide an alternative. eCDF statistics with values closer to zero indicate good balance in the distributions between treatment groups, though there are no criteria for judging how much discrepancy counts as too much.</p>
<p>There are several plots available in the package. The help files, <code>help(package = "MatchIt")</code>, and the previously mentioned vignette provide a description of the types, including histograms and density plots. The package uses the label “Matched” for the adjusted cases.</p>
<p>Let’s examine the standardized mean differences both before and after the stratification. We see that all of the covariates in the adjusted data are lower than the usual criterion (having an absolute value <span class="math inline">\(\le 0.10\)</span>). Those exceeding <span class="math inline">\(0.05\)</span> lie outside the inner (dashed line) bands. These might be good candidates for use in doubly-robust estimation.</p>
<div class="sourceCode" id="cb1150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1150-1"><a href="PScore3.html#cb1150-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">bty =</span> <span class="st">&quot;l&quot;</span>)</span>
<span id="cb1150-2"><a href="PScore3.html#cb1150-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bal_mS, <span class="at">var.order =</span> <span class="st">&quot;unmatched&quot;</span>, <span class="at">abs =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-623-1.png" width="672" /></p>
<p>There is also an option to view the balance within each stratum, which are indicated by the gray numbers in the plot.</p>
<div class="sourceCode" id="cb1151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1151-1"><a href="PScore3.html#cb1151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">bty =</span> <span class="st">&quot;l&quot;</span>)</span>
<span id="cb1151-2"><a href="PScore3.html#cb1151-2" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">summary</span>(mS, <span class="at">subclass =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1151-3"><a href="PScore3.html#cb1151-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(s, <span class="at">var.order =</span> <span class="st">&quot;unmatched&quot;</span>, <span class="at">abs =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-624-1.png" width="672" /></p>
</div>
<div id="estimate-the-effect" class="section level3" number="12.4.2">
<h3><span class="header-section-number">12.4.2</span> Estimate the Effect</h3>
<p>We need to merge the outcome variable with the data that was generated from the <code>matchit()</code> function. First, using the package’s <code>match.data()</code> function, we create a data frame from the <code>mS</code> object we had created. After that, we can import our outcome-variable data set and merge it with our <code>md</code> object.</p>
<div class="sourceCode" id="cb1152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1152-1"><a href="PScore3.html#cb1152-1" aria-hidden="true" tabindex="-1"></a>md   <span class="ot">&lt;-</span> <span class="fu">match.data</span>(mS)</span>
<span id="cb1152-2"><a href="PScore3.html#cb1152-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1152-3"><a href="PScore3.html#cb1152-3" aria-hidden="true" tabindex="-1"></a> outcome <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;ch12_cath_outcomes_only.csv&quot;</span>)</span>
<span id="cb1152-4"><a href="PScore3.html#cb1152-4" aria-hidden="true" tabindex="-1"></a> ca2     <span class="ot">&lt;-</span> <span class="fu">left_join</span>(md, outcome, <span class="at">by =</span> <span class="st">&quot;id&quot;</span>)</span></code></pre></div>
<!-- ```{r} -->
<!-- with(ca2, table(strat5, subclass)) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- md %>% select(catholic, subclass, weights) %>%  -->
<!--        arrange(catholic, subclass) %>%  -->
<!--        unique() %>% data.frame(row.names = NULL) -->
<!-- ``` -->
<p>To estimate the effect and the standard errors, we can use the survey package.</p>
<div class="sourceCode" id="cb1153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1153-1"><a href="PScore3.html#cb1153-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey)</span>
<span id="cb1153-2"><a href="PScore3.html#cb1153-2" aria-hidden="true" tabindex="-1"></a>design_subclass <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">ids =</span> <span class="sc">~</span><span class="dv">1</span>, <span class="at">weights =</span> <span class="sc">~</span>weights, <span class="at">data =</span> ca2)</span>
<span id="cb1153-3"><a href="PScore3.html#cb1153-3" aria-hidden="true" tabindex="-1"></a>fit_subclass     <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(math12 <span class="sc">~</span> catholic, <span class="at">design =</span> design_subclass)</span>
<span id="cb1153-4"><a href="PScore3.html#cb1153-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_subclass)</span></code></pre></div>
<pre><code>## 
## Call:
## svyglm(formula = ..1, design = ..2)
## 
## Survey design:
## survey::svydesign(...)
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  50.8988     0.1339 380.194  &lt; 2e-16 ***
## catholicyes   1.8087     0.4712   3.838 0.000125 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 89.46436)
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<div class="sourceCode" id="cb1155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1155-1"><a href="PScore3.html#cb1155-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(fit_subclass)</span></code></pre></div>
<pre><code>##                  2.5 %    97.5 %
## (Intercept) 50.6363158 51.161212
## catholicyes  0.8849451  2.732527</code></pre>
<p>In keeping with the MatchIt package, we can use robust standard errors from the sandwich package <span class="citation">(<a href="#ref-R-sandwich" role="doc-biblioref">Zeileis &amp; Lumley, 2021</a>)</span>, named after the type of robust standard error. For this, we also need the lmtest package <span class="citation">(<a href="#ref-R-lmtest" role="doc-biblioref">Hothorn et al., 2020</a>)</span> to estimate the coefficients using the <code>coeftest()</code> function on the output of a weighted linear regression. This is the type of approach we will use with matching.</p>
<div class="sourceCode" id="cb1157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1157-1"><a href="PScore3.html#cb1157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb1157-2"><a href="PScore3.html#cb1157-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich)</span>
<span id="cb1157-3"><a href="PScore3.html#cb1157-3" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math12 <span class="sc">~</span> catholic, <span class="at">data =</span> ca2, <span class="at">weights =</span> weights)</span>
<span id="cb1157-4"><a href="PScore3.html#cb1157-4" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(fit1, <span class="at">vcov. =</span> vcovHC)</span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##             Estimate Std. Error  t value  Pr(&gt;|t|)    
## (Intercept) 50.89876    0.13389 380.1518 &lt; 2.2e-16 ***
## catholicyes  1.80874    0.47291   3.8247 0.0001323 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We observe a slightly different standard error. The statistical conclusion is the same as our previous methods.</p>
</div>
</div>
<div id="matching" class="section level2" number="12.5">
<h2><span class="header-section-number">12.5</span> Matching</h2>
<p>Let’s use the MatchIt package with one of the matching methods available. Let’s use full (optimal distance) matching. The MatchIt package use optimal matching from the optimal package <span class="citation">(<a href="#ref-hansen_optimal_2006" role="doc-biblioref">Hansen &amp; Klopfer, 2006</a>)</span>. This procedure takes a minute to run.</p>
<div class="sourceCode" id="cb1159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1159-1"><a href="PScore3.html#cb1159-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MatchIt)</span>
<span id="cb1159-2"><a href="PScore3.html#cb1159-2" aria-hidden="true" tabindex="-1"></a>mF <span class="ot">&lt;-</span> <span class="fu">matchit</span>(ps_mdl1, </span>
<span id="cb1159-3"><a href="PScore3.html#cb1159-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">estimand =</span> <span class="st">&quot;ATE&quot;</span>,</span>
<span id="cb1159-4"><a href="PScore3.html#cb1159-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">method =</span> <span class="st">&quot;full&quot;</span>,</span>
<span id="cb1159-5"><a href="PScore3.html#cb1159-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> ca)</span>
<span id="cb1159-6"><a href="PScore3.html#cb1159-6" aria-hidden="true" tabindex="-1"></a>mF</span></code></pre></div>
<pre><code>## A matchit object
##  - method: Optimal full matching
##  - distance: Propensity score
##              - estimated with logistic regression
##  - number of obs.: 5671 (original), 5671 (matched)
##  - target estimand: ATE
##  - covariates: inc8, inc8Sq, math8, mathfam, fhowfarN, mhowfarN, fight8N, nohw8N, disrupt8N, riskdrop8</code></pre>
<div class="sourceCode" id="cb1161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1161-1"><a href="PScore3.html#cb1161-1" aria-hidden="true" tabindex="-1"></a>bal_mF <span class="ot">&lt;-</span> <span class="fu">summary</span>(mF, <span class="at">standardize =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1161-2"><a href="PScore3.html#cb1161-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(bal_mF<span class="sc">$</span>sum.matched, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##           Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
## distance          0.104         0.104           0.000      1.003     0.003
## inc8             33.820        32.531           0.077      1.142     0.012
## inc8Sq         1481.886      1356.289           0.099      1.173     0.012
## math8            51.604        51.584           0.002      0.870     0.022
## mathfam        1765.652      1724.941           0.040      1.023     0.015
## fhowfarN          3.864         3.815           0.050      0.898     0.009
## mhowfarN          3.923         3.854           0.072      0.769     0.013
## fight8N           0.184         0.220          -0.077      0.930     0.013
## nohw8N            0.170         0.143           0.089         NA     0.028
## disrupt8N         0.143         0.180          -0.100         NA     0.038
## riskdrop8         0.653         0.620           0.042      0.808     0.017
##           eCDF Max Std. Pair Dist.
## distance     0.017           0.013
## inc8         0.043           0.665
## inc8Sq       0.043           0.584
## math8        0.060           0.901
## mathfam      0.054           0.575
## fhowfarN     0.018           0.911
## mhowfarN     0.036           0.945
## fight8N      0.038           0.713
## nohw8N       0.028           0.634
## disrupt8N    0.038           0.687
## riskdrop8    0.060           0.678</code></pre>
<div class="sourceCode" id="cb1163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1163-1"><a href="PScore3.html#cb1163-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">bty =</span> <span class="st">&quot;l&quot;</span>)</span>
<span id="cb1163-2"><a href="PScore3.html#cb1163-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bal_mF, <span class="at">var.order =</span> <span class="st">&quot;unmatched&quot;</span>, <span class="at">abs =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-630-1.png" width="672" /></p>
<p>This method seems to be slightly less effective than the MMWS stratification in reducing imbalance in our data.</p>
<div id="estimate-the-effect-1" class="section level3" number="12.5.1">
<h3><span class="header-section-number">12.5.1</span> Estimate the Effect</h3>
<p>We use the same steps as we did with stratification up until when we estimate the standard errors.</p>
<div class="sourceCode" id="cb1164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1164-1"><a href="PScore3.html#cb1164-1" aria-hidden="true" tabindex="-1"></a>mFd   <span class="ot">&lt;-</span> <span class="fu">match.data</span>(mF)</span>
<span id="cb1164-2"><a href="PScore3.html#cb1164-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1164-3"><a href="PScore3.html#cb1164-3" aria-hidden="true" tabindex="-1"></a> outcome <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;ch12_cath_outcomes_only.csv&quot;</span>)</span>
<span id="cb1164-4"><a href="PScore3.html#cb1164-4" aria-hidden="true" tabindex="-1"></a> ca2     <span class="ot">&lt;-</span> <span class="fu">left_join</span>(mFd, outcome, <span class="at">by =</span> <span class="st">&quot;id&quot;</span>)</span></code></pre></div>
<p>To account for the groupings that we have created using matching, we have to specify the matched groups as clusters when we estimate the standard error. In the survey package, we use the <code>id =</code> argument for this. In our data frame, our cluster variable is the new <code>ca2$subclass</code> variable that was generated when we used the <code>matchit()</code> function. Previously, when we used stratification, the strata were also called subclasses.<a href="#fn76" class="footnote-ref" id="fnref76"><sup>76</sup></a> Optimal full matching is essentially a very fine-grained stratification procedure. In our data, we have 592 matchings. Most of these have a single treatment-group case and several untreated cases because we have far fewer treated than untreated cases.</p>
<div class="sourceCode" id="cb1165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1165-1"><a href="PScore3.html#cb1165-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey)</span>
<span id="cb1165-2"><a href="PScore3.html#cb1165-2" aria-hidden="true" tabindex="-1"></a>design_full <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">ids =</span> <span class="sc">~</span>subclass , </span>
<span id="cb1165-3"><a href="PScore3.html#cb1165-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">weights =</span> <span class="sc">~</span>weights, </span>
<span id="cb1165-4"><a href="PScore3.html#cb1165-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> ca2)</span>
<span id="cb1165-5"><a href="PScore3.html#cb1165-5" aria-hidden="true" tabindex="-1"></a>fit_full    <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(math12 <span class="sc">~</span> catholic, <span class="at">design =</span> design_full)</span>
<span id="cb1165-6"><a href="PScore3.html#cb1165-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_full)</span></code></pre></div>
<pre><code>## 
## Call:
## svyglm(formula = ..1, design = ..2)
## 
## Survey design:
## survey::svydesign(...)
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  50.9759     0.4747 107.387  &lt; 2e-16 ***
## catholicyes   2.0763     0.6410   3.239  0.00127 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 89.64965)
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<div class="sourceCode" id="cb1167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1167-1"><a href="PScore3.html#cb1167-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(fit_full)</span></code></pre></div>
<pre><code>##                  2.5 %    97.5 %
## (Intercept) 50.0436111 51.908199
## catholicyes  0.8173644  3.335273</code></pre>
<p>In keeping with the MatchIt package, we can use robust standard errors from the sandwich package <span class="citation">(<a href="#ref-R-sandwich" role="doc-biblioref">Zeileis &amp; Lumley, 2021</a>)</span>, named after the type of robust standard error. For this, we also need the lmtest package <span class="citation">(<a href="#ref-R-lmtest" role="doc-biblioref">Hothorn et al., 2020</a>)</span> to estimate the coefficients using the <code>coeftest()</code> function on the output of a weighted linear regression. This is the type of approach we will use with matching.</p>
<div class="sourceCode" id="cb1169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1169-1"><a href="PScore3.html#cb1169-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb1169-2"><a href="PScore3.html#cb1169-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich)</span>
<span id="cb1169-3"><a href="PScore3.html#cb1169-3" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math12 <span class="sc">~</span> catholic, <span class="at">data =</span> ca2, <span class="at">weights =</span> weights)</span>
<span id="cb1169-4"><a href="PScore3.html#cb1169-4" aria-hidden="true" tabindex="-1"></a>(coefs <span class="ot">&lt;-</span> <span class="fu">coeftest</span>(fit1, <span class="at">vcov. =</span> vcovCL, <span class="at">cluster =</span> <span class="sc">~</span>subclass))</span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##             Estimate Std. Error  t value  Pr(&gt;|t|)    
## (Intercept) 50.97590    0.47473 107.3776 &lt; 2.2e-16 ***
## catholicyes  2.07632    0.64107   3.2388  0.001207 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We can get the confidence intervals with this method, as well. We see these are very similar to the estimates from the survery-package, which used Taylor series linearization instead of the sandwich estimator for the standard errors.</p>
<div class="sourceCode" id="cb1171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1171-1"><a href="PScore3.html#cb1171-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(coefs)</span></code></pre></div>
<pre><code>##                  2.5 %    97.5 %
## (Intercept) 50.0452428 51.906567
## catholicyes  0.8195679  3.333069</code></pre>
<p>With this method, we observe a higher estimate and a smaller standard error. Of course, we should avoid making decisions about which model to use based on the estimates and their standard error. That’s what our first step was for—examining how well the propensity score method worked.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="1">
<div id="ref-hansen_optimal_2006" class="csl-entry">
Hansen, B. B., &amp; Klopfer, S. O. (2006). Optimal <span>Full</span> <span>Matching</span> and <span>Related</span> <span>Designs</span> via <span>Network</span> <span>Flows</span>. <em>Journal of Computational and Graphical Statistics</em>, <em>15</em>(3), 609–627. <a href="https://doi.org/10.1198/106186006X137047">https://doi.org/10.1198/106186006X137047</a>
</div>
<div id="ref-R-MatchIt" class="csl-entry">
Ho, D., Imai, K., King, G., Stuart, E., &amp; Greifer, N. (2021). <em>MatchIt: Nonparametric preprocessing for parametric causal inference</em>. <a href="https://CRAN.R-project.org/package=MatchIt">https://CRAN.R-project.org/package=MatchIt</a>
</div>
<div id="ref-hong_causality_2015" class="csl-entry">
Hong, G. (2015). <em>Causality in a social world: <span>Moderation</span>, meditation and spill-over</em>. John Wiley &amp; Sons, Ltd. <a href="http://doi.wiley.com/10.1002/9781119030638">http://doi.wiley.com/10.1002/9781119030638</a>
</div>
<div id="ref-R-lmtest" class="csl-entry">
Hothorn, T., Zeileis, A., Farebrother, R. W., &amp; Cummins, C. (2020). <em>Lmtest: Testing linear regression models</em>. <a href="https://CRAN.R-project.org/package=lmtest">https://CRAN.R-project.org/package=lmtest</a>
</div>
<div id="ref-R-survey" class="csl-entry">
Lumley, T. (2021). <em>Survey: Analysis of complex survey samples</em>. <a href="http://r-survey.r-forge.r-project.org/survey/">http://r-survey.r-forge.r-project.org/survey/</a>
</div>
<div id="ref-R-sandwich" class="csl-entry">
Zeileis, A., &amp; Lumley, T. (2021). <em>Sandwich: Robust covariance matrix estimators</em>. <a href="https://sandwich.R-Forge.R-project.org/">https://sandwich.R-Forge.R-project.org/</a>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="72">
<li id="fn72"><p>The variable name <code>Freq</code> came from the table function. This is actually our MMWS weight.<a href="PScore3.html#fnref72" class="footnote-back">↩︎</a></p></li>
<li id="fn73"><p>We can also use the <code>merge()</code> function, which is the same as dplyr’s <code>inner_join()</code> function.<a href="PScore3.html#fnref73" class="footnote-back">↩︎</a></p></li>
<li id="fn74"><p>We’ve seen the pipe operator, <code>%&gt;%</code>, before; it says to take what’s on its left and do the stuff on the right.<a href="PScore3.html#fnref74" class="footnote-back">↩︎</a></p></li>
<li id="fn75"><p>Here, we’re using the package’s <code>match.data()</code> function to create a data frame from the output of the <code>matchit()</code> function.<a href="PScore3.html#fnref75" class="footnote-back">↩︎</a></p></li>
<li id="fn76"><p>We don’t specify the strata as clusters when we use the MMWS method.<a href="PScore3.html#fnref76" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="PScore2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
