<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Part 6 Regression Discontinuity, Part 1 | Using R for Quasi-Experimental Designs</title>
  <meta name="description" content="QEDs in R" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Part 6 Regression Discontinuity, Part 1 | Using R for Quasi-Experimental Designs" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="QEDs in R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Part 6 Regression Discontinuity, Part 1 | Using R for Quasi-Experimental Designs" />
  
  <meta name="twitter:description" content="QEDs in R" />
  

<meta name="author" content="George M. Harrison  University of Hawai‘i at Mānoa, College of Education" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="DID.html"/>
<link rel="next" href="RD2.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 1em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#what-is-r"><i class="fa fa-check"></i><b>1.1</b> What is R</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basics.html"><a href="basics.html"><i class="fa fa-check"></i><b>2</b> Some Fundamentals of Coding in R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basics.html"><a href="basics.html#objectives"><i class="fa fa-check"></i><b>2.1</b> Objectives</a></li>
<li class="chapter" data-level="2.2" data-path="basics.html"><a href="basics.html#creating-an-r-script-file"><i class="fa fa-check"></i><b>2.2</b> Creating an R Script File</a></li>
<li class="chapter" data-level="2.3" data-path="basics.html"><a href="basics.html#creating-objects-by-assigning-information-to-them"><i class="fa fa-check"></i><b>2.3</b> Creating objects by assigning information to them</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="basics.html"><a href="basics.html#assigning-character-strings-to-an-object"><i class="fa fa-check"></i><b>2.3.1</b> Assigning Character Strings to an Object</a></li>
<li class="chapter" data-level="2.3.2" data-path="basics.html"><a href="basics.html#assigning-numeric-elements-to-an-object"><i class="fa fa-check"></i><b>2.3.2</b> Assigning Numeric Elements to an Object</a></li>
<li class="chapter" data-level="2.3.3" data-path="basics.html"><a href="basics.html#creating-vectors"><i class="fa fa-check"></i><b>2.3.3</b> Creating Vectors</a></li>
<li class="chapter" data-level="2.3.4" data-path="basics.html"><a href="basics.html#performing-operations-on-vectors"><i class="fa fa-check"></i><b>2.3.4</b> Performing Operations on Vectors</a></li>
<li class="chapter" data-level="2.3.5" data-path="basics.html"><a href="basics.html#using-functions"><i class="fa fa-check"></i><b>2.3.5</b> Using Functions</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="basics.html"><a href="basics.html#create-a-data-frame-from-code"><i class="fa fa-check"></i><b>2.4</b> Create a data frame from code</a></li>
<li class="chapter" data-level="2.5" data-path="basics.html"><a href="basics.html#working-with-matrices"><i class="fa fa-check"></i><b>2.5</b> Working with Matrices</a></li>
<li class="chapter" data-level="2.6" data-path="basics.html"><a href="basics.html#dffromcsv"><i class="fa fa-check"></i><b>2.6</b> Creating a Data Frame from a CSV File</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="examine.html"><a href="examine.html"><i class="fa fa-check"></i><b>3</b> Examining and Summarizing Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="examine.html"><a href="examine.html#objectives-1"><i class="fa fa-check"></i><b>3.1</b> Objectives</a></li>
<li class="chapter" data-level="3.2" data-path="examine.html"><a href="examine.html#examining-the-data"><i class="fa fa-check"></i><b>3.2</b> Examining the Data</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="examine.html"><a href="examine.html#the-data-frame"><i class="fa fa-check"></i><b>3.2.1</b> The Data Frame</a></li>
<li class="chapter" data-level="3.2.2" data-path="examine.html"><a href="examine.html#subsetting-by-rows"><i class="fa fa-check"></i><b>3.2.2</b> Subsetting by Rows</a></li>
<li class="chapter" data-level="3.2.3" data-path="examine.html"><a href="examine.html#subsetting-by-columns"><i class="fa fa-check"></i><b>3.2.3</b> Subsetting by Columns</a></li>
<li class="chapter" data-level="3.2.4" data-path="examine.html"><a href="examine.html#descriptive-statistics"><i class="fa fa-check"></i><b>3.2.4</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="3.2.5" data-path="examine.html"><a href="examine.html#creating-a-custom-function-to-estimate-the-confidence-interval-of-the-mean"><i class="fa fa-check"></i><b>3.2.5</b> Creating a Custom Function to Estimate the Confidence Interval of the Mean</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="examine.html"><a href="examine.html#summarizing-data-by-group-and-an-introduction-to-lists"><i class="fa fa-check"></i><b>3.3</b> Summarizing Data by Group (and an introduction to lists)</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="examine.html"><a href="examine.html#calculating-standardized-mean-difference-and-variance-ratio-of-a-covariate"><i class="fa fa-check"></i><b>3.3.1</b> Calculating Standardized Mean Difference and Variance Ratio of a Covariate</a></li>
<li class="chapter" data-level="3.3.2" data-path="examine.html"><a href="examine.html#creating-a-factor-variable-from-a-numeric-variable"><i class="fa fa-check"></i><b>3.3.2</b> Creating a Factor Variable from a Numeric Variable</a></li>
<li class="chapter" data-level="3.3.3" data-path="examine.html"><a href="examine.html#aggregate_explain"><i class="fa fa-check"></i><b>3.3.3</b> The <code>aggregate()</code> function</a></li>
<li class="chapter" data-level="3.3.4" data-path="examine.html"><a href="examine.html#plotting-data-by-group"><i class="fa fa-check"></i><b>3.3.4</b> Plotting data by group</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="examine.html"><a href="examine.html#extra-stuff"><i class="fa fa-check"></i><b>3.4</b> Extra Stuff</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="examine.html"><a href="examine.html#using-ggplot"><i class="fa fa-check"></i><b>3.4.1</b> Using ggplot</a></li>
<li class="chapter" data-level="3.4.2" data-path="examine.html"><a href="examine.html#subsetting-data-and-separately-analyzing-each-group"><i class="fa fa-check"></i><b>3.4.2</b> Subsetting data and separately analyzing each group</a></li>
<li class="chapter" data-level="3.4.3" data-path="examine.html"><a href="examine.html#the-tidyverse-approach-to-by-group-analyses"><i class="fa fa-check"></i><b>3.4.3</b> The Tidyverse Approach to By-Group Analyses</a></li>
<li class="chapter" data-level="3.4.4" data-path="examine.html"><a href="examine.html#plotting-summary-statistics"><i class="fa fa-check"></i><b>3.4.4</b> Plotting summary statistics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="rct.html"><a href="rct.html"><i class="fa fa-check"></i><b>4</b> Examples with Randomized Experiments</a>
<ul>
<li class="chapter" data-level="4.1" data-path="rct.html"><a href="rct.html#objectives-2"><i class="fa fa-check"></i><b>4.1</b> Objectives</a></li>
<li class="chapter" data-level="4.2" data-path="rct.html"><a href="rct.html#preparation"><i class="fa fa-check"></i><b>4.2</b> Preparation</a></li>
<li class="chapter" data-level="4.3" data-path="rct.html"><a href="rct.html#analysis-of-linear-models"><i class="fa fa-check"></i><b>4.3</b> Analysis of Linear Models</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="rct.html"><a href="rct.html#independent-samples-t-test-approach"><i class="fa fa-check"></i><b>4.3.1</b> Independent samples <em>t</em>-test approach</a></li>
<li class="chapter" data-level="4.3.2" data-path="rct.html"><a href="rct.html#simple-linear-regression"><i class="fa fa-check"></i><b>4.3.2</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="4.3.3" data-path="rct.html"><a href="rct.html#multiple-linear-regression"><i class="fa fa-check"></i><b>4.3.3</b> Multiple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="rct.html"><a href="rct.html#bootstrapping-to-get-confidence-intervals"><i class="fa fa-check"></i><b>4.4</b> Bootstrapping to Get Confidence Intervals</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="rct.html"><a href="rct.html#the-value-of-bootstrapping"><i class="fa fa-check"></i><b>4.4.1</b> The value of bootstrapping</a></li>
<li class="chapter" data-level="4.4.2" data-path="rct.html"><a href="rct.html#another-way-to-bootstrap-the-standard-error-of-mean-differences"><i class="fa fa-check"></i><b>4.4.2</b> Another way to bootstrap the standard error of mean differences</a></li>
<li class="chapter" data-level="4.4.3" data-path="rct.html"><a href="rct.html#simple-regression"><i class="fa fa-check"></i><b>4.4.3</b> Simple regression</a></li>
<li class="chapter" data-level="4.4.4" data-path="rct.html"><a href="rct.html#multiple-regression"><i class="fa fa-check"></i><b>4.4.4</b> Multiple regression</a></li>
<li class="chapter" data-level="4.4.5" data-path="rct.html"><a href="rct.html#summary-on-bootstrapping"><i class="fa fa-check"></i><b>4.4.5</b> Summary on Bootstrapping</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="rct.html"><a href="rct.html#estimating-the-average-treatment-on-the-treated-att"><i class="fa fa-check"></i><b>4.5</b> Estimating the Average Treatment on the Treated (ATT)</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="rct.html"><a href="rct.html#artificially-introducing-no-shows"><i class="fa fa-check"></i><b>4.5.1</b> Artificially Introducing No-shows</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="DID.html"><a href="DID.html"><i class="fa fa-check"></i><b>5</b> Difference in Differences</a>
<ul>
<li class="chapter" data-level="5.1" data-path="DID.html"><a href="DID.html#objectives-3"><i class="fa fa-check"></i><b>5.1</b> Objectives</a></li>
<li class="chapter" data-level="5.2" data-path="DID.html"><a href="DID.html#import-and-prepare-the-data"><i class="fa fa-check"></i><b>5.2</b> Import and Prepare the Data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="DID.html"><a href="DID.html#prepare-the-data"><i class="fa fa-check"></i><b>5.2.1</b> Prepare the data</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="DID.html"><a href="DID.html#using-the-survey-package"><i class="fa fa-check"></i><b>5.3</b> Using the survey package</a></li>
<li class="chapter" data-level="5.4" data-path="DID.html"><a href="DID.html#direct-estimates-as-shown-in-table-8.1-on-page-143"><i class="fa fa-check"></i><b>5.4</b> Direct estimates, as shown in Table 8.1 on page 143</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="DID.html"><a href="DID.html#first-difference-direct-estimate-in-panel-a."><i class="fa fa-check"></i><b>5.4.1</b> First difference, direct estimate in Panel A.</a></li>
<li class="chapter" data-level="5.4.2" data-path="DID.html"><a href="DID.html#estimate-from-the-linear-probability-model-ols-estimate-shown-in-table-8.1-on-page-143-panel-b."><i class="fa fa-check"></i><b>5.4.2</b> Estimate from the linear-probability model (OLS) estimate shown in Table 8.1 on page 143, Panel B.</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="DID.html"><a href="DID.html#difference-in-differences-simple-approach-table-8.2-p.-157"><i class="fa fa-check"></i><b>5.5</b> Difference in differences, simple approach (Table 8.2, p. 157)</a></li>
<li class="chapter" data-level="5.6" data-path="DID.html"><a href="DID.html#difference-in-differences-using-regression"><i class="fa fa-check"></i><b>5.6</b> Difference in differences using regression</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="DID.html"><a href="DID.html#compare-the-results-from-the-four-different-strategies"><i class="fa fa-check"></i><b>5.6.1</b> Compare the results from the four different strategies</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="DID.html"><a href="DID.html#summary-of-the-did-model-strategy"><i class="fa fa-check"></i><b>5.7</b> Summary of the DID model strategy</a></li>
<li class="chapter" data-level="5.8" data-path="DID.html"><a href="DID.html#accounting-for-the-binary-y-variable"><i class="fa fa-check"></i><b>5.8</b> Accounting for the binary Y variable</a></li>
<li class="chapter" data-level="5.9" data-path="DID.html"><a href="DID.html#plotting-the-difference-in-differences"><i class="fa fa-check"></i><b>5.9</b> Plotting the difference in differences</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="DID.html"><a href="DID.html#plotfrompred"><i class="fa fa-check"></i><b>5.9.1</b> Plotting from the predicted values of the model</a></li>
<li class="chapter" data-level="5.9.2" data-path="DID.html"><a href="DID.html#doing-it-in-ggplot2"><i class="fa fa-check"></i><b>5.9.2</b> Doing it in ggplot2</a></li>
<li class="chapter" data-level="5.9.3" data-path="DID.html"><a href="DID.html#seeing-where-the-regression-estimate-is-in-the-plot"><i class="fa fa-check"></i><b>5.9.3</b> Seeing where the regression estimate is in the plot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="RD1.html"><a href="RD1.html"><i class="fa fa-check"></i><b>6</b> Regression Discontinuity, Part 1</a>
<ul>
<li class="chapter" data-level="6.1" data-path="RD1.html"><a href="RD1.html#objectives-4"><i class="fa fa-check"></i><b>6.1</b> Objectives</a></li>
<li class="chapter" data-level="6.2" data-path="RD1.html"><a href="RD1.html#import-and-prepare-the-data-1"><i class="fa fa-check"></i><b>6.2</b> Import and Prepare the Data</a></li>
<li class="chapter" data-level="6.3" data-path="RD1.html"><a href="RD1.html#different-difference-in-differences"><i class="fa fa-check"></i><b>6.3</b> Different Difference in Differences</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="RD1.html"><a href="RD1.html#our-first-difference"><i class="fa fa-check"></i><b>6.3.1</b> Our first difference</a></li>
<li class="chapter" data-level="6.3.2" data-path="RD1.html"><a href="RD1.html#a-plausible-second-difference"><i class="fa fa-check"></i><b>6.3.2</b> A plausible second difference</a></li>
<li class="chapter" data-level="6.3.3" data-path="RD1.html"><a href="RD1.html#another-plausible-second-difference"><i class="fa fa-check"></i><b>6.3.3</b> Another plausible second difference</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="RD1.html"><a href="RD1.html#mread3640"><i class="fa fa-check"></i><b>6.4</b> Broadening the bandwidth</a></li>
<li class="chapter" data-level="6.5" data-path="RD1.html"><a href="RD1.html#summary-up-to-this-point"><i class="fa fa-check"></i><b>6.5</b> Summary up to this point</a></li>
<li class="chapter" data-level="6.6" data-path="RD1.html"><a href="RD1.html#examining-if-the-results-are-consistent-with-different-bandwidths"><i class="fa fa-check"></i><b>6.6</b> Examining if the results are consistent with different bandwidths</a></li>
<li class="chapter" data-level="6.7" data-path="RD1.html"><a href="RD1.html#functional-form-in-rdd"><i class="fa fa-check"></i><b>6.7</b> Functional Form in RDD</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="RD1.html"><a href="RD1.html#plotting-the-two-sides-allowing-different-slopes"><i class="fa fa-check"></i><b>6.7.1</b> Plotting the two sides, allowing different slopes</a></li>
<li class="chapter" data-level="6.7.2" data-path="RD1.html"><a href="RD1.html#broader-analytic-windows"><i class="fa fa-check"></i><b>6.7.2</b> Broader analytic windows</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="RD1.html"><a href="RD1.html#using-the-rddtools-package"><i class="fa fa-check"></i><b>6.8</b> Using the rddtools Package</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="RD1.html"><a href="RD1.html#examining-the-bandwidth-identified-by-the-package"><i class="fa fa-check"></i><b>6.8.1</b> Examining the bandwidth identified by the package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="RD2.html"><a href="RD2.html"><i class="fa fa-check"></i><b>7</b> Regression Discontinuity, Part 2</a>
<ul>
<li class="chapter" data-level="7.1" data-path="RD2.html"><a href="RD2.html#here-are-the-steps-we-will-take"><i class="fa fa-check"></i><b>7.1</b> Here are the steps we will take:</a></li>
<li class="chapter" data-level="7.2" data-path="RD2.html"><a href="RD2.html#the-data"><i class="fa fa-check"></i><b>7.2</b> The Data</a></li>
<li class="chapter" data-level="7.3" data-path="RD2.html"><a href="RD2.html#examine-the-data-the-assignment-rule-adherence-and-compliance"><i class="fa fa-check"></i><b>7.3</b> Examine the Data, the Assignment-rule Adherence, and Compliance</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="RD2.html"><a href="RD2.html#assignment-rule-adherence"><i class="fa fa-check"></i><b>7.3.1</b> Assignment-rule adherence</a></li>
<li class="chapter" data-level="7.3.2" data-path="RD2.html"><a href="RD2.html#compliance"><i class="fa fa-check"></i><b>7.3.2</b> Compliance</a></li>
<li class="chapter" data-level="7.3.3" data-path="RD2.html"><a href="RD2.html#create-bins-of-the-assignment-variable"><i class="fa fa-check"></i><b>7.3.3</b> Create Bins of the Assignment Variable</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="RD2.html"><a href="RD2.html#examining-assumptions"><i class="fa fa-check"></i><b>7.4</b> Examining Assumptions</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="RD2.html"><a href="RD2.html#assumption-1the-continuity-assumption"><i class="fa fa-check"></i><b>7.4.1</b> Assumption 1—the continuity assumption</a></li>
<li class="chapter" data-level="7.4.2" data-path="RD2.html"><a href="RD2.html#assumption-2discontinuities-in-the-covariates"><i class="fa fa-check"></i><b>7.4.2</b> Assumption 2—Discontinuities in the covariates</a></li>
<li class="chapter" data-level="7.4.3" data-path="RD2.html"><a href="RD2.html#assumption-3checking-for-pseudo-cut-offs-in-the-outcome"><i class="fa fa-check"></i><b>7.4.3</b> Assumption 3—Checking for pseudo-cut-offs in the outcome</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="RD2.html"><a href="RD2.html#examining-the-parametric-functional-form"><i class="fa fa-check"></i><b>7.5</b> Examining the Parametric Functional Form</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="RD2.html"><a href="RD2.html#restricting-bandwidth"><i class="fa fa-check"></i><b>7.5.1</b> Restricting bandwidth</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="RD2.html"><a href="RD2.html#restband"><i class="fa fa-check"></i><b>7.6</b> Estimating the Effect</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="RD2.html"><a href="RD2.html#parametric-model"><i class="fa fa-check"></i><b>7.6.1</b> Parametric Model</a></li>
<li class="chapter" data-level="7.6.2" data-path="RD2.html"><a href="RD2.html#non-parametric-model-local-linear-estimation"><i class="fa fa-check"></i><b>7.6.2</b> Non-parametric Model: Local Linear Estimation</a></li>
<li class="chapter" data-level="7.6.3" data-path="RD2.html"><a href="RD2.html#including-covariates"><i class="fa fa-check"></i><b>7.6.3</b> Including covariates</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="RD2.html"><a href="RD2.html#sensitivity-analysis"><i class="fa fa-check"></i><b>7.7</b> Sensitivity Analysis</a></li>
<li class="chapter" data-level="7.8" data-path="RD2.html"><a href="RD2.html#accounting-for-fuzziness"><i class="fa fa-check"></i><b>7.8</b> Accounting for Fuzziness</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="RD2.html"><a href="RD2.html#fuzzy-non-parametric-model"><i class="fa fa-check"></i><b>7.8.1</b> Fuzzy non-parametric model</a></li>
<li class="chapter" data-level="7.8.2" data-path="RD2.html"><a href="RD2.html#summary-about-fuzzy-rdd"><i class="fa fa-check"></i><b>7.8.2</b> Summary about fuzzy RDD</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="IVE.html"><a href="IVE.html"><i class="fa fa-check"></i><b>8</b> Instrumental Variable Estimation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="IVE.html"><a href="IVE.html#objectives-5"><i class="fa fa-check"></i><b>8.1</b> Objectives</a></li>
<li class="chapter" data-level="8.2" data-path="IVE.html"><a href="IVE.html#preparation-1"><i class="fa fa-check"></i><b>8.2</b> Preparation</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="IVE.html"><a href="IVE.html#examining-the-data-1"><i class="fa fa-check"></i><b>8.2.1</b> Examining the data</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="IVE.html"><a href="IVE.html#moments-reported-in-table-10.2-p.-219"><i class="fa fa-check"></i><b>8.3</b> Moments reported in Table 10.2 (p. 219)</a></li>
<li class="chapter" data-level="8.4" data-path="IVE.html"><a href="IVE.html#two-stage-least-squares-1"><i class="fa fa-check"></i><b>8.4</b> Two-stage Least Squares</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="IVE.html"><a href="IVE.html#first-stage"><i class="fa fa-check"></i><b>8.4.1</b> First stage</a></li>
<li class="chapter" data-level="8.4.2" data-path="IVE.html"><a href="IVE.html#second-stage"><i class="fa fa-check"></i><b>8.4.2</b> Second stage</a></li>
<li class="chapter" data-level="8.4.3" data-path="IVE.html"><a href="IVE.html#obtaining-the-correct-standard-errors"><i class="fa fa-check"></i><b>8.4.3</b> Obtaining the correct standard errors</a></li>
<li class="chapter" data-level="8.4.4" data-path="IVE.html"><a href="IVE.html#letting-the-software-do-the-work"><i class="fa fa-check"></i><b>8.4.4</b> Letting the software do the work</a></li>
<li class="chapter" data-level="8.4.5" data-path="IVE.html"><a href="IVE.html#noticing-the-covariance-between-errors"><i class="fa fa-check"></i><b>8.4.5</b> Noticing the covariance between errors</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="IVE.html"><a href="IVE.html#two-stage-least-squares-with-covariates"><i class="fa fa-check"></i><b>8.5</b> Two-Stage Least Squares with Covariates</a></li>
<li class="chapter" data-level="8.6" data-path="IVE.html"><a href="IVE.html#using-multiple-instruments"><i class="fa fa-check"></i><b>8.6</b> Using Multiple Instruments</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="IVE.html"><a href="IVE.html#system-of-equations"><i class="fa fa-check"></i><b>8.6.1</b> System of equations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="IVE2.html"><a href="IVE2.html"><i class="fa fa-check"></i><b>9</b> Practice with Instrumental Variable Estimation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="IVE2.html"><a href="IVE2.html#objectives-6"><i class="fa fa-check"></i><b>9.1</b> Objectives</a></li>
<li class="chapter" data-level="9.2" data-path="IVE2.html"><a href="IVE2.html#import-and-prepare-the-data-2"><i class="fa fa-check"></i><b>9.2</b> Import and Prepare the Data</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="IVE2.html"><a href="IVE2.html#descriptive-statistics-1"><i class="fa fa-check"></i><b>9.2.1</b> Descriptive statistics</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="IVE2.html"><a href="IVE2.html#covariate-balance"><i class="fa fa-check"></i><b>9.3</b> Covariate Balance</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="IVE2.html"><a href="IVE2.html#covariate-balance-on-d"><i class="fa fa-check"></i><b>9.3.1</b> Covariate balance on <span class="math inline">\(D\)</span></a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="IVE2.html"><a href="IVE2.html#compliance-table-1"><i class="fa fa-check"></i><b>9.4</b> Compliance Table</a></li>
<li class="chapter" data-level="9.5" data-path="IVE2.html"><a href="IVE2.html#estimating-the-causal-effect"><i class="fa fa-check"></i><b>9.5</b> Estimating the Causal Effect</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="IVE2.html"><a href="IVE2.html#the-naïve-estimate"><i class="fa fa-check"></i><b>9.5.1</b> The naïve estimate</a></li>
<li class="chapter" data-level="9.5.2" data-path="IVE2.html"><a href="IVE2.html#the-late-estimate-from-ive"><i class="fa fa-check"></i><b>9.5.2</b> The LATE estimate from IVE</a></li>
<li class="chapter" data-level="9.5.3" data-path="IVE2.html"><a href="IVE2.html#making-the-intercept-meaningful"><i class="fa fa-check"></i><b>9.5.3</b> Making the intercept meaningful</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="PScore1.html"><a href="PScore1.html"><i class="fa fa-check"></i><b>10</b> Propensity Score Analysis 1: The underlying logic</a>
<ul>
<li class="chapter" data-level="10.1" data-path="PScore1.html"><a href="PScore1.html#import-the-data-and-prepare-for-analysis"><i class="fa fa-check"></i><b>10.1</b> Import the Data and Prepare for Analysis</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="PScore1.html"><a href="PScore1.html#creating-a-numeric-version-of-the-base-income-variables"><i class="fa fa-check"></i><b>10.1.1</b> Creating a numeric version of the base-income variables</a></li>
<li class="chapter" data-level="10.1.2" data-path="PScore1.html"><a href="PScore1.html#creating-some-custom-functions"><i class="fa fa-check"></i><b>10.1.2</b> Creating some custom functions</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="PScore1.html"><a href="PScore1.html#stratifying-on-a-covariate"><i class="fa fa-check"></i><b>10.2</b> Stratifying on a Covariate</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="PScore1.html"><a href="PScore1.html#checking-the-imbalance-in-the-treatment-status"><i class="fa fa-check"></i><b>10.2.1</b> Checking the imbalance in the treatment status</a></li>
<li class="chapter" data-level="10.2.2" data-path="PScore1.html"><a href="PScore1.html#creating-the-strata-from-the-covariate"><i class="fa fa-check"></i><b>10.2.2</b> Creating the strata from the covariate</a></li>
<li class="chapter" data-level="10.2.3" data-path="PScore1.html"><a href="PScore1.html#checking-for-imbalance-within-each-stratum"><i class="fa fa-check"></i><b>10.2.3</b> Checking for imbalance within each stratum</a></li>
<li class="chapter" data-level="10.2.4" data-path="PScore1.html"><a href="PScore1.html#using-tidyverse-to-check-imbalance"><i class="fa fa-check"></i><b>10.2.4</b> Using Tidyverse to check imbalance</a></li>
<li class="chapter" data-level="10.2.5" data-path="PScore1.html"><a href="PScore1.html#ate-and-att"><i class="fa fa-check"></i><b>10.2.5</b> ATE and ATT</a></li>
<li class="chapter" data-level="10.2.6" data-path="PScore1.html"><a href="PScore1.html#pooling-across-strata-to-calculate-the-ate-and-att"><i class="fa fa-check"></i><b>10.2.6</b> Pooling across strata to calculate the ATE and ATT</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="PScore1.html"><a href="PScore1.html#stratifying-on-two-covariates"><i class="fa fa-check"></i><b>10.3</b> Stratifying on Two Covariates</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="PScore1.html"><a href="PScore1.html#calculating-the-ate-and-att"><i class="fa fa-check"></i><b>10.3.1</b> Calculating the ATE and ATT</a></li>
<li class="chapter" data-level="10.3.2" data-path="PScore1.html"><a href="PScore1.html#tidyverse-approach"><i class="fa fa-check"></i><b>10.3.2</b> Tidyverse approach</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="PScore1.html"><a href="PScore1.html#estimating-propensity-scores"><i class="fa fa-check"></i><b>10.4</b> Estimating Propensity Scores</a></li>
<li class="chapter" data-level="10.5" data-path="PScore1.html"><a href="PScore1.html#creating-strata-from-propensity-scores"><i class="fa fa-check"></i><b>10.5</b> Creating Strata from Propensity Scores</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="PScore1.html"><a href="PScore1.html#adding-more-covariates"><i class="fa fa-check"></i><b>10.5.1</b> Adding more covariates</a></li>
<li class="chapter" data-level="10.5.2" data-path="PScore1.html"><a href="PScore1.html#ate-and-att-for-the-five-stratum-model"><i class="fa fa-check"></i><b>10.5.2</b> ATE and ATT for the five-stratum model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="PScore2.html"><a href="PScore2.html"><i class="fa fa-check"></i><b>11</b> Propensity Score Analysis 2: Weighting</a>
<ul>
<li class="chapter" data-level="11.1" data-path="PScore2.html"><a href="PScore2.html#import-the-data-and-prepare-for-analysis-1"><i class="fa fa-check"></i><b>11.1</b> Import the Data and Prepare for Analysis</a></li>
<li class="chapter" data-level="11.2" data-path="PScore2.html"><a href="PScore2.html#specify-custom-functions"><i class="fa fa-check"></i><b>11.2</b> Specify Custom Functions</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="PScore2.html"><a href="PScore2.html#imbalance-functions"><i class="fa fa-check"></i><b>11.2.1</b> Imbalance functions</a></li>
<li class="chapter" data-level="11.2.2" data-path="PScore2.html"><a href="PScore2.html#overlap-functions"><i class="fa fa-check"></i><b>11.2.2</b> Overlap functions</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="PScore2.html"><a href="PScore2.html#assess-imbalance-in-observed-covariates"><i class="fa fa-check"></i><b>11.3</b> Assess Imbalance in Observed Covariates</a></li>
<li class="chapter" data-level="11.4" data-path="PScore2.html"><a href="PScore2.html#check-overlap"><i class="fa fa-check"></i><b>11.4</b> Check Overlap</a></li>
<li class="chapter" data-level="11.5" data-path="PScore2.html"><a href="PScore2.html#calculate-the-weights"><i class="fa fa-check"></i><b>11.5</b> Calculate the Weights</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="PScore2.html"><a href="PScore2.html#dealing-with-extreme-weights"><i class="fa fa-check"></i><b>11.5.1</b> Dealing with extreme weights</a></li>
<li class="chapter" data-level="11.5.2" data-path="PScore2.html"><a href="PScore2.html#specifying-whether-to-estimate-ate-or-att"><i class="fa fa-check"></i><b>11.5.2</b> Specifying whether to estimate ATE or ATT</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="PScore2.html"><a href="PScore2.html#conduct-balance-checks-after-weighting"><i class="fa fa-check"></i><b>11.6</b> Conduct balance checks after weighting</a></li>
<li class="chapter" data-level="11.7" data-path="PScore2.html"><a href="PScore2.html#estimate-the-treatment-effect"><i class="fa fa-check"></i><b>11.7</b> Estimate the Treatment Effect</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="PScore2.html"><a href="PScore2.html#estimating-the-correct-standard-error"><i class="fa fa-check"></i><b>11.7.1</b> Estimating the correct standard error</a></li>
<li class="chapter" data-level="11.7.2" data-path="PScore2.html"><a href="PScore2.html#use-a-doubly-robust-estimate"><i class="fa fa-check"></i><b>11.7.2</b> Use a doubly robust estimate</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="PScore2.html"><a href="PScore2.html#using-the-twang-package"><i class="fa fa-check"></i><b>11.8</b> Using the Twang Package</a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="PScore2.html"><a href="PScore2.html#examining-covariate-balance"><i class="fa fa-check"></i><b>11.8.1</b> Examining covariate balance</a></li>
<li class="chapter" data-level="11.8.2" data-path="PScore2.html"><a href="PScore2.html#estimating-the-propensity-scores-and-getting-the-weights"><i class="fa fa-check"></i><b>11.8.2</b> Estimating the propensity scores and getting the weights</a></li>
<li class="chapter" data-level="11.8.3" data-path="PScore2.html"><a href="PScore2.html#estimating-the-effect"><i class="fa fa-check"></i><b>11.8.3</b> Estimating the effect</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="PScore3.html"><a href="PScore3.html"><i class="fa fa-check"></i><b>12</b> Propensity Score Analysis 3: Stratification and Matching</a>
<ul>
<li class="chapter" data-level="12.1" data-path="PScore3.html"><a href="PScore3.html#calculate-the-mmwss-from-the-propensity-scores"><i class="fa fa-check"></i><b>12.1</b> Calculate the MMWSs from the propensity scores</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="PScore3.html"><a href="PScore3.html#estimate-the-propensity-scores"><i class="fa fa-check"></i><b>12.1.1</b> Estimate the propensity scores</a></li>
<li class="chapter" data-level="12.1.2" data-path="PScore3.html"><a href="PScore3.html#calculate-the-quintiles"><i class="fa fa-check"></i><b>12.1.2</b> Calculate the quintiles</a></li>
<li class="chapter" data-level="12.1.3" data-path="PScore3.html"><a href="PScore3.html#examine-the-strata"><i class="fa fa-check"></i><b>12.1.3</b> Examine the strata</a></li>
<li class="chapter" data-level="12.1.4" data-path="PScore3.html"><a href="PScore3.html#calculate-the-mmwss"><i class="fa fa-check"></i><b>12.1.4</b> Calculate the MMWSs</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="PScore3.html"><a href="PScore3.html#conduct-balance-checks-after-weighting-1"><i class="fa fa-check"></i><b>12.2</b> Conduct balance checks after weighting</a></li>
<li class="chapter" data-level="12.3" data-path="PScore3.html"><a href="PScore3.html#estimate-the-ate"><i class="fa fa-check"></i><b>12.3</b> Estimate the ATE</a></li>
<li class="chapter" data-level="12.4" data-path="PScore3.html"><a href="PScore3.html#using-the-matchit-package"><i class="fa fa-check"></i><b>12.4</b> Using the MatchIt Package</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="PScore3.html"><a href="PScore3.html#examining-balance"><i class="fa fa-check"></i><b>12.4.1</b> Examining Balance</a></li>
<li class="chapter" data-level="12.4.2" data-path="PScore3.html"><a href="PScore3.html#estimate-the-effect"><i class="fa fa-check"></i><b>12.4.2</b> Estimate the Effect</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="PScore3.html"><a href="PScore3.html#matching"><i class="fa fa-check"></i><b>12.5</b> Matching</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="PScore3.html"><a href="PScore3.html#estimate-the-effect-1"><i class="fa fa-check"></i><b>12.5.1</b> Estimate the Effect</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Using R for Quasi-Experimental Designs</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="RD1" class="section level1" number="6">
<h1><span class="header-section-number">Part 6</span> Regression Discontinuity, Part 1</h1>
<p>Chapter 9 of Murnane and Willett <span class="citation">(<a href="#ref-murnane_methods_2011" role="doc-biblioref">2011</a>)</span> helps us see the underlying logic of regression discontinuity designs by helping us see the underlying assumptions and choices we face when we use a difference-in-differences strategy, and then taking us into an example with regression discontinuity in which we examine the functional form. Their chapter begins with several pedagogical examples of DID with the Maimonides data, which are from work conducted by Angrist and Lavy <span class="citation">(<a href="#ref-angrist_using_1999" role="doc-biblioref">1999</a>)</span> to investigate the effects of class size on achievement.</p>
<div id="objectives-4" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Objectives</h2>
<ol style="list-style-type: decimal">
<li>Strengthen our understanding of the underlying assumptions and choices in difference in differences.</li>
<li>Use this understanding to see the value of regression discontinuity designs.</li>
<li>Understand the decisions involved in a regression-discontinuity design, starting with functional form and bandwidth.</li>
<li>Use R code to estimate effects and generate plots.</li>
</ol>
</div>
<div id="import-and-prepare-the-data-1" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Import and Prepare the Data</h2>
<p>The data were available as a SAS data set from UCLA’s site, which I had then saved to a CSV file <em>Ch 09 angrist.csv</em> using the following code.</p>
<div class="sourceCode" id="cb494"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb494-1"><a href="RD1.html#cb494-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(sas7bdat) <span class="co"># package for reading SAS files</span></span>
<span id="cb494-2"><a href="RD1.html#cb494-2" aria-hidden="true" tabindex="-1"></a>  angrist <span class="ot">&lt;-</span> <span class="fu">read.sas7bdat</span>(<span class="st">&quot;https://stats.idre.ucla.edu/wp-content/uploads/2016/02/angrist.sas7bdat&quot;</span>)</span>
<span id="cb494-3"><a href="RD1.html#cb494-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write.csv</span>(angrist,<span class="at">file =</span> <span class="st">&quot;Ch 09 angrist.csv&quot;</span>,<span class="at">row.names =</span> F)</span></code></pre></div>
<p>Let’s import the data.</p>
<div class="sourceCode" id="cb495"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb495-1"><a href="RD1.html#cb495-1" aria-hidden="true" tabindex="-1"></a>ang <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;Ch 09 angrist.csv&quot;</span>)</span>
<span id="cb495-2"><a href="RD1.html#cb495-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ang)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    2019 obs. of  4 variables:
##  $ read             : num  58 82.6 46.3 66.6 75 ...
##  $ size             : int  8 9 9 9 10 10 10 10 11 11 ...
##  $ intended_classize: num  8 9 9 9 10 10 10 10 11 11 ...
##  $ observed_classize: int  8 9 9 11 10 10 10 10 11 17 ...</code></pre>
<p>And, let’s rename the columns:</p>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb497-1"><a href="RD1.html#cb497-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ang) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;read&quot;</span>,<span class="st">&quot;coh_size&quot;</span>,<span class="st">&quot;int_size&quot;</span>,<span class="st">&quot;obs_size&quot;</span>)</span>
<span id="cb497-2"><a href="RD1.html#cb497-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ang)</span></code></pre></div>
<pre><code>##    read coh_size int_size obs_size
## 1 58.00        8        8        8
## 2 82.63        9        9        9
## 3 46.33        9        9        9
## 4 66.56        9        9       11
## 5 75.00       10       10       10
## 6 80.56       10       10       10</code></pre>
<p>Each row in the data frame is a classroom, which is the unit of analysis. Here’s a description of the columns:</p>
<ul>
<li><code>read</code> is the class’s reading-achievement score. This is the outcome variable, measured (we assume) at the end of the academic year.</li>
<li><code>coh_size</code> is the cohort size, which is the number of students during the enrollment period at the start of the academic year.</li>
<li><code>int_size</code> is the intended class size, per the Maimonides rule.</li>
<li><code>obs_size</code> is the observed class size later in the academic year.</li>
</ul>
<p>The causal claim being investigated is whether the policy of splitting a large class into two smaller classes leads to higher reading achievement scores of the class.</p>
<p>Let’s make a group variable that represents the assignment variable based on Maimonides rule. Those cohorts containing over 40 students were split into two smaller classes and assigned to the <em>small</em> condition. We can think of the <em>small</em> status as being the treatment group, with <code>small = 1</code> for classes that were made smaller, per the exogenous Maimonides assignment rule, and <code>small = 0</code> for classes that were not made smaller.</p>
<div class="sourceCode" id="cb499"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb499-1"><a href="RD1.html#cb499-1" aria-hidden="true" tabindex="-1"></a>ang<span class="sc">$</span>small <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(ang<span class="sc">$</span>coh_size <span class="sc">&gt;</span> <span class="dv">40</span>,<span class="dv">1</span>,<span class="dv">0</span>)</span></code></pre></div>
<p>Let’s center the forcing variable, <em>coh_size</em>, which helps us to interpret the intercept. This is discussed on pp. 178–180.</p>
<div class="sourceCode" id="cb500"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb500-1"><a href="RD1.html#cb500-1" aria-hidden="true" tabindex="-1"></a>ang<span class="sc">$</span>csize <span class="ot">&lt;-</span> ang<span class="sc">$</span>coh_size<span class="dv">-41</span></span></code></pre></div>
<p>Let’s make a subset of the data that has cohort enrollment sizes between 36 and 46 students. This is to help us think through this demonstration. It also makes sense if we are examining the intent of the policy and its causal effect. Here, and in the rest of this code, we’re using the <code>subset()</code> function, but we could easily do this in other ways in R. Instead of that function, we could use indexing, such as <code>ang[ang$coh_size &gt;= 36 &amp; ang$coh_size &lt;= 46, ]</code> to achieve the same result.</p>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb501-1"><a href="RD1.html#cb501-1" aria-hidden="true" tabindex="-1"></a>ang3646 <span class="ot">&lt;-</span> <span class="fu">subset</span>(ang, coh_size <span class="sc">&gt;=</span> <span class="dv">36</span> <span class="sc">&amp;</span> coh_size <span class="sc">&lt;=</span> <span class="dv">46</span>)</span></code></pre></div>
<p>Let’s examine means of the classes’ reading scores by their enrollment size. We’ll use the <code>aggregate()</code> function to view this by cohort size. We looked at this in <a href="examine.html#aggregate_explain" target="_blank">a previous section of this tutorial</a>.</p>
<div class="sourceCode" id="cb502"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb502-1"><a href="RD1.html#cb502-1" aria-hidden="true" tabindex="-1"></a>ReadByM <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(read <span class="sc">~</span> coh_size, <span class="at">data =</span> ang3646, mean)</span>
<span id="cb502-2"><a href="RD1.html#cb502-2" aria-hidden="true" tabindex="-1"></a>ReadByM</span></code></pre></div>
<pre><code>##    coh_size     read
## 1        36 67.30445
## 2        37 68.94066
## 3        38 67.85400
## 4        39 68.87000
## 5        40 67.92847
## 6        41 73.67670
## 7        42 67.59560
## 8        43 77.17644
## 9        44 72.16160
## 10       45 76.91684
## 11       46 70.30814</code></pre>
<p>The following code creates Table 9.1 of Murnane and Willett.</p>
<blockquote>
<p>There’s a lot in this code and you can skip over it to get to the meat of the lesson. Basically, we’re using the <code>table()</code> function to get the number of observations at each cohort size. The output of that is a table, which we turn into a data frame. Because coh_size is a number but the <code>table()</code> function turned it into a factor, we turn it back into a numeric type variable using the <code>as.numeric(levels())</code> line of code. We then calculate the mean size of the classes by each cohort size, with <code>by(obs_size, coh_size, mean)</code>, which we make numeric and round. We identify what its treatment status is with the <code>NominalSize</code> variable. The last two variables are the mean (across classes) and standard deviations (across classes) at each cohort size.</p>
</blockquote>
<div class="sourceCode" id="cb504"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb504-1"><a href="RD1.html#cb504-1" aria-hidden="true" tabindex="-1"></a>T9<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">table</span>(ang3646<span class="sc">$</span>coh_size))</span>
<span id="cb504-2"><a href="RD1.html#cb504-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">names</span>(T9<span class="fl">.1</span>)   <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;coh_size&quot;</span>,<span class="st">&quot;freq&quot;</span>)</span>
<span id="cb504-3"><a href="RD1.html#cb504-3" aria-hidden="true" tabindex="-1"></a>   T9<span class="fl">.1</span><span class="sc">$</span>coh_size <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">levels</span>(T9<span class="fl">.1</span><span class="sc">$</span>coh_size))                         <span class="co">#Coercing the coh_size variable to be numeric instead of factor</span></span>
<span id="cb504-4"><a href="RD1.html#cb504-4" aria-hidden="true" tabindex="-1"></a>T9<span class="fl">.1</span><span class="sc">$</span>IntendedSize<span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">with</span>(ang3646, <span class="fu">by</span>(int_size, coh_size, mean)))   <span class="co">#The by() function to get the mean class size by each set of schools of cohort sizes 36 through 46</span></span>
<span id="cb504-5"><a href="RD1.html#cb504-5" aria-hidden="true" tabindex="-1"></a>T9<span class="fl">.1</span><span class="sc">$</span>ObservedSize<span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(<span class="fu">with</span>(ang3646, <span class="fu">by</span>(obs_size,coh_size, mean))),<span class="dv">1</span>)<span class="co">#The by() function again, also, rounded to 1 decimal place.</span></span>
<span id="cb504-6"><a href="RD1.html#cb504-6" aria-hidden="true" tabindex="-1"></a>T9<span class="fl">.1</span><span class="sc">$</span>NominalSize <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(T9<span class="fl">.1</span><span class="sc">$</span>coh_size<span class="sc">&gt;</span><span class="dv">40</span>,<span class="st">&quot;Small&quot;</span>,<span class="st">&quot;Large&quot;</span>)                  <span class="co">#Labeling schools that, by Maimonides Rule, split into two smaller classes (small)</span></span>
<span id="cb504-7"><a href="RD1.html#cb504-7" aria-hidden="true" tabindex="-1"></a>T9<span class="fl">.1</span><span class="sc">$</span>ReadByM     <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(<span class="fu">with</span>(ang3646, <span class="fu">by</span>(read,coh_size, mean))),    <span class="dv">2</span>)<span class="co">#Mean achievement by cohort (unit of analysis is classes, not students, so it&#39;s a mean among the classes&#39; means)</span></span>
<span id="cb504-8"><a href="RD1.html#cb504-8" aria-hidden="true" tabindex="-1"></a>T9<span class="fl">.1</span><span class="sc">$</span>ReadBySD    <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(<span class="fu">with</span>(ang3646, <span class="fu">by</span>(read,coh_size, sd))),      <span class="dv">2</span>)</span>
<span id="cb504-9"><a href="RD1.html#cb504-9" aria-hidden="true" tabindex="-1"></a>T9<span class="fl">.1</span></span></code></pre></div>
<pre><code>##    coh_size freq IntendedSize ObservedSize NominalSize ReadByM ReadBySD
## 1        36    9         36.0         27.4       Large   67.30    12.36
## 2        37    9         37.0         26.2       Large   68.94     8.50
## 3        38   10         38.0         33.1       Large   67.85    14.04
## 4        39   10         39.0         31.2       Large   68.87    12.07
## 5        40    9         40.0         29.9       Large   67.93     7.87
## 6        41   28         20.5         22.7       Small   73.68     8.77
## 7        42   25         21.0         23.4       Small   67.60     9.30
## 8        43   24         21.5         22.1       Small   77.18     7.47
## 9        44   17         22.0         24.4       Small   72.16     7.71
## 10       45   19         22.5         22.7       Small   76.92     8.71
## 11       46   20         23.0         22.6       Small   70.31     9.78</code></pre>
</div>
<div id="different-difference-in-differences" class="section level2" number="6.3">
<h2><span class="header-section-number">6.3</span> Different Difference in Differences</h2>
<div id="our-first-difference" class="section level3" number="6.3.1">
<h3><span class="header-section-number">6.3.1</span> Our first difference</h3>
<p>And now for something completely different (well, maybe not completely). Here is a simple first-difference analysis, which M &amp; W discussed on p. 170. Remember that this is a demonstration to help us think about RDD; it’s <em>not</em> the recommended analysis.</p>
<p>First, let’s subset our data to include only the first difference—the cohort sizes of 40 and 41. We can calculate the mean, by their treatment-group status.</p>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb506-1"><a href="RD1.html#cb506-1" aria-hidden="true" tabindex="-1"></a>ang4041 <span class="ot">&lt;-</span> <span class="fu">subset</span>(ang, coh_size <span class="sc">==</span> <span class="dv">40</span><span class="sc">|</span>coh_size <span class="sc">==</span> <span class="dv">41</span>)</span>
<span id="cb506-2"><a href="RD1.html#cb506-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(ang4041, <span class="fu">by</span>(read, small, mean))</span></code></pre></div>
<pre><code>## small: 0
## [1] 67.92847
## ------------------------------------------------------------ 
## small: 1
## [1] 73.6767</code></pre>
<p>Let’s fit a linear model on this, with <span class="math inline">\(\text{read} = \beta_0 + \beta_{1}\text{small} + \epsilon\)</span> as our regression equation.</p>
<div class="sourceCode" id="cb508"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb508-1"><a href="RD1.html#cb508-1" aria-hidden="true" tabindex="-1"></a>(fit4041 <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(read <span class="sc">~</span> small, <span class="at">data =</span> ang4041)))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = read ~ small, data = ang4041)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -18.3567  -4.6267  -0.3867   6.1533  15.5933 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   67.928      2.856  23.781   &lt;2e-16 ***
## small          5.748      3.283   1.751   0.0888 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.569 on 35 degrees of freedom
## Multiple R-squared:  0.08051,    Adjusted R-squared:  0.05424 
## F-statistic: 3.065 on 1 and 35 DF,  p-value: 0.08877</code></pre>
<p>Note that M &amp; W reported the <em>p</em>-value for a one-sided test but that the statistical test in our output is for the usual two-tailed test <span class="math inline">\(0.0888\)</span>, which is twice as large as what they reported. Usually, we do not report one-sided tests. In any case, if we really wanted to use code to get the one-sided <em>p</em>-value, we could get the estimate and the degrees of freedom from the output and put it inside the <code>pt()</code> function.</p>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb510-1"><a href="RD1.html#cb510-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(<span class="sc">-</span><span class="fu">abs</span>(fit4041<span class="sc">$</span>coefficients[<span class="dv">2</span>,<span class="dv">3</span>]), fit4041<span class="sc">$</span>df[<span class="dv">2</span>])</span></code></pre></div>
<pre><code>## [1] 0.04438463</code></pre>
<p>We’re comparing two cohorts of observations—those on either side of the Maimonides assignment cut-point. If we were to think that no other variables beyond the treatment assignment variable (<code>small</code>) were explaining the difference in reading achievement, we might stop here. There may be a pre-existing relationship, a secular trend, between the forcing variable and the outcome variable. Citing the original authors of the study (Angrist &amp; Lavy), M &amp; W point out that socio-economic status (SES) seems to be related to cohort size, regardless (arguably) of the treatment status. In the population in their study, students living in rural communities are typically of lower SES and these rural communities tend to have smaller cohort sizes. Given that SES is typically related to academic achievement outcomes, there is good reason to believe there is a secular trend.</p>
</div>
<div id="a-plausible-second-difference" class="section level3" number="6.3.2">
<h3><span class="header-section-number">6.3.2</span> A plausible second difference</h3>
<p>This part corresponds with Pages 172–173. We can roughly estimate this secular trend using the difference in means of cohorts of sizes 39 and 38, and subtract that from our first difference. Let’s subset the data to include these four cohorts and calculate the means of each. Note, that these two new cohorts are on the “control” side of the Maimonides assignment rule. Only one, of cohort size 41, was assigned to the treatment group.</p>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="RD1.html#cb512-1" aria-hidden="true" tabindex="-1"></a>ang3841 <span class="ot">&lt;-</span> <span class="fu">subset</span>(ang,coh_size <span class="sc">&gt;=</span> <span class="dv">38</span> <span class="sc">&amp;</span> coh_size <span class="sc">&lt;=</span> <span class="dv">41</span>)</span>
<span id="cb512-2"><a href="RD1.html#cb512-2" aria-hidden="true" tabindex="-1"></a>(ReadBy3841M <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(read <span class="sc">~</span> coh_size, <span class="at">data =</span> ang3841, mean))</span></code></pre></div>
<pre><code>##   coh_size     read
## 1       38 67.85400
## 2       39 68.87000
## 3       40 67.92847
## 4       41 73.67670</code></pre>
<p>We can use regression to estimate the difference in differences. Let’s create a new variable, called <code>larger</code> to distinguish the group with the larger enrollment within each pair. In this small example, the cohort with size 39 is larger than the cohort with 38. Likewise, the cohort of size 41 is larger than its counterpart of size 40. This variable is meant to capture the secular trend—that relationship between the forcing variable and reading achievement. This is the second difference.</p>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb514-1"><a href="RD1.html#cb514-1" aria-hidden="true" tabindex="-1"></a>ang3841<span class="sc">$</span>larger <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(ang3841<span class="sc">$</span>coh_size <span class="sc">==</span> <span class="dv">39</span> <span class="sc">|</span> ang3841<span class="sc">$</span>coh_size <span class="sc">==</span> <span class="dv">41</span>, <span class="dv">1</span>,<span class="dv">0</span>)</span></code></pre></div>
<p>For the first difference, we’ll also create a dummy variable, <code>firstdiff</code>. This is to distinguish the groups that participate in the first difference from those that are in the second difference.</p>
<div class="sourceCode" id="cb515"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb515-1"><a href="RD1.html#cb515-1" aria-hidden="true" tabindex="-1"></a>ang3841<span class="sc">$</span>firstdiff<span class="ot">&lt;-</span> <span class="fu">ifelse</span>(ang3841<span class="sc">$</span>coh_size <span class="sc">&gt;=</span> <span class="dv">40</span>, <span class="dv">1</span>,<span class="dv">0</span>)</span></code></pre></div>
<p>We’re interested in <span class="math inline">\(\beta_3\)</span> in</p>
<p><span class="math display" id="eq:DID1">\[\begin{equation}
\text{read} = \beta_0 + \beta_{1}\text{firstdiff} + \beta_{2}\text{larger} +  \beta_{3}(\text{firstdiff } \times \text{ larger}) + \epsilon \text{.}
  \tag{6.1}
\end{equation}\]</span></p>
<div class="sourceCode" id="cb516"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb516-1"><a href="RD1.html#cb516-1" aria-hidden="true" tabindex="-1"></a>(fit3841 <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(read <span class="sc">~</span> firstdiff<span class="sc">*</span>larger, <span class="at">data =</span> ang3841)))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = read ~ firstdiff * larger, data = ang3841)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.054  -4.267   1.753   6.853  15.796 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      67.85400    3.26658  20.772   &lt;2e-16 ***
## firstdiff         0.07447    4.74622   0.016    0.988    
## larger            1.01600    4.61963   0.220    0.827    
## firstdiff:larger  4.73223    6.08342   0.778    0.440    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.33 on 53 degrees of freedom
## Multiple R-squared:  0.07056,    Adjusted R-squared:  0.01795 
## F-statistic: 1.341 on 3 and 53 DF,  p-value: 0.2709</code></pre>
<p>The secular trend is purportedly captured by the second difference, which is estimated as <span class="math inline">\(\beta_{2} = 1.016\)</span>. The difference due to the policy is <span class="math inline">\(\beta_{3}\)</span>, estimated as <span class="math inline">\(4.732\)</span>, which has been adjusted for the 2nd difference. This is the same as Diff1 <span class="math inline">\(-\)</span> Diff2, or <span class="math inline">\((73.677 - 67.928) - (68.87 - 67.854)\)</span>. The standard error is a little different from that in the book because we’re using regression rather than the direct estimate.</p>
<p>We could plot these two differences. As we had done in the <a href="DID.html#plotfrompred" target="_blank">previous part of this tutorial</a>, we could create a new data set with the prototypical values, then use the <code>predict()</code> function on that data set to get the four points. Alternatively, we could plot the conditional means that we calculated from the <code>aggregate()</code> function.</p>
<div class="sourceCode" id="cb518"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb518-1"><a href="RD1.html#cb518-1" aria-hidden="true" tabindex="-1"></a>mynewdat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">firstdiff =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">larger  =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb518-2"><a href="RD1.html#cb518-2" aria-hidden="true" tabindex="-1"></a>preds    <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="fu">lm</span>(read <span class="sc">~</span> firstdiff<span class="sc">*</span>larger, <span class="at">data =</span> ang3841), </span>
<span id="cb518-3"><a href="RD1.html#cb518-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">newdata =</span> mynewdat)</span>
<span id="cb518-4"><a href="RD1.html#cb518-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">bty =</span> <span class="st">&quot;l&quot;</span>)</span>
<span id="cb518-5"><a href="RD1.html#cb518-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> <span class="dv">38</span><span class="sc">:</span><span class="dv">41</span>,</span>
<span id="cb518-6"><a href="RD1.html#cb518-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> preds,</span>
<span id="cb518-7"><a href="RD1.html#cb518-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;p&quot;</span>,</span>
<span id="cb518-8"><a href="RD1.html#cb518-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">36</span>,<span class="dv">43</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">65</span>,<span class="dv">75</span>),</span>
<span id="cb518-9"><a href="RD1.html#cb518-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb518-10"><a href="RD1.html#cb518-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;September cohort enrollment size&quot;</span>, </span>
<span id="cb518-11"><a href="RD1.html#cb518-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Verbal score (class avg)&quot;</span>,</span>
<span id="cb518-12"><a href="RD1.html#cb518-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">xaxt =</span> <span class="st">&quot;n&quot;</span>)</span>
<span id="cb518-13"><a href="RD1.html#cb518-13" aria-hidden="true" tabindex="-1"></a> <span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">38</span><span class="sc">:</span><span class="dv">41</span>, <span class="at">labels =</span> <span class="dv">38</span><span class="sc">:</span><span class="dv">41</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-270-1.png" width="672" /></p>
<p>Let’s connect this plot to the regression model and its parameter estimates.</p>
<ul>
<li><p>The intercept, <span class="math inline">\(\beta_0\)</span>, is <code>coef(fit3841)[1,1]</code>, which is the first point in our plot, because cohort 38 is coded as <code>firstdiff = 0</code> and <code>larger = 0</code>, making its predicted value <span class="math inline">\(\beta_0 + \beta_1(0) + \beta_2(0) + \beta_3(0 \times 0) = 67.854\)</span>.</p></li>
<li><p>Cohort 39 is coded as <code>firstdiff = 0</code> and <code>larger = 1</code>, making its predicted value <span class="math inline">\(\beta_0 + \beta_1(0) + \beta_2(1) + \beta_3(0 \times 1)\)</span>, which is <code>coef(fit3841)[1,1]</code> <span class="math inline">\(+\)</span> <code>coef(fit3841)[3,1]</code> 67.854 + 1.016 = 68.87.</p></li>
<li><p>Cohort 40 is coded as <code>firstdiff = 1</code> and <code>larger = 0</code>, so its predicted score <span class="math inline">\(\beta_0 + \beta_1(1) + \beta_2(0) + \beta_3(1 \times 0)\)</span>, or <code>coef(fit3841)[1,1]</code> <span class="math inline">\(+\)</span> <code>coef(fit3841)[2,1]</code> = 67.854 + 0.074 = 67.928.</p></li>
<li><p>Cohort 41 is coded as <code>firstdiff = 1</code> and <code>larger = 1</code>, which is <span class="math inline">\(\beta_0 + \beta_1(1) + \beta_2(1) + \beta_3(1 \times 1)\)</span>, which can be obtained with <code>sum(coef(fit3841)[ ,1])</code>, equaling <span class="math inline">\(73.677\)</span>.</p></li>
</ul>
<p>These estimates reproduce the mean reading-achievement scores per cluster that are reported in Table 9.1 of Murnane and Willett.</p>
<p>We can reproduce the first difference from the regression parameters. This is Cohort 41 <span class="math inline">\(-\)</span> Cohort 40, which is <span class="math display">\[\Big(\beta_0 + \beta_1(1) + \beta_2(1) + \beta_3(1 \times 1)\Big) - \Big(\beta_0 + \beta_1(1) + \beta_2(0) + \beta_3(1 \times 0)\Big)\]</span> <span class="math display">\[ = \text{(sum(coef(fit3841)[ ,1]))} - \text{sum(coef(fit3841)[1:2,1])} = 5.748 \text{ .}\]</span></p>
<p>Again, our parameter of interest is <span class="math inline">\(\beta_3\)</span>, which is the effect of being in the treatment group versus not, after adjusting for the secular trend that we have estimated based on the difference in reading-achievement scores in a similar pair of cohorts. That is, we believe—at this point, before seeing the value of an RDD—that given the reading-achievement changes due to a 1 unit increase in cohort size in this similar comparison, we can trust that we can remove that from our first difference to estimate the effect that is central to our research question.</p>
<p>We can see below how the parameters place in the plot, along with the first difference:</p>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-271-1.png" width="672" /></p>
</div>
<div id="another-plausible-second-difference" class="section level3" number="6.3.3">
<h3><span class="header-section-number">6.3.3</span> Another plausible second difference</h3>
<p>A problem with difference in differences with a data set like this is that there are many ways we could have estimated this second difference. For example, if we used a different pair of contiguous cohort sizes, such as cohorts of sizes 37 &amp; 38, our second difference would be different <span class="math inline">\((67.85 - 68.94 = -1.09)\)</span>, as discussed on p. 175. Here’s another plausible example, with cohorts of sizes 36 through 40 for the secular trend versus the first difference. Let’s subset this part of the data and then plot the means.</p>
<div class="sourceCode" id="cb519"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb519-1"><a href="RD1.html#cb519-1" aria-hidden="true" tabindex="-1"></a>ang3641  <span class="ot">&lt;-</span> <span class="fu">subset</span>(ang,coh_size <span class="sc">&gt;=</span> <span class="dv">36</span> <span class="sc">&amp;</span> coh_size <span class="sc">&lt;=</span> <span class="dv">41</span>)</span>
<span id="cb519-2"><a href="RD1.html#cb519-2" aria-hidden="true" tabindex="-1"></a>mread3640<span class="ot">&lt;-</span> <span class="fu">aggregate</span>(read<span class="sc">~</span>coh_size, <span class="at">data =</span> ang3641[ang3641<span class="sc">$</span>coh_size <span class="sc">&lt;</span> <span class="dv">41</span>, ], mean)</span>
<span id="cb519-3"><a href="RD1.html#cb519-3" aria-hidden="true" tabindex="-1"></a>mread41  <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(read<span class="sc">~</span>coh_size, <span class="at">data =</span> ang3641[ang3641<span class="sc">$</span>coh_size <span class="sc">==</span><span class="dv">41</span>, ], mean)</span></code></pre></div>
<p>The X and Y here are for printing the blue prediction line in the subsequet plot.</p>
<div class="sourceCode" id="cb520"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb520-1"><a href="RD1.html#cb520-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">36</span><span class="sc">:</span><span class="dv">41</span>)</span>
<span id="cb520-2"><a href="RD1.html#cb520-2" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="fu">lm</span>(read <span class="sc">~</span> coh_size, <span class="at">data =</span> mread3640),</span>
<span id="cb520-3"><a href="RD1.html#cb520-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">coh_size =</span> X))</span></code></pre></div>
<p>Here’s the plot:</p>
<div class="sourceCode" id="cb521"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb521-1"><a href="RD1.html#cb521-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">bty =</span> <span class="st">&quot;l&quot;</span>)</span>
<span id="cb521-2"><a href="RD1.html#cb521-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(mread3640, </span>
<span id="cb521-3"><a href="RD1.html#cb521-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">plot</span>(coh_size, read, </span>
<span id="cb521-4"><a href="RD1.html#cb521-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">65</span>,<span class="dv">75</span>), <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">36</span>,<span class="dv">43</span>),</span>
<span id="cb521-5"><a href="RD1.html#cb521-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb521-6"><a href="RD1.html#cb521-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;September cohort enrollment size&quot;</span>, </span>
<span id="cb521-7"><a href="RD1.html#cb521-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">ylab =</span> <span class="st">&quot;Verbal score (class avg)&quot;</span>,</span>
<span id="cb521-8"><a href="RD1.html#cb521-8" aria-hidden="true" tabindex="-1"></a>          <span class="fu">lines</span>(coh_size,read)))</span>
<span id="cb521-9"><a href="RD1.html#cb521-9" aria-hidden="true" tabindex="-1"></a>     <span class="fu">lines</span>(X,Y, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lty =</span> <span class="dv">3</span>)</span>
<span id="cb521-10"><a href="RD1.html#cb521-10" aria-hidden="true" tabindex="-1"></a>     <span class="fu">points</span>(mread41, <span class="at">pch =</span> <span class="dv">16</span>)</span>
<span id="cb521-11"><a href="RD1.html#cb521-11" aria-hidden="true" tabindex="-1"></a>     <span class="fu">text</span>(<span class="dv">41</span>, Y[<span class="dv">6</span>] <span class="sc">-</span> .<span class="dv">5</span>, <span class="st">&quot;Provisional projection</span><span class="sc">\n</span><span class="st">  for the class size of 41</span><span class="sc">\n</span><span class="st">  if no Maimonides rule</span><span class="sc">\n</span><span class="st">  were in place&quot;</span>, </span>
<span id="cb521-12"><a href="RD1.html#cb521-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">pos =</span> <span class="dv">4</span>,</span>
<span id="cb521-13"><a href="RD1.html#cb521-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb521-14"><a href="RD1.html#cb521-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> .<span class="dv">8</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-274-1.png" width="672" /></p>
<p>Here’s the linear model of this DID, per Table 9.3 on page 180. Notice that we’re using the <em>centered</em> cohort size (<code>csize</code>), which is <span class="math inline">\(\text{coh_size}-41\)</span>, as our forcing variable. We had created this above with <code>ang$csize &lt;- ang$coh_size-41</code>. This is so we can set the intercept at 41 (explained on pp. 178–180).</p>
<div class="sourceCode" id="cb522"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb522-1"><a href="RD1.html#cb522-1" aria-hidden="true" tabindex="-1"></a>(fit3641 <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(read <span class="sc">~</span> csize <span class="sc">+</span> small, <span class="at">data =</span> ang3641)))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = read ~ csize + small, data = ang3641)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.385  -4.519   1.581   7.004  17.113 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   68.557      3.511  19.523   &lt;2e-16 ***
## csize          0.124      1.068   0.116    0.908    
## small          5.120      4.005   1.279    0.205    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.19 on 72 degrees of freedom
## Multiple R-squared:  0.06624,    Adjusted R-squared:  0.0403 
## F-statistic: 2.554 on 2 and 72 DF,  p-value: 0.08481</code></pre>
<p>Interpreting this model’s coefficients, we can see that if the cohort of size 41 were <em>not</em> split into 2 classes, its estimated achievement would be <span class="math inline">\(68.56\)</span> (i.e., the intercept). This is our counterfactual. Being in a small class (e.g., of size 20 or 21 from a cohort of size 41), is estimated to have an effect of <span class="math inline">\(5.12\)</span> points on the reading achievement test, but the standard error is large in comparison, <span class="math inline">\(4\)</span>. Recall from Table 9.1 that the cohort of size 41 has only 28 observations, so there’s not a lot to work with in regard to statistical power; also, the variance is pretty big, with <span class="math inline">\(SD = 8.77 \therefore Var = 8.77^2 = 76.9129\)</span>.</p>
<p>At this point, we are strictly speaking not using a difference-in-differences strategy, but something better. By including these five points before the cut-off, we are now getting a better estimate of the secular trend—specifically, one that is less affected by the idiosyncratic variation that otherwise would not have been noticed if we had used only a pair of points as a second difference.</p>
</div>
</div>
<div id="mread3640" class="section level2" number="6.4">
<h2><span class="header-section-number">6.4</span> Broadening the bandwidth</h2>
<p>The <code>fit3641</code> analysis did not use information on the right side of the discontinuity. It was a single point. Let’s use more information on the right side to see if we can better estimate the secular trend (the second difference). We can use this equation, which is from Equation 9.1 in Murnane and Willett (p. 179),</p>
<p><span class="math display" id="eq:DID2">\[\begin{equation}
\text{read} = \beta_0 + \beta_{1}\text{csize} + \beta_{2}\text{small} + \epsilon \text{.}
  \tag{6.2}
\end{equation}\]</span></p>
<p>Here is Table 9.4 on page 183. Now, we’re using our data set that is represented in Table 9.1, with all cohorts from size 36 through 46.</p>
<div class="sourceCode" id="cb524"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb524-1"><a href="RD1.html#cb524-1" aria-hidden="true" tabindex="-1"></a>fit3646 <span class="ot">&lt;-</span> (<span class="fu">lm</span>(read <span class="sc">~</span> csize <span class="sc">+</span> small, <span class="at">data =</span> ang3646))</span>
<span id="cb524-2"><a href="RD1.html#cb524-2" aria-hidden="true" tabindex="-1"></a>(fit3646out <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit3646))</span>
<span id="cb524-3"><a href="RD1.html#cb524-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(<span class="sc">-</span><span class="fu">abs</span>(fit3646out<span class="sc">$</span>coefficients[<span class="dv">3</span>,<span class="dv">3</span>]), fit3646out<span class="sc">$</span>df[<span class="dv">2</span>]) <span class="co"># one-tailed p-value</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = read ~ csize + small, data = ang3646)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.384  -5.466   1.312   7.184  17.208 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  68.6957     1.9178  35.821   &lt;2e-16 ***
## csize         0.1707     0.4360   0.391    0.696    
## small         3.8472     2.8112   1.368    0.173    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.674 on 177 degrees of freedom
## Multiple R-squared:  0.04579,    Adjusted R-squared:  0.035 
## F-statistic: 4.246 on 2 and 177 DF,  p-value: 0.0158
## 
## [1] 0.08644695</code></pre>
<p>We can see the effect is not statistically significant.</p>
<p>We can examine the plot of this analysis, along with the projected (counterfactual) estimate if the large-class cohorts’ classes were NOT split at size 41. First, let’s create mean points that we can use in the subsequent plot.</p>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb526-1"><a href="RD1.html#cb526-1" aria-hidden="true" tabindex="-1"></a>mread3640 <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(read <span class="sc">~</span> csize, </span>
<span id="cb526-2"><a href="RD1.html#cb526-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> ang3646[ang3646<span class="sc">$</span>coh_size <span class="sc">&lt;</span>  <span class="dv">41</span>, ], mean)</span>
<span id="cb526-3"><a href="RD1.html#cb526-3" aria-hidden="true" tabindex="-1"></a>mread4146 <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(read <span class="sc">~</span> csize, </span>
<span id="cb526-4"><a href="RD1.html#cb526-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> ang3646[ang3646<span class="sc">$</span>coh_size <span class="sc">&gt;=</span> <span class="dv">41</span>, ], mean)</span></code></pre></div>
<p>Let’s create the Xs and Ys to use in prediction lines in the subsequent plot. Here is the left side prediction (cohorts of size 36 to 40):</p>
<div class="sourceCode" id="cb527"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb527-1"><a href="RD1.html#cb527-1" aria-hidden="true" tabindex="-1"></a>X3641 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">csize =</span> <span class="fu">c</span>(<span class="dv">36</span><span class="sc">:</span><span class="dv">41-41</span>))     <span class="co">#Note that the cohort size of 41 (csize = 0) is counterfactual.</span></span>
<span id="cb527-2"><a href="RD1.html#cb527-2" aria-hidden="true" tabindex="-1"></a>X3641<span class="sc">$</span>small <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(X3641<span class="sc">$</span>csize) )  <span class="co">#Each observation is specified as being in the large-class grp.</span></span>
<span id="cb527-3"><a href="RD1.html#cb527-3" aria-hidden="true" tabindex="-1"></a>Y3641   <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit3646, <span class="at">newdata =</span> X3641) <span class="co">#Predicted avg reading score of the class</span></span></code></pre></div>
<p>Here’s the right side prediction (cohorts of size 41 to 46):</p>
<div class="sourceCode" id="cb528"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb528-1"><a href="RD1.html#cb528-1" aria-hidden="true" tabindex="-1"></a>X4146 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">csize =</span> <span class="fu">c</span>(<span class="dv">41</span><span class="sc">:</span><span class="dv">46-41</span>)) </span>
<span id="cb528-2"><a href="RD1.html#cb528-2" aria-hidden="true" tabindex="-1"></a>X4146<span class="sc">$</span>small <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">length</span>(X4146<span class="sc">$</span>csize) ) <span class="co">#Each observation is specified as being in the SMALL-class grp.</span></span>
<span id="cb528-3"><a href="RD1.html#cb528-3" aria-hidden="true" tabindex="-1"></a>Y4146   <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit3646, <span class="at">newdata =</span> X4146)</span></code></pre></div>
<p>Let’s create a regular plot with one of the groups. We’ll add the other group’s mean points, next.</p>
<div class="sourceCode" id="cb529"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb529-1"><a href="RD1.html#cb529-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">bty =</span> <span class="st">&quot;l&quot;</span>)</span>
<span id="cb529-2"><a href="RD1.html#cb529-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(mread3640,              </span>
<span id="cb529-3"><a href="RD1.html#cb529-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(csize, read, </span>
<span id="cb529-4"><a href="RD1.html#cb529-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylim=</span> <span class="fu">c</span>(<span class="dv">65</span>,<span class="dv">79</span>), </span>
<span id="cb529-5"><a href="RD1.html#cb529-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlim=</span> <span class="fu">c</span>(<span class="dv">36</span>,<span class="dv">47</span>)<span class="sc">-</span><span class="dv">41</span>,</span>
<span id="cb529-6"><a href="RD1.html#cb529-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch=</span><span class="dv">18</span>,</span>
<span id="cb529-7"><a href="RD1.html#cb529-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">&quot;September cohort enrollment size (centered)&quot;</span>, </span>
<span id="cb529-8"><a href="RD1.html#cb529-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">&quot;Verbal score (class avg)&quot;</span>,</span>
<span id="cb529-9"><a href="RD1.html#cb529-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">&quot;Slopes on both sides specified as equal&quot;</span>,</span>
<span id="cb529-10"><a href="RD1.html#cb529-10" aria-hidden="true" tabindex="-1"></a>       <span class="fu">lines</span>(csize, read)))</span>
<span id="cb529-11"><a href="RD1.html#cb529-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(X3641<span class="sc">$</span>csize,Y3641, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)   <span class="co"># The linear fit of the observed &quot;large&quot; class group</span></span>
<span id="cb529-12"><a href="RD1.html#cb529-12" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(mread4146<span class="sc">$</span>csize,mread4146<span class="sc">$</span>read,<span class="at">pch=</span><span class="dv">18</span>) <span class="co"># Mean estimates of cohort sizes of 41 to 46</span></span>
<span id="cb529-13"><a href="RD1.html#cb529-13" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(mread4146<span class="sc">$</span>csize,mread4146<span class="sc">$</span>read)  <span class="co"># The linear fit of the observed &quot;small&quot; class group</span></span>
<span id="cb529-14"><a href="RD1.html#cb529-14" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(X4146<span class="sc">$</span>csize,Y4146, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span>
<span id="cb529-15"><a href="RD1.html#cb529-15" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>,<span class="at">h=</span><span class="cn">NULL</span>,<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-280-1.png" width="672" /></p>
<p>It appears as though there is a discontinuity; however, the LATE of <code>small</code> was not statistically significant. This is a rudimentary regression discontinuity analysis.</p>
</div>
<div id="summary-up-to-this-point" class="section level2" number="6.5">
<h2><span class="header-section-number">6.5</span> Summary up to this point</h2>
<p>This example was presented to illustrate how to think about regression discontinuity designs. The above analysis assumes that</p>
<ol style="list-style-type: lower-alpha">
<li>the secular relationship between cohort size and achievement is linear and</li>
<li>this linearity is the same on both sides of the discontinuity.</li>
</ol>
<p>This is an RDD. The forcing variable is the unit’s cohort size. The treatment variable is whether the unit was assigned to be in a small-class condition or a large-class condition, the latter being thought of as the control group in this example. The general model of this RDD is an ANCOVA,<a href="#fn31" class="footnote-ref" id="fnref31"><sup>31</sup></a></p>
<p><span class="math display" id="eq:ANCOVAeq">\[\begin{eqnarray}
\text{Y}_i = \beta_0 + \beta_1\text{X}_{c_i} +  \beta_2\text{Z}_i + \epsilon_i \text{ ,}
  \tag{6.3}
\end{eqnarray}\]</span></p>
<p>with <span class="math inline">\(\text{X}_{c_i}\)</span> representing unit <span class="math inline">\(i\)</span>’s location on the centered forcing variable, and <span class="math inline">\(\text{Z}_i\)</span> representing unit <span class="math inline">\(i\)</span>’s treatment assignment.<a href="#fn32" class="footnote-ref" id="fnref32"><sup>32</sup></a></p>
<p>ANCOVA assumes that the residual variances are the same in the two levels of the treatment factor. In other words, it assumes that there is not an interaction term that would otherwise explain that variance. In our analysis, we would accept this model if we believed the functional form were the same slope on both sides of the forcing variable. We are also assuming that the functional form is linear.</p>
<p>In the next sections, we investigate three additional questions in RDD: Whether the functional form is the same on both sides of the equation, whether the functional form is curvilinear, and what bandwidth of the analysis we might use.</p>
<p>To investigate unequal functional form, we will include the interaction between the forcing variable and the treatment variable. To investigate curvilinear functional form, we will specify the forcing variable as quadratic, cubic, and so forth. To address bandwidth, we’ll first think about whether we would obtain the same conclusions if we extended the bandwidth. There are data-driven techniques for finding a so-called optimal bandwidth, using some optimizer techniques that are available in R packages, but ultimately our decision about which bandwidth to focus on rests with our understanding of the data and the context.</p>
</div>
<div id="examining-if-the-results-are-consistent-with-different-bandwidths" class="section level2" number="6.6">
<h2><span class="header-section-number">6.6</span> Examining if the results are consistent with different bandwidths</h2>
<p>Table 9.5 on p. 184 presents a bunch of estimates from different analytic window widths. The following syntax produces the coefficients from these different widths:</p>
<div class="sourceCode" id="cb530"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb530-1"><a href="RD1.html#cb530-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(read<span class="sc">~</span>csize <span class="sc">+</span> small, <span class="at">data =</span> ang3641))</span>
<span id="cb530-2"><a href="RD1.html#cb530-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(read<span class="sc">~</span>csize <span class="sc">+</span> small, <span class="at">data =</span> <span class="fu">subset</span>(ang, coh_size<span class="sc">&gt;=</span><span class="dv">35</span> <span class="sc">&amp;</span> coh_size<span class="sc">&lt;=</span><span class="dv">47</span>))) <span class="co">#Analytic window of 6 cohort-size points on either side of the cut</span></span>
<span id="cb530-3"><a href="RD1.html#cb530-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(read<span class="sc">~</span>csize <span class="sc">+</span> small, <span class="at">data =</span> <span class="fu">subset</span>(ang, coh_size<span class="sc">&gt;=</span><span class="dv">34</span> <span class="sc">&amp;</span> coh_size<span class="sc">&lt;=</span><span class="dv">48</span>)))</span>
<span id="cb530-4"><a href="RD1.html#cb530-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(read<span class="sc">~</span>csize <span class="sc">+</span> small, <span class="at">data =</span> <span class="fu">subset</span>(ang, coh_size<span class="sc">&gt;=</span><span class="dv">32</span> <span class="sc">&amp;</span> coh_size<span class="sc">&lt;=</span><span class="dv">50</span>))) </span>
<span id="cb530-5"><a href="RD1.html#cb530-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(read<span class="sc">~</span>csize <span class="sc">+</span> small, <span class="at">data =</span> <span class="fu">subset</span>(ang, coh_size<span class="sc">&gt;=</span><span class="dv">31</span> <span class="sc">&amp;</span> coh_size<span class="sc">&lt;=</span><span class="dv">51</span>))) <span class="co">#Analytic window of 10 cohort-size points</span></span>
<span id="cb530-6"><a href="RD1.html#cb530-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(read<span class="sc">~</span>csize <span class="sc">+</span> small, <span class="at">data =</span> <span class="fu">subset</span>(ang, coh_size<span class="sc">&gt;=</span><span class="dv">30</span> <span class="sc">&amp;</span> coh_size<span class="sc">&lt;=</span><span class="dv">52</span>)))</span>
<span id="cb530-7"><a href="RD1.html#cb530-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(read<span class="sc">~</span>csize <span class="sc">+</span> small, <span class="at">data =</span> <span class="fu">subset</span>(ang, coh_size<span class="sc">&gt;=</span><span class="dv">29</span> <span class="sc">&amp;</span> coh_size<span class="sc">&lt;=</span><span class="dv">53</span>))) <span class="co">#Analytic window of 12 cohort-size points</span></span></code></pre></div>
<p>This output is suppressed here. You could generate a table from each analysis using code such as this:</p>
<div class="sourceCode" id="cb531"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb531-1"><a href="RD1.html#cb531-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">BWidth =</span> <span class="fu">rep</span>(<span class="st">&quot;36,41&quot;</span>, <span class="dv">2</span>), <span class="fu">summary</span>(<span class="fu">lm</span>(read<span class="sc">~</span>csize <span class="sc">+</span> small, <span class="at">data =</span> ang3641))<span class="sc">$</span>coefficients[<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span></code></pre></div>
<pre><code>##       BWidth  Estimate Std..Error
## csize  36,41 0.1239759   1.068103
## small  36,41 5.1201262   4.004709</code></pre>
<p>The purpose of doing this is not for <em>p</em>-hacking. It is to see if our conclusions about the effects are stable across analyses that have different analytic window widths. We can think of this as a sensitivity analysis, given the varying bandwidths.</p>
</div>
<div id="functional-form-in-rdd" class="section level2" number="6.7">
<h2><span class="header-section-number">6.7</span> Functional Form in RDD</h2>
<p>A second question we might have is whether permitting the difference in slope on the two sides of the discontinuity will yield a more precise estimate of the effect. The formula for this adds an interaction term to what is now a general linear model:<a href="#fn33" class="footnote-ref" id="fnref33"><sup>33</sup></a></p>
<p><span class="math display" id="eq:RDDslopesdiffer">\[\begin{eqnarray}
\text{Y}_i = \beta_0 + \beta_1\text{X}_{c_i} + \beta_2\text{Z}_i +  \beta_{3}(\text{X}_{c_i} \times \text{Z}_i) + \epsilon_i \text{ ,}
  \tag{6.4}
\end{eqnarray}\]</span></p>
<p>which with our data set is represented by this equation:</p>
<p><span class="math display">\[\text{read}_i = \beta_0 + \beta_{1}\text{csize}_i + \beta_{2}\text{small}_i +  \beta_{3}(\text{csize}_i \times \text{small}_i) + \epsilon_i \text{.}\]</span>
with <span class="math inline">\(i\)</span> being the unit of analysis—each row in the data set, each of which is a classroom.
This is equivalent to Equation 9.6 in our Chapter, but applied to the Angrist data (instead of the Head Start data). Note that it differs from the previous analysis (Eq. 9.1 in the book) in that it allows the right- and left-side slopes to differ. We’re still interested in the parameter, <code>small</code>, but now it is estimated after controlling for the difference in slopes, as captured by the <code>small:size</code> interaction.</p>
<div class="sourceCode" id="cb533"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb533-1"><a href="RD1.html#cb533-1" aria-hidden="true" tabindex="-1"></a>fitslopes3646 <span class="ot">&lt;-</span> <span class="fu">lm</span>(read <span class="sc">~</span> csize<span class="sc">*</span>small, ang3646)</span>
<span id="cb533-2"><a href="RD1.html#cb533-2" aria-hidden="true" tabindex="-1"></a>(fitslopes3646out <span class="ot">&lt;-</span> <span class="fu">summary</span>(fitslopes3646))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = read ~ csize * small, data = ang3646)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.385  -5.474   1.299   7.181  17.186 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 68.55657    3.34377  20.503   &lt;2e-16 ***
## csize        0.12398    1.01708   0.122    0.903    
## small        3.96239    3.61685   1.096    0.275    
## csize:small  0.05729    1.12648   0.051    0.959    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.701 on 176 degrees of freedom
## Multiple R-squared:  0.0458, Adjusted R-squared:  0.02953 
## F-statistic: 2.816 on 3 and 176 DF,  p-value: 0.04067</code></pre>
<p>Notice that the <em>R</em><sup>2</sup> of the two models is the same and that the estimate of the interaction between the forcing variable and the treatment is very small in comparison to its standard error (thereby yielding a low test statistic).</p>
<div id="plotting-the-two-sides-allowing-different-slopes" class="section level3" number="6.7.1">
<h3><span class="header-section-number">6.7.1</span> Plotting the two sides, allowing different slopes</h3>
<p>Let’s plot this analysis. Most of the code here is the same as the previous plot. The difference is in the model used for the predictions (<code>Y3641M2</code> and <code>Y4146M2</code>) and in the resulting line plots.</p>
<p>Here is the left-side prediction, where each observation is specified as being in the large-class group (the control condition). Note that the cohort size of 41 is included even though it was in the treatment condition (<code>small = 1</code>) in the real data; here, we’re modeling its counterfactual—what the model predicts its reading achievement to be if it were in the control group.</p>
<div class="sourceCode" id="cb535"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb535-1"><a href="RD1.html#cb535-1" aria-hidden="true" tabindex="-1"></a>X3641 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">csize=</span><span class="fu">c</span>(<span class="dv">36</span><span class="sc">:</span><span class="dv">41</span> <span class="sc">-</span> <span class="dv">41</span>)) </span>
<span id="cb535-2"><a href="RD1.html#cb535-2" aria-hidden="true" tabindex="-1"></a>X3641<span class="sc">$</span>small <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(X3641<span class="sc">$</span>csize) ) <span class="co"># Each observation is specified as being in the control group</span></span>
<span id="cb535-3"><a href="RD1.html#cb535-3" aria-hidden="true" tabindex="-1"></a>Y3641M2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fitslopes3646, </span>
<span id="cb535-4"><a href="RD1.html#cb535-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">newdata =</span> X3641)</span></code></pre></div>
<p>Here is the right-side prediction, where each observation is specified as being in the small-class group (the treatment condition).</p>
<div class="sourceCode" id="cb536"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb536-1"><a href="RD1.html#cb536-1" aria-hidden="true" tabindex="-1"></a>X4146 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">csize=</span><span class="fu">c</span>(<span class="dv">41</span><span class="sc">:</span><span class="dv">46-41</span>)) <span class="co"># (Note that the cohort size of 41 (csize = 0) is counterfactual)</span></span>
<span id="cb536-2"><a href="RD1.html#cb536-2" aria-hidden="true" tabindex="-1"></a>  X4146<span class="sc">$</span>small <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">length</span>(X4146<span class="sc">$</span>csize) ) <span class="co"># Each observation is specified as being in the treatment group</span></span>
<span id="cb536-3"><a href="RD1.html#cb536-3" aria-hidden="true" tabindex="-1"></a>  Y4146M2 <span class="ot">&lt;-</span><span class="fu">predict</span>(fitslopes3646, <span class="at">newdata=</span>X4146)  </span></code></pre></div>
<p>Let’s plot these two sides. To plot the points, we’re using <code>mread3640</code>, which we had created <a href="RD1.html#mread3640">above</a> using the <code>aggregate()</code> function.</p>
<div class="sourceCode" id="cb537"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb537-1"><a href="RD1.html#cb537-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(mread3640,</span>
<span id="cb537-2"><a href="RD1.html#cb537-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">plot</span>(csize, read, </span>
<span id="cb537-3"><a href="RD1.html#cb537-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">65</span>,<span class="dv">79</span>), <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">36</span>,<span class="dv">47</span>)<span class="sc">-</span><span class="dv">41</span>, </span>
<span id="cb537-4"><a href="RD1.html#cb537-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">pch=</span><span class="dv">18</span>,</span>
<span id="cb537-5"><a href="RD1.html#cb537-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;September cohort enrollment size (centered)&quot;</span>,</span>
<span id="cb537-6"><a href="RD1.html#cb537-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">ylab =</span> <span class="st">&quot;Verbal score (class avg)&quot;</span>,</span>
<span id="cb537-7"><a href="RD1.html#cb537-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">main =</span> <span class="st">&quot;Slope on each side is estimated separately&quot;</span>,</span>
<span id="cb537-8"><a href="RD1.html#cb537-8" aria-hidden="true" tabindex="-1"></a>          <span class="fu">lines</span>(csize,read)))</span>
<span id="cb537-9"><a href="RD1.html#cb537-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(X3641<span class="sc">$</span>csize,Y3641M2, <span class="at">col =</span> <span class="st">&quot;brown&quot;</span>)           <span class="co">#Now, the linear fit of the observed &quot;large&quot; class group</span></span>
<span id="cb537-10"><a href="RD1.html#cb537-10" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(mread4146<span class="sc">$</span>csize,mread4146<span class="sc">$</span>read, <span class="at">pch =</span> <span class="dv">18</span>) <span class="co">#Mean estimates of cohort sizes of 41 to 46</span></span>
<span id="cb537-11"><a href="RD1.html#cb537-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(mread4146<span class="sc">$</span>csize,mread4146<span class="sc">$</span>read) <span class="co">#The linear fit of the observed &quot;small&quot; class group</span></span>
<span id="cb537-12"><a href="RD1.html#cb537-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(X4146<span class="sc">$</span>csize,Y4146M2, <span class="at">col=</span><span class="st">&quot;darkcyan&quot;</span>)</span>
<span id="cb537-13"><a href="RD1.html#cb537-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>,<span class="at">h=</span><span class="cn">NULL</span>,<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-286-1.png" width="672" /></p>
<p>It appears as though including the varying slopes changes the graph only slightly, which makes sense because the <code>csize:small</code> interaction <span class="math inline">\((\beta_3)\)</span> was tiny, and the <em>R</em><sup>2</sup> of the two models was the same. We should stick with the simpler equation if we plan to use this analytic window (36 to 46) for our analysis.</p>
</div>
<div id="broader-analytic-windows" class="section level3" number="6.7.2">
<h3><span class="header-section-number">6.7.2</span> Broader analytic windows</h3>
<p>What about that broader bandwidth from sizes 29 to 53? Let’s create a subsample for this analysis:</p>
<div class="sourceCode" id="cb538"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb538-1"><a href="RD1.html#cb538-1" aria-hidden="true" tabindex="-1"></a>ang2953 <span class="ot">&lt;-</span> <span class="fu">subset</span>(ang, coh_size <span class="sc">&gt;=</span> <span class="dv">29</span> <span class="sc">&amp;</span> coh_size <span class="sc">&lt;=</span> <span class="dv">53</span>)</span></code></pre></div>
<p>Let’s fit a linear model, with the same slope on both sides:</p>
<div class="sourceCode" id="cb539"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb539-1"><a href="RD1.html#cb539-1" aria-hidden="true" tabindex="-1"></a>fit2953 <span class="ot">&lt;-</span> <span class="fu">lm</span>(read<span class="sc">~</span> csize <span class="sc">+</span> small,<span class="at">data=</span>ang2953) </span>
<span id="cb539-2"><a href="RD1.html#cb539-2" aria-hidden="true" tabindex="-1"></a>(fit2953out <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit2953))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = read ~ csize + small, data = ang2953)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -35.736  -5.880   1.698   6.682  18.630 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  70.1188     1.1512  60.908   &lt;2e-16 ***
## csize        -0.1392     0.1191  -1.168   0.2433    
## small         3.9531     1.7996   2.197   0.0286 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.182 on 420 degrees of freedom
## Multiple R-squared:  0.01456,    Adjusted R-squared:  0.009869 
## F-statistic: 3.103 on 2 and 420 DF,  p-value: 0.04594</code></pre>
<p>And, let’s fit a linear model, with slopes free to differ on both sides:</p>
<div class="sourceCode" id="cb541"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb541-1"><a href="RD1.html#cb541-1" aria-hidden="true" tabindex="-1"></a>fitslopes2953 <span class="ot">&lt;-</span> <span class="fu">lm</span>(read <span class="sc">~</span> csize<span class="sc">*</span>small, <span class="at">data =</span> ang2953)</span>
<span id="cb541-2"><a href="RD1.html#cb541-2" aria-hidden="true" tabindex="-1"></a>(fitslopes2953out <span class="ot">&lt;-</span> <span class="fu">summary</span>(fitslopes2953))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = read ~ csize * small, data = ang2953)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.710  -5.954   1.711   6.735  17.272 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  66.3361     1.8160  36.529  &lt; 2e-16 ***
## csize        -0.7246     0.2484  -2.917  0.00372 ** 
## small         6.6924     2.0582   3.252  0.00124 ** 
## csize:small   0.7570     0.2824   2.680  0.00764 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.115 on 419 degrees of freedom
## Multiple R-squared:  0.03117,    Adjusted R-squared:  0.02424 
## F-statistic: 4.494 on 3 and 419 DF,  p-value: 0.004058</code></pre>
<p>This bandwidth is probably <strong>not</strong> the most appropriate but these results help us to see how the estimates and functional forms can differ.<a href="#fn34" class="footnote-ref" id="fnref34"><sup>34</sup></a></p>
<div id="curvilinear-functional-form" class="section level4" number="6.7.2.1">
<h4><span class="header-section-number">6.7.2.1</span> Curvilinear functional form</h4>
<p>Using this same really broad analytic window, let’s check out a quadratic model, again allowing each side to have a different functional form. The quadratic model has this equation:</p>
<p><span class="math display" id="eq:RDDQuadGenrl">\[\begin{eqnarray}
\text{Y}_i = \beta_0 + \beta_{1}\text{X}_{c_i} + \beta_{2}\text{Z}_i + \beta_{3}\text{X}_{c_i}^2 +  \beta_{4}\text{X}_{c_i}\text{Z}_i + \beta_{5}\text{X}_{c_i}^2\text{Z}_i + \epsilon_i \text{ ,}
  \tag{6.5}
\end{eqnarray}\]</span></p>
<p>which with our variables, is this:</p>
<p><span class="math display">\[\begin{eqnarray}
\text{read}_i = \beta_0 + \beta_{1}\text{csize}_i + \beta_{2}\text{small}_i + \beta_{3}\text{csize}_i^2 +  \beta_{4}(\text{csize}_i \times \text{small}_i) + \beta_{5}(\text{csize}_i^2 \times \text{small}_i) + \epsilon_i
\end{eqnarray}\]</span></p>
<p>In the <code>lm()</code> function, notice that we’re using the <code>I()</code> function in the formula, as in <code>I(csize^2)</code>. This tells R to first calculate the stuff within it before using it as a variable in the formula. We could achieve the same result if we added a new column to the data, such as <code>ang2953$csize_squared &lt;- csize^2</code> and used that new variable in the formula, such as <code>read ~ csize*small + csize_squared*small</code>.</p>
<div class="sourceCode" id="cb543"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb543-1"><a href="RD1.html#cb543-1" aria-hidden="true" tabindex="-1"></a>fitslopesQ2953 <span class="ot">&lt;-</span> <span class="fu">lm</span>(read <span class="sc">~</span> csize<span class="sc">*</span>small <span class="sc">+</span> <span class="fu">I</span>(csize<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span>small, <span class="at">data=</span>ang2953)</span>
<span id="cb543-2"><a href="RD1.html#cb543-2" aria-hidden="true" tabindex="-1"></a>(fitslopesQ2953out <span class="ot">&lt;-</span> <span class="fu">summary</span>(fitslopesQ2953))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = read ~ csize * small + I(csize^2) * small, data = ang2953)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.732  -5.993   1.578   6.818  17.877 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      67.22345    3.05881  21.977   &lt;2e-16 ***
## csize            -0.35030    1.06771  -0.328    0.743    
## small             4.66865    3.31609   1.408    0.160    
## I(csize^2)        0.02865    0.07947   0.360    0.719    
## csize:small       1.03562    1.17885   0.878    0.380    
## small:I(csize^2) -0.08325    0.08908  -0.935    0.351    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.115 on 417 degrees of freedom
## Multiple R-squared:  0.03573,    Adjusted R-squared:  0.02417 
## F-statistic:  3.09 on 5 and 417 DF,  p-value: 0.009437</code></pre>
<p>Let’s look at a cubic form on each side:</p>
<div class="sourceCode" id="cb545"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb545-1"><a href="RD1.html#cb545-1" aria-hidden="true" tabindex="-1"></a>fitslopesC2953 <span class="ot">&lt;-</span> <span class="fu">lm</span>(read<span class="sc">~</span> csize<span class="sc">*</span>small <span class="sc">+</span> <span class="fu">I</span>(csize<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span>small <span class="sc">+</span> <span class="fu">I</span>(csize<span class="sc">^</span><span class="dv">3</span>)<span class="sc">*</span>small, <span class="at">data=</span>ang2953)</span>
<span id="cb545-2"><a href="RD1.html#cb545-2" aria-hidden="true" tabindex="-1"></a>(fitslopesC2953out <span class="ot">&lt;-</span> <span class="fu">summary</span>(fitslopesC2953))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = read ~ csize * small + I(csize^2) * small + I(csize^3) * 
##     small, data = ang2953)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.310  -6.220   1.487   6.790  18.517 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      69.10337    4.94856  13.964   &lt;2e-16 ***
## csize             1.09145    3.16680   0.345    0.731    
## small             3.41951    5.17035   0.661    0.509    
## I(csize^2)        0.29417    0.55472   0.530    0.596    
## I(csize^3)        0.01356    0.02804   0.484    0.629    
## csize:small      -1.28851    3.38419  -0.381    0.704    
## small:I(csize^2) -0.15580    0.60455  -0.258    0.797    
## small:I(csize^3) -0.02425    0.03096  -0.783    0.434    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.127 on 415 degrees of freedom
## Multiple R-squared:  0.03781,    Adjusted R-squared:  0.02158 
## F-statistic:  2.33 on 7 and 415 DF,  p-value: 0.02429</code></pre>
</div>
<div id="comparing-models-with-different-functional-forms" class="section level4" number="6.7.2.2">
<h4><span class="header-section-number">6.7.2.2</span> Comparing models with different functional forms</h4>
<p>Let’s examine fit statistics to see which functional form fits best. We can compare models with the <code>AIC()</code> and <code>BIC()</code> functions. With the Akaike information criterion (AIC) and Bayesian version (BIC), lower implies less error, and better fit. The Bayesian version is useful to see if the results are the same as in the AIC.</p>
<div class="sourceCode" id="cb547"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb547-1"><a href="RD1.html#cb547-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fit2953,fitslopes2953,fitslopesQ2953,fitslopesC2953) </span></code></pre></div>
<pre><code>##                df      AIC
## fit2953         4 3081.155
## fitslopes2953   5 3075.964
## fitslopesQ2953  7 3077.970
## fitslopesC2953  9 3081.056</code></pre>
<div class="sourceCode" id="cb549"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb549-1"><a href="RD1.html#cb549-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(fit2953,fitslopes2953,fitslopesQ2953,fitslopesC2953) </span></code></pre></div>
<pre><code>##                df      BIC
## fit2953         4 3097.345
## fitslopes2953   5 3096.201
## fitslopesQ2953  7 3106.301
## fitslopesC2953  9 3117.483</code></pre>
<p>It looks like the model with different linear slopes on each side, <code>fitslopes2953</code>, fits the best with this broad window of data. (Again, this bandwidth might not be the most appropriate.)</p>
</div>
<div id="plotting-the-model" class="section level4" number="6.7.2.3">
<h4><span class="header-section-number">6.7.2.3</span> Plotting the model</h4>
<p>We can estimate the means in each cohort size, again using the <code>aggregate()</code> function. This is valuable for plotting.</p>
<div class="sourceCode" id="cb551"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb551-1"><a href="RD1.html#cb551-1" aria-hidden="true" tabindex="-1"></a>mread2940 <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(read<span class="sc">~</span>csize, <span class="at">data=</span>ang2953[ang2953<span class="sc">$</span>coh_size<span class="sc">&lt;</span> <span class="dv">41</span>,], mean)</span>
<span id="cb551-2"><a href="RD1.html#cb551-2" aria-hidden="true" tabindex="-1"></a>mread4153 <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(read<span class="sc">~</span>csize, <span class="at">data=</span>ang2953[ang2953<span class="sc">$</span>coh_size<span class="sc">&gt;=</span><span class="dv">41</span>,], mean)</span></code></pre></div>
<p>Let’s plot the model: First, let’s create an object that specifies which model to use in the plot. We can toggle between linear, quadratic, and cubic models to see their plots by commenting out the the models we don’t want.</p>
<div class="sourceCode" id="cb552"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb552-1"><a href="RD1.html#cb552-1" aria-hidden="true" tabindex="-1"></a>MYMODEL <span class="ot">&lt;-</span> fitslopes2953  <span class="co">#Linear (est.separately on each side)</span></span>
<span id="cb552-2"><a href="RD1.html#cb552-2" aria-hidden="true" tabindex="-1"></a><span class="co">#MYMODEL&lt;- fitslopesQ2953 #Quadratic</span></span>
<span id="cb552-3"><a href="RD1.html#cb552-3" aria-hidden="true" tabindex="-1"></a><span class="co">#MYMODEL&lt;- fitslopesC2953 #Cubic</span></span></code></pre></div>
<p>Left side prediction:</p>
<div class="sourceCode" id="cb553"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb553-1"><a href="RD1.html#cb553-1" aria-hidden="true" tabindex="-1"></a>X2941 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">csize =</span> <span class="fu">c</span>(<span class="dv">29</span><span class="sc">:</span><span class="dv">41-41</span>)) <span class="co"># Remember, we&#39;re centering the cohort size</span></span>
<span id="cb553-2"><a href="RD1.html#cb553-2" aria-hidden="true" tabindex="-1"></a>X2941<span class="sc">$</span>small <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(X2941<span class="sc">$</span>csize) )      </span>
<span id="cb553-3"><a href="RD1.html#cb553-3" aria-hidden="true" tabindex="-1"></a>Y2941 <span class="ot">&lt;-</span> <span class="fu">predict</span>(MYMODEL, <span class="at">newdata=</span>X2941)  <span class="co"># Change the &quot;Q&quot; to a &quot;C&quot; in the model name,fitslopesQ2953, and rerun it to see the Cubic plot</span></span></code></pre></div>
<p>Right side prediction:</p>
<div class="sourceCode" id="cb554"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb554-1"><a href="RD1.html#cb554-1" aria-hidden="true" tabindex="-1"></a>X4153 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">csize=</span><span class="fu">c</span>(<span class="dv">41</span><span class="sc">:</span><span class="dv">53-41</span>))</span>
<span id="cb554-2"><a href="RD1.html#cb554-2" aria-hidden="true" tabindex="-1"></a>X4153<span class="sc">$</span>small <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">length</span>(X4153<span class="sc">$</span>csize) )</span>
<span id="cb554-3"><a href="RD1.html#cb554-3" aria-hidden="true" tabindex="-1"></a>Y4153 <span class="ot">&lt;-</span><span class="fu">predict</span>(MYMODEL, <span class="at">newdata=</span>X4153)  <span class="co">#Change the &quot;Q&quot; to a &quot;C&quot; in the model name,fitslopesQ2953, and rerun it to see the Cubic plot</span></span></code></pre></div>
<div class="sourceCode" id="cb555"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb555-1"><a href="RD1.html#cb555-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(mread2940,</span>
<span id="cb555-2"><a href="RD1.html#cb555-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">plot</span>(csize,read, </span>
<span id="cb555-3"><a href="RD1.html#cb555-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">67</span>,<span class="dv">77</span>), <span class="at">xlim=</span>  <span class="fu">c</span>(<span class="dv">29</span>,<span class="dv">53</span>)<span class="sc">-</span><span class="dv">41</span>,<span class="at">pch=</span><span class="dv">18</span>,</span>
<span id="cb555-4"><a href="RD1.html#cb555-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;September cohort enrollment size (centered)&quot;</span>, </span>
<span id="cb555-5"><a href="RD1.html#cb555-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">ylab=</span><span class="st">&quot;Verbal score (class avg)&quot;</span>,</span>
<span id="cb555-6"><a href="RD1.html#cb555-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">main =</span> <span class="st">&quot;Slope on each side is estimated separately&quot;</span>,</span>
<span id="cb555-7"><a href="RD1.html#cb555-7" aria-hidden="true" tabindex="-1"></a>          <span class="fu">lines</span>(csize,read)))</span>
<span id="cb555-8"><a href="RD1.html#cb555-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(X2941<span class="sc">$</span>csize,Y2941, <span class="at">col=</span><span class="st">&quot;brown&quot;</span>)         <span class="co">#Now, the fit of the observed &quot;large classes&quot; group</span></span>
<span id="cb555-9"><a href="RD1.html#cb555-9" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(mread4153<span class="sc">$</span>csize,mread4153<span class="sc">$</span>read,<span class="at">pch=</span><span class="dv">18</span>) <span class="co">#Mean estimates of &quot;small classes&quot; group</span></span>
<span id="cb555-10"><a href="RD1.html#cb555-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(mread4153<span class="sc">$</span>csize,mread4153<span class="sc">$</span>read)          <span class="co">#The prediction line of the observed &quot;small&quot; class group</span></span>
<span id="cb555-11"><a href="RD1.html#cb555-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(X4153<span class="sc">$</span>csize,Y4153, <span class="at">col=</span><span class="st">&quot;darkcyan&quot;</span>)</span>
<span id="cb555-12"><a href="RD1.html#cb555-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>,<span class="at">h=</span><span class="cn">NULL</span>,<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-297-1.png" width="672" /></p>
</div>
<div id="assuming-the-same-functional-form-on-both-sides" class="section level4" number="6.7.2.4">
<h4><span class="header-section-number">6.7.2.4</span> Assuming the same functional form on both sides</h4>
<p>Just as we had done earlier with the smaller bandwidth, we could impose the same functional form on both sides of the cutoff. This is easier to interpret than in models that allow differ shapes on either side because we are assuming that the underlying secular trend is unaffected by assignment to control or treatment group. For the quadratic model, we can remove the interactions:</p>
<p><span class="math display" id="eq:RDDQuadReadSame">\[\begin{eqnarray}
\text{Y}_i = \beta_0 + \beta_{1}\text{X}_{c_i} + \beta_{2}\text{Z}_i + \beta_{3}\text{X}_{c_i}^2 +  \epsilon_i \text{ ,}
  \tag{6.6}
\end{eqnarray}\]</span></p>
<p>which, with our data, is</p>
<p><span class="math display">\[\begin{eqnarray}
\text{read}_i = \beta_0 + \beta_{1}\text{csize}_i + \beta_{2}\text{small}_i + \beta_{3}\text{csize}_i^2 + \epsilon_i \text{.}
\end{eqnarray}\]</span></p>
<div class="sourceCode" id="cb556"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb556-1"><a href="RD1.html#cb556-1" aria-hidden="true" tabindex="-1"></a>fitslopesQ2953_same <span class="ot">&lt;-</span> <span class="fu">lm</span>(read <span class="sc">~</span> csize <span class="sc">+</span> small <span class="sc">+</span> <span class="fu">I</span>(csize<span class="sc">^</span><span class="dv">2</span>), <span class="at">data=</span>ang2953)</span>
<span id="cb556-2"><a href="RD1.html#cb556-2" aria-hidden="true" tabindex="-1"></a>(fitslopesQ2953out_same <span class="ot">&lt;-</span> <span class="fu">summary</span>(fitslopesQ2953_same))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = read ~ csize + small + I(csize^2), data = ang2953)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -34.137  -5.769   1.748   6.639  17.466 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 67.84722    1.53096  44.317  &lt; 2e-16 ***
## csize       -0.29096    0.13659  -2.130  0.03375 *  
## small        5.89445    1.99023   2.962  0.00323 ** 
## I(csize^2)   0.02415    0.01080   2.237  0.02580 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.138 on 419 degrees of freedom
## Multiple R-squared:  0.02619,    Adjusted R-squared:  0.01922 
## F-statistic: 3.757 on 3 and 419 DF,  p-value: 0.01102</code></pre>
<div class="sourceCode" id="cb558"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb558-1"><a href="RD1.html#cb558-1" aria-hidden="true" tabindex="-1"></a>X2941 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">csize =</span> <span class="fu">c</span>(<span class="dv">29</span><span class="sc">:</span><span class="dv">41-41</span>)) </span>
<span id="cb558-2"><a href="RD1.html#cb558-2" aria-hidden="true" tabindex="-1"></a>X2941<span class="sc">$</span>small <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(X2941<span class="sc">$</span>csize) )      </span>
<span id="cb558-3"><a href="RD1.html#cb558-3" aria-hidden="true" tabindex="-1"></a>Y2941 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fitslopesQ2953_same, <span class="at">newdata =</span> X2941)  </span></code></pre></div>
<p>Right side prediction:</p>
<div class="sourceCode" id="cb559"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb559-1"><a href="RD1.html#cb559-1" aria-hidden="true" tabindex="-1"></a>X4153 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">csize=</span><span class="fu">c</span>(<span class="dv">41</span><span class="sc">:</span><span class="dv">53-41</span>))</span>
<span id="cb559-2"><a href="RD1.html#cb559-2" aria-hidden="true" tabindex="-1"></a>X4153<span class="sc">$</span>small <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">length</span>(X4153<span class="sc">$</span>csize) )</span>
<span id="cb559-3"><a href="RD1.html#cb559-3" aria-hidden="true" tabindex="-1"></a>Y4153 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fitslopesQ2953_same, <span class="at">newdata =</span> X4153)  </span></code></pre></div>
<div class="sourceCode" id="cb560"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb560-1"><a href="RD1.html#cb560-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(mread2940,</span>
<span id="cb560-2"><a href="RD1.html#cb560-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">plot</span>(csize, read, </span>
<span id="cb560-3"><a href="RD1.html#cb560-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">67</span>,<span class="dv">77</span>), <span class="at">xlim=</span>  <span class="fu">c</span>(<span class="dv">29</span>,<span class="dv">53</span>)<span class="sc">-</span><span class="dv">41</span>,<span class="at">pch=</span><span class="dv">18</span>,</span>
<span id="cb560-4"><a href="RD1.html#cb560-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;September cohort enrollment size (centered)&quot;</span>, </span>
<span id="cb560-5"><a href="RD1.html#cb560-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">ylab=</span><span class="st">&quot;Verbal score (class avg)&quot;</span>,</span>
<span id="cb560-6"><a href="RD1.html#cb560-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">main =</span> <span class="st">&quot;Functional form set to be the same on both sides&quot;</span>,</span>
<span id="cb560-7"><a href="RD1.html#cb560-7" aria-hidden="true" tabindex="-1"></a>          <span class="fu">lines</span>(csize,read)))</span>
<span id="cb560-8"><a href="RD1.html#cb560-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(X2941<span class="sc">$</span>csize,Y2941, <span class="at">col=</span><span class="st">&quot;brown&quot;</span>)         <span class="co">#Now, the fit of the observed &quot;large classes&quot; group</span></span>
<span id="cb560-9"><a href="RD1.html#cb560-9" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(mread4153<span class="sc">$</span>csize,mread4153<span class="sc">$</span>read,<span class="at">pch=</span><span class="dv">18</span>) <span class="co">#Mean estimates of &quot;small classes&quot; group</span></span>
<span id="cb560-10"><a href="RD1.html#cb560-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(mread4153<span class="sc">$</span>csize,mread4153<span class="sc">$</span>read)          <span class="co">#The prediction line of the observed &quot;small&quot; class group</span></span>
<span id="cb560-11"><a href="RD1.html#cb560-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(X4153<span class="sc">$</span>csize,Y4153, <span class="at">col=</span><span class="st">&quot;darkcyan&quot;</span>)</span>
<span id="cb560-12"><a href="RD1.html#cb560-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>,<span class="at">h=</span><span class="cn">NULL</span>,<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-301-1.png" width="672" /></p>
<p>If this bandwidth made sense for the story of our data, and if we could argue that the secular trend is the same on both sides of the cutpoint, this might be the model we focus on in our analysis and reporting of our study. We could compare this to our earlier best-fitting model, <code>fitslopes2953</code> to see if the deviance from the observed data is less.</p>
<div class="sourceCode" id="cb561"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb561-1"><a href="RD1.html#cb561-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(fitslopes2953 , fitslopesQ2953_same)</span></code></pre></div>
<pre><code>##                     df      AIC
## fitslopes2953        5 3075.964
## fitslopesQ2953_same  5 3078.133</code></pre>
<p>The linear model, with different slopes on either side, still seems to have a slightly better fit than this quadratic model with the same slope on either side.</p>
</div>
</div>
</div>
<div id="using-the-rddtools-package" class="section level2" number="6.8">
<h2><span class="header-section-number">6.8</span> Using the rddtools Package</h2>
<p>Let’s compare our results with those of a package, rddtools.</p>
<p>The rddtools package <span class="citation">(<a href="#ref-R-rddtools" role="doc-biblioref">Stigler &amp; Quast, 2021</a>)</span> can provide parametric (and non-parametric) analyses.
Our “by-hand” analysis above were parametric. We can use <code>help(package = "rddtools")</code> to read about the package.</p>
<div class="sourceCode" id="cb563"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb563-1"><a href="RD1.html#cb563-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rddtools)</span></code></pre></div>
<p>First, we specify the rdd_object, which captures the data, the outcome (reading achievement), the forcing variable (centered cohort size), and the cut-off score on this variable.</p>
<div class="sourceCode" id="cb564"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb564-1"><a href="RD1.html#cb564-1" aria-hidden="true" tabindex="-1"></a>dat_rddtools <span class="ot">&lt;-</span> <span class="fu">rdd_data</span>(<span class="at">y =</span> read, <span class="at">x =</span> csize,</span>
<span id="cb564-2"><a href="RD1.html#cb564-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> ang2953,</span>
<span id="cb564-3"><a href="RD1.html#cb564-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">cutpoint =</span> <span class="dv">0</span> )</span></code></pre></div>
<p>Then, we can use this object in analyses. The default functional form is linear (specified as polynomial order of <code>1</code>).</p>
<div class="sourceCode" id="cb565"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb565-1"><a href="RD1.html#cb565-1" aria-hidden="true" tabindex="-1"></a>(rddtools_L2953 <span class="ot">&lt;-</span> <span class="fu">rdd_reg_lm</span>(dat_rddtools))  </span></code></pre></div>
<pre><code>## ### RDD regression: parametric ###
##  Polynomial order:  1 
##  Slopes:  separate 
##  Number of obs: 423 (left: 115, right: 308)
## 
##  Coefficient:
##   Estimate Std. Error t value Pr(&gt;|t|)   
## D   6.6924     2.0582  3.2516  0.00124 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb567"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb567-1"><a href="RD1.html#cb567-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rddtools_L2953) </span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ ., data = dat_step1, weights = weights)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.710  -5.954   1.711   6.735  17.272 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  66.3361     1.8160  36.529  &lt; 2e-16 ***
## D             6.6924     2.0582   3.252  0.00124 ** 
## x            -0.7246     0.2484  -2.917  0.00372 ** 
## x_right       0.7570     0.2824   2.680  0.00764 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.115 on 419 degrees of freedom
## Multiple R-squared:  0.03117,    Adjusted R-squared:  0.02424 
## F-statistic: 4.494 on 3 and 419 DF,  p-value: 0.004058</code></pre>
<p>We see that this is identical to our previous “by-hand” linear analysis, the coefficients of which are easy to get:</p>
<div class="sourceCode" id="cb569"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb569-1"><a href="RD1.html#cb569-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fitslopes2953out)</span></code></pre></div>
<pre><code>##               Estimate Std. Error   t value      Pr(&gt;|t|)
## (Intercept) 66.3361486  1.8159652 36.529416 2.572799e-132
## csize       -0.7246366  0.2483847 -2.917396  3.719580e-03
## small        6.6924236  2.0581708  3.251637  1.240174e-03
## csize:small  0.7570453  0.2824445  2.680333  7.644987e-03</code></pre>
<p>We can plot the object.<a href="#fn35" class="footnote-ref" id="fnref35"><sup>35</sup></a></p>
<div class="sourceCode" id="cb571"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb571-1"><a href="RD1.html#cb571-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rddtools_L2953)</span></code></pre></div>
<pre><code>## [1] &quot;Mass points detected in the running variable.&quot;</code></pre>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-307-1.png" width="672" /></p>
<p>This does not look pretty. We can adjust the limits on the Y axis.</p>
<div class="sourceCode" id="cb573"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb573-1"><a href="RD1.html#cb573-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rddtools_L2953, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">67</span>,<span class="dv">77</span>))</span></code></pre></div>
<pre><code>## [1] &quot;Mass points detected in the running variable.&quot;</code></pre>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-308-1.png" width="672" /></p>
<p>This shows the linear trends on both sides, similar to our hand-made plot above (though not as pretty, yeah).</p>
<div id="examining-the-bandwidth-identified-by-the-package" class="section level3" number="6.8.1">
<h3><span class="header-section-number">6.8.1</span> Examining the bandwidth identified by the package</h3>
<p>We can use the package’s <code>rdd_bw_ik()</code> function to look at the bandwidth it used. This applies the Imbens-Kalyanaraman (IK) optimal bandwidth calculation to our design. With our linear model, it is a bandwidth of 9.706.</p>
<div class="sourceCode" id="cb575"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb575-1"><a href="RD1.html#cb575-1" aria-hidden="true" tabindex="-1"></a>np_bw2953 <span class="ot">&lt;-</span> <span class="fu">rdd_bw_ik</span>(dat_rddtools)</span>
<span id="cb575-2"><a href="RD1.html#cb575-2" aria-hidden="true" tabindex="-1"></a>(np_2953  <span class="ot">&lt;-</span> <span class="fu">rdd_reg_np</span>(dat_rddtools)) <span class="co"># seems to default to IK BW, so don&#39;t need to specify it</span></span></code></pre></div>
<pre><code>## ### RDD regression: nonparametric local linear###
##  Bandwidth:  9.705921 
##  Number of obs: 315 (left: 88, right: 227)
## 
##  Coefficient:
##   Estimate Std. Error z value Pr(&gt;|z|)  
## D   5.4711     2.3016  2.3771  0.01745 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb577"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb577-1"><a href="RD1.html#cb577-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(np_2953, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">67</span>,<span class="dv">77</span>))</span></code></pre></div>
<pre><code>## [1] &quot;Mass points detected in the running variable.&quot;</code></pre>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-309-1.png" width="672" /></p>
<p>We can look at a quadratic functional form, which is the 2nd polynomial, specified by the <code>order = 2</code> argument.</p>
<div class="sourceCode" id="cb579"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb579-1"><a href="RD1.html#cb579-1" aria-hidden="true" tabindex="-1"></a>(rddtools_Q2953<span class="ot">&lt;-</span> <span class="fu">rdd_reg_lm</span>(dat_rddtools, <span class="at">order =</span> <span class="dv">2</span>)) <span class="co"># Polynomial order of 2 (quadratic)</span></span></code></pre></div>
<pre><code>## ### RDD regression: parametric ###
##  Polynomial order:  2 
##  Slopes:  separate 
##  Number of obs: 423 (left: 115, right: 308)
## 
##  Coefficient:
##   Estimate Std. Error t value Pr(&gt;|t|)
## D   4.6686     3.3161  1.4079   0.1599</code></pre>
<div class="sourceCode" id="cb581"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb581-1"><a href="RD1.html#cb581-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rddtools_Q2953)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ ., data = dat_step1, weights = weights)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.732  -5.993   1.578   6.818  17.877 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 67.22345    3.05881  21.977   &lt;2e-16 ***
## D            4.66865    3.31609   1.408    0.160    
## x           -0.35030    1.06771  -0.328    0.743    
## `x^2`        0.02865    0.07947   0.360    0.719    
## x_right      1.03562    1.17885   0.878    0.380    
## `x^2_right` -0.08325    0.08908  -0.935    0.351    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.115 on 417 degrees of freedom
## Multiple R-squared:  0.03573,    Adjusted R-squared:  0.02417 
## F-statistic:  3.09 on 5 and 417 DF,  p-value: 0.009437</code></pre>
<p>This is identical to our previous “by-hand” quadratic analysis:</p>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb583-1"><a href="RD1.html#cb583-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fitslopesQ2953out)</span></code></pre></div>
<pre><code>##                     Estimate Std. Error    t value     Pr(&gt;|t|)
## (Intercept)      67.22345312 3.05881484 21.9769605 1.164138e-71
## csize            -0.35029844 1.06770784 -0.3280845 7.430124e-01
## small             4.66864898 3.31609410  1.4078759 1.599128e-01
## I(csize^2)        0.02864702 0.07946673  0.3604908 7.186627e-01
## csize:small       1.03561594 1.17885184  0.8784954 3.801808e-01
## small:I(csize^2) -0.08325231 0.08907855 -0.9345943 3.505383e-01</code></pre>
<p>Here’s the plot:</p>
<div class="sourceCode" id="cb585"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb585-1"><a href="RD1.html#cb585-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rddtools_Q2953, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">67</span>,<span class="dv">77</span>))</span></code></pre></div>
<pre><code>## [1] &quot;Mass points detected in the running variable.&quot;</code></pre>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-312-1.png" width="672" /></p>
<p>Here is the cubic function, specified with the third polynomial argument, <code>order = 3</code>.</p>
<div class="sourceCode" id="cb587"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb587-1"><a href="RD1.html#cb587-1" aria-hidden="true" tabindex="-1"></a>(rddtools_C2953<span class="ot">&lt;-</span> <span class="fu">rdd_reg_lm</span>(dat_rddtools,<span class="at">order =</span> <span class="dv">3</span>))</span></code></pre></div>
<pre><code>## ### RDD regression: parametric ###
##  Polynomial order:  3 
##  Slopes:  separate 
##  Number of obs: 423 (left: 115, right: 308)
## 
##  Coefficient:
##   Estimate Std. Error t value Pr(&gt;|t|)
## D   3.4195     5.1704  0.6614   0.5087</code></pre>
<div class="sourceCode" id="cb589"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb589-1"><a href="RD1.html#cb589-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rddtools_C2953) </span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ ., data = dat_step1, weights = weights)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.310  -6.220   1.487   6.790  18.517 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 69.10337    4.94856  13.964   &lt;2e-16 ***
## D            3.41951    5.17035   0.661    0.509    
## x            1.09145    3.16680   0.345    0.731    
## `x^2`        0.29417    0.55472   0.530    0.596    
## `x^3`        0.01356    0.02804   0.484    0.629    
## x_right     -1.28851    3.38419  -0.381    0.704    
## `x^2_right` -0.15580    0.60455  -0.258    0.797    
## `x^3_right` -0.02425    0.03096  -0.783    0.434    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.127 on 415 degrees of freedom
## Multiple R-squared:  0.03781,    Adjusted R-squared:  0.02158 
## F-statistic:  2.33 on 7 and 415 DF,  p-value: 0.02429</code></pre>
<div class="sourceCode" id="cb591"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb591-1"><a href="RD1.html#cb591-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rddtools_C2953, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">67</span>,<span class="dv">77</span>))</span></code></pre></div>
<pre><code>## [1] &quot;Mass points detected in the running variable.&quot;</code></pre>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-313-1.png" width="672" /></p>
<p>We can go quartic, too.</p>
<div class="sourceCode" id="cb593"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb593-1"><a href="RD1.html#cb593-1" aria-hidden="true" tabindex="-1"></a>(rddtools_Qartic2953<span class="ot">&lt;-</span> <span class="fu">rdd_reg_lm</span>(dat_rddtools,<span class="at">order=</span><span class="dv">4</span>)) </span></code></pre></div>
<pre><code>## ### RDD regression: parametric ###
##  Polynomial order:  4 
##  Slopes:  separate 
##  Number of obs: 423 (left: 115, right: 308)
## 
##  Coefficient:
##   Estimate Std. Error t value Pr(&gt;|t|)
## D  0.86636    8.00874  0.1082   0.9139</code></pre>
<div class="sourceCode" id="cb595"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb595-1"><a href="RD1.html#cb595-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rddtools_Qartic2953, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">67</span>,<span class="dv">77</span>))</span></code></pre></div>
<pre><code>## [1] &quot;Mass points detected in the running variable.&quot;</code></pre>
<p><img src="QEDs-in-R_files/figure-html/unnamed-chunk-314-1.png" width="672" /></p>
<p>Using the <code>AIC()</code> function, we can compare the models to see which provides a better fit to the data.</p>
<div class="sourceCode" id="cb597"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb597-1"><a href="RD1.html#cb597-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(rddtools_L2953, </span>
<span id="cb597-2"><a href="RD1.html#cb597-2" aria-hidden="true" tabindex="-1"></a>    rddtools_Q2953, </span>
<span id="cb597-3"><a href="RD1.html#cb597-3" aria-hidden="true" tabindex="-1"></a>    rddtools_C2953, </span>
<span id="cb597-4"><a href="RD1.html#cb597-4" aria-hidden="true" tabindex="-1"></a>    rddtools_Qartic2953)</span></code></pre></div>
<pre><code>##                     df      AIC
## rddtools_L2953       5 3075.964
## rddtools_Q2953       7 3077.970
## rddtools_C2953       9 3081.056
## rddtools_Qartic2953 11 3084.412</code></pre>
<p>It looks like the linear model fits best. But, IES and other funding agencies recommend non-parametric estimates of the functional form, so we could use both. Also, again, this bandwidth in this extended portion of this demostration might not be the most appropriate.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="1">
<div id="ref-angrist_using_1999" class="csl-entry">
Angrist, J. D., &amp; Lavy, V. (1999). Using <span>Maimonides</span>’ rule to estimate the effect of class size on scholastic achievement. <em>The Quarterly Journal of Economics</em>, <em>114</em>, 533–575. <a href="https://doi.org/10.1162/003355399556061">https://doi.org/10.1162/003355399556061</a>
</div>
<div id="ref-murnane_methods_2011" class="csl-entry">
Murnane, R. J., &amp; Willett, J. B. (2011). <em>Methods matter: <span>Improving</span> causal inference in educational and social science research</em>. Oxford University Press.
</div>
<div id="ref-R-rddtools" class="csl-entry">
Stigler, M., &amp; Quast, B. (2021). <em>Rddtools: Toolbox for regression discontinuity design (RDD)</em>. <a href="https://qua.st/rddtools/">https://qua.st/rddtools/</a>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="31">
<li id="fn31"><p>For some readers, you might be more used to seeing ANCOVA with the treatment variable first and the centered forcing variable second, as in <span class="math inline">\(\text{Y}_i = \beta_0 + \beta_1Z_i + \beta_2(X_i - X_c) + \epsilon_i \text{ .}\)</span>, which is an equivalent specification.<a href="RD1.html#fnref31" class="footnote-back">↩︎</a></p></li>
<li id="fn32"><p>Forcing variables are also called <em><em>assignment variables</em></em> and <em><em>running variables</em></em> depending on the discipline. They are what are used to assign units to the treatment condition. It’s important to distinguish the variable used to assign people to levels of <span class="math inline">\(Z\)</span> (in this equation, <span class="math inline">\(X\)</span>) from the variable that results from this assignment mechanism, <span class="math inline">\(Z\)</span>. In an earlier chapter, <span class="math inline">\(Z\)</span> was called an assignment variable because it was the result of the assignment process. In a simple RDD, the forcing variable is continuous and the treatment-assignment variable is binary, coded as <span class="math inline">\(0\)</span> or <span class="math inline">\(1\)</span>.<a href="RD1.html#fnref32" class="footnote-back">↩︎</a></p></li>
<li id="fn33"><p>Earlier in Equation <a href="RD1.html#eq:ANCOVAeq">(6.3)</a>—before we included the interaction—we called this an ANCOVA.<a href="RD1.html#fnref33" class="footnote-back">↩︎</a></p></li>
<li id="fn34"><p>At this broad bandwidth (with cohorts of size 29 to 40 on the control-group side and of size 41 to 53 on the treatment-group size), with this data set, there appears to be more complexity in the secular trend. At a narrow bandwidth (from cohorts of size 36 to 40 in the control and from 41 to 36 in the treatment), we can account for the trend that might occur because of SES and its tendency to be lower in schools with smaller cohorts (and therefore a slight upward slope as cohorts get larger). If we look at the broad bandwidth, we see a downward slope. This might be because smaller cohorts have, well, smaller classes, which in turn translates into higher teacher-student ratios and perhaps higher scores. If we had looked at a bandwidth that was between these two—such as a medium bandwidth—we might find that a curvilinear model form fits better than an a linear one even though with the broad bandwidth and with the narrow bandwidth, a linear form fits.<a href="RD1.html#fnref34" class="footnote-back">↩︎</a></p></li>
<li id="fn35"><p>Ignore the message from the plot that says <code>"Mass points detected in the running variable."</code> It seems to be a bug.<a href="RD1.html#fnref35" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="DID.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="RD2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
