<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Week 05, Discriminant Function Analysis | EDUC 644 Applied Multivariate Statistics</title>
  <meta name="description" content="Course materials for multivariate statistics" />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Week 05, Discriminant Function Analysis | EDUC 644 Applied Multivariate Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course materials for multivariate statistics" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Week 05, Discriminant Function Analysis | EDUC 644 Applied Multivariate Statistics" />
  
  <meta name="twitter:description" content="Course materials for multivariate statistics" />
  

<meta name="author" content="George Harrison" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-04-factorial-manova.html"/>
<link rel="next" href="week-06-principal-components-analysis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="libs/tabwid-1.1.3/tabwid.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Multivariate Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><i class="fa fa-check"></i><b>1</b> Terminology and Matrix Manipulations Used in Multivariate Statistics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#scalars"><i class="fa fa-check"></i><b>1.1</b> Scalars</a></li>
<li class="chapter" data-level="1.2" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#vectors"><i class="fa fa-check"></i><b>1.2</b> Vectors</a></li>
<li class="chapter" data-level="1.3" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#matrices"><i class="fa fa-check"></i><b>1.3</b> Matrices</a></li>
<li class="chapter" data-level="1.4" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#symmetrical-matrices"><i class="fa fa-check"></i><b>1.4</b> Symmetrical Matrices</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#variance-covariance-matrices"><i class="fa fa-check"></i><b>1.4.1</b> Variance-covariance Matrices</a></li>
<li class="chapter" data-level="1.4.2" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#greek-letters"><i class="fa fa-check"></i><b>1.4.2</b> Greek letters</a></li>
<li class="chapter" data-level="1.4.3" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#example-variance-covariance-matrix"><i class="fa fa-check"></i><b>1.4.3</b> Example variance-covariance matrix</a></li>
<li class="chapter" data-level="1.4.4" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#the-diagonal-and-trace"><i class="fa fa-check"></i><b>1.4.4</b> The diagonal and trace</a></li>
<li class="chapter" data-level="1.4.5" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#an-identity-matrix"><i class="fa fa-check"></i><b>1.4.5</b> An identity matrix</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#transposed-vectors-and-matrices"><i class="fa fa-check"></i><b>1.5</b> Transposed Vectors and Matrices</a></li>
<li class="chapter" data-level="1.6" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#matrix-addition-and-subtraction"><i class="fa fa-check"></i><b>1.6</b> Matrix Addition and Subtraction</a></li>
<li class="chapter" data-level="1.7" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#operations-on-matrices-with-a-scalar"><i class="fa fa-check"></i><b>1.7</b> Operations on Matrices with a Scalar</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#sum-of-square-and-cross-product-sscp-matrices"><i class="fa fa-check"></i><b>1.7.1</b> Sum-of-square-and-cross-product (SSCP) matrices</a></li>
<li class="chapter" data-level="1.7.2" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#operations-on-elements-of-a-matrix-example-with-a-correlation-matrix"><i class="fa fa-check"></i><b>1.7.2</b> Operations on elements of a matrix: Example with a correlation matrix</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#matrix-multiplication"><i class="fa fa-check"></i><b>1.8</b> Matrix Multiplication</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#another-example-of-matrix-multiplication-to-get-the-sscp"><i class="fa fa-check"></i><b>1.8.1</b> Another example of matrix multiplication, to get the SSCP</a></li>
<li class="chapter" data-level="1.8.2" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#the-ordering-is-important"><i class="fa fa-check"></i><b>1.8.2</b> The ordering is important</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#inverse-of-a-matrix"><i class="fa fa-check"></i><b>1.9</b> Inverse of a Matrix</a></li>
<li class="chapter" data-level="1.10" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#matrix-determinants-as-generalized-variance"><i class="fa fa-check"></i><b>1.10</b> Matrix determinants, as generalized variance</a></li>
<li class="chapter" data-level="1.11" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#eigenvectors-and-eigenvalues"><i class="fa fa-check"></i><b>1.11</b> Eigenvectors and Eigenvalues</a></li>
<li class="chapter" data-level="1.12" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#summary"><i class="fa fa-check"></i><b>1.12</b> Summary</a></li>
<li class="chapter" data-level="1.13" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#optional-spss-and-r-code-to-manipulate-matrices"><i class="fa fa-check"></i><b>1.13</b> Optional: SPSS and R Code to Manipulate Matrices</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="hotellings-t2.html"><a href="hotellings-t2.html"><i class="fa fa-check"></i><b>2</b> Hotelling’s <span class="math inline">\(T^2\)</span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="hotellings-t2.html"><a href="hotellings-t2.html#within-group-covariance-matrices"><i class="fa fa-check"></i><b>2.1</b> Within-group covariance matrices</a></li>
<li class="chapter" data-level="2.2" data-path="hotellings-t2.html"><a href="hotellings-t2.html#sscp-matrices"><i class="fa fa-check"></i><b>2.2</b> SSCP matrices</a></li>
<li class="chapter" data-level="2.3" data-path="hotellings-t2.html"><a href="hotellings-t2.html#conducting-the-test-using-functions"><i class="fa fa-check"></i><b>2.3</b> Conducting the Test using Functions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html"><i class="fa fa-check"></i><b>3</b> Planned Comparisons and Contrasts</a>
<ul>
<li class="chapter" data-level="3.1" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html#data-from-week-1"><i class="fa fa-check"></i><b>3.1</b> Data from Week 1</a></li>
<li class="chapter" data-level="3.2" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html#orthogonal-contrasts"><i class="fa fa-check"></i><b>3.2</b> Orthogonal contrasts</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html#conditions-for-orthogonal-contrasts"><i class="fa fa-check"></i><b>3.2.1</b> Conditions for orthogonal contrasts</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html#non-orthogonal-contrasts"><i class="fa fa-check"></i><b>3.3</b> Non-orthogonal contrasts</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html#accounting-for-type-i-error-in-non-orthogonal-contrasts."><i class="fa fa-check"></i><b>3.3.1</b> Accounting for Type I error in non-orthogonal contrasts.</a></li>
<li class="chapter" data-level="3.3.2" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html#post-hoc-tests"><i class="fa fa-check"></i><b>3.3.2</b> Post-hoc tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html"><i class="fa fa-check"></i><b>4</b> Week 03 Statistical Assumptions of MANOVA</a>
<ul>
<li class="chapter" data-level="4.1" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#data"><i class="fa fa-check"></i><b>4.1</b> Data</a></li>
<li class="chapter" data-level="4.2" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#descriptive-statistics"><i class="fa fa-check"></i><b>4.2</b> Descriptive statistics</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#by-group-descriptive-statistics"><i class="fa fa-check"></i><b>4.2.1</b> By-group descriptive statistics</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#normality-assumption"><i class="fa fa-check"></i><b>4.3</b> Normality Assumption</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#univariate-normality"><i class="fa fa-check"></i><b>4.3.1</b> Univariate Normality</a></li>
<li class="chapter" data-level="4.3.2" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#examining-univariate-normality-using-quantile-quantile-plots"><i class="fa fa-check"></i><b>4.3.2</b> Examining univariate normality using quantile-quantile plots</a></li>
<li class="chapter" data-level="4.3.3" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#a-caution-about-statistical-tests-of-statistical-assumptions"><i class="fa fa-check"></i><b>4.3.3</b> A caution about statistical tests of statistical assumptions</a></li>
<li class="chapter" data-level="4.3.4" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#mahalanobis-distance-and-multivariate-outliers"><i class="fa fa-check"></i><b>4.3.4</b> Mahalanobis Distance and Multivariate Outliers</a></li>
<li class="chapter" data-level="4.3.5" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#statistical-tests-of-multivariate-normality"><i class="fa fa-check"></i><b>4.3.5</b> Statistical Tests of Multivariate Normality</a></li>
<li class="chapter" data-level="4.3.6" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#homogeneity-of-covariance"><i class="fa fa-check"></i><b>4.3.6</b> Homogeneity of Covariance</a></li>
<li class="chapter" data-level="4.3.7" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#conclusions-about-our-statistical-assumptions"><i class="fa fa-check"></i><b>4.3.7</b> Conclusions about our statistical assumptions</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#fitting-the-manova-model"><i class="fa fa-check"></i><b>4.4</b> Fitting the MANOVA Model</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#follow-up-analysis-with-univariate-f-tests"><i class="fa fa-check"></i><b>4.4.1</b> Follow-up analysis with univariate <em>F</em>-tests</a></li>
<li class="chapter" data-level="4.4.2" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#effect-size"><i class="fa fa-check"></i><b>4.4.2</b> Effect size</a></li>
<li class="chapter" data-level="4.4.3" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#comparing-the-model-without-outlier"><i class="fa fa-check"></i><b>4.4.3</b> Comparing the Model Without Outlier</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#robust-one-way-manova"><i class="fa fa-check"></i><b>4.5</b> Robust One-way MANOVA</a></li>
<li class="chapter" data-level="4.6" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#summary-1"><i class="fa fa-check"></i><b>4.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html"><i class="fa fa-check"></i><b>5</b> Week 04 Factorial MANOVA</a>
<ul>
<li class="chapter" data-level="5.1" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#following-tabachnick-and-fidells-notes"><i class="fa fa-check"></i><b>5.1</b> Following Tabachnick and Fidell’s notes</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#another-way-to-get-the-sscp_w"><i class="fa fa-check"></i><b>5.1.1</b> Another way to get the <span class="math inline">\(SSCP_W\)</span>:</a></li>
<li class="chapter" data-level="5.1.2" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#mathbfsscp_between-for-each-factor"><i class="fa fa-check"></i><b>5.1.2</b> <span class="math inline">\(\mathbf{SSCP_{Between}}\)</span> for each factor</a></li>
<li class="chapter" data-level="5.1.3" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#mathbfsscp_between-for-the-interaction"><i class="fa fa-check"></i><b>5.1.3</b> <span class="math inline">\(\mathbf{SSCP_{Between}}\)</span> for the interaction</a></li>
<li class="chapter" data-level="5.1.4" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#these-by-hand-calculations-will-be-available-in-manova."><i class="fa fa-check"></i><b>5.1.4</b> These by-hand calculations will be available in <code>manova()</code>.</a></li>
<li class="chapter" data-level="5.1.5" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#calculating-the-generalized-variance"><i class="fa fa-check"></i><b>5.1.5</b> Calculating the generalized variance</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#calculating-wilks-lambda"><i class="fa fa-check"></i><b>5.2</b> Calculating Wilks’ Lambda</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#fit-the-factorial-manova"><i class="fa fa-check"></i><b>5.2.1</b> Fit the factorial MANOVA</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#mancova"><i class="fa fa-check"></i><b>5.3</b> MANCOVA</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#mancova-example"><i class="fa fa-check"></i><b>5.3.1</b> MANCOVA example</a></li>
<li class="chapter" data-level="5.3.2" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#lets-think-about-ordering-and-type-i-sums-of-squares"><i class="fa fa-check"></i><b>5.3.2</b> Let’s think about ordering and Type I sums of squares</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html"><i class="fa fa-check"></i><b>6</b> Week 05, Discriminant Function Analysis</a>
<ul>
<li class="chapter" data-level="6.0.1" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#fitting-the-discriminant-function-analysis-model"><i class="fa fa-check"></i><b>6.0.1</b> Fitting the discriminant function analysis model</a></li>
<li class="chapter" data-level="6.0.2" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#dimension-reduction-analysis"><i class="fa fa-check"></i><b>6.0.2</b> Dimension reduction analysis</a></li>
<li class="chapter" data-level="6.0.3" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#structure-and-standardized-discriminant-function-coefficients"><i class="fa fa-check"></i><b>6.0.3</b> Structure and standardized discriminant function coefficients</a></li>
<li class="chapter" data-level="6.0.4" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#discriminant-function-scores"><i class="fa fa-check"></i><b>6.0.4</b> Discriminant function scores</a></li>
<li class="chapter" data-level="6.0.5" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#group-means-centroids-of-the-discriminant-function-scores"><i class="fa fa-check"></i><b>6.0.5</b> Group means (centroids) of the discriminant-function scores</a></li>
<li class="chapter" data-level="6.0.6" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#bivariate-scatterplot"><i class="fa fa-check"></i><b>6.0.6</b> Bivariate scatterplot</a></li>
<li class="chapter" data-level="6.1" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#write-up"><i class="fa fa-check"></i><b>6.1</b> Write-up</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html"><i class="fa fa-check"></i><b>7</b> Week 06: Principal Components Analysis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#example-1-to-see-some-properties-of-pca"><i class="fa fa-check"></i><b>7.1</b> Example 1, to see some properties of PCA</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#pca-with-covariance-vs.-correlation"><i class="fa fa-check"></i><b>7.1.1</b> PCA with Covariance vs. Correlation</a></li>
<li class="chapter" data-level="7.1.2" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#unscaled-eigenvectors"><i class="fa fa-check"></i><b>7.1.2</b> Unscaled eigenvectors</a></li>
<li class="chapter" data-level="7.1.3" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#looking-at-the-properties-of-eigenvectors-and-eigenvalues"><i class="fa fa-check"></i><b>7.1.3</b> Looking at the properties of eigenvectors and eigenvalues</a></li>
<li class="chapter" data-level="7.1.4" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#using-the-psych-package"><i class="fa fa-check"></i><b>7.1.4</b> Using the psych package</a></li>
<li class="chapter" data-level="7.1.5" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#determining-how-many-components-to-retain"><i class="fa fa-check"></i><b>7.1.5</b> Determining how many components to retain</a></li>
<li class="chapter" data-level="7.1.6" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#reduced-pca-model"><i class="fa fa-check"></i><b>7.1.6</b> Reduced PCA model</a></li>
<li class="chapter" data-level="7.1.7" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#interpretation-1"><i class="fa fa-check"></i><b>7.1.7</b> Interpretation</a></li>
<li class="chapter" data-level="7.1.8" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#interpretation-of-the-rotated-solution"><i class="fa fa-check"></i><b>7.1.8</b> Interpretation of the rotated solution</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#example-two"><i class="fa fa-check"></i><b>7.2</b> Example Two</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#pca-on-unstandardized-scores"><i class="fa fa-check"></i><b>7.2.1</b> PCA on Unstandardized Scores</a></li>
<li class="chapter" data-level="7.2.2" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#pca-on-the-standardized-scores"><i class="fa fa-check"></i><b>7.2.2</b> PCA on the Standardized Scores</a></li>
<li class="chapter" data-level="7.2.3" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#let-the-psych-package-do-the-work"><i class="fa fa-check"></i><b>7.2.3</b> Let the Psych Package Do the Work</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#heptathlon-example"><i class="fa fa-check"></i><b>7.3</b> Heptathlon example</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#data-and-data-cleaning"><i class="fa fa-check"></i><b>7.3.1</b> Data and data cleaning</a></li>
<li class="chapter" data-level="7.3.2" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#examine-assumption-of-linearity"><i class="fa fa-check"></i><b>7.3.2</b> Examine assumption of linearity</a></li>
<li class="chapter" data-level="7.3.3" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#multivariate-normality-and-outliers"><i class="fa fa-check"></i><b>7.3.3</b> Multivariate normality and outliers</a></li>
<li class="chapter" data-level="7.3.4" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#re-examine-linearity-and-normality"><i class="fa fa-check"></i><b>7.3.4</b> Re-examine linearity and normality</a></li>
<li class="chapter" data-level="7.3.5" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#fit-the-initial-pca"><i class="fa fa-check"></i><b>7.3.5</b> Fit the initial PCA</a></li>
<li class="chapter" data-level="7.3.6" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#determine-the-number-of-components-to-retain"><i class="fa fa-check"></i><b>7.3.6</b> Determine the number of components to retain</a></li>
<li class="chapter" data-level="7.3.7" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#refit-the-pca-model-using-rotation-if-that-is-acceptable-in-your-field"><i class="fa fa-check"></i><b>7.3.7</b> Refit the PCA model, using rotation if that is acceptable in your field</a></li>
<li class="chapter" data-level="7.3.8" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#interpret-the-components"><i class="fa fa-check"></i><b>7.3.8</b> Interpret the components</a></li>
<li class="chapter" data-level="7.3.9" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#saving-the-scores"><i class="fa fa-check"></i><b>7.3.9</b> Saving the scores</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#other-example-from-later-in-the-chapter-not-assigned"><i class="fa fa-check"></i><b>7.4</b> Other example from later in the chapter (not assigned)</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#usairpollution-data"><i class="fa fa-check"></i><b>7.4.1</b> USairpollution Data</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#another-resource"><i class="fa fa-check"></i><b>7.5</b> Another resource</a></li>
<li class="chapter" data-level="7.6" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#references"><i class="fa fa-check"></i><b>7.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html"><i class="fa fa-check"></i><b>8</b> Week 07: Exploratory Factor Analysis, Part 1</a>
<ul>
<li class="chapter" data-level="8.1" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#introductory-comments"><i class="fa fa-check"></i><b>8.1</b> Introductory comments</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#packages"><i class="fa fa-check"></i><b>8.1.1</b> Packages</a></li>
<li class="chapter" data-level="8.1.2" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#efa-ne-pca"><i class="fa fa-check"></i><b>8.1.2</b> EFA <span class="math inline">\(\ne\)</span> PCA</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#preparatory-steps"><i class="fa fa-check"></i><b>8.2</b> Preparatory steps</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#examining-the-data"><i class="fa fa-check"></i><b>8.2.1</b> Examining the data</a></li>
<li class="chapter" data-level="8.2.2" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#addressing-assumptions"><i class="fa fa-check"></i><b>8.2.2</b> Addressing assumptions</a></li>
<li class="chapter" data-level="8.2.3" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#determining-factorability"><i class="fa fa-check"></i><b>8.2.3</b> Determining factorability</a></li>
<li class="chapter" data-level="8.2.4" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#determining-how-many-factors-to-retain"><i class="fa fa-check"></i><b>8.2.4</b> Determining how many factors to retain</a></li>
<li class="chapter" data-level="8.2.5" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#factor-analysis-with-a-data-matrix-raw-data"><i class="fa fa-check"></i><b>8.2.5</b> Factor analysis with a data matrix (raw data)</a></li>
<li class="chapter" data-level="8.2.6" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#factor-analysis-with-correlation-data"><i class="fa fa-check"></i><b>8.2.6</b> Factor analysis with correlation data</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#references-1"><i class="fa fa-check"></i><b>8.3</b> References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html"><i class="fa fa-check"></i><b>9</b> Week 08: Exploratory Factor Analysis, Part 2</a>
<ul>
<li class="chapter" data-level="9.1" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#factor-analysis-with-correlation-data-1"><i class="fa fa-check"></i><b>9.1</b> Factor analysis with correlation data</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#setting-up-the-data-1"><i class="fa fa-check"></i><b>9.1.1</b> Setting up the data</a></li>
<li class="chapter" data-level="9.1.2" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#preparatory-steps-2"><i class="fa fa-check"></i><b>9.1.2</b> Preparatory steps</a></li>
<li class="chapter" data-level="9.1.3" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#performing-the-factor-analysis-1"><i class="fa fa-check"></i><b>9.1.3</b> Performing the factor analysis</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#efa-with-categorical-data"><i class="fa fa-check"></i><b>9.2</b> EFA with categorical data</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#describing-categorical-data"><i class="fa fa-check"></i><b>9.2.1</b> Describing categorical data</a></li>
<li class="chapter" data-level="9.2.2" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#factor-scores"><i class="fa fa-check"></i><b>9.2.2</b> Factor scores</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#practice"><i class="fa fa-check"></i><b>9.3</b> Practice</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#summary-2"><i class="fa fa-check"></i><b>9.3.1</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#references-2"><i class="fa fa-check"></i><b>9.4</b> References</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html"><i class="fa fa-check"></i><b>10</b> Week 09: Confirmatory Factor Analysis</a>
<ul>
<li class="chapter" data-level="10.1" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#preparatory-steps-3"><i class="fa fa-check"></i><b>10.1</b> Preparatory steps</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#describing-the-data"><i class="fa fa-check"></i><b>10.1.1</b> Describing the data</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#fitting-a-cfa-model"><i class="fa fa-check"></i><b>10.2</b> Fitting a CFA model</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#making-sure-the-model-was-correctly-estimated"><i class="fa fa-check"></i><b>10.2.1</b> Making sure the model was correctly estimated</a></li>
<li class="chapter" data-level="10.2.2" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#evaluating-the-model-fit"><i class="fa fa-check"></i><b>10.2.2</b> Evaluating the model fit</a></li>
<li class="chapter" data-level="10.2.3" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#interpretting-the-parameter-estimates"><i class="fa fa-check"></i><b>10.2.3</b> Interpretting the parameter estimates</a></li>
<li class="chapter" data-level="10.2.4" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#further-inspecting-our-model"><i class="fa fa-check"></i><b>10.2.4</b> Further inspecting our model</a></li>
<li class="chapter" data-level="10.2.5" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#further-inspecting-our-models-parameters"><i class="fa fa-check"></i><b>10.2.5</b> Further inspecting our model’s parameters</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#using-alternative-model-specifications"><i class="fa fa-check"></i><b>10.3</b> Using alternative model specifications</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#rescaling-the-factors-to-be-standardized"><i class="fa fa-check"></i><b>10.3.1</b> Rescaling the factors to be standardized</a></li>
<li class="chapter" data-level="10.3.2" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#specifying-a-competing-nested-model"><i class="fa fa-check"></i><b>10.3.2</b> Specifying a competing, nested, model</a></li>
<li class="chapter" data-level="10.3.3" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#conducting-model-comparisons"><i class="fa fa-check"></i><b>10.3.3</b> Conducting model comparisons</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#estimating-factor-scores"><i class="fa fa-check"></i><b>10.4</b> Estimating factor scores</a></li>
<li class="chapter" data-level="10.5" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#cfa-with-categorical-data"><i class="fa fa-check"></i><b>10.5</b> CFA with categorical data</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#using-data-from-an-r-package"><i class="fa fa-check"></i><b>10.5.1</b> Using data from an R package</a></li>
<li class="chapter" data-level="10.5.2" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#preparing-the-data"><i class="fa fa-check"></i><b>10.5.2</b> Preparing the data</a></li>
<li class="chapter" data-level="10.5.3" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#describing-the-data-1"><i class="fa fa-check"></i><b>10.5.3</b> Describing the data</a></li>
<li class="chapter" data-level="10.5.4" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#fitting-the-cfa-model"><i class="fa fa-check"></i><b>10.5.4</b> Fitting the CFA model</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#way-tldr-summary"><i class="fa fa-check"></i><b>10.6</b> Way TL;DR Summary</a></li>
<li class="chapter" data-level="10.7" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#references-3"><i class="fa fa-check"></i><b>10.7</b> References</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">EDUC 644 Applied Multivariate Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-05-discriminant-function-analysis" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">6</span> Week 05, Discriminant Function Analysis<a href="week-05-discriminant-function-analysis.html#week-05-discriminant-function-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The following code follows the first example in Chapter 10 of Pituch and Stevens. The results are not exactly the same, with some discriminant-function scores being opposite in sign or slightly different from those in SPSS. This is because the algorithms in SPSS and R differ; however, the interpretations are the same.</p>
<p>The data are the same as those from previous chapters, in the <code>SENIORWISE.sav</code> data set.</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="week-05-discriminant-function-analysis.html#cb264-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb264-2"><a href="week-05-discriminant-function-analysis.html#cb264-2" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb264-3"><a href="week-05-discriminant-function-analysis.html#cb264-3" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">&quot;SENIORWISE.sav&quot;</span>)</span>
<span id="cb264-4"><a href="week-05-discriminant-function-analysis.html#cb264-4" tabindex="-1"></a><span class="fu">names</span>(dat) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(dat))</span>
<span id="cb264-5"><a href="week-05-discriminant-function-analysis.html#cb264-5" tabindex="-1"></a>dat<span class="sc">$</span>group <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">as_factor</span>(dat<span class="sc">$</span>group)</span>
<span id="cb264-6"><a href="week-05-discriminant-function-analysis.html#cb264-6" tabindex="-1"></a><span class="fu">glimpse</span>(dat)</span></code></pre></div>
<pre><code>## Rows: 300
## Columns: 5
## $ self_efficacy &lt;dbl&gt; 71.12113, 52.79091, 48.47966, 44.68057, 63.27477, 57.46376, 63.44811, 55.29445…
## $ verbal        &lt;dbl&gt; 68.77818, 65.92806, 47.47397, 53.70983, 62.73965, 61.65866, 61.41480, 44.31990…
## $ dafs          &lt;dbl&gt; 84.16686, 61.80243, 38.93529, 77.71841, 60.50377, 58.31163, 47.58763, 52.05460…
## $ group         &lt;fct&gt; Memory Training, Memory Training, Memory Training, Memory Training, Memory Tra…
## $ case          &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,…</code></pre>
<div id="fitting-the-discriminant-function-analysis-model" class="section level3 hasAnchor" number="6.0.1">
<h3><span class="header-section-number">6.0.1</span> Fitting the discriminant function analysis model<a href="week-05-discriminant-function-analysis.html#fitting-the-discriminant-function-analysis-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As is usual in R, there are many different ways to accomplish the same thing. The MASS package, and its <code>lda()</code> function seems to be one frequently used function for conducting linear discriminant function analysis in R.</p>
<p>More conveniently, the <a href="https://rdrr.io/cran/DFA.CANCOR/man/DFA.html">DFA.CANCOR</a> package provides output that is similar to that of SPSS and SAS and provides an output that is easy to use.</p>
<p>In the <code>DFA.CANCOR::DFA()</code> function, we specify the data, the group variable, the discriminant variables (which were the dependent variables in MANOVA), and we set <code>predictive = FALSE</code> because we’re doing <em>descriptive</em> discriminant analysis (rather than classification, which is discussed later in the chapter). I also set <code>verbos = FALSE</code> but you can set it to <code>TRUE</code> (the default) if you want to see the lengthy output. We can save the output to an object and request specific information, stored as lists (which we can read about in the help file), from that output. You can examine the plot they provide if you set that the <code>TRUE</code>.</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="week-05-discriminant-function-analysis.html#cb266-1" tabindex="-1"></a><span class="co"># install.packages(&quot;DFA.CANCOR&quot;)</span></span>
<span id="cb266-2"><a href="week-05-discriminant-function-analysis.html#cb266-2" tabindex="-1"></a><span class="fu">library</span>(DFA.CANCOR)</span>
<span id="cb266-3"><a href="week-05-discriminant-function-analysis.html#cb266-3" tabindex="-1"></a>fit.dfa <span class="ot">&lt;-</span> <span class="fu">DFA</span>(<span class="at">data =</span> dat, </span>
<span id="cb266-4"><a href="week-05-discriminant-function-analysis.html#cb266-4" tabindex="-1"></a>            <span class="at">groups =</span> <span class="st">&quot;group&quot;</span>, </span>
<span id="cb266-5"><a href="week-05-discriminant-function-analysis.html#cb266-5" tabindex="-1"></a>            <span class="at">variables =</span> <span class="fu">c</span>(<span class="st">&quot;self_efficacy&quot;</span>, <span class="st">&quot;verbal&quot;</span>, <span class="st">&quot;dafs&quot;</span>),</span>
<span id="cb266-6"><a href="week-05-discriminant-function-analysis.html#cb266-6" tabindex="-1"></a>            <span class="at">predictive =</span> <span class="cn">FALSE</span>,</span>
<span id="cb266-7"><a href="week-05-discriminant-function-analysis.html#cb266-7" tabindex="-1"></a>            <span class="at">plot =</span> <span class="cn">FALSE</span>,</span>
<span id="cb266-8"><a href="week-05-discriminant-function-analysis.html#cb266-8" tabindex="-1"></a>            <span class="at">verbos =</span> <span class="cn">FALSE</span>) <span class="co"># verbose = TRUE is the default and outputs everything.</span></span></code></pre></div>
</div>
<div id="dimension-reduction-analysis" class="section level3 hasAnchor" number="6.0.2">
<h3><span class="header-section-number">6.0.2</span> Dimension reduction analysis<a href="week-05-discriminant-function-analysis.html#dimension-reduction-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here are the results reported in Table 10.4 (p. 401) of our reading.</p>
<p>Here are the eigenvalues:</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="week-05-discriminant-function-analysis.html#cb267-1" tabindex="-1"></a>fit.dfa<span class="sc">$</span>evals</span></code></pre></div>
<pre><code>##  Function eigenvalue proportion of variance canonical r
##         1 0.29047037             0.91909386   0.4744352
##         2 0.02556957             0.08090614   0.1578989</code></pre>
<p>We learned in MANOVA that Wilks’ lambda can be calculated as
<span class="math display">\[\Lambda = \frac{|\mathbf{W}|}{|\mathbf{W} + \mathbf{B}|}\]</span>
It can also be calculated from the eigenvalues as
<span class="math display">\[\Lambda = \frac{1}{1 + \phi_1} \times \frac{1}{1 + \phi_2} \times \cdots \times \frac{1}{1 + \phi_r}\]</span>
In R, we can use the following code to compute this equation:</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="week-05-discriminant-function-analysis.html#cb269-1" tabindex="-1"></a>Wilks.Lambda <span class="ot">&lt;-</span> <span class="fu">prod</span>( <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> fit.dfa<span class="sc">$</span>evals[ ,<span class="dv">2</span>]) )</span>
<span id="cb269-2"><a href="week-05-discriminant-function-analysis.html#cb269-2" tabindex="-1"></a>Wilks.Lambda</span></code></pre></div>
<pre><code>## [1] 0.7555911</code></pre>
<p>The statistical test is distributed as a <span class="math inline">\(\chi^2\)</span> with <span class="math inline">\(p(k-1)\)</span> degrees of freedom.</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="week-05-discriminant-function-analysis.html#cb271-1" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dat)</span>
<span id="cb271-2"><a href="week-05-discriminant-function-analysis.html#cb271-2" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="co"># number of discriminant variables (DVs if we were doing MANOVA)</span></span>
<span id="cb271-3"><a href="week-05-discriminant-function-analysis.html#cb271-3" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">levels</span>(dat<span class="sc">$</span>group))</span>
<span id="cb271-4"><a href="week-05-discriminant-function-analysis.html#cb271-4" tabindex="-1"></a>df <span class="ot">&lt;-</span> p<span class="sc">*</span>(k<span class="dv">-1</span>)</span>
<span id="cb271-5"><a href="week-05-discriminant-function-analysis.html#cb271-5" tabindex="-1"></a>eigenvalues <span class="ot">&lt;-</span> fit.dfa<span class="sc">$</span>evals[ ,<span class="dv">2</span>]</span>
<span id="cb271-6"><a href="week-05-discriminant-function-analysis.html#cb271-6" tabindex="-1"></a>Chi.sqr <span class="ot">&lt;-</span> (N <span class="sc">-</span> <span class="dv">1</span> <span class="sc">-</span> (p <span class="sc">+</span> k) <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">log</span>(<span class="dv">1</span> <span class="sc">+</span> eigenvalues))</span>
<span id="cb271-7"><a href="week-05-discriminant-function-analysis.html#cb271-7" tabindex="-1"></a>Chi.sqr</span></code></pre></div>
<pre><code>## [1] 82.95546</code></pre>
<p>And here is the <em>p</em>-value:</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="week-05-discriminant-function-analysis.html#cb273-1" tabindex="-1"></a><span class="fu">pchisq</span>(Chi.sqr, <span class="at">df =</span> df, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 8.74953e-16</code></pre>
<p>With the second discriminant function, we use the rest of the eigenvalues in the equation. In this case, there is only one:</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="week-05-discriminant-function-analysis.html#cb275-1" tabindex="-1"></a>Wilks.Lambda2 <span class="ot">&lt;-</span> <span class="fu">prod</span>( <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> eigenvalues[<span class="dv">2</span>] ) )</span>
<span id="cb275-2"><a href="week-05-discriminant-function-analysis.html#cb275-2" tabindex="-1"></a>Wilks.Lambda2</span></code></pre></div>
<pre><code>## [1] 0.9750679</code></pre>
<p>The statistical test is now of the remaining function(s):</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="week-05-discriminant-function-analysis.html#cb277-1" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> (p<span class="dv">-1</span>)<span class="sc">*</span>(k<span class="dv">-2</span>)</span>
<span id="cb277-2"><a href="week-05-discriminant-function-analysis.html#cb277-2" tabindex="-1"></a>Chi.sqr <span class="ot">&lt;-</span> (N <span class="sc">-</span> <span class="dv">1</span> <span class="sc">-</span> (p <span class="sc">+</span> k) <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">log</span>(<span class="dv">1</span> <span class="sc">+</span> fit.dfa<span class="sc">$</span>evals[<span class="dv">2</span>,<span class="dv">2</span>]))</span>
<span id="cb277-3"><a href="week-05-discriminant-function-analysis.html#cb277-3" tabindex="-1"></a>p.value <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(Chi.sqr, <span class="at">df =</span> df2, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb277-4"><a href="week-05-discriminant-function-analysis.html#cb277-4" tabindex="-1"></a></span>
<span id="cb277-5"><a href="week-05-discriminant-function-analysis.html#cb277-5" tabindex="-1"></a>Chi.sqr</span></code></pre></div>
<pre><code>## [1] 7.473449</code></pre>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="week-05-discriminant-function-analysis.html#cb279-1" tabindex="-1"></a>p.value</span></code></pre></div>
<pre><code>## [1] 0.02383204</code></pre>
<p>Alternatively, we can pull up the results from our output of the <code>DFA()</code> function.</p>
<p>Here are the statistical tests:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="week-05-discriminant-function-analysis.html#cb281-1" tabindex="-1"></a>fit.dfa<span class="sc">$</span>mv_Wilk</span></code></pre></div>
<pre><code>##             Wilk&#39;s Lambda F-approx. df1 df2            p
## 1 through 2     0.7555911 14.791342   6 590 8.764499e-16
## 2 through 2     0.9750679  3.784297   2 296 2.383204e-02</code></pre>
<p>Because Wilk’s Lambda with the second discriminant function resulted in <code>NaN</code>, let’s look at the Pillai’s trace statistics:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="week-05-discriminant-function-analysis.html#cb283-1" tabindex="-1"></a>fit.dfa<span class="sc">$</span>mv_Pillai</span></code></pre></div>
<pre><code>##             Pillai-Bartlett Trace F-approx. df1 df2            p
## 1 through 2            0.25002083 14.096580   6 592 4.933440e-15
## 2 through 2            0.02493207  3.809866   2 596 2.269257e-02</code></pre>
<p>The Wilks’ lambda for the second discriminant function in R showed up as <code>NaN</code> (not a number), but the Pillai’s trace results were successful, so we used those and conluded that we can use all two discriminant functions.</p>
<p>Note that we have three levels to the group variable, so <span class="math inline">\(k - 1 = 2\)</span>. We have three discriminant variables (<code>self_efficacy</code>, <code>verbal</code>, and <code>dafs</code>), so <span class="math inline">\(p = 3\)</span>. The maximum number of discriminant functions we can get with these data is <span class="math inline">\(min(p, k-1)\)</span>, which is two. The model with the second discriminant function is statistically significant, so we can include both the first and second discriminant function in our analysis. <strong>If</strong> only the first model were significant, we would interpret only that first discriminant function; in other words, we could reduce the number of dimensions to one.</p>
<div id="effect-sizes" class="section level4 hasAnchor" number="6.0.2.1">
<h4><span class="header-section-number">6.0.2.1</span> Effect sizes<a href="week-05-discriminant-function-analysis.html#effect-sizes" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can look at the effect size in two different ways: 1) as the proportion of between-group variance that is accounted for by each discriminant function, and 2) the proportion of variance in the discriminant variable that is between groups. Here’s the first one, which uses the sums-of-squares.<a href="#fn26" class="footnote-ref" id="fnref26"><sup>26</sup></a></p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="week-05-discriminant-function-analysis.html#cb285-1" tabindex="-1"></a>(N <span class="sc">-</span> k)<span class="sc">*</span>eigenvalues <span class="sc">/</span> <span class="fu">sum</span>((N <span class="sc">-</span> k)<span class="sc">*</span>eigenvalues )</span></code></pre></div>
<pre><code>##                       
## 0.91909386 0.08090614</code></pre>
<p>Which are the same values in the <code>proportion of variance</code> column in the output:</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="week-05-discriminant-function-analysis.html#cb287-1" tabindex="-1"></a>fit.dfa<span class="sc">$</span>evals</span></code></pre></div>
<pre><code>##  Function eigenvalue proportion of variance canonical r
##         1 0.29047037             0.91909386   0.4744352
##         2 0.02556957             0.08090614   0.1578989</code></pre>
<p>The first discriminant function explains 92% of the between-group variance, which is a strong effect. The second one was 8.10% of the variance, which is much lower.</p>
<p>The other effect size is the proportion of variance in the discriminating variable that is explained by the group, which is analogous to eta-squared.</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="week-05-discriminant-function-analysis.html#cb289-1" tabindex="-1"></a>canon.cor <span class="ot">&lt;-</span> fit.dfa<span class="sc">$</span>evals[, <span class="dv">4</span>]</span>
<span id="cb289-2"><a href="week-05-discriminant-function-analysis.html#cb289-2" tabindex="-1"></a>canon.cor</span></code></pre></div>
<pre><code>##                     
## 0.4744352 0.1578989</code></pre>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="week-05-discriminant-function-analysis.html#cb291-1" tabindex="-1"></a>canon.cor<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>##                       
## 0.22508876 0.02493207</code></pre>
<p>So, about 23% of the variance in the first discriminant function is explained by the group variable; about 2.50% of that of the second discriminant function is explained by the group variable.</p>
</div>
</div>
<div id="structure-and-standardized-discriminant-function-coefficients" class="section level3 hasAnchor" number="6.0.3">
<h3><span class="header-section-number">6.0.3</span> Structure and standardized discriminant function coefficients<a href="week-05-discriminant-function-analysis.html#structure-and-standardized-discriminant-function-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here are the results that are displayed in Table 10.5 (p. 403) of the text.</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="week-05-discriminant-function-analysis.html#cb293-1" tabindex="-1"></a>fit.dfa<span class="sc">$</span>coefs_structure</span></code></pre></div>
<pre><code>##               Function 1 Function 2
## self_efficacy -0.8199226  0.3637932
## verbal        -0.7656266 -0.6366741
## dafs          -0.6760304  0.2335248</code></pre>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="week-05-discriminant-function-analysis.html#cb295-1" tabindex="-1"></a>fit.dfa<span class="sc">$</span>coefs_standardized</span></code></pre></div>
<pre><code>##               Function 1 Function 2
## self_efficacy -0.5714374  0.5478547
## verbal        -0.4399244 -1.0593537
## dafs          -0.2829758  0.5262326</code></pre>
<p>This is where we interpret what the discriminant functions mean. We use the standardized discriminant-function coefficients for this purpose unless only the first one was found statistically significant. Pituch and Stevens observed that the three standardized coefficients on the first composite variable are somewhat similar. We see that self-efficacy and verbal constituted good proportions of this discriminant function—their standardized DF coefficients indicated that this relationship was, respectively, about about 0.57 and 0.44 of a standard deviation unit of the discriminant function. This result makes sense because self-efficacy in memory skills and verbal memory skills will be related if the self-efficacy belief held by the seniors was accurate. The third one, DAFS (daily functioning skills) was somewhat related to the discriminant function, at 0.28. Note that all three are the same sign, which means the three discriminant variables relate to the discriminant function in the same direction. Our interpretation of this discriminant function is a matter of judgement. Any ideas on how to label this discriminant function?</p>
<p>The second discriminant function had one relationship, with verbal memory of -1.06, that stood out stronger than the other two. It was also in the opposite direction to the other two observed variables’ relationships to this composite variable. This second function seems to represent verbal memory beyond what the first function had represented.</p>
</div>
<div id="discriminant-function-scores" class="section level3 hasAnchor" number="6.0.4">
<h3><span class="header-section-number">6.0.4</span> Discriminant function scores<a href="week-05-discriminant-function-analysis.html#discriminant-function-scores" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Each case in our data set has a discriminant function score. This is their score on the composite (AKA discriminant function), which is calculated based on the unstandardized (raw) coefficients.</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="week-05-discriminant-function-analysis.html#cb297-1" tabindex="-1"></a>fit.dfa<span class="sc">$</span>coefs_raw</span></code></pre></div>
<pre><code>##                Function 1  Function 2
## self_efficacy -0.06128037  0.05875138
## verbal        -0.04621916 -0.11129737
## dafs          -0.02972191  0.05527201</code></pre>
<p>For example, Case 1 has a discriminant function score of
<span class="math display">\[d_{(i=1),1} = -2.67\]</span></p>
<p>which comes from the raw coefficients and an intercept. Here are the raw scores on the discriminant variables (the DVs if we do MANOVA) for Case 1 (using some excessive tidyverse coding to get around the troubles with tibbles):</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="week-05-discriminant-function-analysis.html#cb299-1" tabindex="-1"></a>(dat[<span class="dv">1</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]) <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>() <span class="sc">%&gt;%</span> <span class="fu">round</span>(., <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##   self_efficacy verbal  dafs
## 1         71.12  68.78 84.17</code></pre>
<p>Their discriminant function score is calculated as</p>
<p><span class="math display">\[d_{(i=1),1} = 7.37 +
-0.0613 (71.12) + -0.0462 (68.78) + -0.0297 (84.17) \]</span></p>
<p>Here are the results that are displayed in Table 10.9 (p. 407) of the text. We’ll use these to calculate the centroids that are reported in Table 10.6. Each person’s discriminant-function score is recorded in the output, which we can attach to the data. Here, I’m labeling discriminant function 1 and 2 <code>d1</code> and <code>d2</code>.</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="week-05-discriminant-function-analysis.html#cb301-1" tabindex="-1"></a>dat[, <span class="fu">c</span>(<span class="st">&quot;d1&quot;</span>, <span class="st">&quot;d2&quot;</span>)] <span class="ot">&lt;-</span> fit.dfa<span class="sc">$</span>dfa_scores[, <span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb301-2"><a href="week-05-discriminant-function-analysis.html#cb301-2" tabindex="-1"></a><span class="fu">head</span>(dat, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 7
##    self_efficacy verbal  dafs group            case     d1      d2
##            &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;           &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
##  1          71.1   68.8  84.2 Memory Training     1 -2.67   1.16  
##  2          52.8   65.9  61.8 Memory Training     2 -0.750 -0.834 
##  3          48.5   47.5  38.9 Memory Training     3  1.05  -0.297 
##  4          44.7   53.7  77.7 Memory Training     4 -0.161  0.929 
##  5          63.3   62.7  60.5 Memory Training     5 -1.21   0.0649
##  6          57.5   61.7  58.3 Memory Training     6 -0.735 -0.277 
##  7          63.4   61.4  47.6 Memory Training     7 -0.772 -0.491 
##  8          55.3   44.3  52.1 Memory Training     8  0.385  1.18  
##  9          52.8   67.7  61.1 Memory Training     9 -0.810 -1.07  
## 10          46.0   52.5  36.8 Memory Training    10  1.03  -1.12</code></pre>
</div>
<div id="group-means-centroids-of-the-discriminant-function-scores" class="section level3 hasAnchor" number="6.0.5">
<h3><span class="header-section-number">6.0.5</span> Group means (centroids) of the discriminant-function scores<a href="week-05-discriminant-function-analysis.html#group-means-centroids-of-the-discriminant-function-scores" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here are the results that are displayed in Table 10.6 (p. 404) of the text. We can use dplyr’s <code>group_by()</code> and <code>summarize()</code> functions, then save the means as a small data frame, which we’ll use in the plot reported in our reading. We can also add the standard deviations.<a href="#fn27" class="footnote-ref" id="fnref27"><sup>27</sup></a> If we want, we can also include the raw scores of the discriminant variables, though these would be earlier in the report when we reported the descriptive statistics.</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="week-05-discriminant-function-analysis.html#cb303-1" tabindex="-1"></a>grpcentroids <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb303-2"><a href="week-05-discriminant-function-analysis.html#cb303-2" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb303-3"><a href="week-05-discriminant-function-analysis.html#cb303-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">M1 =</span> <span class="fu">mean</span>(d1),</span>
<span id="cb303-4"><a href="week-05-discriminant-function-analysis.html#cb303-4" tabindex="-1"></a>            <span class="at">M2 =</span> <span class="fu">mean</span>(d2),</span>
<span id="cb303-5"><a href="week-05-discriminant-function-analysis.html#cb303-5" tabindex="-1"></a>            <span class="at">SD1 =</span> <span class="fu">sd</span>(d1),</span>
<span id="cb303-6"><a href="week-05-discriminant-function-analysis.html#cb303-6" tabindex="-1"></a>            <span class="at">SD2 =</span> <span class="fu">sd</span>(d2),</span>
<span id="cb303-7"><a href="week-05-discriminant-function-analysis.html#cb303-7" tabindex="-1"></a>            <span class="at">m_sef=</span> <span class="fu">mean</span>(self_efficacy),</span>
<span id="cb303-8"><a href="week-05-discriminant-function-analysis.html#cb303-8" tabindex="-1"></a>            <span class="at">m_ver=</span> <span class="fu">mean</span>(verbal),</span>
<span id="cb303-9"><a href="week-05-discriminant-function-analysis.html#cb303-9" tabindex="-1"></a>            <span class="at">m_daf=</span> <span class="fu">mean</span>(dafs))</span>
<span id="cb303-10"><a href="week-05-discriminant-function-analysis.html#cb303-10" tabindex="-1"></a>grpcentroids <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), round, <span class="dv">2</span>))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 8
##   group              M1    M2   SD1   SD2 m_sef m_ver m_daf
##   &lt;fct&gt;           &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Memory Training -0.76 -0.01  1.01  1.07  58.5  60.2  59.2
## 2 Health Training  0.36  0.2   0.99  0.95  50.6  50.8  52.4
## 3 Control          0.4  -0.19  1.01  0.98  49.0  52.9  51.2</code></pre>
<p>Alternatively, we can use the output from the function to get the same report of the centroid means.</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="week-05-discriminant-function-analysis.html#cb305-1" tabindex="-1"></a>fit.dfa<span class="sc">$</span>centroids</span></code></pre></div>
<pre><code>##                 Function 1  Function 2
## Memory Training -0.7579728 -0.01040184
## Health Training  0.3575702  0.19985504
## Control          0.4004027 -0.18945320</code></pre>
</div>
<div id="bivariate-scatterplot" class="section level3 hasAnchor" number="6.0.6">
<h3><span class="header-section-number">6.0.6</span> Bivariate scatterplot<a href="week-05-discriminant-function-analysis.html#bivariate-scatterplot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The plot like that in Figure 10.2 is not automatically generated by the <code>DFA()</code> function, probably because this is only meaningful when we have two discriminant functions, but we can use ggplot with the discriminant-function scores to do something similar. Here, we’re using the discriminant-function scores we had attached to the data, plotting them on a scatterplot, and then using the group centroids we just calculated and saved to the <code>grpcentroids</code> object to overlay the group means. Note that the sign of the discriminant functions is reversed compared to that of SPSS—in other words, those who scored positive in SPSS scored negative in R. What we’re interested in is the difference between the groups, not in their signs, so the interpretation is the same.</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="week-05-discriminant-function-analysis.html#cb307-1" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb307-2"><a href="week-05-discriminant-function-analysis.html#cb307-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> d1, <span class="at">y =</span> d2)) <span class="sc">+</span> </span>
<span id="cb307-3"><a href="week-05-discriminant-function-analysis.html#cb307-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb307-4"><a href="week-05-discriminant-function-analysis.html#cb307-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> grpcentroids, <span class="fu">aes</span>(<span class="at">x =</span> M1, <span class="at">y =</span> M2, <span class="at">shape =</span> group), </span>
<span id="cb307-5"><a href="week-05-discriminant-function-analysis.html#cb307-5" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;dark red&quot;</span>, </span>
<span id="cb307-6"><a href="week-05-discriminant-function-analysis.html#cb307-6" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">4</span>)</span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-149-1.png" width="672" /></p>
</div>
<div id="write-up" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Write-up<a href="week-05-discriminant-function-analysis.html#write-up" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We fit the linear discriminant function analysis to the data using the CFA function from the DFA.CANCOR package (O’Connor, 2022) in R. There were two possible discriminant functions from the data; both were statistically significant and retained for the analysis.</p>
<p>The first discriminant function of the multivariate solution accounted for 92% of the between-group variance on these three variables. We examined the associated standardized discriminant-function coefficients (SDFC) and identified that self-efficacy <span class="math inline">\((SDFC = -0.575)\)</span> and verbal memory <span class="math inline">\((SDFC = -0.44)\)</span> were most important in forming the function that discriminated among the three treatment groups. Daily functioning skills (DAFS) contributed somewhat to the function <span class="math inline">\((SDFC = -0.28)\)</span> as well. The structure coefficients indicated that the first two observed measures had strong correlations with the multivariate composite: For self-efficacy, <span class="math inline">\(r = -.82\)</span> and for verbal memory, <span class="math inline">\(r = -.77\)</span>; with dafs, there was a moderate correlation <span class="math inline">\((r = -.68)\)</span>. For this composite variable, the mean standardized discriminant-function score for the memory-training group was <span class="math inline">\(-0.76 (SD = 1.00)\)</span>, for the health-training group was <span class="math inline">\(M = 0.36 (SD = 0.99)\)</span>, and for the control group was <span class="math inline">\(M = 0.40 (SD = 1.00)\)</span>. Note that these discriminant-function scores are reverse in sign, at least in our model here, of those on the raw scores; in other words, the memory training group had higher scores on this linear combination of self-efficacy and verbal memory (and DAFS to some extent) than the other two groups. The difference was strong—more than one standard-deviation unit.</p>
<p>The second discriminant function only explained about 8% of the between-group variance on these discriminant variables. On this composite variable, verbal memory was the strongest contributor, <span class="math inline">\((SDFC = -1.06)\)</span>. The SDFCs of the other two discriminant variables (0.55 and 0.53) were about half the strength. The structure coefficients were moderate to weak: With the verbal-memory variable, <span class="math inline">\(r = -.64\)</span>; with the other two, the correlations were <span class="math inline">\(r = .36\)</span> and <span class="math inline">\(r = .23\)</span> for self-efficacy and dafs respectively. On this discriminant function, the health-training group <span class="math inline">\(M = 0.20 (SD = 0.95)\)</span> differed from the other two groups, <span class="math inline">\(M = -0.01 (SD = 1.01)\)</span> for the memory training group and <span class="math inline">\(M = -0.19 (SD = 1.01)\)</span> for the dafs group. Though this dimension explains very little of the systematic variance in the model, there is some degree to which the health training had an effect on seniors’ verbal-memory skills beyond what was accounted for in the first composite score.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="26">
<li id="fn26"><p>Recall that we can calculate the sums of squares as the variance times the degrees of freedom. The eigenvalues are variances of the discriminant functions.<a href="week-05-discriminant-function-analysis.html#fnref26" class="footnote-back">↩︎</a></p></li>
<li id="fn27"><p>Note that because these are standardized scores, the standard deviation of the entire sample across the groups is <span class="math inline">\(1.00\)</span> but within each group, it not necessarily be <span class="math inline">\(1.00\)</span>.<a href="week-05-discriminant-function-analysis.html#fnref27" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-04-factorial-manova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-06-principal-components-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
