<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Week 03 Statistical Assumptions of MANOVA | EDUC 644 Applied Multivariate Statistics</title>
  <meta name="description" content="Course materials for multivariate statistics" />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Week 03 Statistical Assumptions of MANOVA | EDUC 644 Applied Multivariate Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course materials for multivariate statistics" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Week 03 Statistical Assumptions of MANOVA | EDUC 644 Applied Multivariate Statistics" />
  
  <meta name="twitter:description" content="Course materials for multivariate statistics" />
  

<meta name="author" content="George Harrison" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="planned-comparisons-and-contrasts.html"/>
<link rel="next" href="week-04-factorial-manova.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="libs/tabwid-1.1.3/tabwid.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Multivariate Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><i class="fa fa-check"></i><b>1</b> Terminology and Matrix Manipulations Used in Multivariate Statistics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#scalars"><i class="fa fa-check"></i><b>1.1</b> Scalars</a></li>
<li class="chapter" data-level="1.2" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#vectors"><i class="fa fa-check"></i><b>1.2</b> Vectors</a></li>
<li class="chapter" data-level="1.3" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#matrices"><i class="fa fa-check"></i><b>1.3</b> Matrices</a></li>
<li class="chapter" data-level="1.4" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#symmetrical-matrices"><i class="fa fa-check"></i><b>1.4</b> Symmetrical Matrices</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#variance-covariance-matrices"><i class="fa fa-check"></i><b>1.4.1</b> Variance-covariance Matrices</a></li>
<li class="chapter" data-level="1.4.2" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#greek-letters"><i class="fa fa-check"></i><b>1.4.2</b> Greek letters</a></li>
<li class="chapter" data-level="1.4.3" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#example-variance-covariance-matrix"><i class="fa fa-check"></i><b>1.4.3</b> Example variance-covariance matrix</a></li>
<li class="chapter" data-level="1.4.4" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#the-diagonal-and-trace"><i class="fa fa-check"></i><b>1.4.4</b> The diagonal and trace</a></li>
<li class="chapter" data-level="1.4.5" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#an-identity-matrix"><i class="fa fa-check"></i><b>1.4.5</b> An identity matrix</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#transposed-vectors-and-matrices"><i class="fa fa-check"></i><b>1.5</b> Transposed Vectors and Matrices</a></li>
<li class="chapter" data-level="1.6" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#matrix-addition-and-subtraction"><i class="fa fa-check"></i><b>1.6</b> Matrix Addition and Subtraction</a></li>
<li class="chapter" data-level="1.7" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#operations-on-matrices-with-a-scalar"><i class="fa fa-check"></i><b>1.7</b> Operations on Matrices with a Scalar</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#sum-of-square-and-cross-product-sscp-matrices"><i class="fa fa-check"></i><b>1.7.1</b> Sum-of-square-and-cross-product (SSCP) matrices</a></li>
<li class="chapter" data-level="1.7.2" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#operations-on-elements-of-a-matrix-example-with-a-correlation-matrix"><i class="fa fa-check"></i><b>1.7.2</b> Operations on elements of a matrix: Example with a correlation matrix</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#matrix-multiplication"><i class="fa fa-check"></i><b>1.8</b> Matrix Multiplication</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#another-example-of-matrix-multiplication-to-get-the-sscp"><i class="fa fa-check"></i><b>1.8.1</b> Another example of matrix multiplication, to get the SSCP</a></li>
<li class="chapter" data-level="1.8.2" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#the-ordering-is-important"><i class="fa fa-check"></i><b>1.8.2</b> The ordering is important</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#inverse-of-a-matrix"><i class="fa fa-check"></i><b>1.9</b> Inverse of a Matrix</a></li>
<li class="chapter" data-level="1.10" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#matrix-determinants-as-generalized-variance"><i class="fa fa-check"></i><b>1.10</b> Matrix determinants, as generalized variance</a></li>
<li class="chapter" data-level="1.11" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#eigenvectors-and-eigenvalues"><i class="fa fa-check"></i><b>1.11</b> Eigenvectors and Eigenvalues</a></li>
<li class="chapter" data-level="1.12" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#summary"><i class="fa fa-check"></i><b>1.12</b> Summary</a></li>
<li class="chapter" data-level="1.13" data-path="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html"><a href="terminology-and-matrix-manipulations-used-in-multivariate-statistics.html#optional-spss-and-r-code-to-manipulate-matrices"><i class="fa fa-check"></i><b>1.13</b> Optional: SPSS and R Code to Manipulate Matrices</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="hotellings-t2.html"><a href="hotellings-t2.html"><i class="fa fa-check"></i><b>2</b> Hotelling’s <span class="math inline">\(T^2\)</span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="hotellings-t2.html"><a href="hotellings-t2.html#within-group-covariance-matrices"><i class="fa fa-check"></i><b>2.1</b> Within-group covariance matrices</a></li>
<li class="chapter" data-level="2.2" data-path="hotellings-t2.html"><a href="hotellings-t2.html#sscp-matrices"><i class="fa fa-check"></i><b>2.2</b> SSCP matrices</a></li>
<li class="chapter" data-level="2.3" data-path="hotellings-t2.html"><a href="hotellings-t2.html#conducting-the-test-using-functions"><i class="fa fa-check"></i><b>2.3</b> Conducting the Test using Functions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html"><i class="fa fa-check"></i><b>3</b> Planned Comparisons and Contrasts</a>
<ul>
<li class="chapter" data-level="3.1" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html#data-from-week-1"><i class="fa fa-check"></i><b>3.1</b> Data from Week 1</a></li>
<li class="chapter" data-level="3.2" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html#orthogonal-contrasts"><i class="fa fa-check"></i><b>3.2</b> Orthogonal contrasts</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html#conditions-for-orthogonal-contrasts"><i class="fa fa-check"></i><b>3.2.1</b> Conditions for orthogonal contrasts</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html#non-orthogonal-contrasts"><i class="fa fa-check"></i><b>3.3</b> Non-orthogonal contrasts</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html#accounting-for-type-i-error-in-non-orthogonal-contrasts."><i class="fa fa-check"></i><b>3.3.1</b> Accounting for Type I error in non-orthogonal contrasts.</a></li>
<li class="chapter" data-level="3.3.2" data-path="planned-comparisons-and-contrasts.html"><a href="planned-comparisons-and-contrasts.html#post-hoc-tests"><i class="fa fa-check"></i><b>3.3.2</b> Post-hoc tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html"><i class="fa fa-check"></i><b>4</b> Week 03 Statistical Assumptions of MANOVA</a>
<ul>
<li class="chapter" data-level="4.1" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#data"><i class="fa fa-check"></i><b>4.1</b> Data</a></li>
<li class="chapter" data-level="4.2" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#descriptive-statistics"><i class="fa fa-check"></i><b>4.2</b> Descriptive statistics</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#by-group-descriptive-statistics"><i class="fa fa-check"></i><b>4.2.1</b> By-group descriptive statistics</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#normality-assumption"><i class="fa fa-check"></i><b>4.3</b> Normality Assumption</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#univariate-normality"><i class="fa fa-check"></i><b>4.3.1</b> Univariate Normality</a></li>
<li class="chapter" data-level="4.3.2" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#examining-univariate-normality-using-quantile-quantile-plots"><i class="fa fa-check"></i><b>4.3.2</b> Examining univariate normality using quantile-quantile plots</a></li>
<li class="chapter" data-level="4.3.3" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#a-caution-about-statistical-tests-of-statistical-assumptions"><i class="fa fa-check"></i><b>4.3.3</b> A caution about statistical tests of statistical assumptions</a></li>
<li class="chapter" data-level="4.3.4" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#mahalanobis-distance-and-multivariate-outliers"><i class="fa fa-check"></i><b>4.3.4</b> Mahalanobis Distance and Multivariate Outliers</a></li>
<li class="chapter" data-level="4.3.5" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#statistical-tests-of-multivariate-normality"><i class="fa fa-check"></i><b>4.3.5</b> Statistical Tests of Multivariate Normality</a></li>
<li class="chapter" data-level="4.3.6" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#homogeneity-of-covariance"><i class="fa fa-check"></i><b>4.3.6</b> Homogeneity of Covariance</a></li>
<li class="chapter" data-level="4.3.7" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#conclusions-about-our-statistical-assumptions"><i class="fa fa-check"></i><b>4.3.7</b> Conclusions about our statistical assumptions</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#fitting-the-manova-model"><i class="fa fa-check"></i><b>4.4</b> Fitting the MANOVA Model</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#follow-up-analysis-with-univariate-f-tests"><i class="fa fa-check"></i><b>4.4.1</b> Follow-up analysis with univariate <em>F</em>-tests</a></li>
<li class="chapter" data-level="4.4.2" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#effect-size"><i class="fa fa-check"></i><b>4.4.2</b> Effect size</a></li>
<li class="chapter" data-level="4.4.3" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#comparing-the-model-without-outlier"><i class="fa fa-check"></i><b>4.4.3</b> Comparing the Model Without Outlier</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#robust-one-way-manova"><i class="fa fa-check"></i><b>4.5</b> Robust One-way MANOVA</a></li>
<li class="chapter" data-level="4.6" data-path="week-03-statistical-assumptions-of-manova.html"><a href="week-03-statistical-assumptions-of-manova.html#summary-1"><i class="fa fa-check"></i><b>4.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html"><i class="fa fa-check"></i><b>5</b> Week 04 Factorial MANOVA</a>
<ul>
<li class="chapter" data-level="5.1" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#following-tabachnick-and-fidells-notes"><i class="fa fa-check"></i><b>5.1</b> Following Tabachnick and Fidell’s notes</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#another-way-to-get-the-sscp_w"><i class="fa fa-check"></i><b>5.1.1</b> Another way to get the <span class="math inline">\(SSCP_W\)</span>:</a></li>
<li class="chapter" data-level="5.1.2" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#mathbfsscp_between-for-each-factor"><i class="fa fa-check"></i><b>5.1.2</b> <span class="math inline">\(\mathbf{SSCP_{Between}}\)</span> for each factor</a></li>
<li class="chapter" data-level="5.1.3" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#mathbfsscp_between-for-the-interaction"><i class="fa fa-check"></i><b>5.1.3</b> <span class="math inline">\(\mathbf{SSCP_{Between}}\)</span> for the interaction</a></li>
<li class="chapter" data-level="5.1.4" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#these-by-hand-calculations-will-be-available-in-manova."><i class="fa fa-check"></i><b>5.1.4</b> These by-hand calculations will be available in <code>manova()</code>.</a></li>
<li class="chapter" data-level="5.1.5" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#calculating-the-generalized-variance"><i class="fa fa-check"></i><b>5.1.5</b> Calculating the generalized variance</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#calculating-wilks-lambda"><i class="fa fa-check"></i><b>5.2</b> Calculating Wilks’ Lambda</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#fit-the-factorial-manova"><i class="fa fa-check"></i><b>5.2.1</b> Fit the factorial MANOVA</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#mancova"><i class="fa fa-check"></i><b>5.3</b> MANCOVA</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#mancova-example"><i class="fa fa-check"></i><b>5.3.1</b> MANCOVA example</a></li>
<li class="chapter" data-level="5.3.2" data-path="week-04-factorial-manova.html"><a href="week-04-factorial-manova.html#lets-think-about-ordering-and-type-i-sums-of-squares"><i class="fa fa-check"></i><b>5.3.2</b> Let’s think about ordering and Type I sums of squares</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html"><i class="fa fa-check"></i><b>6</b> Week 05, Discriminant Function Analysis</a>
<ul>
<li class="chapter" data-level="6.0.1" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#fitting-the-discriminant-function-analysis-model"><i class="fa fa-check"></i><b>6.0.1</b> Fitting the discriminant function analysis model</a></li>
<li class="chapter" data-level="6.0.2" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#dimension-reduction-analysis"><i class="fa fa-check"></i><b>6.0.2</b> Dimension reduction analysis</a></li>
<li class="chapter" data-level="6.0.3" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#structure-and-standardized-discriminant-function-coefficients"><i class="fa fa-check"></i><b>6.0.3</b> Structure and standardized discriminant function coefficients</a></li>
<li class="chapter" data-level="6.0.4" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#discriminant-function-scores"><i class="fa fa-check"></i><b>6.0.4</b> Discriminant function scores</a></li>
<li class="chapter" data-level="6.0.5" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#group-means-centroids-of-the-discriminant-function-scores"><i class="fa fa-check"></i><b>6.0.5</b> Group means (centroids) of the discriminant-function scores</a></li>
<li class="chapter" data-level="6.0.6" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#bivariate-scatterplot"><i class="fa fa-check"></i><b>6.0.6</b> Bivariate scatterplot</a></li>
<li class="chapter" data-level="6.1" data-path="week-05-discriminant-function-analysis.html"><a href="week-05-discriminant-function-analysis.html#write-up"><i class="fa fa-check"></i><b>6.1</b> Write-up</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html"><i class="fa fa-check"></i><b>7</b> Week 06: Principal Components Analysis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#example-1-to-see-some-properties-of-pca"><i class="fa fa-check"></i><b>7.1</b> Example 1, to see some properties of PCA</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#pca-with-covariance-vs.-correlation"><i class="fa fa-check"></i><b>7.1.1</b> PCA with Covariance vs. Correlation</a></li>
<li class="chapter" data-level="7.1.2" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#unscaled-eigenvectors"><i class="fa fa-check"></i><b>7.1.2</b> Unscaled eigenvectors</a></li>
<li class="chapter" data-level="7.1.3" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#looking-at-the-properties-of-eigenvectors-and-eigenvalues"><i class="fa fa-check"></i><b>7.1.3</b> Looking at the properties of eigenvectors and eigenvalues</a></li>
<li class="chapter" data-level="7.1.4" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#using-the-psych-package"><i class="fa fa-check"></i><b>7.1.4</b> Using the psych package</a></li>
<li class="chapter" data-level="7.1.5" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#determining-how-many-components-to-retain"><i class="fa fa-check"></i><b>7.1.5</b> Determining how many components to retain</a></li>
<li class="chapter" data-level="7.1.6" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#reduced-pca-model"><i class="fa fa-check"></i><b>7.1.6</b> Reduced PCA model</a></li>
<li class="chapter" data-level="7.1.7" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#interpretation-1"><i class="fa fa-check"></i><b>7.1.7</b> Interpretation</a></li>
<li class="chapter" data-level="7.1.8" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#interpretation-of-the-rotated-solution"><i class="fa fa-check"></i><b>7.1.8</b> Interpretation of the rotated solution</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#example-two"><i class="fa fa-check"></i><b>7.2</b> Example Two</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#pca-on-unstandardized-scores"><i class="fa fa-check"></i><b>7.2.1</b> PCA on Unstandardized Scores</a></li>
<li class="chapter" data-level="7.2.2" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#pca-on-the-standardized-scores"><i class="fa fa-check"></i><b>7.2.2</b> PCA on the Standardized Scores</a></li>
<li class="chapter" data-level="7.2.3" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#let-the-psych-package-do-the-work"><i class="fa fa-check"></i><b>7.2.3</b> Let the Psych Package Do the Work</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#heptathlon-example"><i class="fa fa-check"></i><b>7.3</b> Heptathlon example</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#data-and-data-cleaning"><i class="fa fa-check"></i><b>7.3.1</b> Data and data cleaning</a></li>
<li class="chapter" data-level="7.3.2" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#examine-assumption-of-linearity"><i class="fa fa-check"></i><b>7.3.2</b> Examine assumption of linearity</a></li>
<li class="chapter" data-level="7.3.3" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#multivariate-normality-and-outliers"><i class="fa fa-check"></i><b>7.3.3</b> Multivariate normality and outliers</a></li>
<li class="chapter" data-level="7.3.4" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#re-examine-linearity-and-normality"><i class="fa fa-check"></i><b>7.3.4</b> Re-examine linearity and normality</a></li>
<li class="chapter" data-level="7.3.5" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#fit-the-initial-pca"><i class="fa fa-check"></i><b>7.3.5</b> Fit the initial PCA</a></li>
<li class="chapter" data-level="7.3.6" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#determine-the-number-of-components-to-retain"><i class="fa fa-check"></i><b>7.3.6</b> Determine the number of components to retain</a></li>
<li class="chapter" data-level="7.3.7" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#refit-the-pca-model-using-rotation-if-that-is-acceptable-in-your-field"><i class="fa fa-check"></i><b>7.3.7</b> Refit the PCA model, using rotation if that is acceptable in your field</a></li>
<li class="chapter" data-level="7.3.8" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#interpret-the-components"><i class="fa fa-check"></i><b>7.3.8</b> Interpret the components</a></li>
<li class="chapter" data-level="7.3.9" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#saving-the-scores"><i class="fa fa-check"></i><b>7.3.9</b> Saving the scores</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#other-example-from-later-in-the-chapter-not-assigned"><i class="fa fa-check"></i><b>7.4</b> Other example from later in the chapter (not assigned)</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#usairpollution-data"><i class="fa fa-check"></i><b>7.4.1</b> USairpollution Data</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#another-resource"><i class="fa fa-check"></i><b>7.5</b> Another resource</a></li>
<li class="chapter" data-level="7.6" data-path="week-06-principal-components-analysis.html"><a href="week-06-principal-components-analysis.html#references"><i class="fa fa-check"></i><b>7.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html"><i class="fa fa-check"></i><b>8</b> Week 07: Exploratory Factor Analysis, Part 1</a>
<ul>
<li class="chapter" data-level="8.1" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#introductory-comments"><i class="fa fa-check"></i><b>8.1</b> Introductory comments</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#packages"><i class="fa fa-check"></i><b>8.1.1</b> Packages</a></li>
<li class="chapter" data-level="8.1.2" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#efa-ne-pca"><i class="fa fa-check"></i><b>8.1.2</b> EFA <span class="math inline">\(\ne\)</span> PCA</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#preparatory-steps"><i class="fa fa-check"></i><b>8.2</b> Preparatory steps</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#examining-the-data"><i class="fa fa-check"></i><b>8.2.1</b> Examining the data</a></li>
<li class="chapter" data-level="8.2.2" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#addressing-assumptions"><i class="fa fa-check"></i><b>8.2.2</b> Addressing assumptions</a></li>
<li class="chapter" data-level="8.2.3" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#determining-factorability"><i class="fa fa-check"></i><b>8.2.3</b> Determining factorability</a></li>
<li class="chapter" data-level="8.2.4" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#determining-how-many-factors-to-retain"><i class="fa fa-check"></i><b>8.2.4</b> Determining how many factors to retain</a></li>
<li class="chapter" data-level="8.2.5" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#factor-analysis-with-a-data-matrix-raw-data"><i class="fa fa-check"></i><b>8.2.5</b> Factor analysis with a data matrix (raw data)</a></li>
<li class="chapter" data-level="8.2.6" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#factor-analysis-with-correlation-data"><i class="fa fa-check"></i><b>8.2.6</b> Factor analysis with correlation data</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="week-07-exploratory-factor-analysis-part-1.html"><a href="week-07-exploratory-factor-analysis-part-1.html#references-1"><i class="fa fa-check"></i><b>8.3</b> References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html"><i class="fa fa-check"></i><b>9</b> Week 08: Exploratory Factor Analysis, Part 2</a>
<ul>
<li class="chapter" data-level="9.1" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#factor-analysis-with-correlation-data-1"><i class="fa fa-check"></i><b>9.1</b> Factor analysis with correlation data</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#setting-up-the-data-1"><i class="fa fa-check"></i><b>9.1.1</b> Setting up the data</a></li>
<li class="chapter" data-level="9.1.2" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#preparatory-steps-2"><i class="fa fa-check"></i><b>9.1.2</b> Preparatory steps</a></li>
<li class="chapter" data-level="9.1.3" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#performing-the-factor-analysis-1"><i class="fa fa-check"></i><b>9.1.3</b> Performing the factor analysis</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#efa-with-categorical-data"><i class="fa fa-check"></i><b>9.2</b> EFA with categorical data</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#describing-categorical-data"><i class="fa fa-check"></i><b>9.2.1</b> Describing categorical data</a></li>
<li class="chapter" data-level="9.2.2" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#factor-scores"><i class="fa fa-check"></i><b>9.2.2</b> Factor scores</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#practice"><i class="fa fa-check"></i><b>9.3</b> Practice</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#summary-2"><i class="fa fa-check"></i><b>9.3.1</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="week-08-exploratory-factor-analysis-part-2.html"><a href="week-08-exploratory-factor-analysis-part-2.html#references-2"><i class="fa fa-check"></i><b>9.4</b> References</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html"><i class="fa fa-check"></i><b>10</b> Week 09: Confirmatory Factor Analysis</a>
<ul>
<li class="chapter" data-level="10.1" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#preparatory-steps-3"><i class="fa fa-check"></i><b>10.1</b> Preparatory steps</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#describing-the-data"><i class="fa fa-check"></i><b>10.1.1</b> Describing the data</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#fitting-a-cfa-model"><i class="fa fa-check"></i><b>10.2</b> Fitting a CFA model</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#making-sure-the-model-was-correctly-estimated"><i class="fa fa-check"></i><b>10.2.1</b> Making sure the model was correctly estimated</a></li>
<li class="chapter" data-level="10.2.2" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#evaluating-the-model-fit"><i class="fa fa-check"></i><b>10.2.2</b> Evaluating the model fit</a></li>
<li class="chapter" data-level="10.2.3" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#interpretting-the-parameter-estimates"><i class="fa fa-check"></i><b>10.2.3</b> Interpretting the parameter estimates</a></li>
<li class="chapter" data-level="10.2.4" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#further-inspecting-our-model"><i class="fa fa-check"></i><b>10.2.4</b> Further inspecting our model</a></li>
<li class="chapter" data-level="10.2.5" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#further-inspecting-our-models-parameters"><i class="fa fa-check"></i><b>10.2.5</b> Further inspecting our model’s parameters</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#using-alternative-model-specifications"><i class="fa fa-check"></i><b>10.3</b> Using alternative model specifications</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#rescaling-the-factors-to-be-standardized"><i class="fa fa-check"></i><b>10.3.1</b> Rescaling the factors to be standardized</a></li>
<li class="chapter" data-level="10.3.2" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#specifying-a-competing-nested-model"><i class="fa fa-check"></i><b>10.3.2</b> Specifying a competing, nested, model</a></li>
<li class="chapter" data-level="10.3.3" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#conducting-model-comparisons"><i class="fa fa-check"></i><b>10.3.3</b> Conducting model comparisons</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#estimating-factor-scores"><i class="fa fa-check"></i><b>10.4</b> Estimating factor scores</a></li>
<li class="chapter" data-level="10.5" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#cfa-with-categorical-data"><i class="fa fa-check"></i><b>10.5</b> CFA with categorical data</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#using-data-from-an-r-package"><i class="fa fa-check"></i><b>10.5.1</b> Using data from an R package</a></li>
<li class="chapter" data-level="10.5.2" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#preparing-the-data"><i class="fa fa-check"></i><b>10.5.2</b> Preparing the data</a></li>
<li class="chapter" data-level="10.5.3" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#describing-the-data-1"><i class="fa fa-check"></i><b>10.5.3</b> Describing the data</a></li>
<li class="chapter" data-level="10.5.4" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#fitting-the-cfa-model"><i class="fa fa-check"></i><b>10.5.4</b> Fitting the CFA model</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#way-tldr-summary"><i class="fa fa-check"></i><b>10.6</b> Way TL;DR Summary</a></li>
<li class="chapter" data-level="10.7" data-path="week-09-confirmatory-factor-analysis.html"><a href="week-09-confirmatory-factor-analysis.html#references-3"><i class="fa fa-check"></i><b>10.7</b> References</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">EDUC 644 Applied Multivariate Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-03-statistical-assumptions-of-manova" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Week 03 Statistical Assumptions of MANOVA<a href="week-03-statistical-assumptions-of-manova.html#week-03-statistical-assumptions-of-manova" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>After assuming that the dependent variables are continuous, there are three statistical assumptions, which Pituch &amp; Stevens presented. Here, we address the assumptions of multivariate normality and homogeneity of covariance matrices among groups.</p>
<div id="data" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Data<a href="week-03-statistical-assumptions-of-manova.html#data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This is the data set discussed in Pituch and Stevens’ chapter for this week’s reading. According to them, “Our example comes from a study on the cost of transporting milk from farms to dairy plants” (Pituch &amp; Stevens, 2016, p. 230). Their groups (the <code>gp</code> variable) are two types of trucks: Gasoline and diesel fueled. The dependent variables are <code>y1</code> for fuel costs; <code>y2</code> for repairs costs, and <code>y3</code> for capital costs.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="week-03-statistical-assumptions-of-manova.html#cb73-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb73-2"><a href="week-03-statistical-assumptions-of-manova.html#cb73-2" tabindex="-1"></a><span class="fu">library</span>(haven) <span class="co"># To read SPSS data files</span></span>
<span id="cb73-3"><a href="week-03-statistical-assumptions-of-manova.html#cb73-3" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">&quot;MILK.sav&quot;</span>)</span>
<span id="cb73-4"><a href="week-03-statistical-assumptions-of-manova.html#cb73-4" tabindex="-1"></a><span class="co"># Changing the names of the variables to lowercase:</span></span>
<span id="cb73-5"><a href="week-03-statistical-assumptions-of-manova.html#cb73-5" tabindex="-1"></a><span class="fu">names</span>(dat) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(dat))</span>
<span id="cb73-6"><a href="week-03-statistical-assumptions-of-manova.html#cb73-6" tabindex="-1"></a>dat<span class="sc">$</span>gp <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">as_factor</span>(dat<span class="sc">$</span>gp)</span>
<span id="cb73-7"><a href="week-03-statistical-assumptions-of-manova.html#cb73-7" tabindex="-1"></a><span class="co"># Let&#39;s add an id variable so we can identify cases.</span></span>
<span id="cb73-8"><a href="week-03-statistical-assumptions-of-manova.html#cb73-8" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(dat), </span>
<span id="cb73-9"><a href="week-03-statistical-assumptions-of-manova.html#cb73-9" tabindex="-1"></a>                  dat)</span>
<span id="cb73-10"><a href="week-03-statistical-assumptions-of-manova.html#cb73-10" tabindex="-1"></a><span class="fu">glimpse</span>(dat) <span class="co"># or use str(dat)</span></span></code></pre></div>
<pre><code>## Rows: 59
## Columns: 5
## $ id &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25…
## $ gp &lt;fct&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
## $ y1 &lt;dbl&gt; 16.44, 7.19, 9.92, 4.24, 11.20, 14.25, 13.50, 13.32, 29.11, 12.68, 7.51, 9.90, 10.25, 11.…
## $ y2 &lt;dbl&gt; 12.43, 2.70, 1.35, 5.78, 5.05, 5.78, 10.98, 14.27, 15.09, 7.61, 5.80, 3.63, 5.07, 6.15, 1…
## $ y3 &lt;dbl&gt; 11.23, 3.92, 9.75, 7.78, 10.67, 9.88, 10.60, 9.45, 3.28, 10.23, 8.13, 9.13, 10.17, 7.61, …</code></pre>
<p>Here are the general steps in a MANOVA:</p>
<ol style="list-style-type: decimal">
<li>Examine descriptive statistics and plots.</li>
<li>Address the statistical assumptions. We will focus on multivariate normality and homogeneity of the covariance matrices among groups.</li>
<li>Specify any planned comparisons and set the contrasts. Our data set has only two groups, so we won’t need this in this exampe.</li>
<li>Fit the MANOVA model and test the omnibus null hypothesis.</li>
<li>If the omnibus test is rejected, examine either (a) univariate ANOVAs or (b) discriminant function analysis. We’ll use univariate ANOVAs, but many scholars suggest doing a discriminant function analysis, which will be a topic in a future session for us.</li>
</ol>
</div>
<div id="descriptive-statistics" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Descriptive statistics<a href="week-03-statistical-assumptions-of-manova.html#descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We should examine if there is a relationship among the dependent variables. If there is zero, or very low, correlation among them, we should forget MANOVA and simply use ANOVA on each. If the correlations are too high, we risk multicollinearity and, in turn, problems in inverting the matrix when we conduct the multivariate test; Tabachnick and Fidell (2013) suggest correlations over .90 should be flagged.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="week-03-statistical-assumptions-of-manova.html#cb75-1" tabindex="-1"></a>ycors <span class="ot">&lt;-</span> <span class="fu">cor</span>(dat[ , <span class="fu">c</span>(<span class="st">&quot;y1&quot;</span>, <span class="st">&quot;y2&quot;</span>, <span class="st">&quot;y3&quot;</span>)]) </span>
<span id="cb75-2"><a href="week-03-statistical-assumptions-of-manova.html#cb75-2" tabindex="-1"></a><span class="fu">round</span>(ycors, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##       y1   y2    y3
## y1  1.00 0.33 -0.06
## y2  0.33 1.00  0.36
## y3 -0.06 0.36  1.00</code></pre>
<p>We see moderate correlations among two pairs but effectively no relationship between <code>y1</code> and <code>y3</code> (fuel costs and capital costs seem to be unrelated). These data are okay for a MANOVA.</p>
<p>Similarly, we can examine plots among the three variables in case there is a non-linear relationship or there are outliers affecting the relationships. Here, we’re combining them into a single plot, but plot could be viewed independently if we don’t want to use the gridExtra package.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="week-03-statistical-assumptions-of-manova.html#cb77-1" tabindex="-1"></a>py1 <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> y1, <span class="at">y =</span> y2)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span>
<span id="cb77-2"><a href="week-03-statistical-assumptions-of-manova.html#cb77-2" tabindex="-1"></a>py2 <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> y1, <span class="at">y =</span> y3)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span>
<span id="cb77-3"><a href="week-03-statistical-assumptions-of-manova.html#cb77-3" tabindex="-1"></a>py3 <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> y2, <span class="at">y =</span> y3)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span>
<span id="cb77-4"><a href="week-03-statistical-assumptions-of-manova.html#cb77-4" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb77-5"><a href="week-03-statistical-assumptions-of-manova.html#cb77-5" tabindex="-1"></a><span class="fu">grid.arrange</span>(py1, py2, py3, <span class="at">ncol=</span><span class="dv">2</span>, </span>
<span id="cb77-6"><a href="week-03-statistical-assumptions-of-manova.html#cb77-6" tabindex="-1"></a>             <span class="at">top =</span> <span class="st">&quot;Dependent variables&quot;</span>)</span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-58-1.png" width="672" />
It seems like the correlation between <code>y1</code> and <code>y2</code> might be affected by two outliers. Still, there are no obvious non-linear relationships.</p>
<p>In future analyses, such as in factor analysis, we’ll also look at the <strong>assumption of linearity</strong> among the dependent variables. These bivariate plots provide some evidence of this assumption. We could also look at three-dimensional plots (which I don’t know how to do in R) to see the relationships among all three variables—in that case, we might see an American football shape representing some relationship among three variables. With four variables, my brain is unable to imagine such a plot but that’s what the assumption of linearity with multivariate data would entail.</p>
<div id="by-group-descriptive-statistics" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> By-group descriptive statistics<a href="week-03-statistical-assumptions-of-manova.html#by-group-descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can examine descriptive statistics by group. We did this in our previous class with the psych package’s <code>describeBy()</code> function.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="week-03-statistical-assumptions-of-manova.html#cb78-1" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb78-2"><a href="week-03-statistical-assumptions-of-manova.html#cb78-2" tabindex="-1"></a><span class="fu">describeBy</span>(dat<span class="sc">$</span>y1, <span class="at">group =</span> dat<span class="sc">$</span>gp, <span class="at">data =</span> dat) <span class="co"># Fuel costs</span></span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: 1
##    vars  n  mean  sd median trimmed  mad  min   max range skew kurtosis  se
## X1    1 36 12.22 4.8  11.15   11.61 3.22 4.24 29.11 24.87 1.71     3.68 0.8
## ---------------------------------------------------------------------------- 
## group: 2
##    vars  n  mean   sd median trimmed  mad  min  max range skew kurtosis   se
## X1    1 23 10.11 2.09   9.77   10.01 1.88 6.47 15.9  9.43 0.61     0.55 0.44</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="week-03-statistical-assumptions-of-manova.html#cb80-1" tabindex="-1"></a><span class="fu">describeBy</span>(dat<span class="sc">$</span>y2, <span class="at">group =</span> dat<span class="sc">$</span>gp, <span class="at">data =</span> dat) <span class="co"># Repair costs</span></span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: 1
##    vars  n mean   sd median trimmed  mad  min   max range skew kurtosis  se
## X1    1 36 8.11 4.19   7.67    7.97 4.66 1.35 17.44 16.09 0.33    -0.95 0.7
## ---------------------------------------------------------------------------- 
## group: 2
##    vars  n  mean   sd median trimmed mad  min   max range skew kurtosis   se
## X1    1 23 10.76 5.08  11.75   10.63 4.4 2.94 21.52 18.58 0.16    -0.94 1.06</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="week-03-statistical-assumptions-of-manova.html#cb82-1" tabindex="-1"></a><span class="fu">describeBy</span>(dat<span class="sc">$</span>y3, <span class="at">group =</span> dat<span class="sc">$</span>gp, <span class="at">data =</span> dat) <span class="co"># Capital costs</span></span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: 1
##    vars  n mean   sd median trimmed  mad  min   max range skew kurtosis   se
## X1    1 36 9.59 3.74   9.62    9.41 3.68 3.28 17.59 14.31 0.33    -0.61 0.62
## ---------------------------------------------------------------------------- 
## group: 2
##    vars  n  mean   sd median trimmed  mad  min   max range skew kurtosis   se
## X1    1 23 18.17 6.83  17.45   17.81 5.56 5.99 35.18 29.19 0.52    -0.02 1.42</code></pre>
<p>We see that the gasoline and diesel trucks (the two groups) differ in each of these three costs, especially in the third dependent variable. Our MANOVA will test whether the two types of trucks statistically-significantly differ in total costs while accounting for the relationships among these costs. We might ask why go to the trouble when we could simply calculate a composite total cost for each truck as the sum of the three variables. Taking the sum is one kind of linear combination of variables. MANOVA finds the optimal linear combination by re-combining the variance, which is the topic of discriminant analysis and principal components analysis. For now, let’s get back to the topic of statistical assumptions.</p>
</div>
</div>
<div id="normality-assumption" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Normality Assumption<a href="week-03-statistical-assumptions-of-manova.html#normality-assumption" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="univariate-normality" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Univariate Normality<a href="week-03-statistical-assumptions-of-manova.html#univariate-normality" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Univariate normality is a necessary but insufficient for multivariate normality. We can explore normality of each dependent variable in each group.<a href="#fn18" class="footnote-ref" id="fnref18"><sup>18</sup></a> First, we could look for univariate outliers, per the example in the reading. After that, let’s examine the kurtosis and skew estimates and plots.</p>
<p>At this point, we’re following Pituch and Stevens’ (and Tabachnick &amp; Fidell’s) approach to analyze assumptions of the <strong>observed dependent-variable data</strong>. The code and interpretations can also be used with the <strong>residual scores</strong> corresponding with each dependent variable, which is addressed later on in this code. I’d actually recommend simply skipping to doing these steps with the residual data, but I’ll follow Pituch and Stevens’ approach first. The primary reason scholars suggest using the observed data is to avoid temptation of looking at the model results, such as with <code>summary(my.fitted.model)</code>, which in R we can avoid by simply not asking for the results even though we have fit the model.</p>
<div id="identifying-univariate-outliers-within-groups" class="section level4 hasAnchor" number="4.3.1.1">
<h4><span class="header-section-number">4.3.1.1</span> Identifying univariate outliers within groups<a href="week-03-statistical-assumptions-of-manova.html#identifying-univariate-outliers-within-groups" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Pituch and Stevens suggested examining <em>z</em>-scores of each variable within each group to identify any plausible outliers. They suggested a <em>z</em>-score greater than 2.5 in magnitude would merit scrutiny, which is approximately equal to a two-tailed test at alpha = .01. This advice is different from that of Tabachnick and Fidell (2013), who suggest a criterion of 3.29, corresponding with an alpha = .001, but also qualify this by saying that we might change this threshold depending on the sample size, as a large sample will more likely yield outliers.<a href="#fn19" class="footnote-ref" id="fnref19"><sup>19</sup></a></p>
<p>To get standardized scores, we can use the <code>scale()</code> function for each variable separately.<a href="#fn20" class="footnote-ref" id="fnref20"><sup>20</sup></a> In the code below, we use the dplyr package to calculate the <em>z</em>-scores and create a dummy variable that indicates which are outliers based on the criterion Pituch and Stevens suggested.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="week-03-statistical-assumptions-of-manova.html#cb84-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb84-2"><a href="week-03-statistical-assumptions-of-manova.html#cb84-2" tabindex="-1"></a>datz <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> </span>
<span id="cb84-3"><a href="week-03-statistical-assumptions-of-manova.html#cb84-3" tabindex="-1"></a>  <span class="fu">group_by</span>(gp) <span class="sc">%&gt;%</span> </span>
<span id="cb84-4"><a href="week-03-statistical-assumptions-of-manova.html#cb84-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">y1.z =</span> <span class="fu">scale</span>(y1),</span>
<span id="cb84-5"><a href="week-03-statistical-assumptions-of-manova.html#cb84-5" tabindex="-1"></a>         <span class="at">y2.z =</span> <span class="fu">scale</span>(y2),</span>
<span id="cb84-6"><a href="week-03-statistical-assumptions-of-manova.html#cb84-6" tabindex="-1"></a>         <span class="at">y3.z =</span> <span class="fu">scale</span>(y3),</span>
<span id="cb84-7"><a href="week-03-statistical-assumptions-of-manova.html#cb84-7" tabindex="-1"></a>         <span class="at">outlier_uni =</span> <span class="fu">if_else</span>(<span class="fu">abs</span>(y1.z) <span class="sc">&gt;</span> <span class="fl">2.5</span> <span class="sc">|</span></span>
<span id="cb84-8"><a href="week-03-statistical-assumptions-of-manova.html#cb84-8" tabindex="-1"></a>                               <span class="fu">abs</span>(y2.z) <span class="sc">&gt;</span> <span class="fl">2.5</span> <span class="sc">|</span></span>
<span id="cb84-9"><a href="week-03-statistical-assumptions-of-manova.html#cb84-9" tabindex="-1"></a>                               <span class="fu">abs</span>(y3.z) <span class="sc">&gt;</span> <span class="fl">2.5</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb84-10"><a href="week-03-statistical-assumptions-of-manova.html#cb84-10" tabindex="-1"></a>datz <span class="sc">%&gt;%</span> <span class="fu">filter</span>(outlier_uni <span class="sc">==</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 9
## # Groups:   gp [2]
##      id gp       y1    y2    y3 y1.z[,1] y2.z[,1] y3.z[,1] outlier_uni
##   &lt;int&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;
## 1     9 1      29.1  15.1  3.28     3.52    1.67    -1.69            1
## 2    21 1      26.2  17.4 16.9      2.91    2.23     1.95            1
## 3    52 2      15.9  12.9 19.1      2.77    0.421    0.135           1</code></pre>
<p>We see three cases we could flag as outliers, all on <code>y1</code>. Two of these cases (Cases 9 &amp; 21) are in Group 1; one (Case 52) was in Group 2. These <em>z</em>-scores are not terribly excessive—only Case 9 exceeds the criterion of 3.29. We could examine these data to see if there was a data-entry error. Let’s assume it was not and carry on by seeing if these same cases show up in our examination of multivariate normality.</p>
</div>
<div id="kurtosis-and-skew" class="section level4 hasAnchor" number="4.3.1.2">
<h4><span class="header-section-number">4.3.1.2</span> Kurtosis and skew<a href="week-03-statistical-assumptions-of-manova.html#kurtosis-and-skew" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We used the psych package above when we used the <code>describeBy()</code> function. We could simply interpret those and use the absolute value of 2 as the criterion. Looking at that, we see that on <code>y1</code>, Group 1 has a kurtosis exceeding the magnitude of 2.00. It is positive, indicating leptokurtosis (too much pointiness), which becomes less problematic with samples greater than 100 or so; a platykurtic skew, which has thick tails, underestimates the sample’s variance until about a sample size of 200 (Tabachnick &amp; Fidell, 2013, p. 80, cite Waternaux, 1976). Based on the univariate kurtosis and skew estimates of <code>y2</code> and <code>y3</code>, we do not see evidence that these two variables differ from normality within each group.</p>
<p>We could also use confidence intervals to determine if the kurtosis and skew are outside of an expected range that might constitute normality. The DescTools package can provide these confidence intervals; they suggest using the bootstrap estimator, <code>bca</code> for the confidence intervals. Here’s an example of skew with the first dependent variable only:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="week-03-statistical-assumptions-of-manova.html#cb86-1" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb86-2"><a href="week-03-statistical-assumptions-of-manova.html#cb86-2" tabindex="-1"></a><span class="fu">tapply</span>(dat<span class="sc">$</span>y1,</span>
<span id="cb86-3"><a href="week-03-statistical-assumptions-of-manova.html#cb86-3" tabindex="-1"></a>       dat<span class="sc">$</span>gp,</span>
<span id="cb86-4"><a href="week-03-statistical-assumptions-of-manova.html#cb86-4" tabindex="-1"></a>       DescTools<span class="sc">::</span>Kurt, </span>
<span id="cb86-5"><a href="week-03-statistical-assumptions-of-manova.html#cb86-5" tabindex="-1"></a>       <span class="at">method =</span> <span class="dv">3</span> , <span class="co"># Use method 2 if you want the same result as SPSS </span></span>
<span id="cb86-6"><a href="week-03-statistical-assumptions-of-manova.html#cb86-6" tabindex="-1"></a>       <span class="at">conf.level =</span> .<span class="dv">95</span>,</span>
<span id="cb86-7"><a href="week-03-statistical-assumptions-of-manova.html#cb86-7" tabindex="-1"></a>       <span class="at">ci.type =</span> <span class="st">&quot;bca&quot;</span>)</span></code></pre></div>
<pre><code>## $`1`
##       kurt     lwr.ci     upr.ci 
##  3.6784860  0.5597267 11.2928002 
## 
## $`2`
##       kurt     lwr.ci     upr.ci 
##  0.5480051 -0.7509224  4.0266324</code></pre>
<p>The 3.68 kurtosis for Group 1 on this variable is within their confidence interval, suggesting it might not be enough to flag non-normality.</p>
</div>
<div id="examining-univariate-normality-using-density-plots" class="section level4 hasAnchor" number="4.3.1.3">
<h4><span class="header-section-number">4.3.1.3</span> Examining univariate normality using density plots<a href="week-03-statistical-assumptions-of-manova.html#examining-univariate-normality-using-density-plots" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can examine plots of each variable, by group. First, let’s examine density plots of each variable, within each group, and compare that to the theoretical normal distribution. For this, the easiest way seems to be with the ggpubr package, which has the <code>ggdensity()</code> function instead of the <code>ggplot()</code> function we usually use.<a href="#fn21" class="footnote-ref" id="fnref21"><sup>21</sup></a></p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="week-03-statistical-assumptions-of-manova.html#cb88-1" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb88-2"><a href="week-03-statistical-assumptions-of-manova.html#cb88-2" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb88-3"><a href="week-03-statistical-assumptions-of-manova.html#cb88-3" tabindex="-1"></a>  <span class="fu">filter</span>(gp <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span>       <span class="co"># subset to Group 1, using dplyr.</span></span>
<span id="cb88-4"><a href="week-03-statistical-assumptions-of-manova.html#cb88-4" tabindex="-1"></a><span class="fu">ggdensity</span>(<span class="at">x =</span> <span class="st">&quot;y1&quot;</span>,         <span class="co"># specify which variable.</span></span>
<span id="cb88-5"><a href="week-03-statistical-assumptions-of-manova.html#cb88-5" tabindex="-1"></a>          <span class="at">fill =</span> <span class="st">&quot;gray50&quot;</span>,  <span class="co"># observed density is colored gray.</span></span>
<span id="cb88-6"><a href="week-03-statistical-assumptions-of-manova.html#cb88-6" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,  <span class="co"># remove line from observed density plot</span></span>
<span id="cb88-7"><a href="week-03-statistical-assumptions-of-manova.html#cb88-7" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Gasoline trucks&quot;</span>) <span class="sc">+</span> </span>
<span id="cb88-8"><a href="week-03-statistical-assumptions-of-manova.html#cb88-8" tabindex="-1"></a>  <span class="co"># I know `gp == 1` matches gasoline trucks, so I use `title = `.</span></span>
<span id="cb88-9"><a href="week-03-statistical-assumptions-of-manova.html#cb88-9" tabindex="-1"></a>  <span class="co"># And, here&#39;s the theoretical normal density line, layered on top:</span></span>
<span id="cb88-10"><a href="week-03-statistical-assumptions-of-manova.html#cb88-10" tabindex="-1"></a>  <span class="fu">stat_overlay_normal_density</span>(<span class="at">color =</span> <span class="st">&quot;darkred&quot;</span>)</span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<p>We can see that compared to a theoretical normal distribution, the distribution of <code>y1</code> with the Gasoline-truck group is leptokurtic (too peaked) and positively skewed. This is consistent with the skew and kurtosis reported in the <code>describeBy()</code> function earlier, 1.71 and 3.68 respectively. The two outliers seem to be responsible for this bump on the right side.</p>
<p>We can do this for every group and every variable. Here’s the diesel group with <code>y1</code>.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="week-03-statistical-assumptions-of-manova.html#cb89-1" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb89-2"><a href="week-03-statistical-assumptions-of-manova.html#cb89-2" tabindex="-1"></a>  <span class="fu">filter</span>(gp <span class="sc">==</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span>       </span>
<span id="cb89-3"><a href="week-03-statistical-assumptions-of-manova.html#cb89-3" tabindex="-1"></a><span class="fu">ggdensity</span>(<span class="at">x =</span> <span class="st">&quot;y1&quot;</span>,         </span>
<span id="cb89-4"><a href="week-03-statistical-assumptions-of-manova.html#cb89-4" tabindex="-1"></a>          <span class="at">fill =</span> <span class="st">&quot;gray50&quot;</span>,  </span>
<span id="cb89-5"><a href="week-03-statistical-assumptions-of-manova.html#cb89-5" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,  </span>
<span id="cb89-6"><a href="week-03-statistical-assumptions-of-manova.html#cb89-6" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">&quot;Diesel trucks&quot;</span>,</span>
<span id="cb89-7"><a href="week-03-statistical-assumptions-of-manova.html#cb89-7" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;Fuel costs&quot;</span>) <span class="sc">+</span> </span>
<span id="cb89-8"><a href="week-03-statistical-assumptions-of-manova.html#cb89-8" tabindex="-1"></a>  <span class="fu">stat_overlay_normal_density</span>(<span class="at">color =</span> <span class="st">&quot;darkred&quot;</span>)</span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-63-1.png" width="672" />
The second group’s scores on this variable seem to come from a population with a normal distribution.<a href="#fn22" class="footnote-ref" id="fnref22"><sup>22</sup></a> We see a little bump on the right hand side, probably caused by that outlier we found with the <em>z</em>-scores.</p>
<p>We can also display both groups in a plot as separate panels (or facets). Here, we’re adding the <code>facet.by =</code> argument from this function (which is specific to this function, in looking at <code>?ggdensity</code>), with the group variable in our data, <code>gp</code>, plot the two groups next to each other in their respective panel of the plot. Then, we’re making the label of the panel more informative with <code>panel.labs = list(gp = c("Gasoline", "Diesel"))</code>, where the <code>gp</code> here is, again, the name of the group variable in our data set.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="week-03-statistical-assumptions-of-manova.html#cb90-1" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb90-2"><a href="week-03-statistical-assumptions-of-manova.html#cb90-2" tabindex="-1"></a><span class="fu">ggdensity</span>(<span class="at">x =</span> <span class="st">&quot;y1&quot;</span>,</span>
<span id="cb90-3"><a href="week-03-statistical-assumptions-of-manova.html#cb90-3" tabindex="-1"></a>          <span class="at">fill =</span> <span class="st">&quot;gray50&quot;</span>,</span>
<span id="cb90-4"><a href="week-03-statistical-assumptions-of-manova.html#cb90-4" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,  </span>
<span id="cb90-5"><a href="week-03-statistical-assumptions-of-manova.html#cb90-5" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;Fuel costs&quot;</span>,</span>
<span id="cb90-6"><a href="week-03-statistical-assumptions-of-manova.html#cb90-6" tabindex="-1"></a>          <span class="at">facet.by =</span> <span class="st">&quot;gp&quot;</span>, </span>
<span id="cb90-7"><a href="week-03-statistical-assumptions-of-manova.html#cb90-7" tabindex="-1"></a>          <span class="at">panel.labs =</span> <span class="fu">list</span>(<span class="at">gp =</span> <span class="fu">c</span>(<span class="st">&quot;Gasoline&quot;</span>, <span class="st">&quot;Diesel&quot;</span>)) ) <span class="sc">+</span> </span>
<span id="cb90-8"><a href="week-03-statistical-assumptions-of-manova.html#cb90-8" tabindex="-1"></a>  <span class="fu">stat_overlay_normal_density</span>(<span class="at">color =</span> <span class="st">&quot;darkred&quot;</span>)</span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
<p>The one problem with this layout is that the y-axis is on the same scale for both variables, which seems to stretch the y-axis scale so it appears as though the second group is excessively leptokurtic. However, by comparing this to the superimposed normal curve, we see it is not too peaked.</p>
<p>Let’s look at the other two variables:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="week-03-statistical-assumptions-of-manova.html#cb91-1" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb91-2"><a href="week-03-statistical-assumptions-of-manova.html#cb91-2" tabindex="-1"></a><span class="fu">ggdensity</span>(<span class="at">x =</span> <span class="st">&quot;y2&quot;</span>,</span>
<span id="cb91-3"><a href="week-03-statistical-assumptions-of-manova.html#cb91-3" tabindex="-1"></a>          <span class="at">fill =</span> <span class="st">&quot;gray50&quot;</span>,</span>
<span id="cb91-4"><a href="week-03-statistical-assumptions-of-manova.html#cb91-4" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,  </span>
<span id="cb91-5"><a href="week-03-statistical-assumptions-of-manova.html#cb91-5" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;Repair costs&quot;</span>,</span>
<span id="cb91-6"><a href="week-03-statistical-assumptions-of-manova.html#cb91-6" tabindex="-1"></a>          <span class="at">facet.by =</span> <span class="st">&quot;gp&quot;</span>, </span>
<span id="cb91-7"><a href="week-03-statistical-assumptions-of-manova.html#cb91-7" tabindex="-1"></a>          <span class="at">panel.labs =</span> <span class="fu">list</span>(<span class="at">gp =</span> <span class="fu">c</span>(<span class="st">&quot;Gasoline&quot;</span>, <span class="st">&quot;Diesel&quot;</span>)) ) <span class="sc">+</span> </span>
<span id="cb91-8"><a href="week-03-statistical-assumptions-of-manova.html#cb91-8" tabindex="-1"></a>  <span class="fu">stat_overlay_normal_density</span>(<span class="at">color =</span> <span class="st">&quot;darkred&quot;</span>)</span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
<p>Although the observed density plots look truncated, with some fat tails, we do see support for the conclusion that the sample data are drawn from a population of normally distributed data.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="week-03-statistical-assumptions-of-manova.html#cb92-1" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb92-2"><a href="week-03-statistical-assumptions-of-manova.html#cb92-2" tabindex="-1"></a><span class="fu">ggdensity</span>(<span class="at">x =</span> <span class="st">&quot;y3&quot;</span>,</span>
<span id="cb92-3"><a href="week-03-statistical-assumptions-of-manova.html#cb92-3" tabindex="-1"></a>          <span class="at">fill =</span> <span class="st">&quot;gray50&quot;</span>,</span>
<span id="cb92-4"><a href="week-03-statistical-assumptions-of-manova.html#cb92-4" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,  </span>
<span id="cb92-5"><a href="week-03-statistical-assumptions-of-manova.html#cb92-5" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">&quot;Capital costs&quot;</span>,</span>
<span id="cb92-6"><a href="week-03-statistical-assumptions-of-manova.html#cb92-6" tabindex="-1"></a>          <span class="at">facet.by =</span> <span class="st">&quot;gp&quot;</span>, </span>
<span id="cb92-7"><a href="week-03-statistical-assumptions-of-manova.html#cb92-7" tabindex="-1"></a>          <span class="at">panel.labs =</span> <span class="fu">list</span>(<span class="at">gp =</span> <span class="fu">c</span>(<span class="st">&quot;Gasoline&quot;</span>, <span class="st">&quot;Diesel&quot;</span>)) ) <span class="sc">+</span> </span>
<span id="cb92-8"><a href="week-03-statistical-assumptions-of-manova.html#cb92-8" tabindex="-1"></a>  <span class="fu">stat_overlay_normal_density</span>(<span class="at">color =</span> <span class="st">&quot;darkred&quot;</span>)</span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<p>These plots also suggest the sample data seem to come from a population of normally distributed data.</p>
</div>
</div>
<div id="examining-univariate-normality-using-quantile-quantile-plots" class="section level3 hasAnchor" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Examining univariate normality using quantile-quantile plots<a href="week-03-statistical-assumptions-of-manova.html#examining-univariate-normality-using-quantile-quantile-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Quantile-quantile plots are probably the most useful for examining normality. They’re a little less work than the density plots, too. If you want a refresher on what quantiles are and how Q-Q plots are generated, Josh Starmer has a couple of videos: one on quantiles, <a href="https://www.youtube.com/watch?v=IFKQLDmRK0Y">linked to here</a>, and one on Q-Q plots, <a href="https://www.youtube.com/watch?v=okjYjClSjOg">linked to here</a>.</p>
<p>Here’s a plot of the first group with the first variable:</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="week-03-statistical-assumptions-of-manova.html#cb93-1" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb93-2"><a href="week-03-statistical-assumptions-of-manova.html#cb93-2" tabindex="-1"></a>  <span class="fu">filter</span>(gp <span class="sc">==</span> <span class="st">&quot;1&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb93-3"><a href="week-03-statistical-assumptions-of-manova.html#cb93-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> y1)) <span class="sc">+</span></span>
<span id="cb93-4"><a href="week-03-statistical-assumptions-of-manova.html#cb93-4" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb93-5"><a href="week-03-statistical-assumptions-of-manova.html#cb93-5" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb93-6"><a href="week-03-statistical-assumptions-of-manova.html#cb93-6" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="st">&quot;Norm quantiles&quot;</span>) <span class="sc">+</span></span>
<span id="cb93-7"><a href="week-03-statistical-assumptions-of-manova.html#cb93-7" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="st">&quot;Sample quantiles&quot;</span>) <span class="sc">+</span> </span>
<span id="cb93-8"><a href="week-03-statistical-assumptions-of-manova.html#cb93-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Gasoline trucks&quot;</span>)</span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-67-1.png" width="672" /></p>
<p>We see the effect of those two outliers on the plot in Group 1 (gasoline trucks). Their scores are much higher than we would expect if the data were from a normal distribution. Without them, it would look normal.</p>
<p>Here’s the second group:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="week-03-statistical-assumptions-of-manova.html#cb94-1" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb94-2"><a href="week-03-statistical-assumptions-of-manova.html#cb94-2" tabindex="-1"></a>  <span class="fu">filter</span>(gp <span class="sc">==</span> <span class="st">&quot;2&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb94-3"><a href="week-03-statistical-assumptions-of-manova.html#cb94-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> y1)) <span class="sc">+</span></span>
<span id="cb94-4"><a href="week-03-statistical-assumptions-of-manova.html#cb94-4" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb94-5"><a href="week-03-statistical-assumptions-of-manova.html#cb94-5" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb94-6"><a href="week-03-statistical-assumptions-of-manova.html#cb94-6" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="st">&quot;Norm quantiles&quot;</span>) <span class="sc">+</span></span>
<span id="cb94-7"><a href="week-03-statistical-assumptions-of-manova.html#cb94-7" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="st">&quot;Sample quantiles&quot;</span>) <span class="sc">+</span> </span>
<span id="cb94-8"><a href="week-03-statistical-assumptions-of-manova.html#cb94-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Diesel trucks&quot;</span>)</span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p>In Group 2, <code>y1</code> looks normal enough, with most of the scores very close to the line, though there is one observation with a score that is unexpectedly high.</p>
<p>We could use ggplot for the other four plots. Let’s look at a function from the car package that also provides some error bands:</p>
<div id="univariate-q-q-plots-from-other-packages" class="section level4 hasAnchor" number="4.3.2.1">
<h4><span class="header-section-number">4.3.2.1</span> Univariate Q-Q plots from other packages<a href="week-03-statistical-assumptions-of-manova.html#univariate-q-q-plots-from-other-packages" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The car package’s <code>qqPlot()</code> is convenient in that it includes an error band for interpreting points that are off the line, and it labels outliers. This approach requires the input be a matrix or vector (not a data frame, as ggplot requires). For this, we need to change our group variable to be numeric and create a matrix with group and our dependent variables:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="week-03-statistical-assumptions-of-manova.html#cb95-1" tabindex="-1"></a>ym <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="at">gp =</span> <span class="fu">as.numeric</span>(dat<span class="sc">$</span>gp), dat[, <span class="dv">3</span><span class="sc">:</span><span class="dv">5</span>])</span>
<span id="cb95-2"><a href="week-03-statistical-assumptions-of-manova.html#cb95-2" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb95-3"><a href="week-03-statistical-assumptions-of-manova.html#cb95-3" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">qqPlot</span>(ym[,<span class="dv">2</span>], <span class="at">ylab =</span> <span class="st">&quot;Y1&quot;</span>, <span class="at">groups =</span> ym[,<span class="dv">1</span>])</span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="week-03-statistical-assumptions-of-manova.html#cb96-1" tabindex="-1"></a><span class="co"># For the other two variables:</span></span>
<span id="cb96-2"><a href="week-03-statistical-assumptions-of-manova.html#cb96-2" tabindex="-1"></a><span class="co"># car::qqPlot(ym[,3], ylab = &quot;Y2&quot;, groups = ym[,1])</span></span>
<span id="cb96-3"><a href="week-03-statistical-assumptions-of-manova.html#cb96-3" tabindex="-1"></a><span class="co"># car::qqPlot(ym[,4], ylab = &quot;Y3&quot;, groups = ym[,1])</span></span></code></pre></div>
<p>This also labels the row number of the observations that might be flagged as outliers. We see results that are consistent with the above plots. This was only with the first dependent variable; we’d use the same code with the other two.</p>
<p>Another package we could use is ggpubr, with the <code>ggqqplot()</code> function. We used this package with our density plots. This is convenient because we don’t have to change the data into matrix format:</p>
<p>Here’s are all the plots with this package:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="week-03-statistical-assumptions-of-manova.html#cb97-1" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb97-2"><a href="week-03-statistical-assumptions-of-manova.html#cb97-2" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb97-3"><a href="week-03-statistical-assumptions-of-manova.html#cb97-3" tabindex="-1"></a>  <span class="fu">filter</span>(gp <span class="sc">==</span> <span class="st">&quot;1&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb97-4"><a href="week-03-statistical-assumptions-of-manova.html#cb97-4" tabindex="-1"></a>  <span class="fu">ggqqplot</span>(<span class="at">x =</span> <span class="st">&quot;y1&quot;</span>,</span>
<span id="cb97-5"><a href="week-03-statistical-assumptions-of-manova.html#cb97-5" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">&quot;Gasoline trucks&#39; fuel costs&quot;</span>) </span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="week-03-statistical-assumptions-of-manova.html#cb98-1" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb98-2"><a href="week-03-statistical-assumptions-of-manova.html#cb98-2" tabindex="-1"></a>  <span class="fu">filter</span>(gp <span class="sc">==</span> <span class="st">&quot;2&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb98-3"><a href="week-03-statistical-assumptions-of-manova.html#cb98-3" tabindex="-1"></a>  <span class="fu">ggqqplot</span>(<span class="at">x =</span> <span class="st">&quot;y1&quot;</span>,</span>
<span id="cb98-4"><a href="week-03-statistical-assumptions-of-manova.html#cb98-4" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">&quot;Diesel trucks&#39; fuel costs&quot;</span>) </span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-70-2.png" width="672" /></p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="week-03-statistical-assumptions-of-manova.html#cb99-1" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb99-2"><a href="week-03-statistical-assumptions-of-manova.html#cb99-2" tabindex="-1"></a>  <span class="fu">filter</span>(gp <span class="sc">==</span> <span class="st">&quot;1&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb99-3"><a href="week-03-statistical-assumptions-of-manova.html#cb99-3" tabindex="-1"></a>  <span class="fu">ggqqplot</span>(<span class="at">x =</span> <span class="st">&quot;y2&quot;</span>,</span>
<span id="cb99-4"><a href="week-03-statistical-assumptions-of-manova.html#cb99-4" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">&quot;Gasoline trucks&#39; repair costs&quot;</span>) </span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-70-3.png" width="672" /></p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="week-03-statistical-assumptions-of-manova.html#cb100-1" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb100-2"><a href="week-03-statistical-assumptions-of-manova.html#cb100-2" tabindex="-1"></a>  <span class="fu">filter</span>(gp <span class="sc">==</span> <span class="st">&quot;2&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb100-3"><a href="week-03-statistical-assumptions-of-manova.html#cb100-3" tabindex="-1"></a>  <span class="fu">ggqqplot</span>(<span class="at">x =</span> <span class="st">&quot;y2&quot;</span>,</span>
<span id="cb100-4"><a href="week-03-statistical-assumptions-of-manova.html#cb100-4" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">&quot;Diesel trucks&#39; repair costs&quot;</span>) </span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-70-4.png" width="672" /></p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="week-03-statistical-assumptions-of-manova.html#cb101-1" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb101-2"><a href="week-03-statistical-assumptions-of-manova.html#cb101-2" tabindex="-1"></a>  <span class="fu">filter</span>(gp <span class="sc">==</span> <span class="st">&quot;1&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb101-3"><a href="week-03-statistical-assumptions-of-manova.html#cb101-3" tabindex="-1"></a>  <span class="fu">ggqqplot</span>(<span class="at">x =</span> <span class="st">&quot;y3&quot;</span>,</span>
<span id="cb101-4"><a href="week-03-statistical-assumptions-of-manova.html#cb101-4" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">&quot;Gasoline trucks&#39; capital costs&quot;</span>) </span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-70-5.png" width="672" /></p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="week-03-statistical-assumptions-of-manova.html#cb102-1" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb102-2"><a href="week-03-statistical-assumptions-of-manova.html#cb102-2" tabindex="-1"></a>  <span class="fu">filter</span>(gp <span class="sc">==</span> <span class="st">&quot;2&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb102-3"><a href="week-03-statistical-assumptions-of-manova.html#cb102-3" tabindex="-1"></a>  <span class="fu">ggqqplot</span>(<span class="at">x =</span> <span class="st">&quot;y3&quot;</span>,</span>
<span id="cb102-4"><a href="week-03-statistical-assumptions-of-manova.html#cb102-4" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">&quot;Diesel trucks&#39; capital costs&quot;</span>) </span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-70-6.png" width="672" /></p>
<p>This one does <em>not</em> label the outliers, which is why I like the car package’s version better.</p>
<p>If I were in a hurry and I needed to assess univariate normality, I’d simply look at the Q-Q plots from the car package. If I wanted to publish something pretty, I’d use ggplot or ggpubr’s ggqqplot, and I’d display the density plots with the normal distribution layered over them for comparison.</p>
</div>
<div id="statistical-tests-of-univariate-normality" class="section level4 hasAnchor" number="4.3.2.2">
<h4><span class="header-section-number">4.3.2.2</span> Statistical tests of univariate normality<a href="week-03-statistical-assumptions-of-manova.html#statistical-tests-of-univariate-normality" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>There are also statistical tests of normality. The Shapiro–Wilk test seems to be well regarded. To demonstrate, let’s examine <code>y1</code> with Group 1:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="week-03-statistical-assumptions-of-manova.html#cb103-1" tabindex="-1"></a>g1 <span class="ot">&lt;-</span> <span class="fu">subset</span>(dat, gp <span class="sc">==</span> <span class="dv">1</span>, <span class="at">select =</span> <span class="fu">c</span>(<span class="st">&quot;y1&quot;</span>, <span class="st">&quot;y2&quot;</span>, <span class="st">&quot;y3&quot;</span>))</span>
<span id="cb103-2"><a href="week-03-statistical-assumptions-of-manova.html#cb103-2" tabindex="-1"></a><span class="fu">shapiro.test</span>(g1<span class="sc">$</span>y1)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  g1$y1
## W = 0.83672, p-value = 9.555e-05</code></pre>
<p>The <em>p</em>-value below our critical alpha of .05 indicates that for Group 1, we can reject the null hypothesis that <code>y1</code> is from a normal distribution. We don’t like this result.</p>
<p>Let’s look at Group 2 on this same variable:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="week-03-statistical-assumptions-of-manova.html#cb105-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(g1<span class="sc">$</span>y2)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  g1$y2
## W = 0.96282, p-value = 0.2623</code></pre>
<p>The same test with Group 2 did not reject the null hypothesis, which indicates we do not have evidence to suggest <code>y1</code> differs from normality. We would do this test by-group for the other two variables and hope we got non-significance.<a href="#fn23" class="footnote-ref" id="fnref23"><sup>23</sup></a></p>
</div>
</div>
<div id="a-caution-about-statistical-tests-of-statistical-assumptions" class="section level3 hasAnchor" number="4.3.3">
<h3><span class="header-section-number">4.3.3</span> A caution about statistical tests of statistical assumptions<a href="week-03-statistical-assumptions-of-manova.html#a-caution-about-statistical-tests-of-statistical-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As with most (or all) statistical tests of statistical assumptions, we are arguing for the null hypothesis, which is kind of antithetical to null-hypothesis statistical testing but that’s how it seems to be done.</p>
<p>With small sample sizes, statistical tests like Shapiro-Wilk show non-significance even when the data are not normal. With large sample sizes, they’re too sensitive to deviations from normality. With this, statistical tests of normality should not be the primary source of evidence for evaluating this assumption.</p>
</div>
<div id="mahalanobis-distance-and-multivariate-outliers" class="section level3 hasAnchor" number="4.3.4">
<h3><span class="header-section-number">4.3.4</span> Mahalanobis Distance and Multivariate Outliers<a href="week-03-statistical-assumptions-of-manova.html#mahalanobis-distance-and-multivariate-outliers" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can calculate each observation’s Mahalanobis distance. I think of this as the observation’s degree of weirdness compared to the rest of the data. This is a function of leverage, which was addressed in multiple regression.</p>
<!-- $$\text{Mahalanobis distance} = (N - 1)(h_{ii} - 1/N)$$ -->
<!-- where $h_{ii}$ (or "RHAT") is the leverage.  -->
<p>Mahalanobis distances are in squared units, so we use a chi-square distribution instead of a normal distribution with quantiles in our Q-Q plots. The <code>mahalanobis()</code> function from Base R has three arguments: the matrix of multivariate variables, the means of those those variables (in <code>center=</code>), and the covariance matrix of those variables.<a href="#fn24" class="footnote-ref" id="fnref24"><sup>24</sup></a> We’ll create a matrix of our dependent variables for the first argument and use the <code>colMeans()</code> and <code>cov()</code> functions to get the latter two.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="week-03-statistical-assumptions-of-manova.html#cb107-1" tabindex="-1"></a>dvs <span class="ot">&lt;-</span> <span class="fu">cbind</span>(dat[,<span class="fu">c</span>(<span class="st">&quot;y1&quot;</span>,<span class="st">&quot;y2&quot;</span>,<span class="st">&quot;y3&quot;</span>)])</span>
<span id="cb107-2"><a href="week-03-statistical-assumptions-of-manova.html#cb107-2" tabindex="-1"></a>distances <span class="ot">&lt;-</span> <span class="fu">mahalanobis</span>(dvs, </span>
<span id="cb107-3"><a href="week-03-statistical-assumptions-of-manova.html#cb107-3" tabindex="-1"></a>                         <span class="at">center =</span> <span class="fu">colMeans</span>(dvs), </span>
<span id="cb107-4"><a href="week-03-statistical-assumptions-of-manova.html#cb107-4" tabindex="-1"></a>                         <span class="at">cov =</span> <span class="fu">cov</span>(dvs))</span></code></pre></div>
<p>Each observation has a multivariate distance, so let’s save it to the data frame:</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="week-03-statistical-assumptions-of-manova.html#cb108-1" tabindex="-1"></a>dat<span class="sc">$</span>distancesraw <span class="ot">&lt;-</span> distances</span></code></pre></div>
<p>We might notice that for some observations, they have really high Mahalanobis distance values. We could sort them from high to low to see if there is a quick descent before it then levels out:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="week-03-statistical-assumptions-of-manova.html#cb109-1" tabindex="-1"></a><span class="fu">sort</span>(dat<span class="sc">$</span>distancesraw, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>] <span class="co"># first 20 observations</span></span></code></pre></div>
<pre><code>##  [1] 20.369430 13.881471 12.473991 11.967188  9.750828  5.731465  5.132105  4.292636  3.937175
## [10]  3.885500  3.418971  3.413827  2.976672  2.950409  2.940999  2.823275  2.647751  2.496250
## [19]  2.491660  2.472095</code></pre>
<div id="outliers" class="section level4 hasAnchor" number="4.3.4.1">
<h4><span class="header-section-number">4.3.4.1</span> Outliers<a href="week-03-statistical-assumptions-of-manova.html#outliers" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>There is a standard way to see if they are outliers. We calculate the <em>p</em>-value of that Mahalanobis distance, from a chi-square distribution with <span class="math inline">\(p-1\)</span> degrees of freedom (where <em>p</em> = number of dependent variables), and use <span class="math inline">\(p &lt; .001\)</span> as a criterion for identifying an outlier.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="week-03-statistical-assumptions-of-manova.html#cb111-1" tabindex="-1"></a>dat<span class="sc">$</span>p <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(distances, </span>
<span id="cb111-2"><a href="week-03-statistical-assumptions-of-manova.html#cb111-2" tabindex="-1"></a>                <span class="at">df =</span> (<span class="fu">ncol</span>(dvs)<span class="sc">-</span><span class="dv">1</span>), <span class="co"># df is number of variables - 1</span></span>
<span id="cb111-3"><a href="week-03-statistical-assumptions-of-manova.html#cb111-3" tabindex="-1"></a>                <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<p>Let’s flag any cases with a <em>p</em>-value lower than our alpha = .001 criterion. In this code, we’re using <code>ifelse()</code> to dummy code any cases with criterion as <code>1</code> and <code>0</code> otherwise. Then, we’re requesting rows of the data that have a value of <code>1</code> on this new variable.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="week-03-statistical-assumptions-of-manova.html#cb112-1" tabindex="-1"></a>dat<span class="sc">$</span>outlier <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(dat<span class="sc">$</span>p <span class="sc">&lt;</span> .<span class="dv">001</span>, </span>
<span id="cb112-2"><a href="week-03-statistical-assumptions-of-manova.html#cb112-2" tabindex="-1"></a>                      <span class="dv">1</span>, <span class="co"># the case gets a 1 if p &lt; .001</span></span>
<span id="cb112-3"><a href="week-03-statistical-assumptions-of-manova.html#cb112-3" tabindex="-1"></a>                      <span class="dv">0</span>) <span class="co"># otherwise, the value on this new variable is 0</span></span>
<span id="cb112-4"><a href="week-03-statistical-assumptions-of-manova.html#cb112-4" tabindex="-1"></a><span class="co"># We can see two outliers here:</span></span>
<span id="cb112-5"><a href="week-03-statistical-assumptions-of-manova.html#cb112-5" tabindex="-1"></a>dat[dat<span class="sc">$</span>outlier <span class="sc">==</span> <span class="dv">1</span>, ]</span></code></pre></div>
<pre><code>##    id gp    y1    y2    y3 distancesraw            p outlier
## 9   9  1 29.11 15.09  3.28     20.36943 3.774282e-05       1
## 21 21  1 26.16 17.44 16.89     13.88147 9.675577e-04       1</code></pre>
<p>Not surprisingly, these are the two pains in the neck in our univariate analysis. Out liars, out!</p>
<p>The Mahalanobis distances are in squared units. The car package has a function we can use for this to generate a kind of Q-Q plot. Instead of a normal distribution of quantiles on the X axis, we can specify a chi-squared distribution. Everitt and Hothorn (2011) use similar procedures to obtain the same type of plot.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="week-03-statistical-assumptions-of-manova.html#cb114-1" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb114-2"><a href="week-03-statistical-assumptions-of-manova.html#cb114-2" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">qqPlot</span>(distances, </span>
<span id="cb114-3"><a href="week-03-statistical-assumptions-of-manova.html#cb114-3" tabindex="-1"></a>            <span class="at">distribution =</span> <span class="st">&quot;chisq&quot;</span>, <span class="at">df =</span> <span class="fu">mean</span>(distances), </span>
<span id="cb114-4"><a href="week-03-statistical-assumptions-of-manova.html#cb114-4" tabindex="-1"></a>            <span class="at">lwd =</span> <span class="dv">1</span>, </span>
<span id="cb114-5"><a href="week-03-statistical-assumptions-of-manova.html#cb114-5" tabindex="-1"></a>            <span class="at">grid =</span> <span class="cn">FALSE</span>, </span>
<span id="cb114-6"><a href="week-03-statistical-assumptions-of-manova.html#cb114-6" tabindex="-1"></a>            <span class="at">main =</span> <span class="st">&quot;Multi-normal Q-Q Plot on Raw Data&quot;</span>, </span>
<span id="cb114-7"><a href="week-03-statistical-assumptions-of-manova.html#cb114-7" tabindex="-1"></a>            <span class="at">xlab =</span> <span class="fu">expression</span>(chi<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="st">&quot; quantiles&quot;</span>), </span>
<span id="cb114-8"><a href="week-03-statistical-assumptions-of-manova.html#cb114-8" tabindex="-1"></a>            <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="st">&quot;Mahalanobis distances &quot;</span><span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-78-1.png" width="672" /></p>
<pre><code>## [1]  9 21</code></pre>
</div>
<div id="mahalanobis-distance-using-residuals" class="section level4 hasAnchor" number="4.3.4.2">
<h4><span class="header-section-number">4.3.4.2</span> Mahalanobis Distance using Residuals<a href="week-03-statistical-assumptions-of-manova.html#mahalanobis-distance-using-residuals" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Many scholars point out that the normality assumption is really about the residuals of the model. Let’s fit our MANOVA model <strong>without examining the results</strong> and save the residuals to the data frame, then conduct this same approach we did above with Mahalanobis distance:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="week-03-statistical-assumptions-of-manova.html#cb116-1" tabindex="-1"></a>dvs     <span class="ot">&lt;-</span> <span class="fu">cbind</span>(dat<span class="sc">$</span>y1, dat<span class="sc">$</span>y2, dat<span class="sc">$</span>y3)</span>
<span id="cb116-2"><a href="week-03-statistical-assumptions-of-manova.html#cb116-2" tabindex="-1"></a>man.mod <span class="ot">&lt;-</span> <span class="fu">manova</span>(dvs <span class="sc">~</span> gp, <span class="at">data =</span> dat)</span>
<span id="cb116-3"><a href="week-03-statistical-assumptions-of-manova.html#cb116-3" tabindex="-1"></a>dat[, <span class="fu">c</span>(<span class="st">&quot;res1&quot;</span>, <span class="st">&quot;res2&quot;</span>, <span class="st">&quot;res3&quot;</span>)] <span class="ot">&lt;-</span> man.mod<span class="sc">$</span>residuals</span>
<span id="cb116-4"><a href="week-03-statistical-assumptions-of-manova.html#cb116-4" tabindex="-1"></a>resids <span class="ot">&lt;-</span> <span class="fu">cbind</span>(dat[,<span class="fu">c</span>(<span class="st">&quot;res1&quot;</span>, <span class="st">&quot;res2&quot;</span>, <span class="st">&quot;res3&quot;</span>)])</span>
<span id="cb116-5"><a href="week-03-statistical-assumptions-of-manova.html#cb116-5" tabindex="-1"></a>distances <span class="ot">&lt;-</span> <span class="fu">mahalanobis</span>(resids, </span>
<span id="cb116-6"><a href="week-03-statistical-assumptions-of-manova.html#cb116-6" tabindex="-1"></a>                         <span class="at">center =</span> <span class="fu">colMeans</span>(resids), </span>
<span id="cb116-7"><a href="week-03-statistical-assumptions-of-manova.html#cb116-7" tabindex="-1"></a>                         <span class="at">cov =</span> <span class="fu">cov</span>(resids))</span>
<span id="cb116-8"><a href="week-03-statistical-assumptions-of-manova.html#cb116-8" tabindex="-1"></a>dat<span class="sc">$</span>distances <span class="ot">&lt;-</span> distances</span>
<span id="cb116-9"><a href="week-03-statistical-assumptions-of-manova.html#cb116-9" tabindex="-1"></a>dat<span class="sc">$</span>p <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(distances, </span>
<span id="cb116-10"><a href="week-03-statistical-assumptions-of-manova.html#cb116-10" tabindex="-1"></a>                <span class="at">df =</span> (<span class="fu">ncol</span>(resids)<span class="sc">-</span><span class="dv">1</span>), <span class="co"># df is number of variables - 1</span></span>
<span id="cb116-11"><a href="week-03-statistical-assumptions-of-manova.html#cb116-11" tabindex="-1"></a>                <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span>
<span id="cb116-12"><a href="week-03-statistical-assumptions-of-manova.html#cb116-12" tabindex="-1"></a></span>
<span id="cb116-13"><a href="week-03-statistical-assumptions-of-manova.html#cb116-13" tabindex="-1"></a>dat<span class="sc">$</span>outlier <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(dat<span class="sc">$</span>p <span class="sc">&lt;</span> .<span class="dv">001</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb116-14"><a href="week-03-statistical-assumptions-of-manova.html#cb116-14" tabindex="-1"></a>dat[dat<span class="sc">$</span>outlier <span class="sc">==</span> <span class="dv">1</span>, ]</span></code></pre></div>
<pre><code>##   id gp    y1    y2   y3 distancesraw            p outlier     res1   res2      res3 distances
## 9  9  1 29.11 15.09 3.28     20.36943 1.989997e-05       1 16.89139 6.9775 -6.310278  21.64958</code></pre>
<p>Now, we see that Case 9 is the only outlier. Let’s look at the multivariate analogue to the univariate Q-Q plot, now with residuals:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="week-03-statistical-assumptions-of-manova.html#cb118-1" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb118-2"><a href="week-03-statistical-assumptions-of-manova.html#cb118-2" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">qqPlot</span>(distances, </span>
<span id="cb118-3"><a href="week-03-statistical-assumptions-of-manova.html#cb118-3" tabindex="-1"></a>            <span class="at">distribution =</span> <span class="st">&quot;chisq&quot;</span>, <span class="at">df =</span> <span class="fu">mean</span>(distances), </span>
<span id="cb118-4"><a href="week-03-statistical-assumptions-of-manova.html#cb118-4" tabindex="-1"></a>            <span class="at">lwd =</span> <span class="dv">1</span>, </span>
<span id="cb118-5"><a href="week-03-statistical-assumptions-of-manova.html#cb118-5" tabindex="-1"></a>            <span class="at">grid =</span> <span class="cn">FALSE</span>, </span>
<span id="cb118-6"><a href="week-03-statistical-assumptions-of-manova.html#cb118-6" tabindex="-1"></a>            <span class="at">main =</span> <span class="st">&quot;Multi-normal Q-Q Plot on Residuals&quot;</span>, </span>
<span id="cb118-7"><a href="week-03-statistical-assumptions-of-manova.html#cb118-7" tabindex="-1"></a>            <span class="at">xlab =</span> <span class="fu">expression</span>(chi<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="st">&quot; quantiles&quot;</span>), </span>
<span id="cb118-8"><a href="week-03-statistical-assumptions-of-manova.html#cb118-8" tabindex="-1"></a>            <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="st">&quot;Mahalanobis distances &quot;</span><span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-80-1.png" width="672" /></p>
<pre><code>## [1]  9 21</code></pre>
<p>We see a very similar shape to what we saw with the raw data. It looks like we will not be able to claim we have met the assumption of normality. However, we should really be examining multidimensional normality <strong>within each group</strong>, not the entire data set. Let’s do that:</p>
<!-- #### Using ggplot -->
<!-- We could do something similar with GGplot. This is as far as I got: -->
<!-- ```{r} -->
<!-- library(ggplot2) -->
<!-- qq_all <- dat %>%   -->
<!--   ggplot(aes(sample = distances)) + -->
<!--   # the distribution is not in quantiles but in chi-square distribution -->
<!--   # the df of the chisq dist is the mean(distances): -->
<!--   geom_qq(distribution = qchisq, dparams = mean(distances) ) + -->
<!--   stat_qq_line(distribution = qchisq, dparams = mean(distances) ) + -->
<!--   scale_x_continuous(name = expression(chi^2 * " quantiles") ) +  -->
<!--   scale_y_continuous(name = expression("Mahalanobis distances "^2))  -->
<!-- qq_all -->
<!-- ``` -->
</div>
<div id="multivariate-residual-q-q-plot-by-group" class="section level4 hasAnchor" number="4.3.4.3">
<h4><span class="header-section-number">4.3.4.3</span> Multivariate residual Q-Q plot by group<a href="week-03-statistical-assumptions-of-manova.html#multivariate-residual-q-q-plot-by-group" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>With the residuals, we can use the <code>groups =</code> argument to specify the group. This requires that the matrix have a column that is the group variable.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="week-03-statistical-assumptions-of-manova.html#cb120-1" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb120-2"><a href="week-03-statistical-assumptions-of-manova.html#cb120-2" tabindex="-1"></a>distances_gp <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="at">gp =</span> <span class="fu">as.numeric</span>(dat<span class="sc">$</span>gp), distances)</span>
<span id="cb120-3"><a href="week-03-statistical-assumptions-of-manova.html#cb120-3" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">qqPlot</span>(distances_gp[, <span class="sc">-</span><span class="dv">1</span>], </span>
<span id="cb120-4"><a href="week-03-statistical-assumptions-of-manova.html#cb120-4" tabindex="-1"></a>            <span class="at">distribution =</span> <span class="st">&quot;chisq&quot;</span>, <span class="at">df =</span> <span class="fu">mean</span>(distances_gp[, <span class="sc">-</span><span class="dv">1</span>]), </span>
<span id="cb120-5"><a href="week-03-statistical-assumptions-of-manova.html#cb120-5" tabindex="-1"></a>            <span class="at">groups =</span> distances_gp[,<span class="st">&quot;gp&quot;</span>],</span>
<span id="cb120-6"><a href="week-03-statistical-assumptions-of-manova.html#cb120-6" tabindex="-1"></a>            <span class="at">lwd =</span> <span class="dv">1</span>, </span>
<span id="cb120-7"><a href="week-03-statistical-assumptions-of-manova.html#cb120-7" tabindex="-1"></a>            <span class="at">grid =</span> <span class="cn">FALSE</span>, </span>
<span id="cb120-8"><a href="week-03-statistical-assumptions-of-manova.html#cb120-8" tabindex="-1"></a>            <span class="at">main =</span> <span class="st">&quot;Multi-normal Q-Q Plot on Residuals&quot;</span>, </span>
<span id="cb120-9"><a href="week-03-statistical-assumptions-of-manova.html#cb120-9" tabindex="-1"></a>            <span class="at">xlab =</span> <span class="fu">expression</span>(chi<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="st">&quot; quantiles&quot;</span>), </span>
<span id="cb120-10"><a href="week-03-statistical-assumptions-of-manova.html#cb120-10" tabindex="-1"></a>            <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="st">&quot;Mahalanobis distances &quot;</span><span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div>
<p><img src="multivariate_stats_files/figure-html/unnamed-chunk-81-1.png" width="672" /></p>
<p>Clearly, Case 9 is a candidate for removal and seeing if the results will lead to the same statistical conclusion if the case were retained.</p>
</div>
</div>
<div id="statistical-tests-of-multivariate-normality" class="section level3 hasAnchor" number="4.3.5">
<h3><span class="header-section-number">4.3.5</span> Statistical Tests of Multivariate Normality<a href="week-03-statistical-assumptions-of-manova.html#statistical-tests-of-multivariate-normality" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Just as there are statistical tests of univariate normality, there are of multivariate normality. And, just as was the case with their univariate counterparts, the statistical test is sensitive to sample size, just as any test is. With this, if we have a large sample size, we will likely have a statistical significance when the divergence from normality is only negligible. In other words, this source of evidence should be used in conjunction with plots.</p>
<p>Here is the <code>mshapiro.test()</code> function from the mvnormtest package. This function requires the data be arranged as rows instead of columns, so we’ll use the transpose function, <code>t()</code> within the test.
First, let’s separate the dependent variables by group. Here, we’re using their respective residuals, but many authors simply use the dependent variables on the grounds that researchers would be tempted to analyze the results of their fitted model (which is needed to get the residuals) before analyzing the assumptions.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="week-03-statistical-assumptions-of-manova.html#cb121-1" tabindex="-1"></a>dvs.gp1     <span class="ot">&lt;-</span> <span class="fu">subset</span>(dat, gp <span class="sc">==</span> <span class="dv">1</span>, <span class="at">select =</span> <span class="fu">c</span>(<span class="st">&quot;res1&quot;</span>, <span class="st">&quot;res2&quot;</span>, <span class="st">&quot;res3&quot;</span>))</span>
<span id="cb121-2"><a href="week-03-statistical-assumptions-of-manova.html#cb121-2" tabindex="-1"></a>dvs.gp2     <span class="ot">&lt;-</span> <span class="fu">subset</span>(dat, gp <span class="sc">==</span> <span class="dv">2</span>, <span class="at">select =</span> <span class="fu">c</span>(<span class="st">&quot;res1&quot;</span>, <span class="st">&quot;res2&quot;</span>, <span class="st">&quot;res3&quot;</span>))</span>
<span id="cb121-3"><a href="week-03-statistical-assumptions-of-manova.html#cb121-3" tabindex="-1"></a></span>
<span id="cb121-4"><a href="week-03-statistical-assumptions-of-manova.html#cb121-4" tabindex="-1"></a><span class="fu">library</span>(mvnormtest)</span>
<span id="cb121-5"><a href="week-03-statistical-assumptions-of-manova.html#cb121-5" tabindex="-1"></a><span class="fu">mshapiro.test</span>( <span class="fu">t</span>(dvs.gp1) )</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  Z
## W = 0.81141, p-value = 2.767e-05</code></pre>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="week-03-statistical-assumptions-of-manova.html#cb123-1" tabindex="-1"></a><span class="fu">mshapiro.test</span>( <span class="fu">t</span>(dvs.gp2) )</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  Z
## W = 0.94576, p-value = 0.2384</code></pre>
<p>We see results that are consistent with our outliers and plots. The multivariate normality assumption was not met because Group 1 had a multivariate distribution that was significantly different from normal.</p>
</div>
<div id="homogeneity-of-covariance" class="section level3 hasAnchor" number="4.3.6">
<h3><span class="header-section-number">4.3.6</span> Homogeneity of Covariance<a href="week-03-statistical-assumptions-of-manova.html#homogeneity-of-covariance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Box’s M test can be conducted using the <code>box_m()</code> function from the rstatix package, the <code>boxM()</code> function from the biotools package, or the <code>boxM()</code> function from the heplots package. Let’s arbitrarily use the latter:</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="week-03-statistical-assumptions-of-manova.html#cb125-1" tabindex="-1"></a><span class="fu">library</span>(heplots)</span>
<span id="cb125-2"><a href="week-03-statistical-assumptions-of-manova.html#cb125-2" tabindex="-1"></a><span class="fu">boxM</span>(dat[ , <span class="fu">c</span>(<span class="st">&quot;y1&quot;</span>, <span class="st">&quot;y2&quot;</span>, <span class="st">&quot;y3&quot;</span>)], dat[ , <span class="st">&quot;gp&quot;</span>])</span></code></pre></div>
<pre><code>## 
##  Box&#39;s M-test for Homogeneity of Covariance Matrices
## 
## data:  dat[, c(&quot;y1&quot;, &quot;y2&quot;, &quot;y3&quot;)]
## Chi-Sq (approx.) = 30.543, df = 6, p-value = 3.098e-05</code></pre>
<p>This assumption was not met. If we had a balanced design, this might not be an issue. Tabachick and Fidell state that Box’s M test tends to be too sensitive, but in this case, the violation seems to be undeniable.</p>
<p>One thing we could do is examine the covariance matrices for each group, and see whether the smaller group has the larger variance-covariance, which in turn would lead to overly lenient estimations of statistical significance and inflated Type I errors.</p>
<p>Here are the <em>n</em>-sizes:</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="week-03-statistical-assumptions-of-manova.html#cb127-1" tabindex="-1"></a><span class="fu">table</span>(dat<span class="sc">$</span>gp)</span></code></pre></div>
<pre><code>## 
##  1  2 
## 36 23</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="week-03-statistical-assumptions-of-manova.html#cb129-1" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">table</span>(dat<span class="sc">$</span>gp)) <span class="sc">/</span> <span class="fu">min</span>(<span class="fu">table</span>(dat<span class="sc">$</span>gp))</span></code></pre></div>
<pre><code>## [1] 1.565217</code></pre>
<p>Group 1 (<em>n</em> = 36) is over 1.5 times larger than Group 2 (or, Group 2 is about two-thirds as big as Group 1). If we see that Group 2 has larger values in the covariance matrix, our MANOVA test statistics will err on the side of leniency, risking Type I error rate inflation. On the other hand, if Group 1 has larger covariance, we err on the side of conservation, risking loss of statistical power. For credibility in our statistical conclusions, the latter scenario is preferable. Note that if we had equal group sizes, MANOVA is pretty “robust” in its statistical tests; here, we don’t.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="week-03-statistical-assumptions-of-manova.html#cb131-1" tabindex="-1"></a>dat1 <span class="ot">&lt;-</span> <span class="fu">subset</span>(dat, gp <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb131-2"><a href="week-03-statistical-assumptions-of-manova.html#cb131-2" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> <span class="fu">subset</span>(dat, gp <span class="sc">==</span> <span class="dv">2</span>)</span>
<span id="cb131-3"><a href="week-03-statistical-assumptions-of-manova.html#cb131-3" tabindex="-1"></a>covm1 <span class="ot">&lt;-</span> <span class="fu">cov</span>(dat1[, <span class="fu">c</span>(<span class="st">&quot;res1&quot;</span>, <span class="st">&quot;res2&quot;</span>, <span class="st">&quot;res3&quot;</span>)])</span>
<span id="cb131-4"><a href="week-03-statistical-assumptions-of-manova.html#cb131-4" tabindex="-1"></a>covm2 <span class="ot">&lt;-</span> <span class="fu">cov</span>(dat2[, <span class="fu">c</span>(<span class="st">&quot;res1&quot;</span>, <span class="st">&quot;res2&quot;</span>, <span class="st">&quot;res3&quot;</span>)])</span>
<span id="cb131-5"><a href="week-03-statistical-assumptions-of-manova.html#cb131-5" tabindex="-1"></a><span class="fu">round</span>(covm1, <span class="dv">1</span>)</span></code></pre></div>
<pre><code>##      res1 res2 res3
## res1 23.0 12.4  2.9
## res2 12.4 17.5  4.8
## res3  2.9  4.8 14.0</code></pre>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="week-03-statistical-assumptions-of-manova.html#cb133-1" tabindex="-1"></a><span class="fu">round</span>(covm2, <span class="dv">1</span>)</span></code></pre></div>
<pre><code>##      res1 res2 res3
## res1  4.4  0.8  2.4
## res2  0.8 25.9  7.7
## res3  2.4  7.7 46.7</code></pre>
<p>The pattern is not consistent in terms of which group has larger variances or covariances. With <code>y1</code>, Group 1 has larger variance (23.0 vs 4.4); with <code>y2</code>, there might be similar variances in the two groups (17.5 and 25.9); with <code>y3</code>, there is lower variance in Group 1 (14.0 vs 46.7). And, we haven’t even compared the covariances, which also seem to differ. What do we do?</p>
<p>Boiling each of these covariance matrices down to a single number will be helpful in identifying which group has higher variance, which in turn is important for determining if our violation of this assumption will result in a more conservative or more liberal statistical conclusion. Pituch and Stevens used SPSS, which included the determinant of the covariance matrix for each group in its output. Our Box test output did not provide this, but we can use the determinants of the by-group residual covariance matrices to accomplish the same thing:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="week-03-statistical-assumptions-of-manova.html#cb135-1" tabindex="-1"></a><span class="fu">det</span>(covm1)</span></code></pre></div>
<pre><code>## [1] 3172.914</code></pre>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="week-03-statistical-assumptions-of-manova.html#cb137-1" tabindex="-1"></a><span class="fu">det</span>(covm2)</span></code></pre></div>
<pre><code>## [1] 4860.31</code></pre>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="week-03-statistical-assumptions-of-manova.html#cb139-1" tabindex="-1"></a><span class="fu">det</span>(covm2) <span class="sc">/</span> <span class="fu">det</span>(covm1)</span></code></pre></div>
<pre><code>## [1] 1.531813</code></pre>
<p>The generalized variance of the smaller group is 1.5 times that of the larger group. This suggests that the test will be biased to show an effect when there might not be one—that is, increasing Type I error. This is bad news because if we find statistical significance, we won’t know if it is because of population differences or because of this bias.</p>
<!-- ## Homogeneity of variance -->
<!-- We can examine univariate homogeneity of variance for each variable, to identify if a particular variable's variance is the culprit. We can use the `leveneTest()` in the car package: -->
<!-- ```{r} -->
<!-- library(car) -->
<!-- a1 <- aov(y1 ~ gp, data = dat) -->
<!-- a2 <- aov(y2 ~ gp, data = dat) -->
<!-- a3 <- aov(y3 ~ gp, data = dat) -->
<!-- car::leveneTest(a1) # if add `, center = mean`, will get same as Ch. 6 results. -->
<!-- car::leveneTest(a2) -->
<!-- car::leveneTest(a3) -->
<!-- ``` -->
<!-- We see that with the first and third variables the data do not meet this assumption.  -->
</div>
<div id="conclusions-about-our-statistical-assumptions" class="section level3 hasAnchor" number="4.3.7">
<h3><span class="header-section-number">4.3.7</span> Conclusions about our statistical assumptions<a href="week-03-statistical-assumptions-of-manova.html#conclusions-about-our-statistical-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The statistical assumptions of multivariate normality and homogeneity of covariance were not met with this data set. Pituch and Stevens recommend transforming the data, as would Tabachnick and Fidell. Other scholars (such Curran and Hancock in their podcast, <a href="https://quantitudepod.org/s2e17-embracing-your-non-normality/">linked to here</a>) do not recommend data transformations but instead recommend robust standard errors be used. We’ll take the robust approach in this example.</p>
</div>
</div>
<div id="fitting-the-manova-model" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Fitting the MANOVA Model<a href="week-03-statistical-assumptions-of-manova.html#fitting-the-manova-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>If we had met the assumptions, we’d use the following code.</strong> This is for demonstration only.</p>
<p>The multivariate omnibus null hypothesis is
<span class="math display">\[H_0 = \begin{bmatrix} \mu_{11} \\ \mu_{21} \\ \mu_{31} \ \end{bmatrix}
= \begin{bmatrix} \mu_{12} \\ \mu_{22} \\ \mu_{32} \ \end{bmatrix} \]</span></p>
<p>In other words, with <span class="math inline">\(\mu_{11}\)</span> and <span class="math inline">\(\mu_{12}\)</span>, the population mean of Group 1 on <code>y1</code> is equal to the population mean of Group 2 on <code>y1</code>; with with <span class="math inline">\(\mu_{21}\)</span> and <span class="math inline">\(\mu_{22}\)</span>, the population mean of Group 1 on <code>y2</code> is equal to the population mean of Group 2 on <code>y2</code>; and so forth for <code>y3</code>.</p>
<p>We use the <code>manova()</code> function to fit the model. This requires the dependent variables be in a matrix, which below we accomplish with the <code>cbind()</code> function. We then examine the results with the <code>summary()</code> function (use <code>?summary.manova</code> to look at the help file for these options). We’ll use <code>test = "Pillai"</code>, which is the default because among the four main possible tests to choose from, Pillai’s trace is more suitable for data with unequal covariances.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="week-03-statistical-assumptions-of-manova.html#cb141-1" tabindex="-1"></a>dvs     <span class="ot">&lt;-</span> <span class="fu">cbind</span>(dat<span class="sc">$</span>y1, dat<span class="sc">$</span>y2, dat<span class="sc">$</span>y3)</span>
<span id="cb141-2"><a href="week-03-statistical-assumptions-of-manova.html#cb141-2" tabindex="-1"></a>man.mod <span class="ot">&lt;-</span> <span class="fu">manova</span>(dvs <span class="sc">~</span> gp, <span class="at">data =</span> dat)</span>
<span id="cb141-3"><a href="week-03-statistical-assumptions-of-manova.html#cb141-3" tabindex="-1"></a><span class="fu">summary.manova</span>(man.mod, <span class="at">test =</span> <span class="st">&quot;Pillai&quot;</span>)</span></code></pre></div>
<pre><code>##           Df  Pillai approx F num Df den Df    Pr(&gt;F)    
## gp         1 0.47179   16.375      3     55 1.001e-07 ***
## Residuals 57                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The other tests are Wilks’ lambda, Hotelling’s trace, and Roy’s largest root. Wilks’ lambda is by far the most frequently used test. Wilks’ lambda is calculated as the ratio of the generalized variance of the within to the total generalized variance,
<span class="math display">\[ \text{Wilks&#39; } \Lambda = \frac{|\mathbf{W}|}{|\mathbf{B} + \mathbf{W}|}\]</span>
<!-- Pillai's trace is a generalization of the ANOVA _F_-test and is  -->
<!-- $$ \text{Pillai's trace} = \mathbf{B}(\mathbf{B + W})^{-1} $$ --></p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="week-03-statistical-assumptions-of-manova.html#cb143-1" tabindex="-1"></a><span class="fu">summary.manova</span>(man.mod, <span class="at">test =</span> <span class="st">&quot;Wilks&quot;</span>)</span></code></pre></div>
<pre><code>##           Df   Wilks approx F num Df den Df    Pr(&gt;F)    
## gp         1 0.52821   16.375      3     55 1.001e-07 ***
## Residuals 57                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In this data set, we have only two groups, so the <em>p</em>-values and approximated <em>F</em>-tests are the same across the four types of tests.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="week-03-statistical-assumptions-of-manova.html#cb145-1" tabindex="-1"></a><span class="fu">summary.manova</span>(man.mod, <span class="at">test =</span> <span class="st">&quot;Hotelling-Lawley&quot;</span>)</span></code></pre></div>
<pre><code>##           Df Hotelling-Lawley approx F num Df den Df    Pr(&gt;F)    
## gp         1          0.89319   16.375      3     55 1.001e-07 ***
## Residuals 57                                                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="week-03-statistical-assumptions-of-manova.html#cb147-1" tabindex="-1"></a><span class="fu">summary.manova</span>(man.mod, <span class="at">test =</span> <span class="st">&quot;Roy&quot;</span>)</span></code></pre></div>
<pre><code>##           Df     Roy approx F num Df den Df    Pr(&gt;F)    
## gp         1 0.89319   16.375      3     55 1.001e-07 ***
## Residuals 57                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We can pull out information from the output. For example, here are the SSCP matrices:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="week-03-statistical-assumptions-of-manova.html#cb149-1" tabindex="-1"></a>man.sum <span class="ot">&lt;-</span> <span class="fu">summary.manova</span>(man.mod, <span class="at">test =</span> <span class="st">&quot;Pillai&quot;</span>)</span>
<span id="cb149-2"><a href="week-03-statistical-assumptions-of-manova.html#cb149-2" tabindex="-1"></a>man.sum<span class="sc">$</span>SS</span></code></pre></div>
<pre><code>## $gp
##            [,1]      [,2]      [,3]
## [1,]   62.65568 -78.55802 -254.3505
## [2,]  -78.55802  98.49647  318.9060
## [3,] -254.35048 318.90598 1032.5347
## 
## $Residuals
##          [,1]      [,2]      [,3]
## [1,] 901.4386  449.5777  153.6975
## [2,] 449.5777 1182.8086  336.1357
## [3,] 153.6975  336.1357 1515.1135</code></pre>
<p>The residuals and eigenvalues are in there, too. We’ll address eigenvalues later.</p>
<div id="interpretation" class="section level4 hasAnchor" number="4.4.0.1">
<h4><span class="header-section-number">4.4.0.1</span> Interpretation<a href="week-03-statistical-assumptions-of-manova.html#interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If our research question were indeed about the composite costs of transporting milk given either a diesel or gasoline truck, the best we could say at this point is that there is a difference in costs between the two trucks. Where that difference lies is yet unknown. Should we use gasoline or diesel?<a href="#fn25" class="footnote-ref" id="fnref25"><sup>25</sup></a> We don’t have an answer (which is why I find MANOVA on its own not very useful). To find an answer to this, we turn to either univariate <em>F</em>-tests or discriminant function analysis—which we’ll address in an upcoming lesson. Though, we should present our results with caution, as we did not meet the statistical assumptions.</p>
</div>
<div id="follow-up-analysis-with-univariate-f-tests" class="section level3 hasAnchor" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Follow-up analysis with univariate <em>F</em>-tests<a href="week-03-statistical-assumptions-of-manova.html#follow-up-analysis-with-univariate-f-tests" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Traditionally, though <strong>not</strong> an agreed-upon practice, researchers follow a statistically significant MANOVA with ANOVAs. For this, we could use <code>aov()</code> for each dependent variable. Alternatively, we can use the <code>summary.aov()</code> function on the MANOVA model fitted object:</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="week-03-statistical-assumptions-of-manova.html#cb151-1" tabindex="-1"></a><span class="fu">summary.aov</span>(man.mod)</span></code></pre></div>
<pre><code>##  Response 1 :
##             Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## gp           1  62.66  62.656  3.9619 0.05135 .
## Residuals   57 901.44  15.815                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response 2 :
##             Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## gp           1   98.5  98.496  4.7466 0.03351 *
## Residuals   57 1182.8  20.751                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response 3 :
##             Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## gp           1 1032.5 1032.53  38.845 5.966e-08 ***
## Residuals   57 1515.1   26.58                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We would then carry out the usual ANOVA process of examining planned comparisons or post-hoc tests on the variables that had statistically significant omnibus <em>F</em>-tests. In this example, we only have two groups, so there’s no need.</p>
</div>
<div id="effect-size" class="section level3 hasAnchor" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> Effect size<a href="week-03-statistical-assumptions-of-manova.html#effect-size" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The effect size for each independent variable is calculated from Wilks’ Lambda as
<span class="math display">\[ \text{Partial } \eta^2 = 1-\Lambda^{1/s}\]</span>
where <span class="math inline">\(s\)</span> is either the number of dependent variables, <span class="math inline">\(p\)</span>, or the degrees of freedom of the effect, <strong>whichever is smaller</strong>: <span class="math inline">\(s = \text{min}(p, df_{\text{effect}})\)</span>. We can do this by hand or use the <code>min()</code> function from R:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="week-03-statistical-assumptions-of-manova.html#cb153-1" tabindex="-1"></a>dvs     <span class="ot">&lt;-</span> <span class="fu">cbind</span>(dat<span class="sc">$</span>y1, dat<span class="sc">$</span>y2, dat<span class="sc">$</span>y3)</span>
<span id="cb153-2"><a href="week-03-statistical-assumptions-of-manova.html#cb153-2" tabindex="-1"></a><span class="co"># Here&#39;s `p`, our number of dependent variables:</span></span>
<span id="cb153-3"><a href="week-03-statistical-assumptions-of-manova.html#cb153-3" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dvs)</span>
<span id="cb153-4"><a href="week-03-statistical-assumptions-of-manova.html#cb153-4" tabindex="-1"></a></span>
<span id="cb153-5"><a href="week-03-statistical-assumptions-of-manova.html#cb153-5" tabindex="-1"></a><span class="co"># Here&#39;s the degrees of freedom of the effect, which with a main effect in </span></span>
<span id="cb153-6"><a href="week-03-statistical-assumptions-of-manova.html#cb153-6" tabindex="-1"></a><span class="co"># MANOVA is the number of groups minus 1 (or k - 1). We could use this code:</span></span>
<span id="cb153-7"><a href="week-03-statistical-assumptions-of-manova.html#cb153-7" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">levels</span>(dat<span class="sc">$</span>gp)) </span>
<span id="cb153-8"><a href="week-03-statistical-assumptions-of-manova.html#cb153-8" tabindex="-1"></a><span class="co"># `levels()` gives the levels of the factor. `length()` returns how many.</span></span>
<span id="cb153-9"><a href="week-03-statistical-assumptions-of-manova.html#cb153-9" tabindex="-1"></a>df.eff <span class="ot">&lt;-</span> (k <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb153-10"><a href="week-03-statistical-assumptions-of-manova.html#cb153-10" tabindex="-1"></a>df.eff</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="week-03-statistical-assumptions-of-manova.html#cb155-1" tabindex="-1"></a><span class="co"># Or, we can look at the summary statistics to find the df of the effect:</span></span>
<span id="cb155-2"><a href="week-03-statistical-assumptions-of-manova.html#cb155-2" tabindex="-1"></a>man.mod <span class="ot">&lt;-</span> <span class="fu">manova</span>(dvs <span class="sc">~</span> gp, <span class="at">data =</span> dat)</span>
<span id="cb155-3"><a href="week-03-statistical-assumptions-of-manova.html#cb155-3" tabindex="-1"></a>(man.sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(man.mod, <span class="at">test =</span> <span class="st">&quot;Wilks&quot;</span>) ) </span></code></pre></div>
<pre><code>##           Df   Wilks approx F num Df den Df    Pr(&gt;F)    
## gp         1 0.52821   16.375      3     55 1.001e-07 ***
## Residuals 57                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="week-03-statistical-assumptions-of-manova.html#cb157-1" tabindex="-1"></a><span class="co"># We can see it is 1 in this case. </span></span>
<span id="cb157-2"><a href="week-03-statistical-assumptions-of-manova.html#cb157-2" tabindex="-1"></a><span class="co"># For reproducibility, we could also do it this way:</span></span>
<span id="cb157-3"><a href="week-03-statistical-assumptions-of-manova.html#cb157-3" tabindex="-1"></a>df.eff <span class="ot">&lt;-</span> man.sum<span class="sc">$</span>stats[<span class="st">&quot;gp&quot;</span> , <span class="st">&quot;Df&quot;</span>]</span>
<span id="cb157-4"><a href="week-03-statistical-assumptions-of-manova.html#cb157-4" tabindex="-1"></a><span class="co"># Now, let&#39;s find what `s` is, for our calculation of eta squared:</span></span>
<span id="cb157-5"><a href="week-03-statistical-assumptions-of-manova.html#cb157-5" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">min</span>(p, df.eff) <span class="co"># 1 is less than 3, so the result is 1, here.</span></span>
<span id="cb157-6"><a href="week-03-statistical-assumptions-of-manova.html#cb157-6" tabindex="-1"></a><span class="co"># Get Wilks&#39; lambda:</span></span>
<span id="cb157-7"><a href="week-03-statistical-assumptions-of-manova.html#cb157-7" tabindex="-1"></a>WLambda <span class="ot">&lt;-</span> man.sum<span class="sc">$</span>stats[<span class="st">&quot;gp&quot;</span>, <span class="st">&quot;Wilks&quot;</span>]</span>
<span id="cb157-8"><a href="week-03-statistical-assumptions-of-manova.html#cb157-8" tabindex="-1"></a><span class="co"># Calculate it:</span></span>
<span id="cb157-9"><a href="week-03-statistical-assumptions-of-manova.html#cb157-9" tabindex="-1"></a>my.eta.sq <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> WLambda<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>s)</span>
<span id="cb157-10"><a href="week-03-statistical-assumptions-of-manova.html#cb157-10" tabindex="-1"></a>my.eta.sq</span></code></pre></div>
<pre><code>## [1] 0.4717907</code></pre>
<p>Because we have only one independent variable, we don’t really have a <em>partial</em> <span class="math inline">\(\eta^2\)</span>, as there is no variance from other variables to partial out, so we have an <span class="math inline">\(\eta^2\)</span>. Also, when we have only two groups, the degrees of freedom of the effect is 1, making <span class="math inline">\(s = 1\)</span>, which results in:
<span class="math display">\[\begin{aligned}
\eta^2 &amp;= 1-\Lambda^{1/1} \\
       &amp;= 1-\Lambda^1 \\
       &amp;= 1-\Lambda
\end{aligned}\]</span></p>
<p>Here, our effect size is <span class="math inline">\(\eta^2 = 1 - 0.52821 = 0.47\)</span>, which means that our independent variable explains 47 percent of the variability in the linear composite of the three dependent variables. With two groups, the effect size is the same as the Pillai’s trace statistic.</p>
<p>Instead of doing this calculation ourselves (or maybe to check our calculation), we can use the <code>eta_squared()</code> function on the MANOVA model output. This function is from the effectsize package.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="week-03-statistical-assumptions-of-manova.html#cb159-1" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb159-2"><a href="week-03-statistical-assumptions-of-manova.html#cb159-2" tabindex="-1"></a>dvs     <span class="ot">&lt;-</span> <span class="fu">cbind</span>(dat<span class="sc">$</span>y1, dat<span class="sc">$</span>y2, dat<span class="sc">$</span>y3)</span>
<span id="cb159-3"><a href="week-03-statistical-assumptions-of-manova.html#cb159-3" tabindex="-1"></a>man.mod <span class="ot">&lt;-</span> <span class="fu">manova</span>(dvs <span class="sc">~</span> gp, <span class="at">data =</span> dat)</span>
<span id="cb159-4"><a href="week-03-statistical-assumptions-of-manova.html#cb159-4" tabindex="-1"></a><span class="fu">eta_squared</span>(man.mod)</span></code></pre></div>
<pre><code>## # Effect Size for ANOVA (Type I)
## 
## Parameter | Eta2 (partial) |       95% CI
## -----------------------------------------
## gp        |           0.47 | [0.30, 1.00]
## 
## - One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
<div id="comparing-the-model-without-outlier" class="section level3 hasAnchor" number="4.4.3">
<h3><span class="header-section-number">4.4.3</span> Comparing the Model Without Outlier<a href="week-03-statistical-assumptions-of-manova.html#comparing-the-model-without-outlier" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can conduct the MANOVA analysis without the multivariate outlier to determine if this has an effect on the statitical conclusion. Below, we’re creating a second data set, without the outlier, by using the <code>!</code> operator in front of the row index.</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="week-03-statistical-assumptions-of-manova.html#cb161-1" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> dat</span>
<span id="cb161-2"><a href="week-03-statistical-assumptions-of-manova.html#cb161-2" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> dat2[<span class="sc">!</span>dat2<span class="sc">$</span>outlier <span class="sc">==</span> <span class="dv">1</span>, ]</span>
<span id="cb161-3"><a href="week-03-statistical-assumptions-of-manova.html#cb161-3" tabindex="-1"></a>dvs2     <span class="ot">&lt;-</span> <span class="fu">cbind</span>(dat2<span class="sc">$</span>y1, dat2<span class="sc">$</span>y2, dat2<span class="sc">$</span>y3)</span>
<span id="cb161-4"><a href="week-03-statistical-assumptions-of-manova.html#cb161-4" tabindex="-1"></a>man.mod2  <span class="ot">&lt;-</span> <span class="fu">manova</span>(dvs2 <span class="sc">~</span> gp, <span class="at">data =</span> dat2)</span>
<span id="cb161-5"><a href="week-03-statistical-assumptions-of-manova.html#cb161-5" tabindex="-1"></a><span class="fu">summary.manova</span>(man.mod2, <span class="at">test =</span> <span class="st">&quot;Wilks&quot;</span>)</span></code></pre></div>
<pre><code>##           Df   Wilks approx F num Df den Df    Pr(&gt;F)    
## gp         1 0.50628   17.553      3     54 4.438e-08 ***
## Residuals 56                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We see that the statistical conclusion is unchanged and that the effect is slightly stronger, with <span class="math inline">\(\eta^2 = 0.49\)</span>. Given this, we should retain the outlier and report the test with all of the observations.</p>
<p>That one outlier, ID = 9, was from the Mahalanobis distance with the <em>residuals</em>. If we wanted to see the results with the two outliers detected from the raw data, our <code>outlier</code> variable in our data set would have included both Case 9 and 11.</p>
<p>Another option is to remember who these two cases were (<code>id</code> = 9 &amp; 11) and to create a data set without these two people for the <code>manova()</code> procedure. Here, I’m using (a) the <code>filter()</code> function from the dplyr package (in the tidyverse suite), (b) the code <code>!</code> to exclude these cases that meet the criterion, and (c) the <code>%in%</code> in the criterion. Here, my criterion is if the row contains either a <code>9</code> or <code>21</code> <em>in</em> the <code>id</code> variable (which is a factor in our dataframe).</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="week-03-statistical-assumptions-of-manova.html#cb163-1" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> dat</span>
<span id="cb163-2"><a href="week-03-statistical-assumptions-of-manova.html#cb163-2" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> dat2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span>id <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;9&quot;</span>, <span class="st">&quot;21&quot;</span>) )</span>
<span id="cb163-3"><a href="week-03-statistical-assumptions-of-manova.html#cb163-3" tabindex="-1"></a>dvs2     <span class="ot">&lt;-</span> <span class="fu">cbind</span>(dat2<span class="sc">$</span>y1, dat2<span class="sc">$</span>y2, dat2<span class="sc">$</span>y3)</span>
<span id="cb163-4"><a href="week-03-statistical-assumptions-of-manova.html#cb163-4" tabindex="-1"></a>man.mod2  <span class="ot">&lt;-</span> <span class="fu">manova</span>(dvs2 <span class="sc">~</span> gp, <span class="at">data =</span> dat2)</span>
<span id="cb163-5"><a href="week-03-statistical-assumptions-of-manova.html#cb163-5" tabindex="-1"></a><span class="fu">summary.manova</span>(man.mod2, <span class="at">test =</span> <span class="st">&quot;Wilks&quot;</span>)</span></code></pre></div>
<pre><code>##           Df   Wilks approx F num Df den Df    Pr(&gt;F)    
## gp         1 0.51219   16.826      3     53 8.359e-08 ***
## Residuals 55                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Similar to the model results when we excluded only Case 9, we see a similar statistical conclusion, which in turn is the same as if we had included these two cases. With this, we can include these outliers in ouar data set and report that we conducted this sensitivity analysis.</p>
</div>
</div>
<div id="robust-one-way-manova" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Robust One-way MANOVA<a href="week-03-statistical-assumptions-of-manova.html#robust-one-way-manova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Because the assumptions were not met, we could use a robust version of Wilks’ lambda. This is for one-way MANOVAs only—that is, having a single independent variable. To my knowledge, there are no robust methods for factorial MANOVA or MANCOVA designs—we’d be out of luck. We will not pursue this further, but the documentation is in the package and it is worth knowing that robust approaches exist, at least for one-way MANOVA.</p>
<p>The output with the method I’ve specified below (which is the default) provides a Wilks’ lambda estimate, which is identical to our test, a chi-square test statistic and the <em>p</em>-value leading to the same statistical conclusion. It also reports a matrix of by-group (rows) sample means on the variables (columns), which is not interesting because we already examined that above with <code>describeBy()</code>.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="week-03-statistical-assumptions-of-manova.html#cb165-1" tabindex="-1"></a><span class="fu">library</span>(rrcov)</span>
<span id="cb165-2"><a href="week-03-statistical-assumptions-of-manova.html#cb165-2" tabindex="-1"></a>dvs <span class="ot">&lt;-</span> <span class="fu">cbind</span>(dat<span class="sc">$</span>y1, dat<span class="sc">$</span>y2, dat<span class="sc">$</span>y3)</span>
<span id="cb165-3"><a href="week-03-statistical-assumptions-of-manova.html#cb165-3" tabindex="-1"></a>grp <span class="ot">&lt;-</span> dat<span class="sc">$</span>gp</span>
<span id="cb165-4"><a href="week-03-statistical-assumptions-of-manova.html#cb165-4" tabindex="-1"></a></span>
<span id="cb165-5"><a href="week-03-statistical-assumptions-of-manova.html#cb165-5" tabindex="-1"></a>Wtest <span class="ot">&lt;-</span> <span class="fu">Wilks.test</span>(dvs, </span>
<span id="cb165-6"><a href="week-03-statistical-assumptions-of-manova.html#cb165-6" tabindex="-1"></a>                    <span class="at">grouping =</span> grp, </span>
<span id="cb165-7"><a href="week-03-statistical-assumptions-of-manova.html#cb165-7" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">&quot;c&quot;</span>)</span>
<span id="cb165-8"><a href="week-03-statistical-assumptions-of-manova.html#cb165-8" tabindex="-1"></a>Wtest</span></code></pre></div>
<pre><code>## 
##  One-way MANOVA (Bartlett Chi2)
## 
## data:  x
## Wilks&#39; Lambda = 0.52821, Chi2-Value = 35.424, DF = 3.000, p-value = 9.914e-08
## sample estimates:
##       [,1]     [,2]      [,3]
## 1 12.21861  8.11250  9.590278
## 2 10.10565 10.76174 18.167826</code></pre>
</div>
<div id="summary-1" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Summary<a href="week-03-statistical-assumptions-of-manova.html#summary-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The primary focus of this session was to practice examining the assumptions used in MANOVA. MANOVA is often described as reasonably robust to violations of these two assumptions (probably not to violations of statistical independence) if the sample sizes in each group are equal. To some scholars, data transformation is not a recommended solution because the statistical tests reflect the transformed variables, which are also hard to interpret. If we embrace our non-normality (as Curran and Hancock word it) in MANOVA, the furthest it seems we can get is with one-way MANOVAs. After that, we either throw in the towel or acquiesce to data transformation.</p>
<p>The second example in the reading is with <code>SENIORWISE.sav</code> data and provides a much more satisfying data set for practicing one-way MANOVA. Using the tools in this tutorial, try examining the assumptions with that data set.</p>
<!-- ```{r warning = F, message = F} -->
<!-- #------------------------------------------------------------------ -->
<!-- # EXTRA STUFF: Peeking ahead at MANOVA -->
<!-- # Using the `manova()` function: -->
<!-- fit <- manova(cbind(y1, y2, y3) ~ gp, data = dat) -->
<!-- fit_summary <- summary(fit, test = "Wilks") -->
<!-- fit_summary -->
<!-- W <- fit_summary$SS$Residuals -->
<!-- B <- fit_summary$SS$gp -->
<!-- det(W) / det(B + W) # without rounding error -->
<!-- # Wilk's Lambda is also calculable as the product of (1 / (1 + lambda_i)), -->
<!-- # where lambda_i is the eigenvalue corresponding to the repackaged variance -->
<!-- # of the ith linear composite of the joint dependent variables. -->
<!-- fit_summary$Eigenvalues -->
<!-- # We can use the `eigen()` function on the BW^{-1} matrix. -->
<!-- eigs <- eigen(B %*% solve(W)) -->
<!-- prod(1/(1+eigs$values)) -->
<!-- # In other words, Wilk's Lambda accounts for all the repackaged variance of the  -->
<!-- # composite of these two variables. Lambda is the proportion of unexplained -->
<!-- # variance to explained variance. -->
<!-- # Pillai's trace is calculated as sum(lambda_i / (1 + lambda_i) ) -->
<!-- Pillai <- sum(eigs$values / (1 + eigs$values) ) -->
<!-- Pillai -->
<!-- summary(fit, test = "Pillai") -->
<!-- # Hotelling-Lawley Trace is the sum of the eigenvalues, sum(lambda_i): -->
<!-- Hotell_sq <- sum(eigs$values) -->
<!-- Hotell_sq -->
<!-- summary(fit, test = "Hotelling") -->
<!-- ``` -->

</div>
</div>
<div class="footnotes">
<hr />
<ol start="18">
<li id="fn18"><p>A shortcut is to fit an ANOVA for each dependent variable and then examine the plots. That approach would also be examining the normality of the <em>residuals</em> rather than the raw data, which many scholars believe is more appropriate.<a href="week-03-statistical-assumptions-of-manova.html#fnref18" class="footnote-back">↩︎</a></p></li>
<li id="fn19"><p>We can use the <code>qnorm()</code> function to get the critical value of <em>z</em> at a probability level, such as at <em>p</em> = .01: <code>abs(qnorm(p = .01/2, lower.tail=TRUE)) = 2.58</code>.<a href="week-03-statistical-assumptions-of-manova.html#fnref19" class="footnote-back">↩︎</a></p></li>
<li id="fn20"><p>This standardization can also be in a single line of code, as in <code>apply(dat[, c("y1", "y2", "y3")], 2, scale)</code>.<a href="week-03-statistical-assumptions-of-manova.html#fnref20" class="footnote-back">↩︎</a></p></li>
<li id="fn21"><p>Alternatively, we could use <code>dat %&gt;% filter(gp == 1) %&gt;% ggplot(aes(x = scale(y1) )) + geom_density(fill = "wheat", color = "white") + stat_function(fun = dnorm)</code> if we did not want to use the package.<a href="week-03-statistical-assumptions-of-manova.html#fnref21" class="footnote-back">↩︎</a></p></li>
<li id="fn22"><p>Note that we’re using the term sample and population here because we’re assuming our dependent variables are random (rather than fixed) variables because the cases are randomly sampled from the population.<a href="week-03-statistical-assumptions-of-manova.html#fnref22" class="footnote-back">↩︎</a></p></li>
<li id="fn23"><p>We could also fit the models and conduct this test on the residuals.<a href="week-03-statistical-assumptions-of-manova.html#fnref23" class="footnote-back">↩︎</a></p></li>
<li id="fn24"><p>Can also use the <code>mahalanobis_distance()</code> function in the rstatix package.<a href="week-03-statistical-assumptions-of-manova.html#fnref24" class="footnote-back">↩︎</a></p></li>
<li id="fn25"><p>This makes me want to blame carbon-based pollution on milk, and that’s not even including the massive amount of methane released from cow belching and farting.<a href="week-03-statistical-assumptions-of-manova.html#fnref25" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="planned-comparisons-and-contrasts.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-04-factorial-manova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
